### ISSUE TITLE
Support Amazon SQS

### ISSUE THREAD

**Issue by danielfariati** [atech/postal#10]
Hi!

It would be nice to offer the possibility to use SQS instead of RabbitMQ. 😄 

Thanks!

**Comment by MaddalenaTech** [comment]
Just for my own curiosity, why ?

**Comment by danielfariati** [comment]
One less application to manage / worry about.

**Comment by adamcooke** [comment]
It would be nice to support additional queueing & database engines but it's not something we're going to be dedicating any resources to ourselves right now. We support RabbitMQ & MySQL so there's no huge interest in adding support for anything else.

**Comment by plamentotev** [comment]
Поризволен коментар :+1:
