### ISSUE TITLE
Mx server in configuration file

### ISSUE THREAD

**Issue by afanjul** [atech/postal#100]
Hi there, in dns configuration, it is not clear if we have to use mail.yourdomain.com (as [wiki](https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration) says) or mx.mail.yourdomain.com (as postal.yml says) as our mx server...

What is the right mx address? I think is mx.mail.yourdomain.com, but I'm not sure...

**Comment by adamcooke** [comment]
You can use any MX domain that you want as long as the record has A records pointing to your server.
