### ISSUE TITLE
Clarification for revised fast server configuration

### ISSUE THREAD

**Issue by willpower232** [atech/postal#105]
Under https://github.com/atech/postal/wiki/Click-&-Open-Tracking#enable-the-fast-server, it says 

> You will need to make sure that your nginx server isn't already listening on this IP address.

It might be worth adding something along the lines of

> You can do this by changing the IP addresses in `/etc/nginx/sites-enabled/default`

For the nginx newbies like myself

**Comment by adamcooke** [comment]
Updated 👍  Thanks
