### ISSUE TITLE
Absence of HTML Body

### ISSUE THREAD

**Issue by willpower232** [atech/postal#106]
I believe @adamcooke is already aware of this but thought an issue here would help.

Essentially if one sends a message over the API that contains only a text body but also includes an attachment, Postal implies a HTML body which is blank, save for the click tracking image.

I also understand there are related issues regarding how a HTML message appears on iOS devices.

I suppose a remedy would be for the wrapper to throw an exception if a HTML body is not present but the apparent iOS issue might be deeper than that.

**Comment by adamcooke** [comment]
I was aware but having it here as an issue is useful - thanks!

**Comment by willpower232** [comment]
this is resolved by the merge request but the change isn't showing up having done a `postal auto-upgrade` as the zip file from postal.atech.media hasn't been updated.
