### ISSUE TITLE
SMTP stop working after upgrade

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#109]
This is the log on postal run

> 16:43:15 system          | Procodile supervisor started with PID 3431
> 16:43:15 system          | Application root is /opt/postal/app
> 16:43:15 system          | Automatic respawning is disabled
> 16:43:15 control         | Listening at /opt/postal/app/tmp/pids/procodile.sock
> 16:43:15 system          | Reloading configuration
> 16:43:15 web.1           | Started with PID 3437
> 16:43:15 worker.1        | Started with PID 3439
> 16:43:15 cron.1          | Started with PID 3441
> 16:43:15 smtp.1          | Started with PID 3445
> 16:43:15 requeuer.1      | Started with PID 3447
> 16:43:16 web.1           | => Puma starting in single mode...
> 16:43:16 web.1           | => * Version 3.8.2 (ruby 2.3.4-p301), codename: Sassy Salamander
> 16:43:16 web.1           | => * Min threads: 5, max threads: 5
> 16:43:16 web.1           | => * Environment: production
> 16:43:19 worker.1        | => [worker.1:3439] [2017-05-05T16:43:19.900] INFO -- : Joined main queue
> 16:43:20 requeuer.1      | => [requeuer.1:3447] [2017-05-05T16:43:20.053] INFO -- : Running message requeuer...
> 16:43:20 smtp.1          | => rake aborted!
> 16:43:20 smtp.1          | => 
> 16:43:20 smtp.1          | => Errno::EACCES: Permission denied - bind(2) for "::" port 25
> 16:43:20 smtp.1          | => 
> 16:43:20 smtp.1          | => /opt/postal/app/lib/postal/smtp_server/server.rb:51:in `initialize'
> 16:43:20 smtp.1          | => /opt/postal/app/lib/postal/smtp_server/server.rb:51:in `open'
> 16:43:20 smtp.1          | => /opt/postal/app/lib/postal/smtp_server/server.rb:51:in `listen'
> 16:43:20 smtp.1          | => /opt/postal/app/lib/postal/smtp_server/server.rb:257:in `run'
> 16:43:20 smtp.1          | => /opt/postal/app/lib/tasks/postal.rake:18:in `block (2 levels) in <top (required)>'
> 16:43:20 smtp.1          | => /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
> 16:43:20 smtp.1          | => 
> 16:43:20 smtp.1          | => Tasks: TOP => postal:smtp_server
> 16:43:20 smtp.1          | => 
> 16:43:20 smtp.1          | => (See full trace by running task with --trace)
> 16:43:20 smtp.1          | => 
> 16:43:20 cron.1          | => [cron.1:3441] [2017-05-05T16:43:20.175] INFO -- : Starting clock for 8 events: [ every-1-minutes every-15-minutes every-15-minutes every-15-minutes every-15-minutes every-hour every-hour every-day ]
> 16:43:20 cron.1          | => [cron.1:3441] [2017-05-05T16:43:20.176] INFO -- : Triggering 'every-1-minutes'
> 16:43:20 worker.1        | => [worker.1:3439] [2017-05-05T16:43:20.194] INFO -- : [VXPZ6JTWZA] Started processing RequeueWebhooksJob job
> 16:43:20 worker.1        | => [worker.1:3439] [2017-05-05T16:43:20.236] INFO -- : [VXPZ6JTWZA] Finished processing RequeueWebhooksJob job in 0.04226473s
> 16:43:20 worker.1        | => [worker.1:3439] [2017-05-05T16:43:20.238] INFO -- : [QTW1MFIFRL] Started processing SendNotificationsJob job
> 16:43:20 worker.1        | => [worker.1:3439] [2017-05-05T16:43:20.265] INFO -- : [QTW1MFIFRL] Finished processing SendNotificationsJob job in 0.027769525s
> 16:43:20 web.1           | => * Listening on tcp://127.0.0.1:5000
> 16:43:20 web.1           | => Use Ctrl-C to stop
> 16:43:21 smtp.1          | Process has stopped. Respawning not available.
> 16:43:21 smtp.1          | Removed PID file
> 

It says port 25 is denied, but I only have Postal (well, really it is on 2525) there, and it was working before I upgraded.

**Comment by elfeffe** [comment]
> /opt/postal# postal status
> Procodile Version   1.0.16
> Application Root    /opt/postal/app
> Supervisor PID      3981
> Started             2017-05-05 16:55:38 +0000
> 
>  * smtp only has 2 instances (should have 1)
>  * smtp.2 is not running (Failed)
> 
> || web
> || Quantity            1
> || Command             bundle exec puma -C config/puma.rb
> || Respawning          5 every 3600 seconds
> || Restart mode        usr1
> || Log path            none specified
> || Address/Port        none
> || => web.1            Running      16:55        pid:3987     respawns:0      port:-        tag:-
> 
> || worker
> || Quantity            1
> || Command             bundle exec rake postal:worker
> || Respawning          5 every 3600 seconds
> || Restart mode        start-term
> || Log path            none specified
> || Address/Port        none
> || => worker.2         Running      16:56        pid:4102     respawns:0      port:-        tag:-
> 
> || cron
> || Quantity            1
> || Command             bundle exec rake postal:cron
> || Respawning          5 every 3600 seconds
> || Restart mode        term-start
> || Log path            none specified
> || Address/Port        none
> || => cron.2           Running      16:56        pid:4115     respawns:0      port:-        tag:-
> 
> || smtp
> || Quantity            1
> || Command             bundle exec rake postal:smtp_server
> || Respawning          5 every 3600 seconds
> || Restart mode        usr1
> || Log path            none specified
> || Address/Port        none
> || => smtp.1           Stopped                   pid:4061     respawns:5      port:-        tag:-
> || => smtp.2           Failed       16:56        pid:4195     respawns:5      port:-        tag:-
> 
> || requeuer
> || Quantity            1
> || Command             bundle exec rake postal:requeuer
> || Respawning          5 every 3600 seconds
> || Restart mode        term-start
> || Log path            none specified
> || Address/Port        none
> || => requeuer.2       Running      16:56        pid:4118     respawns:0      port:-        tag:-

**Comment by willpower232** [comment]
have you tried running `setcap` as per the recently revised https://github.com/atech/postal/wiki/Installation#preparing-your-operating-system ?

**Comment by elfeffe** [comment]
The problem is the new file postal.default.yml
It was created today, when I upgraded. It has port 25 for SMTP, I changed it to 2525 and now it works.
Probably you have to fix the code somewhere, I'm not an expert in Ruby :)

**Comment by elfeffe** [comment]
yes, it works with
sudo setcap 'cap_net_bind_service=+ep' /usr/bin/ruby2.3

**Comment by elfeffe** [comment]
@willpower232 So it is not needed to run iptables anymore for port 25?

**Comment by willpower232** [comment]
apparently so, we noticed the wiki lacked iptables related information today and postal runs wonderfully with the setcap in place to allow it to run on the ports it was intended to.

also note the new `bind-address` option for click tracking https://github.com/atech/postal/wiki/Click-&-Open-Tracking#enable-the-fast-server

**Comment by adamcooke** [comment]
Apologies. We made a breaking change which is quite hard to communicate. Here are the details 

https://github.com/atech/postal/wiki/Abandoning-iptables
