### ISSUE TITLE
Disable tracking

### ISSUE THREAD

**Issue by PSunde** [atech/postal#11]
Is there a possibility to disable the fast server/tracking?

**Comment by adamcooke** [comment]
It's enabled per mail server so you just wouldn't enable it on servers that you don't wish to use it on 😄

**Comment by PSunde** [comment]
Okay cool :smiley: 
But maybe I'm overlooking something or I'm just dumb. How exactly I disable it? :confused:  Just delete the fast_server section from the config?

**Comment by adamcooke** [comment]
Oh - I see what you mean. At present, there's no way to configure that process not to run I'm afraid however it will only be used if enabled for a mail server.

**Comment by PSunde** [comment]
Ok. Thank you very much :wink:
