### ISSUE TITLE
SPF record seemingly not required

### ISSUE THREAD

**Issue by alexroosenstein** [atech/postal#110]
Correct me if I'm wrong, but it seems that the SPF record is not required.

The SPF check is done against the return-path domain, which already has a SPF record configured.
I even tried with a domain name that already had a SPF record (but did not include the IPs used by Postal), and that worked fine as well.

Could someone else confirm?

**Comment by adamcooke** [comment]
That's correct most server do check against the return path domain however it doesn't hurt to have the SPF on your domain too. I believe Exchange did something weird with SPF in the past but I don't remember the derails or if it is needed here.
