### ISSUE TITLE
Choose Mail Server Based On Domain

### ISSUE THREAD

**Issue by michaelwilding** [atech/postal#111]
Will Postal allow us to set up rules to send emails with specific domains through an Amazon SES connection (for example) and all other emails through our mail server?

**Comment by adamcooke** [comment]
That would need to be configure in the application that sends the messages. Postal isn't just a proxy for outbound messages, it sends all its own messages.

**Comment by michaelwilding** [comment]
Ah, I thought it was purely an MTA.
