### ISSUE TITLE
Sender check not allowing default ?

### ISSUE THREAD

**Issue by RLejolivet** [atech/postal#112]
Hello,

I just setup a Postal instance to be a central mail server for my homelab, and had my first mails denied because the "From" header was apparently not correct.
After investigating, it seems the following two "From" forms are allowed: 

- "user@my.domain"
- "User Name \<user@my.domain\>"

But not the following form:

- "user@my.domain (User Name)"

The latter being the default form for me. bsd-mailx + postfix, no explicit sender set on my end, so it went with "root@my.domain (root)" and Postal refused it. Is this intended?

**Comment by adamcooke** [comment]
That is the intended behaviour. The third formet you've provided isn't one I've seen before though.

**Comment by RLejolivet** [comment]
After some researching I can't say I've found many other mentions of that form either (aside from [this one random stackoverflow comment](http://stackoverflow.com/a/30230440)), so I'm not surprised you haven't encountered it before.

It does get parsed correctly by the few email clients I just tried it with, so I guess it must not be that uncommon?

**Comment by adamcooke** [comment]
@catphish Any thoughts on this?

**Comment by adamcooke** [comment]
We've looked into this and such formatting is valid so we should support it in Postal. This is therefore a bug 😄
