### ISSUE TITLE
Sending test mails to mail-tester.com

### ISSUE THREAD

**Issue by muratcorlu** [atech/postal#113]
When I try to send a message to a mail-tester.com address from postal panel, I see an error as `No SMTP servers were available for mail-tester.com. Tried mail-tester.com` on delivery report with a "SOFT FAIL" status. What can be the problem?

![image](https://cloud.githubusercontent.com/assets/127687/25776231/4616d152-32b9-11e7-8143-f71e1a21384a.png)

**Comment by mattmartincouk** [comment]
Could be a DNS issue.

What does 

`dig -t MX mail-tester.com`

give you?

**Comment by muratcorlu** [comment]
From my Postal server it gives that:

```
root@postal:~# dig -t MX mail-tester.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t MX mail-tester.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42860
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mail-tester.com.		IN	MX

;; ANSWER SECTION:
mail-tester.com.	349	IN	MX	1 mail-tester.com.

;; Query time: 5 msec
;; SERVER: 108.61.10.10#53(108.61.10.10)
;; WHEN: Sun May 07 01:28:59 UTC 2017
;; MSG SIZE  rcvd: 60
```

**Comment by catphish** [comment]
The error appears to be "execution expired". One possibility here is that your server (or your ISP) has a firewall that is preventing connections out on port 25. You can test connectivity with telnet:

```
telnet mail-tester.com 25
```

**Comment by lutvit** [comment]
I had once the same error. It is Mail-Tester related. Just try another tool for that test. It seems like https://www.emailchecky.com is an interesting alternative.
