### ISSUE TITLE
Development mode still sending messages

### ISSUE THREAD

**Issue by RLejolivet** [atech/postal#114]
Hello,

I just tried to put my mail server in "development mode" to see what would happen. Outgoing messages are held correctly, but incoming messages are still forwarded to my Address Endpoint. I was under the impression that they would be held as well?

> When in Development mode, outgoing **& incoming mail** will be held and only visible in the web interface and will not be sent to **any recipients** or HTTP endpoints.

**Comment by adamcooke** [comment]
This is a documentation bug. In development mode, it should only stop outgoing messages. Incoming messages should be handled as normal.

**Comment by adamcooke** [comment]
Actually, it seems like holding incoming messages in development would be the best solution. Outgoing messages can be held in live services using credentials.

Fixed in 5e13d7d0526d7bbd078ce244cbd81709f9246965
