### ISSUE TITLE
Messages from outlook appear with sender "None" in Postal

### ISSUE THREAD

**Issue by RLejolivet** [atech/postal#116]
Hello,

Minor issue here, when sending a message from my outlook account to a domain going through Postal, the interface shows it as being sent from "None":

![image](https://cloud.githubusercontent.com/assets/9880933/25785180/b0a38f30-337a-11e7-8dfc-2978fb4c3805.png)

Logs didn't seem to indicate any difference compared to say, emails received from gmail. Attached is the full email as downloaded from Postal (and sanitized to remove my username/domain).

[Message-from-outlook.eml.txt](https://github.com/atech/postal/files/981942/Message-from-outlook.eml.txt)

**Comment by adamcooke** [comment]
The data shown as `from` is the data received by the SMTP server in `MAIL FROM`. Can you check your `smtp_server.log` and see what it shows when a connection goes through?

**Comment by adamcooke** [comment]
Looks like the `AUTH=<>` thing is probably messing around with that.

**Comment by adamcooke** [comment]
To confirm, is this a message sent from an Office 365 account?

**Comment by adamcooke** [comment]
Looks to be something to do with this: https://curl.haxx.se/rfc/rfc4954.txt

**Comment by RLejolivet** [comment]
Yes this is from a (personal, not enterprise, if that makes any difference) o365 account.

**Comment by catphish** [comment]
Fixed in 5a757e722a9a2323cad5ea931db4cd874c2be19b
