### ISSUE TITLE
Using letsencrypt certificates for STARTTLS

### ISSUE THREAD

**Issue by afanjul** [atech/postal#118]
Hi there, **I'm trying to use letsencryp certificates in STARTTLS configuration**, so for that I configured the smtp_server like this:

```
smtp_server:
  port: 25
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/myserver.com/cert.pem;
  tls_private_key_path: /etc/letsencrypt/live/myserver.com/privkey.pem;
```
However I think the ruby process can't access that files (with root permissions) and whenever I try to send a mail with STARTTLS the server throw this:

`[NHDEUT] Errno::EACCES: Permission denied @ rb_sysopen - /etc/letsencrypt/live/myserver.com/cert.pem;`

I tried to copy and past the files into config folder and change their permissions and all it's fine, but I think **it's not the best practices** due to letsencrypt automatic renewing polices. I tried to make symbolic links to that files but no way. Other way would be to give wider permissions in etc/letsencrypt folder, but maybe it's not a good idea in terms of security...

Anyone kwow how to solve this issue?

Thanks
Alex

**Comment by adamcooke** [comment]
You could copy them out of Let's Encrypt's directory (and automate it) and own them appropriately so Postal can use them. Postal runs as `postal` by default. If you're using CertBot there is a hook you can configure to run after renewal.

PS: You don't need semicolons on the end of your configuration lines 😄

**Comment by afanjul** [comment]
Thanks @adamcooke  I saw the hook solution in some forums, but maybe was a bit confused for me. Could be a good thing to add this info in the installation docs, isn't it?

**Comment by adamcooke** [comment]
I think using LE for this is a little outside of the scope of a normal installation. Let's Encrypt is really only designed for HTTP (although it will work if you're sharing a hostname for SMTP and your web traffic).
