### ISSUE TITLE
Multiples IPs, IP Pools

### ISSUE THREAD

**Issue by afanjul** [atech/postal#119]
Hi there, I'm almost done with my great postal server configuration. However **I would like to use multiple ip's** assigned for each mail server and I don't find any docs, guide or something.

Could somebody give me a link to any docs about ip pools (if any) or just give me some tips how to add multiple ip's and assignments? I could enable `use_ip_pools: true` in config file, but I don't find how to add ips to this pool, [just a button to save configuration](https://i.snag.gy/HN7VXe.jpg).

**Comment by afanjul** [comment]
Oh sorry... I just found it!
Just restart, and **go to the upper right part of your admin** to add new ips to your pool :D

But now I have another important question for us: could I configure (assign) a ip to a server independently of the "from" or "to"? I mean I would like that one of the mail servers always use a concrete IP (independenlty of the email to send), without rules to apply...

Thanks

**Comment by adamcooke** [comment]
You can set the IP pool a server can use from the server's own settings page. Is that what you mean?

There is a fair amount of documentation to be written about this. I'll be getting on to that shortly! See #87.

**Comment by afanjul** [comment]
@adamcooke  **Yess**!! Thanks a million! I was affraid that we couldn't set a "default" ip pool for each server. Maybe would be a good thing to add a "button" in IP Pool menu saying [Set default IP Pool] linking to settings menu, or something like that... otherwise it could go unnoticed.

**Comment by andresagui** [comment]
Hello! im really new on this. I have my Postal ready.. but with my real address. I can't find how to get or to create IP addresses for the pool. Is there any doc or tool or both. Thank you very much!!!!!
