### ISSUE TITLE
Incorrect wiki rabbitmqctl add_vhost?

### ISSUE THREAD

**Issue by danfitch** [atech/postal#12]
I followed the instructions
sudo rabbitmqctl add_vhost /postal
sudo rabbitmqctl add_user postal XXX
sudo rabbitmqctl set_permissions -p /postal postal ".*" ".*" ".*"

But I was getting an error 
Bunny::NotAllowedError: Connection-level error: NOT_ALLOWED - access to vhost 'postal' refused for user 'postal'

I modified the instructions removing the slash and it appears to be working.  I am still playing around with the software but there may be something missing here.
sudo rabbitmqctl add_vhost postal
sudo rabbitmqctl add_user postal XXX
sudo rabbitmqctl set_permissions -p postal postal ".*" ".*" ".*"

**Comment by adamcooke** [comment]
I think you'll just need to make sure you have the slash in the `postal.yml` file (i.e. `/postal` rather than just `postal`). I'll make sure the example config includes a slash.

**Comment by ajaymishra8423** [comment]
How to clear queued mail 
https://www.screencast.com/t/U0y5SbW0SVy
