### ISSUE TITLE
Email Spam

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#122]
I brought fresh VPS as well as IPs. Also, i have update SPF and DKIM but still all my test email goes into spam? could you please tell me what will be the reason? how to resolve this and get all emails into the inbox deliverability?

**Comment by adamcooke** [comment]
https://github.com/atech/postal/wiki/FAQs#e-mails-sent-through-postal-are-going-to-spam

**Comment by sahilsunesara** [comment]
I have check DNS and configured perfectly as well as SPF & DKIM but still, test email going to spam. What will be the solution now?

**Comment by adamcooke** [comment]
This is really outside the scope of this project to help with this. You'd need to discuss this with whoever you are sending messages to. You can use https://www.mail-tester.com too which might help.
