### ISSUE TITLE
Strange messages filter behavior 

### ISSUE THREAD

**Issue by omniton** [atech/postal#127]
Hi,
I just found that Postal doesn't search messages if address contains **z** before @ (ie planetaz@example.com)
It works fine with any other word like planetax but no chance with planetaz :)

I checked sql queries and in case of planetaz@example.com the postal produces:
```SELECT COUNT(id) AS count FROM `postal-server-3`.`messages` WHERE `scope` = 'outgoing' AND `spam` = 0 AND `rcpt_to` = 'planeta' ORDER BY `timestamp` DESC
SELECT * FROM `postal-server-3`.`messages` WHERE `scope` = 'outgoing' AND `spam` = 0 AND `rcpt_to` = 'planeta' ORDER BY `timestamp` DESC LIMIT 30 OFFSET 0```

in case of planetax@example.com address:
```SELECT COUNT(id) AS count FROM `postal-server-3`.`messages` WHERE `scope` = 'outgoing' AND `spam` = 0 AND `rcpt_to` = 'planetax@example.com' ORDER BY `timestamp` DESC
SELECT * FROM `postal-server-3`.`messages` WHERE `scope` = 'outgoing' AND `spam` = 0 AND `rcpt_to` = 'planetax@example.com' ORDER BY `timestamp` DESC LIMIT 30 OFFSET 0```

**Comment by adamcooke** [comment]
How odd! I'll take a look at that.

**Comment by adamcooke** [comment]
Can you confirm the full string your entering in the search box?

**Comment by omniton** [comment]
to: planetaz@example.com

**Comment by omniton** [comment]
great, it works now, thanks!
