### ISSUE TITLE
Iptable

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#129]
Hello

Any document file for iptable?
how to enable and configure in a good manner and checking that successfully configured?

Thanks and really appreciate you. Your support is awesome brother!

**Comment by adamcooke** [comment]
There is no need to use iptables to make Postal work. You should configure it to protect your server though but that's not really a Postal thing.

**Comment by sahilsunesara** [comment]
Okay thanks you so much @adamcooke 

could you please guide me where I am wrong. I have installed it and restarted postal I can see that Restarted web.1
Restarted fast.1 -> fast.2
Restarted cron.1 -> cron.2
Restarted smtp.1
Restarted requeuer.1 -> requeuer.2

is that work because i noticed that web.1 and smtp.1 is same way.


another question as per postal help i can see postal smtp details but when i configure SMTP it's show's Connection could not be established with host 144.217.XXX.XXX [Connection refused #111] (code: 0)

so could please tell me the correct way of SMTP configuration username and password?

Really appreciated you!

**Comment by adamcooke** [comment]
The fact they stay the same is fine. They are restarted differently to the other processes. 

For the other thing, make sure the port is correct. It sounds like it isn't because you're getting a connection refused.

**Comment by sahilsunesara** [comment]
see connection is perfect

nmap -PN 144.217.243.122
Starting Nmap 7.40 ( https://nmap.org ) at 2017-05-11 14:43 EEST
Nmap scan report for mail.mailleaders.com (144.217.243.122)
Host is up (0.00073s latency).
Not shown: 995 filtered ports
PORT    STATE SERVICE
80/tcp  open  http
110/tcp open  pop3
143/tcp open  imap
993/tcp open  imaps
995/tcp open  pop3s

Nmap done: 1 IP address (1 host up) scanned in 5.02 seconds





could you please tell me how to generate or create smtp username n password ?

**Comment by adamcooke** [comment]
There is no SMTP server listening in that list.

You can create a new mail server through the web interface then create a credential.

**Comment by sahilsunesara** [comment]
if I am not misunderstanding then I have to create a credential from postal web interface am I right?

if I am right then I already created but not working and got that above connection error.

Thanks for your awesome support.

**Comment by adamcooke** [comment]
As I said, there doesn't appear to be an SMTP server listening. None of those ports looks like an SMTP server to me. In fact, one is IMAP and POP3 which suggests you're running some other mail server on the same host which isn't a good idea.

**Comment by sahilsunesara** [comment]
okay..i am totally new in technology. could you please tell me how to remove IMAP and POP3 and install SMTP ? and how to create SMTP username and password

Appreciated your effort and support

**Comment by sahilsunesara** [comment]
hey adam,

Check SMTP 25 is open now and IMAP & POP3 are diable

Starting Nmap 7.01 ( https://nmap.org ) at 2017-05-12 02:36 EDT
Nmap scan report for vps129193.vps.ovh.ca (144.217.243.122)
Host is up (0.0000040s latency).
Not shown: 996 closed ports
PORT    STATE SERVICE
22/tcp  open  ssh
25/tcp  open  smtp
80/tcp  open  http
443/tcp open  https


But still, i am struggling to send email and now able to configure email.

I already create SMTP credential from postal web interface
Please ch below images
POSTAL HELP AREA





POSTAL CREDENTIAL AREA


​

Please guide me where I am wrong


Thanks for your support

**Comment by sahilsunesara** [comment]
Hello

if I am testing postal test-app-smtp myid@domain.com then I got an email...

but if I configure so sent the email I got a connection time out like

Connection could not be established with host 144.217.243.122 [Connection timed out #110]

do u have any idea where I am wrong?

**Comment by adamcooke** [comment]
What port is it trying to connect to? Check the `smtp` section of your config.

**Comment by sahilsunesara** [comment]
I tried both 25 and 2525
