### ISSUE TITLE
postal.yml changes

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#135]
Have just an upgrade but my then working install seems broken.

Logs show:

18:41:03 fast.1          | => Errno::EACCES: Permission denied - bind(2) for "0.0.0.0" port 80
18:41:03 smtp.1          | => Errno::EACCES: Permission denied - bind(2) for "::" port 25

Yet my ports in the config for SMTP are still the default 2525.

Has the config changed again or location?

**Comment by mattmartincouk** [comment]
By sheer chance - found https://github.com/atech/postal/commit/d4fd6b99251da37f322b07f6a63724318a134170.

Might be worth drawing more attention to that one ;)

**Comment by adamcooke** [comment]
I did write a wiki page about this but until we have a 1.0 release we don't have any release notes of ways to communicate things like this. It's rather annoying, I know. 

https://github.com/atech/postal/wiki/Abandoning-iptables
