### ISSUE TITLE
IP Pool Rules - Error

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#136]
```
I, [2017-05-12T00:17:50.622475 #3111]  INFO -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429] Started GET "/org/custserv/ip_pool_rules" for 91.199.78.3 at 2017-05-12 00:17:50 +0100
I, [2017-05-12T00:17:50.623596 #3111]  INFO -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429] Processing by IPPoolRulesController#index as HTML
I, [2017-05-12T00:17:50.623703 #3111]  INFO -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429]   Parameters: {"org_permalink"=>"custserv"}
I, [2017-05-12T00:17:50.772439 #3111]  INFO -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429]   Rendering ip_pool_rules/index.html.haml within layouts/application
I, [2017-05-12T00:17:50.776300 #3111]  INFO -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429]   Rendered organizations/_nav.html.haml (3.3ms)
I, [2017-05-12T00:17:50.776977 #3111]  INFO -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429]   Rendered organization_ip_pools/_nav.html.haml (0.4ms)
I, [2017-05-12T00:17:50.787426 #3111]  INFO -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429]   Rendered ip_pool_rules/index.html.haml within layouts/application (14.8ms)
I, [2017-05-12T00:17:50.787823 #3111]  INFO -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429] Completed 500 Internal Server Error in 164ms (ActiveRecord: 137.6ms)
F, [2017-05-12T00:17:50.789577 #3111] FATAL -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429]
F, [2017-05-12T00:17:50.789673 #3111] FATAL -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429] ActionView::Template::Error (undefined method `ip_pool' for nil:NilClass):
F, [2017-05-12T00:17:50.789974 #3111] FATAL -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429]     60:             %dl.ipPoolRuleList__condition
[89f3c3f8-d022-4dc1-9add-bca449bc2429]     61:               %dt Will be sent using:
[89f3c3f8-d022-4dc1-9add-bca449bc2429]     62:               %dd= ip_pool_rule.ip_pool.name
[89f3c3f8-d022-4dc1-9add-bca449bc2429]     63:     - if @server.ip_pool
[89f3c3f8-d022-4dc1-9add-bca449bc2429]     64:       %p.ipPoolRuleListDefault.u-margin All mail that doesn't match a rule above will be sent using #{@server.ip_pool.name}.
[89f3c3f8-d022-4dc1-9add-bca449bc2429]     65:     %p.u-center= link_to "Add another rule", [:new, organization, @server, :ip_pool_rule], :class => "button button--positive"
F, [2017-05-12T00:17:50.790055 #3111] FATAL -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429]
F, [2017-05-12T00:17:50.790140 #3111] FATAL -- : [89f3c3f8-d022-4dc1-9add-bca449bc2429] app/views/ip_pool_rules/index.html.haml:63:in `_app_views_ip_pool_rules_index_html_haml___1051384519009291652_52715760'
```

There are already rules which were added earlier but this error appears to only occur on the org that has rules. It loads OK on those without any rules.

**Comment by mattmartincouk** [comment]
Not sure this fix worked.

F, [2017-05-15T01:58:15.259185 #3041] FATAL -- : [47880832-20d9-4b63-bfb7-c1234d12b1dd] ActionView::Template::Error (undefined method `ip_pool' for nil:NilClass):
F, [2017-05-15T01:58:15.259475 #3041] FATAL -- : [47880832-20d9-4b63-bfb7-c1234d12b1dd]     60:             %dl.ipPoolRuleList__condition
[47880832-20d9-4b63-bfb7-c1234d12b1dd]     61:               %dt Will be sent using:
[47880832-20d9-4b63-bfb7-c1234d12b1dd]     62:               %dd= ip_pool_rule.ip_pool.name
[47880832-20d9-4b63-bfb7-c1234d12b1dd]     63:     - if @server && @server.ip_pool
[47880832-20d9-4b63-bfb7-c1234d12b1dd]     64:       %p.ipPoolRuleListDefault.u-margin All mail that doesn't match a rule above will be sent using #{@server.ip_pool.name}.
[47880832-20d9-4b63-bfb7-c1234d12b1dd]     65:     %p.u-center= link_to "Add another rule", [:new, organization, @server, :ip_pool_rule], :class => "button button--positive"
F, [2017-05-15T01:58:15.259579 #3041] FATAL -- : [47880832-20d9-4b63-bfb7-c1234d12b1dd]
F, [2017-05-15T01:58:15.259668 #3041] FATAL -- : [47880832-20d9-4b63-bfb7-c1234d12b1dd] app/views/ip_pool_rules/index.html.haml:63:in `_app_views_ip_pool_rules_index_html_haml___1796347729016451487_55497600'

Upgraded but that error still shows.

File confirmed on file system as having the changes in d33994c.

**Comment by adamcooke** [comment]
I think this is actually a different issue. I think you have a rule that belongs to an IP pool that no longer exists. I have made an adjustment to delete rules associated with a pool when it is deleted (9a76538f11064fb1bdb5f15aa8310ea04b68725c) but you'll need to track down the erroneous route and remove it manually I'm afraid. The following will do that in `postal console`:

```ruby
IPPoolRule.all.select { |i| i.ip_pool.nil? }.each(&:destroy)
```

**Comment by mattmartincouk** [comment]
Did that.

irb(main):001:0> IPPoolRule.all.select { |i| i.ip_pool.nil? }.each(&:destroy)
=> []
irb(main):002:0>

but it still errors.

Have checked in the database in ip_pool_rules and they all match to existing items that exist in other referenced tables.
