### ISSUE TITLE
sending emails via smtp

### ISSUE THREAD

**Issue by steliosmilidonis** [atech/postal#137]
Currently we use the following method for sending emails using a postfix server using smtp

We create an instance of javax.mail.Session and pass properties with server and login credentials
call session.getTransport("smtp") to get an instance of javax.mail.Transport
call transport.connect("login", "password")
loop all emails to send
    create an instance of javax.mail.internet.MimeMessage passing session 
    set subject, body, recipients etc on message
    call transport.sendMessage(message, message.getAllRecipients())
end loop
call transport.close()

the above methos works with plain postfix however when we use the smtp server on postal only the first email is send and we get a 530 authentication reuired for the rest.

Is there a way we can overcome this issue?

**Comment by catphish** [comment]
I believe this is a bug, causing the authentication credentials to be forgotten between multiple emails when the `RSET` command is used.  We will try to get this fixed shortly.

**Comment by steliosmilidonis** [comment]
Thanks for he quick reply , awaiting for the bug fix

**Comment by sahilsunesara** [comment]
could please please tell me how to send an email via SMTP?

I can send the test email from the command like postal test-app-smtp name@domain.com
then it's work perfectly but now I want to configure with application to send email but I am not able to verify. could you please guide me

**Comment by adamcooke** [comment]
@sahilsunesara Please don't hijack issues asking for support. If you need to ask a question, please open a new issue.

**Comment by catphish** [comment]
This should be fixed by dacddb4d8e32ed78de25278109e8d711f1a397fe
