### ISSUE TITLE
Updated today and it catch all my requests to port 80

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#139]
I have upgraded Postal today, and I can't access to my other webs ont he same server. It is like if Postal catch all the request, and then redirect to Postal in https.
Can it be related to Postal or not?
I didn't change anything on nginx, I olny upgraded Postal

**Comment by adamcooke** [comment]
Could it be related to this https://github.com/atech/postal/wiki/Abandoning-iptables?

That sounds like your nginx configuration though.

**Comment by elfeffe** [comment]
I just installed in on a separated server
