### ISSUE TITLE
API documentation or tests?

### ISSUE THREAD

**Issue by deepflame** [atech/postal#14]
Hi there,

first thanks for making this awesome project open source. Looks really well written.
However what I am kinda missing is tests/specs or any other kind of documentation.

Do you have that somewhere else? Could not find that in the repo.

Thanks
Andreas

**Comment by adamcooke** [comment]
Tests are lacking at the moment. I plan on adding a good suite shortly. The app was put together quite quickly but tests are going to be very much needed to maintain any sort of ability to keep the project maintained well. Expect to see these in the next few weeks.

API documentation can be found within the application itself when it's running. I will publish the API docs as some static HTML somewhere soon. In the meantime, you can view them [here](https://my.appmail.io/api/docs/v1/welcome). The API currently supports only a couple of methods but I also plan to add more methods as and when I find a need for them or someone asks for something.

**Comment by deepflame** [comment]
Great, thanks for the answer and your efforts. Good luck with the project!
