### ISSUE TITLE
smtp_server keeps dying suddenly

### ISSUE THREAD

**Issue by x86fantini** [atech/postal#140]
hello, after 2 weeks running smooth i suddely can not send any more email, and i always get this error

17:19:47 smtp.1          | => Tasks: TOP => postal:smtp_server
17:19:47 smtp.1          | => 
17:19:47 smtp.1          | => (See full trace by running task with --trace)
17:19:47 smtp.1          | => 
17:19:47 smtp.1          | Warning: this process has been respawned 5 times and keeps dying.
17:19:47 smtp.1          | It will not be respawned automatically any longer and will no longer be managed.
17:19:47 smtp.1          | Removed PID file

how can i trace the issue? thank you

**Comment by adamcooke** [comment]
There should really be more information above that which should give us a clue about what's happening. Is there anything?

**Comment by x86fantini** [comment]
Hi, after digging into logs, i saw "unabel to bind ::25" rather strange since it was working smooth. To fix it, i had to stop portal, run "sudo setcap 'cap_net_bind_service=+ep' /usr/bin/ruby2.3" then restart it.

i guess one one the recent update did broke this

rgds
S

**Comment by adamcooke** [comment]
Ah yes - likely related to this: https://github.com/atech/postal/wiki/Abandoning-iptables

Apologies - I don't have any good way (until we release a 1.0 and have proper release notes) to communicate things like this.
