### ISSUE TITLE
Build a new mail server

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#141]
hello

If i am creating new mail server with another domain name then do i need to add it into config.postal.yml? to use that domain

**Comment by adamcooke** [comment]
No. You add the domain on the Domains option under the server

**Comment by sahilsunesara** [comment]
okay, then how can i use that 2nd domain SMTP.

another question, i added another domain n send test message from postal web interface but it shows pending. what will be the reason?

Also please reply my another issue which i have created few days back
