### ISSUE TITLE
Can't use quick install script

### ISSUE THREAD

**Issue by ro78** [atech/postal#143]
Hello,

I'm trying to use "curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh" on an Ubuntu 16.04 x64 by default on DigitalOcean (under root account).

It seems to end by an error:

> Using bundler 1.14.6
> Installing sass 3.4.22
> Installing useragent 0.16.8
> Installing turbolinks-source 5.0.0
> Installing faraday 0.9.2
> Installing tzinfo 1.2.3
> Installing nokogiri 1.7.1 with native extensions
> /usr/bin/postal: line 19: 11817 Killed                  sudo -u postal bundle install --path=/opt/postal/app/vendor/bundle --without=development --jobs=4 --clean
> root@ubuntu-512mb-lon1-01:~#

Any idea?

Best regards,
Romain

**Comment by adamcooke** [comment]
You probably don't have enough RAM and it's being killed by the system. How much memory do you have?

**Comment by ro78** [comment]
I took the 512MB instance for tests.

**Comment by adamcooke** [comment]
That'll be it then 😄 It needs at least 2GB to run properly.

**Comment by ro78** [comment]
Thank you :)
