### ISSUE TITLE
Be able to sort routes by priority

### ISSUE THREAD

**Issue by ro78** [atech/postal#148]
Hello,

I've configured a rule to forward all incoming emails of "*@domain1.com" to an endpoint.

Let's say I want to have "admin@domain1.com" sent to one endpoint, and all other addresses to another endpoint. I'll have a route for admin@domain1.com, and another one for *@domain1.com, but I can't specify to apply admin@ first, and then *@ if first one doesn't match.

I think it can be nice to be able to change route order.

Romain

**Comment by adamcooke** [comment]
Postal should always choose the most specific route before choosing the wildcard.
