### ISSUE TITLE
RP record - route needed?

### ISSUE THREAD

**Issue by ro78** [atech/postal#149]
Hello,

The RP record, using for return-path values, is created as MX, TXT & A record in DNS.

When I send a message and this message is rejected by remote SMTP, the message is well detected as bounce.

But when message is accepted, and then bounce for an unknown reason, the message is rejected by postal because "rp.postal.mydomain.com" is not an existing domain.

I've added "rp.postal.mydomain.com" to my domains list, and added a route to accept all emails.

Is it the correct way to do things?

Romain

**Comment by mattmartincouk** [comment]
Probably similar to what was mentioned in #146.

Does your the rp name (where CNAME points) have an MX and TXT record?

**Comment by ro78** [comment]
Yes. I'll reinstall from scratch and try again. Email delivery is fine, but not bounces handling when transaction is accepted by remote SMTP, and bounce few minutes later.

**Comment by mattmartincouk** [comment]
You shouldn't need to do that.

Just check the DNS, or better yet, just post the PR domain for the address you've configured.

**Comment by ro78** [comment]
I generated an email to my gmail address.
I took the return-path value in headers, and answered to this address (lc5xvo@rp.postal.borezo.info).

Result : 530 Authentication required

**Comment by mattmartincouk** [comment]
But what is the address you are pointing to rp.postal.borezo.info by way of the CNAME?

 530 auth required is a completely different issue from what you reported earlier.

**Comment by ro78** [comment]
Ok, but 530 auth required is not supposed to happen when a bounce is sent to the @rp.postal.borezo.info address ?

**Comment by mattmartincouk** [comment]
I think your config is also wrong in that case but quite hard to determine from the limited information provided i'm afraid.

Maybe output the :dns section from your postal.yml file?

**Comment by ro78** [comment]
Here it is.
Just to be clear: my issue is that return-path address is not supposed to bounce when it receives an email.

> dns:
>   # Specifies the DNS record that you have configured. Refer to the documentation at
>   # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
>   # information about these.
>   mx_records:
>     - mx.postal.borezo.info
>   smtp_server_hostname: postal.borezo.info
>   spf_include: spf.postal.borezo.info
>   return_path: rp.postal.borezo.info
>   route_domain: routes.postal.borezo.info
>   track_domain: track.postal.borezo.info
>   dkim_identifier: postal
>   domain_verify_prefix: postal-verification
>   custom_return_path_prefix: psrp

**Comment by mattmartincouk** [comment]
That all looks OK so suspect something else is the cause - couldn't guess what though, sorry.

**Comment by ro78** [comment]
Can you try a telnet to port 25 of your telnet and simulate an email to your return-path domain, and post the output here?

I get:
> RCPT TO: <toto@rp.postal.borezo.info>
> 530 Authentication required

**Comment by ro78** [comment]
In domain DNS settings, I have the folllowing:

> Return Path
> 
> OK There's no return path for this domain. This is OK but we recommend adding the record to improve deliverability and achieve DMARC alignment.
> 
> This is optional but we recommend adding this to improve deliverability. You should add a CNAME record at psrp.borezo.info to point to the hostname below.
> 
> rp.postal.borezo.info

I don't know what to change to have something else than "There's no return path for this domain.".

**Comment by ro78** [comment]
I tried to send a real email to a bouncing email address where email is accepted and then bounced.

Here is the log (same issue - 530 Authentification required), so double bounce.

> [2.in-k.borezo.info] 2017/05/15 17:16:28.406860 INFO - smtpd  43196b7fe085d1d40805b52026f373c543e1110e - 127.0.0.1:40672 - starting new transaction 1/50
> [2.in-k.borezo.info] 2017/05/15 17:16:28.414858 INFO - smtpd  43196b7fe085d1d40805b52026f373c543e1110e - 127.0.0.1:40672 - connection upgraded to TLS 1.2 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
> [2.in-k.borezo.info] 2017/05/15 17:16:28.430328 INFO - smtpd  43196b7fe085d1d40805b52026f373c543e1110e - 127.0.0.1:40672 - MAIL FROM lc5xvo@rp.postal.borezo.info
> [2.in-k.borezo.info] 2017/05/15 17:16:28.431206 INFO - smtpd  43196b7fe085d1d40805b52026f373c543e1110e - 127.0.0.1:40672 - RCPT - + bounces@borezo.info
> [2.in-k.borezo.info] 2017/05/15 17:16:28.432393 INFO - smtpd  43196b7fe085d1d40805b52026f373c543e1110e - 127.0.0.1:40672 - message-id: ce5f42c5-9141-4e09-adfc-aa71640f230b@rp.postal.borezo.info
> [2.in-k.borezo.info] 2017/05/15 17:16:28.437083 INFO - smtpd  43196b7fe085d1d40805b52026f373c543e1110e - 127.0.0.1:40672 - message queued as 39b40018b436f8c47ce8af0ee269086b0efe9775
> [2.in-k.borezo.info] 2017/05/15 17:16:28.439298 INFO - smtpd  43196b7fe085d1d40805b52026f373c543e1110e - 127.0.0.1:40672 - EOT
> [2.in-k.borezo.info] 2017/05/15 17:16:28.440506 INFO - delivery-remote dcec7ee196155e9c2499bfd5481abef5380b4a6d: starting new remote delivery 4/50 from lc5xvo@rp.postal.borezo.info to bounces@borezo.info - Message-Id: ce5f42c5-9141-4e09-adfc-aa71640f230b@rp.postal.borezo.info - Queue-Id: 39b40018b436f8c47ce8af0ee269086b0efe9775
> [2.in-k.borezo.info] 2017/05/15 17:16:28.553563 INFO - deliverd-remote dcec7ee196155e9c2499bfd5481abef5380b4a6d - 212.83.146.78:5877 - TLS negociation succeed - TLS 1.2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> [2.in-k.borezo.info] 2017/05/15 17:16:28.608167 INFO - smtpd  ecd735d52b808230a8e7ea14e2f6cd39fe1acc26 - [::1]:53070 - client timeout
> [2.in-k.borezo.info] 2017/05/15 17:16:28.616956 ERROR - deliverd-remote dcec7ee196155e9c2499bfd5481abef5380b4a6d - 212.83.146.78:5877 - RCPT TO bounces@borezo.info failed - 5.5.1 Sorry, no mailbox here by that name - 5.5.1 Sorry, no mailbox here by that name
> [2.in-k.borezo.info] 2017/05/15 17:16:28.624764 INFO - delivery-remote eca4d9690aa3771fab2ca30ce33fe8842cd56a44: starting new remote delivery 5/50 from  to lc5xvo@rp.postal.borezo.info - Message-Id:  - Queue-Id: 4b83bb4b604e30ee868e07681bc5e6ee73a81132
> [2.in-k.borezo.info] 2017/05/15 17:16:28.626205 INFO - deliverd dcec7ee196155e9c2499bfd5481abef5380b4a6d: message from: lc5xvo@rp.postal.borezo.info to: bounces@borezo.info queued with id 4b83bb4b604e30ee868e07681bc5e6ee73a81132 for being bounced.
> [2.in-k.borezo.info] 2017/05/15 17:16:28.709231 ERROR - deliverd-remote eca4d9690aa3771fab2ca30ce33fe8842cd56a44 - 149.202.163.26:25 - RCPT TO lc5xvo@rp.postal.borezo.info failed - Authentication required - Authentication required
> [2.in-k.borezo.info] 2017/05/15 17:16:28.709457 INFO - deliverd eca4d9690aa3771fab2ca30ce33fe8842cd56a44: message from:  to: lc5xvo@rp.postal.borezo.info double bounce: discarding

**Comment by wuweifengsheng** [comment]
mark...

**Comment by Randall-Coding** [comment]
@ro78 I see that on another thread you were getting the error  

> "This message was a bounce but we couldn't link it with any outgoing message and there was no route for it."

Can you tell us me what fixed that?  I'm having the same issue
