### ISSUE TITLE
bundle install error "killed"

### ISSUE THREAD

**Issue by theratris** [atech/postal#15]
These are my logs from a clean install of Ubuntu 16.04

```
root@ubuntu-512mb-nyc2-01:~# postal bundle /opt/postal/app/vendor/bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Using rake 11.3.0
Using multipart-post 2.0.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.1
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 2.0.0
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Using authie 3.0.0
Using execjs 2.7.0
Using minitest 5.10.1
Using bcrypt 3.1.11
Using bson 4.0.4
Using byebug 9.0.6
Using chronic 0.10.2
Using coffee-script-source 1.10.0
Using method_source 0.8.2
Using thor 0.19.4
Using hashie 3.4.6
Using multi_xml 0.5.5
Using amq-protocol 2.0.1
Using deep_merge 1.1.1
Using dynamic_form 1.1.4
Using encrypto_signo 1.0.0
Using epoll 0.3.0
Using tilt 2.0.5
Using jwt 1.5.6
Using mysql2 0.4.4
Using nifty-utils 1.1.7
Using basic_ssl 1.0.3
Using bundler 1.14.6
Using sass 3.4.22
Using useragent 0.16.8
Using turbolinks-source 5.0.0
Using faraday 0.9.2
Using tzinfo 1.2.3
Installing puma 3.8.2 with native extensions
Installing json 1.8.6 with native extensions
Installing nokogiri 1.7.1 with native extensions
/usr/bin/postal: line 19: 23845 Killed                  sudo -u postal bundle install --path=/opt/postal/app/vendor/bundl
e --without=development --jobs=4 --clean
```

**Comment by theratris** [comment]
Oddly enough I ran the same command again and this time it got farther but still failed.
`root@ubuntu-512mb-nyc2-01:~# postal bundle /opt/postal/app/vendor/bundle`

`root@ubuntu-512mb-nyc2-01:~# postal bundle /opt/postal/app/vendor/bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Using rake 11.3.0
Using multipart-post 2.0.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.1
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 2.0.0
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using amq-protocol 2.0.1
Using authie 3.0.0
Using minitest 5.10.1
Using execjs 2.7.0
Using basic_ssl 1.0.3
Using bcrypt 3.1.11
Using bson 4.0.4
Using byebug 9.0.6
Using chronic 0.10.2
Using coffee-script-source 1.10.0
Using method_source 0.8.2
Using thor 0.19.4
Using hashie 3.4.6
Using arel 7.1.4
Using deep_merge 1.1.1
Using dynamic_form 1.1.4
Using encrypto_signo 1.0.0
Using epoll 0.3.0
Using tilt 2.0.5
Using jwt 1.5.6
Using mysql2 0.4.4
Using nifty-utils 1.1.7
Using multi_xml 0.5.5
Using bundler 1.14.6
Using sass 3.4.22
Using useragent 0.16.8
Using turbolinks-source 5.0.0
Using faraday 0.9.2
Using tzinfo 1.2.3
Installing puma 3.8.2 with native extensions
Installing json 1.8.6 with native extensions
Installing nokogiri 1.7.1 with native extensions
Installing rack-test 0.6.3
Installing sprockets 3.7.1
Installing websocket-driver 0.6.5 with native extensions
/usr/bin/postal: line 19: 24448 Killed                  sudo -u postal bundle install --path=/opt/postal/app/vendor/bundl
e --without=development --jobs=4 --clean`

**Comment by adamcooke** [comment]
Looks like your running out of RAM and the system is killing it. What resources have you allocated to it? I can reduce the memory requirement of the bundle command but you'd likely run into issues down the line.

**Comment by theratris** [comment]
Trying to run on 512mb RAM, I suspected this was an issue :(

**Comment by adamcooke** [comment]
Yeh. That'll be it then. You'll need a bit more than that. Probably 4GB although you'll get away with 2GB for a small instance.

**Comment by theratris** [comment]
Added 5GB of swap and back in business! Thanks for the quick answer, so excited to try this out :)

**Comment by adamcooke** [comment]
Good to know. Let us know if you have any other issues.
