### ISSUE TITLE
Slow sending "Message is currently being processed." for some minutes

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#150]
I'm trying the system, I just send one sample email and it is queued for some minutes before send, there is no message about why.
Any idea where can I search for the reason?

**Comment by elfeffe** [comment]
It made a soft fail now
It says

> No SMTP servers were available for gmail.com. Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com

And 
>Network is unreachable - connect(2) for "2a00:1450:400b:c03::1a" port 25, execution expired, Network is unreachable - connect(2) for "2a00:1450:4013:c03::1a" port 25, Network is unreachable - connect(2) for "2a00:1450:4010:c08::1b" port 25, Network is unreachable - connect(2) for "2404:6800:4003:c01::1a" port 25, Network is unreachable - connect(2) for "2404:6800:4008:c03::1a" port 25
Support Ref: V1N1PNKZ


This is an email for a xxx@gmail address

**Comment by ro78** [comment]
It means your server can't reach other ones over IPv6. Check with your provider.

**Comment by adamcooke** [comment]
Does look like an IPv6 problem there. Do you have IPv6 configured?

**Comment by elfeffe** [comment]
I use Amazon EC2
Any idea about how to reach IPv6 with Ubuntu 16.04?
Or how to setup it in Ubuntu, but i think Ubuntu by default should access remote servers with IPv6

**Comment by mattmartincouk** [comment]
IPv6 is probably outside the scope of the support for the project, at a guess.

I'd disable v6 for testing to confirm the software is working fine and then spend some time diagnosing that as a separate issue.

**Comment by ro78** [comment]
IPv6 works on my side.

**Comment by adamcooke** [comment]
If you don't have any IPv6 addresses configured on your IP pool, it shouldn't even try and use any AAAA records and therefore no IPv6 should be tried.

**Comment by elfeffe** [comment]
I have switched to Digital Ocean and it didn't fail until now.
Anyway documentation for IP Pools is still not available, or it is?

**Comment by mattmartincouk** [comment]
@elfeffe - IP Pools are very easy to understand.. I wouldn't think you'd need any docs specifically for it if you navigate the GUI a little. :)

**Comment by elfeffe** [comment]
The official Doc says

> Configuring multiple IP pools will be covered in other documentation.
Here https://github.com/atech/postal/wiki/Installation

The thing is that I can'f find where IP Pools are located, at least in the GUI

**Comment by mattmartincouk** [comment]
Top right - "IP Pools".

https://postal-url/ip_pools

**Comment by elfeffe** [comment]
Thank you, url works, but there is no link on top right.
I use latest version, I think I saw that link on previous versions

**Comment by mattmartincouk** [comment]
I'm running latest and it is there.

Have you enabled in config?

```
general:
  use_ip_pools: true
```

I'd recommend opening a new issue as this one is going off-topic a little.

**Comment by elfeffe** [comment]
Now this is there, thank you.
About delay, it can be related to IPv6, I will see if I still have problems using Digital Ocean

**Comment by adamcooke** [comment]
I'll get around to documenting IP pools soon - apologies! See #87
