### ISSUE TITLE
How to Separate Transactional and Promotional emails ?

### ISSUE THREAD

**Issue by dinu865** [atech/postal#152]
I would like to separate Transactional  & promotional emails for a domain & also i don want to queue the transnational email while shooting the promotion mails .

Dinesh

**Comment by adamcooke** [comment]
At present there is only a single queueing mechanism to separate the processing of the queue based on the type of message. All messages are treated equal. At present, to achieve this you'd need a second installation of Postal.

**Comment by dinu865** [comment]
Thanks for your prompt reply Adam . I know it is possible to prioritise the rabitmq queue. I will pass header with transactional and promotional email and based on the header I am gonna prioritise the queue. I hope it would be the right way to go.Could you please guide me which file I need to look out for?
