### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by beeing** [atech/postal#158]
Hi, I'm trying out Postal but not able to login. There are some CSRF token errors and displayed as below:

![login-error](https://cloud.githubusercontent.com/assets/28744192/26133871/1538dffe-3add-11e7-9726-17ed4179ed90.png)

Is there anything I missed?

Thanks.

**Comment by stayallive** [comment]
I had to disable the forgery protection origin check. However on the latest version I have it enabled and it works just fine (with it enabled, which is the default). Nothing changed on my server setup so I think it might be solved somehow!?

This was my workaround: stayallive/postal@2091a436182272bdd1315979d353c58585405402

**Comment by catphish** [comment]
It's very likely that this was just a browser cookie problem. I'd definitely recommend against disabling the security check if possible. If this happens again, try clearing browser cookies and see if it still occurs.

**Comment by beeing** [comment]
I’ve cleared the cookies, caches, anything that I can find and then reload the Postal login page.

I saw there are 2 cookies created: browser_id and _deliver_session

But when I login the same screen still appears.

The weird thing is that my colleague on a Windows PC able to login but I’m on Mac which can’t login.

**Comment by coderfox** [comment]
Same problem here also macOS Chrome. On Android FireFox login works.

**Comment by mrudelle** [comment]
For anyone interested: Another cause can be a miss-configured "Host" header. For some reason we had two nginx proxy in front of Postal and the second proxy was not configured with

```proxy_set_header Host $http_host;```

So host was rewritten by `proxy_pass` based on the upstream's server hostname which somehow caused the same problems.
