### ISSUE TITLE
Style and JS dosen't found

### ISSUE THREAD

**Issue by minusmillionaer** [atech/postal#16]
Hi

we have installed Postal on CentOS 6 successfully installed. But the Style and JavaScript dosen't load. Somewhere else with this problem?

<img width="604" alt="bildschirmfoto 2017-04-26 um 23 19 21" src="https://cloud.githubusercontent.com/assets/3305960/25457553/02e7bfa2-2ad7-11e7-87ef-88caa22e9e95.png">
<img width="1383" alt="bildschirmfoto 2017-04-26 um 23 18 57" src="https://cloud.githubusercontent.com/assets/3305960/25457552/02e5fbc2-2ad7-11e7-9f68-4dc22b4faf77.png">

**Comment by adamcooke** [comment]
Did you load though nginx or directly on port 5000? Assets are served by nginx so it needs to be in front of the app's web server.

**Comment by minusmillionaer** [comment]
I have an Apache reverse proxy. But when I load the site directly, I get the same error.

**Comment by adamcooke** [comment]
Is your Apache configured to serve files if they exist from /opt/postal/app/public?

**Comment by minusmillionaer** [comment]
The Apache is configured as reverse proxy only.

**Comment by adamcooke** [comment]
That's correct. The proxy needs to serve the static files for you. The web server on port 5000 doesn't serve assets at all. I will enable static file serving from the web server but you'll get better performance if you configure it to serve them properly.

**Comment by minusmillionaer** [comment]
Ok. Thank you! I've configured my Apache for static files and it works.

**Comment by adamcooke** [comment]
Great
