### ISSUE TITLE
Problems with multiple ips in pool

### ISSUE THREAD

**Issue by afanjul** [atech/postal#161]
Hi there,
These days we are trying to warm up our ip's, sending a % ratio of our platform emails through postal.

- We had configured 3 pools (P.A, P.B, P.C) with 1 ip in each one (P.A -> IP.A, P.B -> IP.B, P.C -> IP.C).
- We had configured 3 mail servers with a default pool for each one (MS.A -> P.A, MS.B -> P.B, MS.C -> P.C). No IP pools rules anywhere.

The fact is that yesterday I realised that (as we are only sending through Mail Server C (due to our needs)) we have been only warming up 1 IP (IP.C). So I added the two other IPs to the Pool C too. (P.C -> IP.C & IP.B & IP.A). (The hostnames of each IP remain the same too for PTR convenience).

Today I realised that **all of our emails that have been trying to be sent throgh IP.A and IP.B are in queue** without any "sending action" from postal server. 

Once we have removed the IP.A and IP.B from pool C, all the emails have been starting to send again... (I did a postal restart in the middle of this process).

As you can [see here](https://i.snag.gy/BJ3Qli.jpg) all of the queued messages are from this ip's (4 and 5).

Any idea? I will tray to investigate a bit further.
thanks in advance

**Comment by adamcooke** [comment]
When a message is queued with a IP it is added to a different queue on RabbitMQ. Specifically it will be `outgoing-ID` where the ID is the ID of the IP address.

The worker will only listen for messages on the queues where it has the IP configured though so if you have IPs configured in Postal but they aren't actually configured on any servers, the messages will never be able to processed. 

It is designed in this way to ensure that the system works in a clustered installation where IPs can be moved between hosts on failures because only the server with the IP is able to send messages from it.

**Comment by adamcooke** [comment]
I have recently documented IP pools and have made sure to mention this on those docs: https://github.com/atech/postal/wiki/Configuring-IP-Pools

**Comment by afanjul** [comment]
Clarification: when I say Mail Server, Im refering to a "software" mail server configured in Postal. The "mail servers" you can add per organization.

What do yo mean when you say "It's important to make sure that the IP addresses you add in the web interface are actually configured on your Postal servers" ? Are you refering to configure it as real IPs on the machine? In such a case, yes I have the 3 IPs properly configured in my machine.

```
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:50:56:01:28:dc brd ff:ff:ff:ff:ff:ff
    inet x.x.x.1/16 brd x.x.255.255 scope global enp0s3
    inet x.x.x.2/16 brd x.x.255.255 scope global enp0s3
    inet x.x.x.3/16 brd x.x.255.255 scope global enp0s3
    inet6 fe80::250:56ff:fe01:28dc/64 scope link
```

In deed we can actually send emails from the 3 pools (with and IP in eachone) assigned to each mail server. The problem is when I add the first 2 IPS also to the 3rd pool. The emails processed through theses ips wont be sent.

**Comment by afanjul** [comment]
So that is maybe the problem! ^_^, thanks adam

**Comment by jsahani** [comment]
Can you please elaborate this point.
"It's important to make sure that the IP addresses you add in the web interface are actually configured on your Postal servers" ? Are you refering to configure it as real IPs on the machine?"

Kindly add more details where to add those IP's in machine, also which file and how.

Thanks

**Comment by adamcooke** [comment]
You'll need some experience managing a Linux server in order to add IPs to your network interfaces. I suggest posting over on something like ServerFault if you need help with this.
