### ISSUE TITLE
Tracking Domains setup

### ISSUE THREAD

**Issue by Casear** [atech/postal#162]
I try to add a tracking domain. there is error message  "CNAME not configured correctly".
but I didn't see any document about this setting.

I found this description
"This is the domain that requests for tracked links will be directed through when you use click tracking. We recommend using something like click.yourdomain.com. You will need to a CNAME record to point to track.kitchbot.com for this once you've added it."

not sure how make the setting.

**Comment by adamcooke** [comment]
You need to set up on your own DNS server. You should also ensure you have set up `track.kitchbot.com` as per [the instructions](https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration).
