### ISSUE TITLE
Access mechanism so I can use postal like SMTP server to send emails from my interspire

### ISSUE THREAD

**Issue by johnLeads** [atech/postal#166]

**Comment by adamcooke** [comment]
What?

**Comment by johnLeads** [comment]
I want configure for example 10 IPs in postal to send  mails. Then is there some kind of mechanism here so i can use postal has SMTP server in Interspire like SMTP: postal.mydomain.com   User: info password : xxxx Port: 25 Protocol : TLS. Then postal will deliver my email using 10 IPs

**Comment by johnLeads** [comment]
Interspire > Campaigns > Postal : as SMTP Server: > Load Balance b/w 10 IPs

**Comment by ro78** [comment]
Where Interspire is hosted:
- configure Interspire to use Postal as SMTP if possible
- else, configure the local SMTP (like Postfix) to use Postal as relay

**Comment by johnLeads** [comment]
Yes exactly what i want to achieve "configure Interspire to use Postal as SMTP if possible" Now how to do that? as I didn't found any authentication mechanism?

**Comment by ro78** [comment]
Click on your Organization in Postal > select your mail server > Credentials tab
Create a user.
Then on the credential page, click on Help, you will see SMTP address, port, username and password to configure in Interspire.

**Comment by johnLeads** [comment]
How can we setup postal SMTP in Outlook. Its working for interspire but not working for Postal

**Comment by wuweifengsheng** [comment]
I also want know this too.

**Comment by johnLeads** [comment]
https://github.com/atech/postal/issues/204

**Comment by johnLeads** [comment]
Check this they says this can't be done
