### ISSUE TITLE
Sending on Behalf Of

### ISSUE THREAD

**Issue by asithade** [atech/postal#168]
Hi there,

Is it possible for postal to send messages on behalf of other users? 

I.e; when Campaign Monitor sends an email, it shows something like: 
![on-behalf-of-a3 1](https://cloud.githubusercontent.com/assets/3814354/26179524/1ff3ca44-3b19-11e7-9174-6949f0e48d6e.png)

So say I have domain.com and my user has user@gmail.com, I want to send an email on behalf of them as such. Is that possible to do with Postal?

**Comment by afanjul** [comment]
Yes you can, you have to configure the postal mail server to be able to send from any sender, and be sure to add the "sender" header to your emails from your client. For example like this. https://github.com/atech/postal/issues/131#issuecomment-301752362

**Comment by johnLeads** [comment]
What about incoming mails? I have setup mx record correctly but still unable to recive email. m getting server token invalid error whenever try to send email from gmail to my postal server

**Comment by asithade** [comment]
@johnLeads I think you're having a different issue to what I'm trying to achieve here. Please open a separate issue.

@afanjul Thanks for that. I've set it up, and send in the "Sender" header, but get the following error when I try to send:

`Postal::SendError: [UnauthenticatedFromAddress] The From address is not authorised to send mail from this server`

**Comment by adamcooke** [comment]
Try setting it with `m.sender = "address@example.com`.

**Comment by catphish** [comment]
I think it's a method. Maybe:

```
m.sender "address@example.com"
```

**Comment by adamcooke** [comment]
@catphish is correct. No equals needed.

**Comment by asithade** [comment]
That worked perfectly! Thanks guys :)
