### ISSUE TITLE
After upgrade i got SMTP error

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#169]
hello
now i am testing from command line i got error 

postal test-app-smtp apps@mailleaders.com

Message was not delivered successfully to SMTP server.
Error: Errno::ECONNREFUSED (Connection refused - connect(2) for "mail.mailleaders.com" port 2525)

  SMTP Host: mail.mailleaders.com
  SMTP Port: 2525
  SMTP Username: mailleaders/mailleaders
  SMTP Password: as per system genrate

**Comment by adamcooke** [comment]
Check https://github.com/atech/postal/wiki/Abandoning-iptables.
You may want to change the port to 25 rather than 2525.

**Comment by hrmshandy** [comment]
I have some problem

Message was not delivered successfully to SMTP server.
Error: Errno::ECONNREFUSED (Connection refused - connect(2) for "mail.wuling.id" port 25)

  SMTP Host: mail.wuling.id
  SMTP Port: 25
  SMTP Username: wuling/wuling
  SMTP Password: as per system genrate

**Comment by ankitsamarthya** [comment]
I am getting the same error when I am trying to do

postal test-app-smtp (some email)

I am able to send using web interface though.

@sahilsunesara were you able to solve the problem?

**Comment by willpower232** [comment]
Check your firewall and make sure the settings you are using are correct. If you keep experiencing problems, do open a new issue rather than replying to a closed one.

**Comment by ankitsamarthya** [comment]
@willpower232 Thanks. I checked the firewall status and its inactive, also settings looks good to me. I will open a new issue.
