### ISSUE TITLE
NGINX fails to restart after making changes

### ISSUE THREAD

**Issue by theratris** [atech/postal#17]
After running: 
`sudo /etc/init.d/nginx restart`

I get the output: 
```
[....] Restarting nginx (via systemctl): nginx.serviceJob for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
 failed!
```
Here is the error log:

```
-- Unit nginx.service has begun starting up.
Apr 26 22:10:00 ubuntu-512mb-nyc2-01 nginx[2011]: nginx: [emerg] BIO_new_file("/etc/nginx/ssl/postal.crt") failed (SSL: e
Apr 26 22:10:00 ubuntu-512mb-nyc2-01 nginx[2011]: nginx: configuration file /etc/nginx/nginx.conf test failed
Apr 26 22:10:00 ubuntu-512mb-nyc2-01 systemd[1]: nginx.service: Control process exited, code=exited status=1
Apr 26 22:10:00 ubuntu-512mb-nyc2-01 systemd[1]: Failed to start A high performance web server and a reverse proxy server
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has failed.
-- 
-- The result is failed.
Apr 26 22:10:00 ubuntu-512mb-nyc2-01 systemd[1]: nginx.service: Unit entered failed state.
Apr 26 22:10:00 ubuntu-512mb-nyc2-01 systemd[1]: nginx.service: Failed with result 'exit-code'.
Apr 26 22:10:00 ubuntu-512mb-nyc2-01 sudo[1998]: pam_unix(sudo:session): session closed for user root
```

Perhaps I made a mis-configuration in the previous step?

**Comment by adamcooke** [comment]
One of those lines looks truncated. Looks like an issue with the SSL cert in /etc/nginx/ssl/postal.crt. Did you generate one for it?

**Comment by theratris** [comment]
Yes I ran
`openssl req -x509 -newkey rsa:4096 -keyout postal.key -out postal.crt -days 365 -nodes`

But in the config file I left those postal.key & postal.crt alone because I felt they were correct. Did I need to edit those? I only changed two lines to add my domain.

**Comment by adamcooke** [comment]
It depends what directory you were in when you ran the OpenSSL command. Make sure you run it while within /etc/nginx/ssl. I'm not sure that's clear in the docs so I will fix that later too.

**Comment by theratris** [comment]
That folder didn't exist on my system. I went ahead and created it then ran the openssl command it in but it did not fix my issue.

**Comment by adamcooke** [comment]
It could also be the dhparam.pem which is missing too. You can just comment that out and restart. Let me know any errors you see after that.

**Comment by adamcooke** [comment]
I've updated the default nginx config in the repo to comment that out.

**Comment by theratris** [comment]
After commenting out that line NGINX succeeded in restarting!
