### ISSUE TITLE
Mass mail on 1 org causes delays on other orgs

### ISSUE THREAD

**Issue by ro78** [atech/postal#173]
Hello,

I created 2 organizations, both with 1 mail server.

I've sent 10 000 emails to the mail server of org1, then sent 1 email to the mail server of org2.

The mail sent to the org2 mail server is not sent until the queue of 10 000 emails of org1 are done.

Is it normal?

I was expecting that both queues will be proceed at the same time, so I can dispatch campaigns to an org, and transactionals to another one, to ensure transactional emails to be delivered quickly.

Best regards,
Romain

**Comment by adamcooke** [comment]
That is normal on a default install when you only run a single worker. You need more workers to process mail faster. You can add more workers by specifying the quantity in the content file:

```yaml
workers:
  quantity: 10
```

You then need to restart Postal.

**Comment by catphish** [comment]
To clarify, all messages will be processes in the order they are received. There is currently no concept of fair queueing between different mail servers, just a global first-in-first-out.

**Comment by ro78** [comment]
Got it. I truly hope it will change, first-in-first-out is OK for me, if it's only based on mail servers, or at least on organizations. If it's for the entire database, no matter the mail server and/or organization, it's dangerous. In case of mass mailing on one mail server, all other mail servers of the same organization and also other organizations will be impacted.
