### ISSUE TITLE
New feature - contacts list

### ISSUE THREAD

**Issue by ro78** [atech/postal#174]
Hello,

I think it can be nice, inside a mail server or inside an organization, to create a contact list.

A simple form or file import, with list of email addresses, like user1@gmail.com and user2@gmail.com.
When contact list is created, an unique ID is generated and assigned to it.
Then, with only 1 email sent to "ID"@my_postal_domain.com, Postall will automatically dispatch this email to all contacts.

A plus will be to be able to add variables to each contacts (like firstname, lastname, etc), and ask Postal to automatically replace values in the body of the email (example, replace %FIRSTNAME% by the value of the FIRSTNAME variable.

Another one, will be to have an unsubscribe header automatically added to these emails, with a unique email address or link for each contact, so he can use it to unsubscribe.

Romain

**Comment by hd719** [comment]
Hello @ro78 and @catphish can I work on this? 

-Thank you.

**Comment by ro78** [comment]
Of course you can :)

**Comment by catphish** [comment]
I'd suggest the person to ask is @adamcooke as he usually merges and he's very particular about UX and design :1st_place_medal:

**Comment by adamcooke** [comment]
This isn't really something that would fit anywhere in Postal. Postal is an MTA and isn't responsible for managing contact lists or address books.

**Comment by ro78** [comment]
From my point of view Postal is not only a MTA but a complete ESP solution, and integrate such feature will be great.
