### ISSUE TITLE
Failure Code

### ISSUE THREAD

**Issue by longhorninmd** [atech/postal#175]
We've been trying to configure our front-end app to be able to relay mail through postal (running on an EC2 AWS instance).  The SMTP authentication seems to be inconsistent.  For many recipients, the logging shows error:

"530 Authentication required[0m"

However, there are some recipients for which the connection is accepted and the message processed:

"334 PGYzZTE5N2MyZDEyNDE0NjEyY2I5QG10YS5taWdvMDEubmV0Pg==[0m"
"235 Granted for ..."
(after the DATA command) "354 Go ahead[0m"

Has anyone else experienced this?  If so, how did you solve the issue?

Thx!

**Comment by catphish** [comment]
Are you able to provide the full SMTP server log for the connection where this occurs?

**Comment by longhorninmd** [comment]
Does this help?

[34m[smtp.1:32384][0m [2017-05-12T08:53:03.430] DEBUG -- : [T0QRKN] [34m=> 250 OK[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.530] DEBUG -- : [T0QRKN] [32m<= MAIL FROM:<bounce-1683452-7796-248-452@app.xxxxxx.com>[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.531] DEBUG -- : [T0QRKN] [34m=> 250 OK[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.615] DEBUG -- : [T0QRKN] [32m<= RCPT TO:<xxxxxxxx@yandex.com>[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.623] DEBUG -- : [T0QRKN] [34m=> 530 Authentication required[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.709] DEBUG -- : [T0QRKN] [32m<= RSET[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.709] DEBUG -- : [T0QRKN] [34m=> 250 OK[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.807] DEBUG -- : [T0QRKN] [32m<= MAIL FROM:<bounce-1683452-8612-248-452@app.xxxxxxxx.com>[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.808] DEBUG -- : [T0QRKN] [34m=> 250 OK[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.893] DEBUG -- : [T0QRKN] [32m<= RCPT TO:<xxxxxxxxx_mail@yahoo.com>[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.901] DEBUG -- : [T0QRKN] [34m=> 530 Authentication required[0m
[34m[smtp.1:32384][0m [2017-05-12T08:53:03.986] DEBUG -- : [T0QRKN] [32m<= RSET[0m

**Comment by catphish** [comment]
Yes, that is very helpful. Can you confirm what revision of the software you are running? Some changes were made very recently that may already fix this bug.

**Comment by longhorninmd** [comment]
release-0

**Comment by adamcooke** [comment]
`release-0` isn't a commit ref, tag name or version number of Postal.

**Comment by catphish** [comment]
Looking again at the log, I see you are using the `RSET` command. There was a bug where `RSET` un-authenticated a connection, so it's very likely this is your problem. This bug was fixed in dacddb4d8e32ed78de25278109e8d711f1a397fe so it's extremely likely that if you upgrade, this will be resolved.

If the problem persists, could you perhaps get the *full* log of an SMTP session so that we can see whether this session was authenticated or not.

**Comment by longhorninmd** [comment]
Just wanted to report that the update did the trick.  Thanks for your help!
