### ISSUE TITLE
Integrate Mailtrain with Postal

### ISSUE THREAD

**Issue by afanjul** [atech/postal#176]
Hi @adamcooke, firstly thanks for your patient and your really helpful answers to all our questions and doubts using Postal.

Podría insertar información en una cabecera customizada en los emails, para que luego se incluya en el json payload de los eventos de postal?

We are trying to integrate [Mailtrain](https://github.com/Mailtrain-org/mailtrain) [a Mail Marketing web app] with Postal. All it's working fine. The only thing that remains for us to do is the "bounce - webhook" integration. So for that, Mailtrain is using custom headers with the "message id" in outgoing mails so MTA's could send such info back in case of bounces/fails using webhooks events. 

So for example, when you use Mailtrain in conjunction with Sendgrid (as MTA), Mailtrain add [this custom header](https://github.com/Mailtrain-org/mailtrain/blob/85cefc14e8aeed3457b896be6f8063d44a01e9d6/services/sender.js#L406) so that Sendgrid (according [to its api](https://sendgrid.com/docs/API_Reference/SMTP_API/index.html)) could send back the campaign_id to Mailtrain when messages are bounced using a webhook. Mailtrain will be listening (in [this case for sendgrid](https://github.com/Mailtrain-org/mailtrain/blob/d7c06e0a5a0f5dc212fbb7d1b3124b13e8ae0b68/routes/webhooks.js#L171)) to retrieve the message and mark it as bounced.

I'm developing the Postal integration in Mailtrain, but for that, **I would like to know if there is some kind of "custom headers" I could add to messages from Mailtrain so that Postal could sendback this custom info** into the JSON Payload of events (something like x-postal-api).

If it doesn't exist, could you please kindly tell me what files should i "touch" to add this feature in Postal? (I'm sorry I don't know the source code but with some pseudocode or little guide, I could try a pull resquest too).

Many thanks in advance,
Alex

**Comment by stayallive** [comment]
@afanjul looking at the documentation this is already possible. You can set your own message ID through the SMTP or HTTP API and Postal will return that id (`message.message_id`) in the wehook requests allowing you to track the message. 

> https://github.com/atech/postal/wiki/Webhook-Events-&-Payloads

If you require a custom header it is not possible yet since the webhook API does not return any headers and the docs currently state you should retrieve any extra info through their API directly if you require so.

**Comment by afanjul** [comment]
Thanks, I'll give it a try!
