### ISSUE TITLE
Click & open tracking same domain only

### ISSUE THREAD

**Issue by alexroosenstein** [atech/postal#177]
I noticed it only adds click & open tracking to emails if the domain it's sent from is the same as the (parent) tracking domain. (E.g. from: loremipsum@example.com, tracking domain: click.example.com)
But when sending from a different domain than the (parent) tracking domain nothing is added.

Is this intended? Maybe it's something related to my install of Postal, maybe someone else can confirm this behaviour? I did a postal auto-update roughly 30 minutes ago.

**Comment by adamcooke** [comment]
That is the correct & intended behaviour.

**Comment by alexroosenstein** [comment]
May I suggest an enhancement then?
Perhaps a setting where you can define a default tracking domain, which is used regardless of the parent/main domain.

**Comment by webhostinggeek** [comment]
Can we only track email open without adding any URL? 99% emails will not have URL's but we want to track who opened and who did not open.
