### ISSUE TITLE
Log rejected SMTP in GUI

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#178]
Just a suggestion, if possible.

We setup postal for some of our chat transcripts which appeared to be working OK in testing but only after not getting some messages did we find that the chat software sets the from address to the person chatting when sending us a copy - as would be useful.

Postal rejected that because of the from header.

Could messages that are authenticated but have incorrect from headers be logged in the GUI at all?

For now, we've adjusted their code to include a "Sender:" line but not ideal as updates may (will) overwrite it.

**Comment by adamcooke** [comment]
We don't really have anything in the web interface to display errors like this. You'll find the error in your smtp.log file so you could keep an eye on that for updates. The correct solution would be for the application that sends the message to raise an error (or at least notify) when an SMTP server doesn't accept their message.
