### ISSUE TITLE
3800 messages blocked in queue - Raven errors and TCP error

### ISSUE THREAD

**Issue by ro78** [atech/postal#180]
Hello,

Emails are blocked in queue.

Here is what I see in logs (I tried postal restart, OS reboot, nothing better).

> ==> rails.log <==
> [3768] [2017-05-23T06:38:08.523] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> [3772] [2017-05-23T06:38:11.321] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> [worker.5:3802] [2017-05-23T06:38:35.736] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> [worker.2:3795] [2017-05-23T06:38:35.742] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> [worker.4:3799] [2017-05-23T06:38:35.746] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> [smtp.1:3808] [2017-05-23T06:38:35.770] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> [worker.3:3797] [2017-05-23T06:38:35.772] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> [requeuer.1:3810] [2017-05-23T06:38:35.798] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> [worker.1:3793] [2017-05-23T06:38:35.842] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> [cron.1:3805] [2017-05-23T06:38:35.977] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
> 
> ==> smtp_server.log <==
> [smtp.1:3808] [2017-05-23T06:38:37.201] INFO -- : Listening on port 25
> 
> ==> message_requeuer.log <==
> [requeuer.1:3810] [2017-05-23T06:38:37.203] INFO -- : Running message requeuer...
> 
> ==> cron.log <==
> [cron.1:3805] [2017-05-23T06:38:37.312] INFO -- : Starting clock for 8 events: [ every-1-minutes every-15-minutes every-15-minutes every-15-minutes every-15-minutes every-hour every-hour every-day ]
> [cron.1:3805] [2017-05-23T06:38:37.330] INFO -- : Triggering 'every-1-minutes'
> [cron.1:3805] [2017-05-23T06:38:37.343] ERROR -- : Could not establish TCP connection to any of the configured hosts
> 
> ==> rails.log <==
> [web.1:3791] [2017-05-23T06:38:37.988] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
>

**Comment by TrollAH** [comment]
I think this is the relevant line: 

> [cron.1:3805] [2017-05-23T06:38:37.343] ERROR -- : Could not establish TCP connection to any of the configured hosts

I would guess that something went wrong with rabbitMQ?

**Comment by ro78** [comment]
It seems that my disk is full. I'm checking it, I'll close if I fix it after disk cleanup.
