### ISSUE TITLE
Error: EOFError (end of file reached)

### ISSUE THREAD

**Issue by w3update** [atech/postal#184]
Hi,

I am getting following error 
"Message was not delivered successfully to SMTP server.
Error: EOFError (end of file reached)"
while testing the app on command line using 
postal test-app-smtp email@mydomain.com

any idea?

**Comment by catphish** [comment]
Have a look in the SMTP server log. Post the logs here if you're not sure what's happening.

**Comment by w3update** [comment]
![image](https://cloud.githubusercontent.com/assets/4979654/26351358/f5d0aec4-3fd4-11e7-85fe-3bc83714f41c.png)

This is my port status 
getting this error while connecting to smtp  
[Connection timed out #110] (code: 0)

Also as per screenshot it seems IPv6 25 only enabled? I also checked after disabling ufw to stop.

after making changes to port and restarting postal restart not new port open 

as I can see in status with netstat -tulpn

**Comment by w3update** [comment]
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.949] DEBUG -- : [NUK8KW] Not logging further message data.
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.998] ERROR -- : [NUK8KW] An error occurred while processing data from a client.
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] Bunny::AuthenticationFailureError: Authentication with RabbitMQ failed. Please check your connection settings. Username: postal, vhost: /postal, password length: 14
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/session.rb:1082:in `open_connection'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/session.rb:304:in `start'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/rabbit_mq.rb:15:in `create_connection'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/rabbit_mq.rb:20:in `create_channel'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/worker.rb:181:in `job_channel'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/worker.rb:187:in `job_queue'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/job.rb:28:in `queue'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/app/app/models/queued_message.rb:46:in `queue'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:382:in `block in make_lambda'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:232:in `block in conditional'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:456:in `block in call'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:456:in `each'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:456:in `call'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_commit_callbacks'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:354:in `committed!'
[34m[smtp.1:3849][0m [2017-05-23T07:03:37.999] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:87:in `commit_records'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:178:in `commit_transaction'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:202:in `within_new_transaction'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:324:in `save!'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/suppressor.rb:45:in `save!'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/persistence.rb:51:in `create!'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/message_db/message.rb:347:in `add_to_message_queue'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/message_db/message.rb:566:in `_create'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/message_db/message.rb:206:in `save'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/client.rb:400:in `block in finished'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/client.rb:386:in `each'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/client.rb:386:in `finished'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/client.rb:334:in `block in data'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/client.rb:47:in `handle'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/server.rb:159:in `block (2 levels) in run_event_loop'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `select'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `block in run_event_loop'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `loop'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `run_event_loop'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/postal/smtp_server/server.rb:259:in `run'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.000] ERROR -- : [NUK8KW] /opt/postal/app/lib/tasks/postal.rake:18:in `block (2 levels) in <top (required)>'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
[34m[smtp.1:3849][0m [2017-05-23T07:03:38.001] ERROR -- : [NUK8KW] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'

**Comment by w3update** [comment]
In smtpserver log getting:

Bunny::AuthenticationFailureError: Authentication with RabbitMQ failed. Please check your connection settings. Username: postal, vhost: /postal, password length: 14

**Comment by adamcooke** [comment]
Sounds like a configuration error with your RabbitMQ then. Check the credentials are correct and that your RabbitMQ server is running.

**Comment by w3update** [comment]
I installed using quick installation guide.
and in last step it ended with an error saying postal database already exist nevertheless I went on accessing the postal it was up and running.
may quick installation guide need to be work upon.
is there any step missing though all service restart very well.
now i am looking into rabitmq

**Comment by adamcooke** [comment]
I've just run through the quick install instructions and it all works fine on a totally clean Ubuntu 16.04 VM (https://github.com/atech/postal/wiki/Quick-Install). Is that the one you tried?

**Comment by w3update** [comment]
manually i configured rabitmq with default postal users.
now command line smtp connection accepted.
but message not passing through to recipient server.
in dashboard message status i can see: **No delivery attempts yet.**

**Comment by w3update** [comment]
wow now it got relayed unfortunately i was using smtp-relay - config parameter which is meant to relay to third party smtp service.

**Comment by w3update** [comment]
though command line testing succeed on port 25.
while connecting to smtp via php based client i..e phpmailer or swiftmailer getting connection error  [Connection timed out #110] (code: 0)
any idea?

**Comment by w3update** [comment]
I am getting this in worker error log

 Host has '**ipv4** but its pair (**ipv6**) isn't here. Cannot add now.

how can I resolve this?

**Comment by w3update** [comment]
It seems the error was related to IPv6 in pool that I resolved, still looking for PHP Client connectivity.

**Comment by w3update** [comment]
@adamcooke everything is working fine for me except I am not able to connect SMTP with smtp credentials php client based on swiftmailer/phpmailer.
it give connection error 110
any idea?
