### ISSUE TITLE
Issue running setcap on container host (was: fail Quick install script)

### ISSUE THREAD

**Issue by EBII** [atech/postal#185]
Hello stop at this line 

sudo setcap 'cap_net_bind_service=+ep' /usr/bin/ruby2.3

Failed to set capabilities on file `/usr/bin/ruby2.3' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file

i use fresh ubuntu16.04 container up to date on proxmox 4 
regards

**Comment by adamcooke** [comment]
Are you running this on a container? Sounds like it's not supported.

**Comment by catphish** [comment]
Perhaps ask the Proxmox team about this. Looks like others have similar issues with containers and setcap: https://www.digitalocean.com/community/questions/how-do-i-get-setcap-to-work-in-docker-container

**Comment by EBII** [comment]
Yes with lxc we can remove privileges from system 
/etc/pve/lxc/<vmid>.conf
i set from 1 to 0 
unprivileged: 0
and it is ok

**Comment by catphish** [comment]
Glad to hear this resolved it :slightly_smiling_face:
