### ISSUE TITLE
Get status in webhook payload

### ISSUE THREAD

**Issue by jlnmrc** [atech/postal#187]
Hello,
Thank you @adamcooke for your work on Postal!
It would be nice to get the status/reason of the message bounced directly in the payload JSON or, at least, a copy of the plain text message (so we can parse it).
Without this, we have to go through the platform to understand what happened (overquota, unknown user, ...)
Thank you again,
Julien

**Comment by adamcooke** [comment]
Are you talking about the `MessageBounced` event?

**Comment by jlnmrc** [comment]
Yes, absolutely.

**Comment by adamcooke** [comment]
In the case of a bounce message, we don't actually know the reason. This is contained within the bounce message but we don't parse this to try to find it. You would need to implement your own logic to read the message and determine it's purpose.

You can use the message API to obtain the full content of the message from the Postal API whenever you receive it. https://atech.github.io/postal-api/controllers/messages/message.html
