### ISSUE TITLE
Integrate MJML markup

### ISSUE THREAD

**Issue by smalot** [atech/postal#188]
MJML is a markup language designed to reduce the pain of coding a responsive email. Its semantic syntax makes it easy and straightforward while its rich standard components library fastens your development time and lightens your email codebase. MJML’s open-source engine takes care of translating the MJML you wrote into responsive HTML.

https://github.com/mjmlio/mjml

**Comment by adamcooke** [comment]
This isn't really something that would fit anywhere in Postal. Postal is an MTA and isn't responsible for the composition of any messages.

**Comment by ro78** [comment]
From my point of view Postal is not only a MTA but a complete ESP solution, and integrate such feature will be great.

**Comment by smalot** [comment]
Sendmail is a MTA.
Postal is indeed really more.
Supporting responsive emailing is essential

**Comment by adamcooke** [comment]
I disagree I'm afraid. Sending responsive emailing the job of the person who composes the message, not the server that sends it.

**Comment by catphish** [comment]
Responsive email seems like a good idea. This should be something the software composing the emails can take care of.
