### ISSUE TITLE
Tracking URL regex doesn't match all links (in the HTML body)

### ISSUE THREAD

**Issue by alexroosenstein** [atech/postal#189]
`<a href="http://www.google.com">http://www.google.com</a>`
`<a href="http://www.google.com/?q=abc">http://www.google.com/?q=abc</a>`
`<a href="http://www.google.com/search/">http://www.google.com/search/</a>`
`<a href="http://www.google.com/">http://www.google.com/</a>`

The regex matches the first 3 links, but not the last one. Only applicable to the HTML body by the way, in the plain text body all links are replaced properly.

**Comment by mattmartincouk** [comment]
Probably related to #115
