### ISSUE TITLE
HELO invalid?

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#19]
We're seeing the odd error when trying to send.

504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname

I cannot see anywhere in the configuration where that needs to be set (or can be).

Any pointers?

**Comment by jduncanator** [comment]
Your mail client needs to send a fully qualified host name in its HELO command. This is a setting you need to change in whatever SMTP client you are using.

**Comment by mattmartincouk** [comment]
The HELO is set by this software unrelated to the SMTP client. Even using the inbuilt tester gives localhost.

Server hostname is correct.

**Comment by jduncanator** [comment]
I'm trying to understand where you are getting the error. Are you using the web or SMTP APIs? If you are using the SMTP API and you are getting that error message, then it is a configuration you need to change in your SMTP client.

**Comment by mattmartincouk** [comment]
API or SMTP aside, it occurs when using the send message option.. which is the same HELO seen regardless if SMTP or API.

**Comment by jduncanator** [comment]
Then it is most likely the recipients mail server that is rejecting the message because the host name (localhost in your instance) is not fully qualified. This is a common spam protection method. Try sending to a different address hosted by a different provider and see if you receive the same error message.

**Comment by mattmartincouk** [comment]
Yes I know this. It needs to be set somewhere, to stop it happening hence why the issue has been raised.

**Comment by jduncanator** [comment]
Also make sure that your servers host name (shown using the `hostname` command in a terminal on Linux) displays a fully qualified domain and that you have appropriate entries in your hosts file.

I've setup three of these this morning, all of which have correct fully qualified hostnames configured, and it all worked out of the box.

**Comment by jduncanator** [comment]
I'm assuming you've also set the appropriate hostname under the DNS section of config/postal.yml (specifically `smtp_server_hostname`).

**Comment by jduncanator** [comment]
Past that, it may be a bug, but I've just verified that it is sending the correct hostname in the HELO that is set in the postal.yml file as of the current commit in master, and everything works fine.

**Comment by jduncanator** [comment]
@mattmartincouk Sorry for being such a pain, I've just confirmed this is a bug. I've just been able to reproduce this issue, and its obvious from the code why it occurs. [Here](https://github.com/atech/postal/blob/0f10481da0a276d2be5cb8ec5b7b181268f865c6/lib/postal/smtp_sender.rb#L60) the SMTP Client is setup, and is passed in either the `source_ip_address.hostname` or `localhost` if `source_ip_address` is `nil`:

```ruby
smtp_client.start(@source_ip_address ? @source_ip_address.hostname : "localhost")
```

It just so happens that `source_ip_address` is always `nil` as it's only used in the [unqueue_message job](https://github.com/atech/postal/blob/0f10481da0a276d2be5cb8ec5b7b181268f865c6/app/jobs/unqueue_message_job.rb), and [always passes in `nil`](https://github.com/atech/postal/blob/0f10481da0a276d2be5cb8ec5b7b181268f865c6/app/jobs/unqueue_message_job.rb#L213-L218):

```ruby
when SMTPEndpoint
    sender = cached_sender(Postal::SMTPSender, queued_message.message.recipient_domain, nil, :servers => [queued_message.message.endpoint])
when HTTPEndpoint
    sender = cached_sender(Postal::HTTPSender, queued_message.message.endpoint)
when AddressEndpoint
    sender = cached_sender(Postal::SMTPSender, queued_message.message.endpoint.domain, nil, :force_rcpt_to => queued_message.message.endpoint.address)
```

This should pass in either `smtp_server_hostname`, a new configuration entry for the host name, or could be programmatically determined by doing an nslookup of the local IP address the server is configured to run on (this should resolve to the local host name on all sane operating systems).

**Comment by adamcooke** [comment]
I see the problem here. When Postal is configured not to use IP pools (current default behaviour) it will send "localhost" in HELO on outgoing SMTP connections. I'll update this shortly so that we use the SMTP hostname by default rather than a forced localhost. This was never an issue before because we've always used IP pools where the hostname is configured based on the IP that is sending the message.

**Comment by jduncanator** [comment]
@adamcooke Yea, I came to the same conclusion, was just making sure.

**Comment by adamcooke** [comment]
I assume @mattmartincouk is talking about outgoing messages. The lines you've linked to at the bottom there are about routing incoming email. Regardless, they should also not fallback to localhost either!

For outgoing messages the IP is passed in from the queued message object but this will be nil if IP pools are disabled. See [here](https://github.com/atech/postal/blob/0f10481da0a276d2be5cb8ec5b7b181268f865c6/app/jobs/unqueue_message_job.rb#L370). 

The fix will be to replace the fallback localhost on the `smtp_client.start` method.

**Comment by jduncanator** [comment]
@adamcooke Yeap, I noticed that too, but didn't have the time to find my way around the code to find the culprit, although I suspected it to be IP pool related.

Might I suggest the local servers host name as the fallback, or alternatively, a new configuration value? `smtp_server_hostname` has a slightly different meaning (at least in our installation) than the value that we'd see in the HELO.

**Comment by adamcooke** [comment]
I am planning on having a separate value for HELO with just a fallback to `smtp_server_hostname` if it's missing. I would usually recommend enabling and using IP pools though anyway which allows the hostname to be changed depending on the sending IP (so you can match it with some reverse DNS).

**Comment by jduncanator** [comment]
That's the way we currently do it, but we have an internal testing instance that doesn't have IP pools setup and would like to be able to manually set the HELO for that. Your solution sounds perfect! Thanks.

**Comment by jduncanator** [comment]
I guess we could always just setup a single IP pool for the testing instance. Maybe it's best to just require an IP pool and have it fail with a message telling you to set one up if you don't have any? Would simplify it.

**Comment by adamcooke** [comment]
This is now sorted.

You can configure the HELO hostname using `dns.helo_hostname` or it will simply fallback to using `dns.smtp_server_hostname`.

**Comment by mattmartincouk** [comment]
Sorry to re-post on this one.

For mails in the queue which seem to still want to send out using the default pool (we found turning on the pools solved this before your posts) thus setting localhost, is there a way to force them to use the now set pool for that user?

**Comment by adamcooke** [comment]
The IP is chosen when the message is added to the queue so I'm afraid it's stuck with whatever it was when it was added.
