### ISSUE TITLE
How do i configure postal to send emails from 587 or 2525 port instead of 25.

### ISSUE THREAD

**Issue by jsahani** [atech/postal#190]
Hi Team,

I have successfully installed Postal and installed my SSL and everything else, the only thing i can't seem to find/understand that how do i configure Postal to send emails from 587 or 2525 port instead of port 25, with TLS as i have a valid SSL cert installed.

Thanks

**Comment by catphish** [comment]
I'm afraid I don't understand your question. Outbound are always sent *from* a random port, and they are always sent *to* port 25. As far as I know there is no other way to send emails.

If you're referring to the port that SMTP listens on, this is currently always port 25. Did you want to change this, and if so, why? Doing so is certainly possible, but would break the ability to receive incoming email.

**Comment by catphish** [comment]
If what you want to do is send emails from your application to Postal using TLS as follows:

```
smtp_server:
  tls_enabled: true
```

By default, Postal will look for the key and certifate in config/smtp.key and config/smtp.crt but you can configure this also if desired.

Once this is done, you can send your emails by configuring your client to use `STARTTLS` which also runs on port 25.

**Comment by jlnmrc** [comment]
By default, the only port open is 25. You can configure this in postal.yml : 
`smtp_server:
 port: 25`
But I suggest you to keep port 25 open and use iptables/prerouting to add 2525 or 587

**Comment by Gullimama** [comment]
> I'm afraid I don't understand your question. Outbound are always sent _from_ a random port, and they are always sent _to_ port 25. As far as I know there is no other way to send emails.
> 
> If you're referring to the port that SMTP listens on, this is currently always port 25. Did you want to change this, and if so, why? Doing so is certainly possible, but would break the ability to receive incoming email.

Hi, Just wanted to understand the second point....
When I do a google search: "what port gmail smtp use", the answer say 465. 
Say, in a scenario, port 25 is blocked, and instead another port is to be used for sending and receiving mails where MX records only point to IPs, is that not possible?

**Comment by catphish** [comment]
> sending and receiving

Sending, and receiving, are completely different things.

Receiving email can absolutely only be done on port 25. This is the only port than an MX record can point to.

When sending email, your email relay server could listen on any port.

Postal uses port 25 for both.

**Comment by mishudm** [comment]
I also need to open port 25

**Comment by usr-h** [comment]
Caddy generated ssl location is: /opt/postal/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/
but not work 587 port + anoter Postal problem is: NOT possible send from to same email.. example test@mydomain.com to  test@mydomain.com impossible send email! WHY??

**Comment by nward** [comment]
Port 587 is SMTP submission, from clients to an MTA to be relayed over the Internet - which is the outbound use case of postal server.

25 should be supported for submission, but 587 should be encouraged in preference to 25.

Weird that DNAT is the proposed solution here, it's very useful to be able to get metrics over which clients used 25 and which used 587.

**Comment by JoSoG89** [comment]
This works for me:
`sudo iptables -t nat -A PREROUTING -p tcp --dport 587 -j REDIRECT --to-port 25`
