### ISSUE TITLE
Documentation issue: MX Records

### ISSUE THREAD

**Issue by willpower232** [atech/postal#191]
In evaluating our setup having routed mail through it for a few days, we found a couple of issues in the Domains & DNS Configuration regarding MX records.

As per https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration, we have an MX record set up.

1 - the `postal.yml` summary at the bottom doesn't list any mx.whatever records

2 - the documentation should highlight that you must not make your MX record a CNAME

3 - the documentation suggests two records but does not suggest what the second one (i.e. mx2.whatever) should be

**Comment by adamcooke** [comment]
I've removed the section about MX records because it was confusing and for more advanced users when you run multiple servers. It is perfectly acceptable to just point domain MX records to the A records of the server.
