### ISSUE TITLE
user settings timezone does not correspond to message history timezone

### ISSUE THREAD

**Issue by willpower232** [atech/postal#194]
Our server is running in GMT so the message history is correct (apparently using the server timezone) but the "message received" time (which apparently uses the timezone set in user settings) was wrong visually.

(screenshot uses very wrong timezone to highlight incorrectness)

![capture](https://cloud.githubusercontent.com/assets/1619102/26494760/395139f8-4218-11e7-8356-64f400a55a9f.PNG)

**Comment by adamcooke** [comment]
Fixed in https://github.com/atech/postal/commit/6f29bc8d3f6f197d142724a7baee7376ff5fe8aa
