### ISSUE TITLE
Add API method for accessing attachments on messages

### ISSUE THREAD

**Issue by adamcooke** [atech/postal#197]

**Comment by LaurensN** [comment]
DeliverHQ provided a feature to directly access stored attachments:

In the DeliverHQ parameters:

```
payload => {
  .....
  .....
  attachments: [{filename: '123.pdf', content_type: 'application/pdf', size: 123, url: 'link/to/attachment.pdf'}]
}
```

Postal:

```
params => {
   ...
   ...
    attachments: [{filename: '123.pdf', content_type: 'application/pdf', size: 123, data: Base64_data }]
}
```

In Postal it is only possible to directly download the attachments via the interface itself, by accessing the download urls:

`xxxxxxxxxxxxx.com/org/xxxx/servers/test/messages/15/attachment?attachment=0`

It would be really nice to also include the url to the attachment in the inbound e-mail payload. (preferably via an unauthenticated hashed route or token auth)
