### ISSUE TITLE
Import from AppMail

### ISSUE THREAD

**Issue by deanpcmad** [atech/postal#2]
Hey there, I understand you've only just released this but it would be cool to have an import function to import servers and messages from AppMail into my new Postal server (once I have it setup)

**Comment by adamcooke** [comment]
I'm afraid I don't think this will be very forthcoming. AppMail doesn't have an API to allow this at the moment and Postal and AppMail have now diverged enough that I don't want to be adding features into AppMail that would then need to be ported to Postal. Sorry.

**Comment by deanpcmad** [comment]
No problems!
