### ISSUE TITLE
Full mail server support

### ISSUE THREAD

**Issue by kristiandrucker** [atech/postal#20]
Hi, will it be possible to have a full mail server support? (SMTP, IMAP, POP3). It would be nice for users that want to use it as a normal mail server for their company.

**Comment by adamcooke** [comment]
I'm afraid that is all rather outside the scope of this project. We'd rather build something that can do its job very well with a more limited feature set.

**Comment by ConneXNL** [comment]
@adamcooke It would certainly help to get some guidelines on where to go in order to use it as a normal mail server.
