### ISSUE TITLE
Can't receive incoming mails: 550 Invalid server token

### ISSUE THREAD

**Issue by Nurza** [atech/postal#200]
Hello, I have an issue with incoming emails. (maybe same problem as #167)

Version used: 1.0.0-7d2484d47f-stable

I made an organization and a mail server. 
Then, I have set up a route:

Name: test@testmail.xxxxx.fr
Endpoint: xxxxxxxx@gmail.com

Then, when I send a message with an another mail client to this mail, example:
Mail from yyyyyyyy@gmail.com to test@testmail.xxxxx.fr

Gmail send me a message:
```
 550 Invalid server token

Final-Recipient: rfc822; test@testmail.xxxxx.fr
Action: failed
Status: 5.0.0
Remote-MTA: dns; testmail.xxxxx.fr. (178.xx.xx.152, the server for the
 domain testmail.xxxxx.fr.)
Diagnostic-Code: smtp; 550 Invalid server token
Last-Attempt-Date: Wed, 31 May 2017 05:45:19 -0700 (PDT)
```
When I look at the logs in ```/opt/postal/log/smtp_server.log```:
```
[smtp.1:6819] [2017-05-31T12:16:59.950] INFO -- : Listening on port 25
[smtp.1:6819] [2017-05-31T12:24:11.918] DEBUG -- : [LK9UHO]    Connection opened from ::ffff:209.85.217.177
[smtp.1:6819] [2017-05-31T12:24:11.919] DEBUG -- : [LK9UHO]    Client identified as ::ffff:209.85.217.177
[smtp.1:6819] [2017-05-31T12:24:12.104] DEBUG -- : [LK9UHO] <= EHLO mail-ua0-f177.google.com
[smtp.1:6819] [2017-05-31T12:24:12.113] DEBUG -- : [LK9UHO] => 250-My capabilities are
[smtp.1:6819] [2017-05-31T12:24:12.113] DEBUG -- : [LK9UHO] => 250-STARTTLS
[smtp.1:6819] [2017-05-31T12:24:12.113] DEBUG -- : [LK9UHO] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:6819] [2017-05-31T12:24:12.336] DEBUG -- : [LK9UHO] <= STARTTLS
[smtp.1:6819] [2017-05-31T12:24:12.337] DEBUG -- : [LK9UHO] => 220 Ready to start TLS
[smtp.1:6819] [2017-05-31T12:24:12.753] DEBUG -- : [LK9UHO] <= EHLO mail-ua0-f177.google.com
[smtp.1:6819] [2017-05-31T12:24:12.761] DEBUG -- : [LK9UHO] => 250-My capabilities are
[smtp.1:6819] [2017-05-31T12:24:12.761] DEBUG -- : [LK9UHO] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:6819] [2017-05-31T12:24:12.984] DEBUG -- : [LK9UHO] <= MAIL FROM:<yyyyyyyy@gmail.com>
[smtp.1:6819] [2017-05-31T12:24:12.985] DEBUG -- : [LK9UHO] => 250 OK
[smtp.1:6819] [2017-05-31T12:24:13.077] DEBUG -- : [LK9UHO] <= RCPT TO:<test@testmail.xxxxx.fr>
[smtp.1:6819] [2017-05-31T12:24:13.551] DEBUG -- : [LK9UHO] => 550 Invalid server token
[smtp.1:6819] [2017-05-31T12:24:13.644] DEBUG -- : [LK9UHO] <= QUIT
[smtp.1:6819] [2017-05-31T12:24:13.644] DEBUG -- : [LK9UHO] => 221 Closing Connection
[smtp.1:6819] [2017-05-31T12:24:13.644] DEBUG -- : [LK9UHO]    Connection closed
```

The output of the ```host testmail.xxxxx.fr``` command:

```    
testmail.xxxxx.fr has address 178.xx.xx.152
testmail.xxxxx.fr mail is handled by 10 testmail.xxxxx.fr.
```

(So I have a good DNS MX setup)

Can you help me please? Thank you very much.

**Comment by adamcooke** [comment]
You can't configure Postal to receive messages on the same domain as that which is used `dns.return_path` or any domain that beings with the `dns.custom_return_path_prefix`.

**Comment by Nurza** [comment]
Thank you for you response. So what can I do to achieve my goal?

If I set a different ```dns.return_path``` value, now I have the error: 
```
550 Invalid route token
```

**Comment by adamcooke** [comment]
It also can't be the same as `dns.route_domain`

**Comment by wuweifengsheng** [comment]
Adam, I just have installed one postal on one of my VPS, there is several concepts I have confused, for example could you please explain more detail about dns.return_path and dns.custom_return_path_prefix

**Comment by catphish** [comment]
@Nurza did you get this resolved?

**Comment by Nurza** [comment]
Yes, I created a sub domains for each service very much like this: https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration

And it worked.

Thank you very much !
