### ISSUE TITLE
How to know Default DKIM Private Key

### ISSUE THREAD

**Issue by w3update** [atech/postal#202]
Hi,
How can we know DKIM private key for the domain?
this help to verify sending domain from email sending app.
thanks

**Comment by adamcooke** [comment]
This is in `config/signing.key`. If you want the value to add for your DNS, you can run `postal default-dkim-record`

**Comment by oasis1234** [comment]
Wrong info. The DKIM key comes from the database. See: https://github.com/atech/postal/issues/616
