### ISSUE TITLE
client to sending email

### ISSUE THREAD

**Issue by wuweifengsheng** [atech/postal#204]
How can I use a client like outlook/Thunderbird to sending email via postal?

**Comment by adamcooke** [comment]
You can't. That's not what Postal is all about

**Comment by wuweifengsheng** [comment]
So how to sending a html email?

**Comment by adamcooke** [comment]
You should send your message to the SMTP server provided in Postal. The HTML email would be written by some sort of web application.

**Comment by wuweifengsheng** [comment]
thank you, Adam.

another question, I have enabled ip pool but just one ip, do I need assign it by manual or it's will be automatically assigned?
