### ISSUE TITLE
postal auto-upgrade failing, reference to uglifier

### ISSUE THREAD

**Issue by willpower232** [atech/postal#205]
just ran a casual postal auto-upgrade and encountered the following error:

```
rake aborted!

LoadError: cannot load such file -- uglifier
```

![capture](https://cloud.githubusercontent.com/assets/1619102/26724545/f55b1e92-4791-11e7-8563-91607bf35997.PNG)

**Comment by adamcooke** [comment]
I think this was fixed in https://github.com/atech/postal/commit/97f95fe831fd10c80057871ebc014ea2f1b738db 

Can you try it again?

**Comment by willpower232** [comment]
I saw it download a code change but its still asking for uglifier :-(

**Comment by adamcooke** [comment]
Can you try deleting `/opt/postal/app/.bundle/config` and trying again?

**Comment by willpower232** [comment]
there we go, all sorted :-)

**Comment by adamcooke** [comment]
Great 👍
