### ISSUE TITLE
DKIM is too long for Amazon Route 53

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#21]
Amazon Route 53 says it's too long, how can i reduce it or use 1024 instead of 2048?

**Comment by adamcooke** [comment]
Ah. That. Yes. You'll need to regenerate your signing key to be 1024. 

```
openssl genrsa -out /opt/postal/app/config/signing.key 1024
```

I will update the config initialization to generate a 1024 key for now to allow it to work with DNS servers that can't seem to handle splitting DNS records.

**Comment by adamcooke** [comment]
(For the record, the per domain DKIM keys were already being generated as 1024)

**Comment by elfeffe** [comment]
I think the problem is the folder structure, the instructions have some wrong part.

My folder structure is /opt/postal/app
But at the same level (of app) I have config, and then I have another config inside app

If I create the keys in 1024, the signing.key updated is the one in /opt/postal/app/config
But not the one in /opt/postal/config (If I get it with postal default-dkim-record I get the wrong 2048 again)

Can that be related to https://github.com/atech/postal/issues/23 ?

**Comment by adamcooke** [comment]
All configuration should be in `/opt/postal/config`. There shouldn't be any of your configuration in `/opt/postal/app/config`. I will check documentation to make sure there are no reference to `/opt/postal/app/config` because that shouldn't be used.

**Comment by adamcooke** [comment]
Apologies  - I put the wrong URL further up in this thread. I have corrected it to avoid confusion in the future.

**Comment by elfeffe** [comment]
No, in that case documentation is ok.
I just told you that because in that case the system has generated a 2048 key by default, and when I generated the new one, it was located inside /app/config and postal default-dkim-record returns the one in /config, I had to navigate to /app/config/signing.key to get the 1024 one
