### ISSUE TITLE
DNS configuration

### ISSUE THREAD

**Issue by wuweifengsheng** [atech/postal#210]
I can sending out email now but all into spam.

I am actually confused of https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration  this article instruction.

I have copy all DNS record from my server domain config page likes below, but still unable pass the test of postal "check my records are correct", would Adam able to explain to me more about it.

I have use godaddy for DNS setup with just one single ip.

SPF Record

WARNING No SPF record exists for this domain

You need to add a TXT record at the apex/root of your domain (@) with the following content. If you already send mail from another service, you may just need to add include:spf.postal.example.com to your existing record.

v=spf1 a mx include:spf.postal.example.com ~all
DKIM Record

WARNING No TXT records were returned for postal-QZwUIn._domainkey.mx.amotic.net

You need to add a new TXT record with the name postal-QZwUIn._domainkey with the following content.

v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDD99mJOLwgfWOjt17QobkLEyeVGSLqB/okptFQ+/muisbU7wddvP3F3ii6CfbMZvVz+YdirHnVpTyBPaAv/7kn6soqBX1zakkBl4VlqZ9bsFohoTKjZwGWJOhytoz7c1RVZD0H3PvyCt6/pYbiTg20NZlvPr0EhH3EVegZlF/f3QIDAQAB;

the below is the configure from godaddy zone export for you reference.:

; Domain: amotic.net
; Exported (y-m-d hh:mm:ss): 2017-06-03 01:04:10
;
; This file is intended for use for informational and archival
; purposes ONLY and MUST be edited before use on a production
; DNS server.
;
; In particular, you must update the SOA record with the correct
; authoritative name server and contact e-mail address information,
; and add the correct NS records for the name servers which will
; be authoritative for this domain.
;
; For further information, please consult the BIND documentation
; located on the following website:
;
; http://www.isc.org/
;
; And RFC 1035:
;
; http://www.ietf.org/rfc/rfc1035.txt
;
; Please note that we do NOT offer technical support for any use
; of this zone data, the BIND name server, or any other third-
; party DNS software.
;
; Use at your own risk.

; SOA Record
amotic.net.	600	IN	SOA	ns17.domaincontrol.com.	dns.jomax.net (
				2017060309
				28800
				7200
				604800
				600
				)

; A Records
mx	3600	IN	A	45.76.210.83

; MX Records
@	3600	IN	MX	5	mx.amotic.net

; TXT Records
postal-qzwuin._domainkey	3600	IN	TXT	"v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDD99mJOLwgfWOjt17QobkLEyeVGSLqB/okptFQ+/muisbU7wddvP3F3ii6CfbMZvVz+YdirHnVpTyBPaAv/7kn6soqBX1zakkBl4VlqZ9bsFohoTKjZwGWJOhytoz7c1RVZD0H3PvyCt6/pYbiTg20NZlvPr0EhH3EVegZlF/f3QIDAQAB;"
@	3600	IN	TXT	"v=spf1 a mx include:spf.postal.example.com ~all"

; NS Records
@	3600	IN	NS	ns17.domaincontrol.com
@	3600	IN	NS	ns18.domaincontrol.com

**Comment by willpower232** [comment]
spf.postal.example.com is literally an example.

You need to make spf.postal.amotic.net as a TXT record which references the main IP of your postal server and then make use of that.

**Comment by wuweifengsheng** [comment]
Will:
Actually I have tested it that txt record
spf.postal  and point to 45.76.210.83 but still failed of check records correct step, what's happened? is that godaddy DNS has some restriction on this?

**Comment by willpower232** [comment]
According to https://www.whatsmydns.net/#TXT/amotic.net the SPF record needs changing from spf.postal.example.com to whatever your SPF record for your postal is

**Comment by wuweifengsheng** [comment]
I have modified it 3 mins ago, now may updated already. 
I also confused with the dkim record setup.

**Comment by willpower232** [comment]
Your DKIM record looks right but you'll probably have to wait some hours before godaddy actually updates your DNS. You should wait a bit and then check whatsmydns.net again.

**Comment by wuweifengsheng** [comment]
the problem is even DKIM record are right but unable to pass the check records correct internal of postal I have installed, that's why I am confused.

**Comment by willpower232** [comment]
your domain seems to be missing the SPF record entirely now, I'd suggest reviewing the domain names mentioned in postal.yml and studying the record check pages to make sure you have everything in place properly

**Comment by infooer** [comment]
nihao, You need to restart postal to get your postal.yml configuration content in effect...

**Comment by jsahani** [comment]
@wuweifengsheng If you need installation service, let me know :)

**Comment by nimix3** [comment]
hello,
How to configure DNS server for postal?
I need to install and configure Bind with Postal?

**Comment by igerzog** [comment]
You can do this in the control panel of your personal domain registrar. It is not necessary to install your own BIND server.
