### ISSUE TITLE
MySQL error on syslog

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#213]
`Jun  5 08:35:06 Userver mysqld[23060]: 2017-06-05  8:35:06 139888520293120 [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. The statement is unsafe because it uses a LIMIT clause. This is unsafe because the set of rows included cannot be predicted. Statement: UPDATE `queued_messages` SET `queued_messages`.`locked_by` = 'host:Userver pid:6564 procname:worker.5 job:VU33AGB4HY', `queued_messages`.`locked_at` = '2017-06-05 08:35:06.648159' WHERE (retry_after IS NULL OR retry_after <= '2017-06-05 08:35:36.648221') AND `queued_messages`.`batch_key` = 'outgoing-domain.com' AND `queued_messages`.`ip_address_id` IS NULL AND `queued_messages`.`locked_by` IS NULL AND `queued_messages`.`locked_at` IS NULL LIMIT 100`

I don't know if it's important, but I share just in case

**Comment by mattmartincouk** [comment]
Are you replicating your database?

You probably want to change your binlog format if so.

**Comment by elfeffe** [comment]
No, I just run the quick install. It installs MariaDB, I didn't touch
anything

2017-06-05 12:20 GMT+02:00 mattmartincouk <notifications@github.com>:

**Comment by catphish** [comment]
This is only important if you implement database replication. I don't think the installer touches the database configuration, so this is probably out of scope for now. Thanks for the note though, will consider it when writing any clustering documentation.

**Comment by elfeffe** [comment]
The thing is that you get one warning per email sent. not important, but not elegant either.
