### ISSUE TITLE
Testing email Error

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#216]
hello

i am trying to send test email from postal but i got soft fail error and showing SOFT FAIL
No SMTP servers were available for gmail.com. Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com

How to resolve this?

**Comment by adamcooke** [comment]
You should be able to find more information about the error by clicking "show technical details"

**Comment by ajsb85** [comment]
![imagen](https://user-images.githubusercontent.com/663460/27516184-100bb7bc-59b5-11e7-9472-618c8a3280a7.png)
