### ISSUE TITLE
Python API Client

### ISSUE THREAD

**Issue by thatjpcsguy** [atech/postal#219]
Opening this issue for something ive been working on, and will probably properly package up at some point, a Python API Client, because i couldnt find one elsewhere :)

Put in a gist here for now because its pretty simple in its current form.
https://gist.github.com/thatjpcsguy/18e98ad221fee4480d522453e71655b4

**Comment by adamcooke** [comment]
Thanks. If you ever make this into a package, open up a new issue and we'll link to it from the client list :)
