### ISSUE TITLE
Email Template Library

### ISSUE THREAD

**Issue by thatjpcsguy** [atech/postal#220]
Huge feature request - and i'm not sure if this fits in with the roadmap of the product. But i would find it insanely useful if i could upload an email template to a "library", which then the template ID can later be referenced in an API call. 

Hopefully this code will demonstrate my point (in the example im actually using campaign monitor)

```
# Create a new mailer and define your message
tx_mailer = Transactional(auth)

# email template ID
email_public_confirmation = '74069586-83f7-4664-8c1b-31b481b6c8f0'


email_data = {
        'full_name': new_user.name,
        'code': new_user.password_reset_hash
}

to_email = 'blah@blah.com'

# Send the message
tx_mailer.smart_email_send(email_public_confirmation, to_email, data=email_data)

```

I can totally understand if you want it not to go down this track though, because its a total rabbit hole of then having a template creator, etc etc

**Comment by willpower232** [comment]
sorry to rain on your parade but I think they've already answered this one

https://github.com/atech/postal/issues/188
https://github.com/atech/postal/wiki/FAQs#can-you-add-mailing-list-feature

**Comment by thatjpcsguy** [comment]
Ah i didn't actually see this.

If i built this out as a seperate project/service, is it something people would be interested in?

Does anyone know if open source stuff like this exists?

**Comment by willpower232** [comment]
There is phplist off the top of my head, I haven't used it for a while but I remember it wasn't super plain sailing. Certainly bound to be some interest if you made something that used postal.

**Comment by infooer** [comment]
so i want to konw whether i can use phplist as client and postal as server while sending over HTTP using API .

**Comment by willpower232** [comment]
If I remember correctly, phplist sends its own messages (so wouldn't need postal at all) and would almost definitely require modifications to use any API to send messages. I'm not a phplist expert in any way.
