### ISSUE TITLE
New to Postal

### ISSUE THREAD

**Issue by yeah-nothing** [atech/postal#221]
hello, I just had some general questions about the software. I hope that's okay to post them here.

here goes.....

1. Can I set up Postal on Amazon Ec2? Provided that my Ec2 instance is the correct version of Ubuntu for Postal to run on?

2. Now some domain providers only allow a certain number of emails to be sent per hour. Can Postal do large email blasts in a timely manner? I mean more then 200 to 300 an hour?

3. Could I setup Postal with Sendy?

4. Once Postal is installed and running how do I access it in the browser? For example Wordpress has an admin url that I can log into.

Thank You

**Comment by willpower232** [comment]
1. yes but there are a few caveats as Amazon filters outgoing SMTP, see https://github.com/atech/postal/issues/192 and https://github.com/atech/postal/issues/212

2. depends mostly on the spec of your server and also permission from Amazon, see https://github.com/atech/postal/issues/192 (again)

3. I'm not a Sendy user but it seems unlikely, Sendy looks like it only sends through SES

4. Postal has a web interface as the only way of using it using whatever domain name you set it up with

**Comment by catphish** [comment]
Closing as appears to be answered. Thanks!
