### ISSUE TITLE
memory issues

### ISSUE THREAD

**Issue by willpower232** [atech/postal#222]
![capture](https://user-images.githubusercontent.com/1619102/26920692-aa99544c-4c31-11e7-8cbb-e4cb5253e0f2.PNG)

As you can see from this graph, we have been struggling with memory usage. The change is so dramatic and has occurred around the time I auto-upgraded as we brought more websites into our postal (May 25th).

The lack of available memory has caused serious issues on the server and lots of crashes. The MySQL child process IDs are in the 700s or 800s when this happens, suggesting there have been plenty open and indeed there are dozens sleeping.

We currently have 24 postal server databases but none are large enough to use up all that memory.

**Comment by adamcooke** [comment]
Do you know which processes are using the most ram?

We have been looking at some memory issues in the worker processes and we have a commit going out later which seems to address the issue of an ever growing memory footprint of a worker.

**Comment by catphish** [comment]
As Adam mentioned, I have now pushed 48863dd6f41bf3e228b4d18dff43b6629c79b7bc which should prevent excessive memory usage in the workers. Our current usage (after a few days of processing a lot of mail) is as follows:

```
[postal] web 449 MB
[postal] worker 415 MB
[postal] worker 392 MB
[postal] worker 367 MB
[postal] worker 355 MB
[postal] smtp 264 MB
[postal] fast 112 MB
[postal] requeuer 105 MB
[postal] cron 90 MB
rabbitmq 92 MB
spamd child 86 MB
spamd child 82 MB
mysql 3.5GB (the size of MySQL doesn't depend on usage, we configure ours this way)
```

It would be very helpful if you could determine which processes specifically are growing too large, and how they compare to the numbers above.

**Comment by willpower232** [comment]
certainly, can you tell me how you got that information? At the minute, we can just see a lot of `mysqld` processes.

**Comment by catphish** [comment]
This information comes from the output of the command `ps aux`. The most interesting column is `RSS` which shows the usage of physical memory in KB. You should only have one `mysqld` process, you may be seeing its threads.

**Comment by willpower232** [comment]
```
USER       PID %CPU %MEM    VSZ   RSS    TTY  STAT START   TIME COMMAND
rabbitmq  1303  0.2  2.3 1181320   94420 ?    Ssl  09:54   0:09 /usr/lib/erlang/erts-7.3/bin/beam.smp -W w -A 64 -P 10$
rabbitmq  1475  0.0  0.0   26304     232 ?    S    09:54   0:00 /usr/lib/erlang/erts-7.3/bin/epmd -daemon
mysql     1741  0.1  7.7 1085920  314704 ?    Ssl  09:54   0:06 /usr/sbin/mysqld
postal    1905  0.0  0.2 1091644   12120 ?    Sl   09:54   0:00 [procodile] Postal (/opt/postal/app)
postal    1911  0.1  4.1  970648  169080 ?    Sl   09:54   0:04 [postal] web.1
postal    1913  0.0  3.2  953864  131912 ?    Sl   09:54   0:03 [postal] fast.1
postal    1915  0.1  4.6  818260  188592 ?    Sl   09:54   0:04 [postal] worker.1 (i
postal    1917  0.1  4.6  811672  187104 ?    Sl   09:54   0:04 [postal] worker.2 (i
postal    1919  0.1  3.8  792740  153932 ?    Sl   09:54   0:04 [postal] worker.3 (i
postal    1931  0.1  4.4  808204  181140 ?    Sl   09:54   0:04 [postal] worker.4 (i
postal    1940  0.1  4.2  803660  172140 ?    Sl   09:54   0:04 [postal] worker.5 (i
postal    1951  0.1  3.6  796560  149344 ?    Sl   09:54   0:04 [postal] worker.6 (i
postal    1973  0.1  4.0  802524  165356 ?    Sl   09:54   0:04 [postal] worker.7 (i
postal    1984  0.1  4.3  813500  177676 ?    Sl   09:54   0:04 [postal] worker.8 (i
postal    1986  0.1  4.5  809000  186000 ?    Sl   09:54   0:04 [postal] worker.9 (i
postal    1990  0.1  4.6  815544  189592 ?    Sl   09:54   0:04 [postal] worker.10 (
postal    1992  0.1  2.3  350940   94516 ?    Sl   09:54   0:03 [postal] cron.1
postal    1997  0.0  2.6  366496  105884 ?    Sl   09:54   0:02 [postal] smtp.1
postal    2002  0.0  2.5  360200  104272 ?    Sl   09:54   0:03 [postal] requeuer.1
rabbitmq  2094  0.0  0.0    7504     976 ?    Ss   09:54   0:00 inet_gethost 4
rabbitmq  2095  0.0  0.0   13856    1744 ?    S    09:54   0:00 inet_gethost 4
```

This is after an hours worth of usage. Yes there are an awful lot of threads for MySQL.

I'm tempted to leave it a bit longer for more dramatic numbers and then `postal auto-upgrade`.

**Comment by willpower232** [comment]
```
USER       PID %MEM      RSS       RSS %MEM
rabbitmq  1303  2.3    94420     94420  2.3
rabbitmq  1475  0.0      232       232  0.0
mysql     1741  8.3   339104    314704  7.7
postal    1905  0.2    12120     12120  0.2
postal    1911  4.6   187028    169080  4.1
postal    1913  4.0   164344    131912  3.2
postal    1915  4.4   179624    188592  4.6
postal    1917  4.8   195548    187104  4.6
postal    1919  4.1   167144    153932  3.8
postal    1931  4.6   186080    181140  4.4
postal    1940  4.8   196984    172140  4.2
postal    1951  4.0   162112    149344  3.6
postal    1973  4.5   185096    165356  4.0
postal    1984  4.4   180508    177676  4.3
postal    1986  4.6   186776    186000  4.5
postal    1990  4.6   189676    189592  4.6
postal    1992  2.3    94516     94516  2.3
postal    1997  2.7   109616    105884  2.6
postal    2002  2.6   106956    104272  2.5
rabbitmq  2094  0.0      976       976  0.0
rabbitmq  2095  0.0     1744      1744  0.0
```

An hour and a half later, you can see most of the postal processes have lost memory BUT the `mysql` process has grown significantly.

**Comment by catphish** [comment]
If any of these processes continue to grow indefinitely, we can look into it, however in the meantime I would say that your memory usage numbers are quite normal (certainly lower than ours). I think MySQL with its default config will probably grow to around 400MB. Other than that, the application should grow to around 2.5GB total (see our numbers), and perhaps a couple of hundred MB more for spamassassin, bringing the total to around 3.5GB. How large is the machine you are using? It should run (with not a huge margin for safety) on a 4GB machine.

Looking at your graphs, it would appear that your machine often hovers at around 256MB of free memory, so it might be that you are only a little bit short of having enough.

Finally, I would definitely suggest trying the patch I mentioned earlier.

**Comment by willpower232** [comment]
I've updated our postal to include the patch and will monitor, we can schedule an update for the memory early next week if it keeps getting close. Will update when we know more.

**Comment by catphish** [comment]
Great, do open another ticket and let us know the details if you see any processes that seem to keep growing. With regard to MySQL, this is probably beyond what we can assist with, though it might be nice if we documented the expected memory usage of a default installation.
