### ISSUE TITLE
what's the best VPS host

### ISSUE THREAD

**Issue by yeah-nothing** [atech/postal#225]
What's the best VPS host for Postal? Could I run it on my local machine in a VM?

**Comment by willpower232** [comment]
Postal requires TWO internet connected IP addresses so you could run it from your local machine if you are getting two IP addresses from your ISP.

Amazon EC2 and DigitalOcean both provide VPSes with the ability to add at least two IP addresses.

**Comment by adamcooke** [comment]
You don't **need** two IPs - you only need the extra one if you want to do message delivery tracking. As far as I know, Digital Oceans don't allow multiple IPv4 addresses though.

However, we use DigitalOcean for testing installs etc... and it all works well.

**Comment by willpower232** [comment]
For your reference, you can get a Floating IP with DigitalOcean which acts like an Elastic IP in AWS so you can give your server a second IP address and also move it to another server at your discretion.

The only challenge is discovering the "internal" IP address that the Floating IP communicates on so you can specifically bind stuff to it
