### ISSUE TITLE
Typo in wiki Starting-on-boot

### ISSUE THREAD

**Issue by ways** [atech/postal#226]
On https://github.com/atech/postal/wiki/Starting-on-boot it says to create file 

> /etc/systemd/system/postal.conf

but it should be

> /etc/systemd/system/postal.service

Otherwise you'll get this error when attempting to enable the service:

```
# systemctl enable postal
Failed to execute operation: No such file or directory
```

**Comment by catphish** [comment]
Fixed, thanks!
