### ISSUE TITLE
Mysql2::Error: Access denied for user 'postal'@'localhost' to database 'postal'

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#23]
if I use "postal" user, which I can test on command line and works, it says that error when initialize.

If I use root user, it creates all the tables, but then it says the same error (I think it's when is trying to create the admin user).

**Comment by adamcooke** [comment]
Be sure to connect to `127.0.0.1` rather than `localhost`

**Comment by elfeffe** [comment]
Sure, this is what I use

main_db:
  host: 127.0.0.1
  port: 3306
  username: postal
  password: pass
  database: postal

message_db:
  host: 127.0.0.1
  port: 3306
  username: postal
  password: pass
  prefix: postal

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: postal
  password: pass
  vhost: /postal

**Comment by elfeffe** [comment]
With that login information I can log using mysql in command line

It's strange that with root it can create tables, and fails after that. With postal user it fails and doesn't create tables

**Comment by adamcooke** [comment]
Once the initial tables have been created it will try to create a database for an initial mail server which uses the `message_db` credentials so it could be failing here. The error looks like it's authenticating to `localhost` rather than `127.0.0.1`  which MySQL distinguishes between depending on your configuration

**Comment by elfeffe** [comment]
Ok, I filled root on message_db and it works
All the same, but root user.
No idea...

**Comment by adamcooke** [comment]
I'd say there was certainly something up with the way permissions have been added on your server. I'm actually just midway through an install following the instructions so I'll let you know if it doesn't work as expected.

**Comment by fwaechter** [comment]
Double check the steps described here: [Installation: Preparing the database](https://github.com/atech/postal/wiki/Installation#preparing-the-database) and try to `FLUSH PRIVILEGES;` after the last `CREATE...` and `GRANT ALL...` commands to reload all privileges previously granted. Documentation here: [MariaDB: FLUSH Command](https://mariadb.com/kb/en/mariadb/flush/)

Note that the postal user _can't create new databases_ but has full access to all existing databases prefixed with `postal-`

General Comment: Normally a dash `-` _should not_ be used as a prefix separator instead an underscore `_` _should_ separate prefix and name.

**Comment by adamcooke** [comment]
> Note that the postal user can't create new databases but has full access to all existing databases prefixed with postal-

My experience tells me that it can create these databases.

**Comment by fwaechter** [comment]
[You're right](https://stackoverflow.com/questions/2950054/let-mysql-users-create-databases-but-allow-access-to-only-their-own-databases). Sorry.
