### ISSUE TITLE
Email From POSTAL

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#232]
Hello

Just for idea could you please tell me how many emails I can send from postal? Is there are any limit?

My VPS Details
OpenStack KVM
2 vCores
2.4 GHz
8 GB RAM
40 GB SSD
Local RAID 10

**Comment by catphish** [comment]
It's hard to give a definitive answer, it depends a lot on the complexity of the email emails being processed, how fast the receiving servers respond. At a very rough guess, I'd say a starting point of 10 emails per second would be reasonable. We'd always be interested to know what results you get though.
