### ISSUE TITLE
Postal Restart Error

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#233]
Hello

if I do restart then I got this error. Please check

Stopped worker.4
Stopped worker.5
Restarted web.1
Restarted cron.3 -> cron.4
Restarted smtp.1
Restarted requeuer.3 -> requeuer.4

is it fine or it's error?

**Comment by catphish** [comment]
It's not clear without context why some worker processes were stopped rather than restarted. Why did you restart? Are you having a problem? These tickets are getting silly now.

**Comment by mattmartincouk** [comment]
You guys need to sort that paid support option. ;)
