### ISSUE TITLE
quick installation guide does not work at digitalocean

### ISSUE THREAD

**Issue by jakesullyneytiri** [atech/postal#236]
Hi,

was trying to install this through quick install doc but when i run this 
"curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh"

it does some work with packages but then i get this error: 
"Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libmysqlclient-dev : Depends: libmysqlclient18 (= 5.5.55-0ubuntu0.14.04.1) but it is not going to be installed
 mariadb-server : Depends: mariadb-server-10.1 (= 10.1.24+maria-1~xenial) but it is not going to be installed
E: Unable to correct problems, you have held broken packages."

it sems the installer wont work on ubuntu at digitalocean as you guys noted on quick install guide that it does work :/ any solution how to fix this??

Also digitalocean only have down to 14.04.5 as ubuntu version.

/Thanks

**Comment by stayallive** [comment]
The quick start also mentions Ubuntu 16.04 LTS is required (for the quick start to work), you are running 14.04.5.

**Comment by jakesullyneytiri** [comment]
it didn't do that before, it said 14.04 then.

**Comment by adamcooke** [comment]
Run it again on a clean Ubuntu 16.04 machine.
