### ISSUE TITLE
Held messages

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#239]
I think there is no sense to held messages for one month, the world can end in one month.
Is there any way to auto clean held messages?

**Comment by mattmartincouk** [comment]
This is more user preference than a wide logic.

Some would argue it is better to have the message sent than not at all. We have broadband customers who decide to host their own mail server and due to fault/outage/power/whatever, their service could be broken and a repair could take time - I know for them, they'd not want to lose email.

**Comment by elfeffe** [comment]
I understand.
But at least any interface (or setting) to handle it will be great.
We can't delete held messages.

**Comment by mattmartincouk** [comment]
Not sure that is correct?

<img width="614" alt="screen shot 2017-06-21 at 5 34 30 pm" src="http://scrn.at/KFm0n.png">

There is the option to delete held messages in the message itself.

**Comment by elfeffe** [comment]
Yes, the problem is that we have more than 500 held messages :)

2017-06-21 18:35 GMT+02:00 mattmartincouk <notifications@github.com>:

**Comment by ravimantri** [comment]
Issue I've about 100K emails stuck with status "held". So the main thing is how can I delete all emails or force all to deliver?

**Comment by adamcooke** [comment]
If you have a lot of held messages, you can use the console to put them all back into your message queue.

```
postal console
```

```ruby
Server['org-name/server-name'].message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }
```

**Comment by adamcooke** [comment]
I've added two issues to assist with these issues. #257 and #256

**Comment by ravimantri** [comment]
@catphish @adamcooke, how can I delete the held list all at once?

**Comment by ravimantri** [comment]
@catphish @adamcooke, It' very urgent! How can I delete the held list (100K) all at once?

Looking for your help. Thanks

**Comment by vardhamanshetti** [comment]
```rb(main):001:0> Server['org-name/server-name'].message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }
NoMethodError: undefined method `message_db' for nil:NilClass
	from (irb):1
	from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
irb(main):002:0> 

```

**Comment by adamcooke** [comment]
You've entered the server name and/or organization name incorrectly.

**Comment by vady1** [comment]
From where  will I get server name?

**Comment by ravimantri** [comment]
Dear @adamcooke by running "Server['org-name/server-name'].message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }"

I get "NoMethodError: undefined method `message_db' for nil:NilClass"

What to do? My all emails are stuck in held, nothing processing.

Thanks

**Comment by adamcooke** [comment]
You've entered the server name and/or organization name incorrectly.

**Comment by ravimantri** [comment]
Thanks for your prompt reply. I actually used:

Server['gupta-publications/smtp-1'].message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }

**Comment by adamcooke** [comment]
You can get the correct org & server names from the URL in the web interface. I'd suggest that `gupta-publications/smtp-1` is wrong.

**Comment by ravimantri** [comment]
This is the Postal Interface I access: https://postal.domain.com/org/gupta-publications/servers/smtp-1

**Comment by adamcooke** [comment]
You can try to get the server

```ruby
server = Organization.find_by_permalink('org-name').servers.find_by_permalink('smtp-1')
server.message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { \|m\| m.add_to_message_queue(:manual => true) }
--



```

**Comment by ravimantri** [comment]
irb(main):004:0> server = Organization.find_by_permalink('gupta-publications').servers.find_by_permalink('smtp-1')
=> #<Server id: 1, organization_id: 1, uuid: "673f939a-b43b-4b7d-87a6-6a572cda6034", name: "SMTP - 1", mode: "Live", ip_pool_id: nil, created_at: "2017-07-26 14:35:51", updated_at: "2017-07-27 08:42:53", permalink: "smtp-1", send_limit: 100, deleted_at: nil, message_retention_days: 2, raw_message_retention_days: 1, raw_message_retention_size: 512, allow_sender: false, token: "uato7r", send_limit_approaching_at: nil, send_limit_approaching_notified_at: nil, send_limit_exceeded_at: nil, send_limit_exceeded_notified_at: nil, spam_threshold: #<BigDecimal:7cb1310,'0.5E1',9(18)>, spam_failure_threshold: #<BigDecimal:7cb11d0,'0.2E2',9(18)>, postmaster_address: nil, suspended_at: nil, outbound_spam_threshold: nil, domains_not_to_click_track: nil, suspension_reason: nil, log_smtp_data: false>

irb(main):005:0> server.message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { \|m\| m.add_to_message_queue(:manual => true) }
SyntaxError: (irb):5: syntax error, unexpected $undefined
...:scope => 'outgoing'}).each { \|m\| m.add_to_message_queue(:...
...                               ^
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by ravimantri** [comment]
@adamcooke, anymore suggestions? Thanks

**Comment by chocochrispi** [comment]
It works! thanks

**Comment by influenist** [comment]
Any option to delete the held queue by console? I see here only options to re-add them to the queue.

Thanks!

**Comment by PureMSP** [comment]
Doesn't work for me neither.!
```
NoMethodError: undefined method `servers' for nil:NilClass
        from (irb):1
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

No matter what I try!

**Comment by adamcooke** [comment]
You're getting the organization name wrong if you're getting that error.

**Comment by hadifarnoud** [comment]
what if I want to cancel them all @adamcooke ? can you post the query for that too?

**Comment by njolin** [comment]
@adamcooke can you shed some light on how to delete the held messages using the console please? Thanks!

**Comment by lovelyns** [comment]
> If you have a lot of held outgoing messages, you can use the console to put them all back into your message queue and have them resend.
> 
> ```
> postal console
> ```
> 
> ```ruby
> Server['org-name/server-name'].message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }
> ```

Hello @adamcooke 
please how do i get message_db ?

**Comment by lovelyns** [comment]
> > If you have a lot of held outgoing messages, you can use the console to put them all back into your message queue and have them resend.
> > ```
> > postal console
> > ```
> > 
> > 
> > ```ruby
> > Server['org-name/server-name'].message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }
> > ```
> 
> Hello @adamcooke
> please how do i get message_db ?

I am getting the below error @adamcooke please help
NoMethodError: undefined method `message_db' for nil:NilClass

**Comment by willpower232** [comment]
This is answered above

> You've entered the server name and/or organization name incorrectly.

**Comment by lovelyns** [comment]
Thanks @willpower232 

Am I still on track?

I got the below result;

=> #<Server id: 1, organization_id: 1, uuid: "25d927cc-d369-413a-bd80-5468c20db4b1", name: "Mail Server 1", mode: "Live", ip_pool_id: nil, created_at: "2019-04-17 13:16:51", updated_at: "2019-05-10 13:49:45", permalink: "mail-server-1", send_limit: nil, deleted_at: nil, message_retention_days: 60, raw_message_retention_days: 30, raw_message_retention_size: 2048, allow_sender: true, token: "vchvvr", send_limit_approaching_at: nil, send_limit_approaching_notified_at: nil, send_limit_exceeded_at: nil, send_limit_exceeded_notified_at: nil, spam_threshold: #<BigDecimal:6e4ea20,'0.5E1',9(18)>, spam_failure_threshold: #<BigDecimal:6e4e908,'0.2E2',9(18)>, postmaster_address: nil, suspended_at: nil, outbound_spam_threshold: nil, domains_not_to_click_track: nil, suspension_reason: nil, log_smtp_data: true>
irb(main):002:0> server.message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { \|m\| m.add_to_message_queue(:manual => true) }

**Comment by lovelyns** [comment]
> It worked for me, thanks!

Hi @chocochrispi 
Could you please guide me on how you were able to get this done if my org name is **matter** and my server name is **mail-server-10** ?

**Comment by chocochrispi** [comment]
> > It worked for me, thanks!
> 
> Hi @chocochrispi
> Could you please guide me on how you were able to get this done if my org name is **matter** and my server name is **mail-server-10** ?

`server = Organization.find_by_permalink('matter').servers.find_by_permalink('mail-server-10')`
`server.message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }`

**Comment by lovelyns** [comment]
> > > It worked for me, thanks!
> > 
> > 
> > Hi @chocochrispi
> > Could you please guide me on how you were able to get this done if my org name is **matter** and my server name is **mail-server-10** ?
> 
> `server = Organization.find_by_permalink('matter').servers.find_by_permalink('mail-server-10')`
> `server.message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }`

Thanks a million @chocochrispi it works

**Comment by pjv** [comment]
Here’s how to re-send all the hard fails:

`postal console`

`Server['organization/server’].message_db.messages(:where => {:status => 'HardFail', :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }`

NOTE: you have to know what your `organization` and `server` are.

**Comment by quauhtlimtz** [comment]
For the Postal server version during feb 2025, this is an updated example to put the first 100 held messages back on queue: 
`Server.find_by(permalink: 'your-smtp-server-short-name').message_db.messages.where(held: true, scope: 'outgoing').limit(100).each { |m| m.add_to_message_queue(manual: true) }`

**Comment by baderdean** [comment]
How I did it, just a bit simpler because org-name/server-name didn't work for me. Basically postal console is just a ruby console. So here it is:

```
sudo docker exec -t -i postal /bin/sh
postal console
```
wait a little bit then:
```
Server.find_by(name: 'Server Name').message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }
```

I even found a way to do it batch by batch in order to maintain a good reputation:
```
Server.find_by(name: 'Server Name').message_db.messages.where(held: 1, scope: 'outgoing').limit(1000).each { |m| m.add_to_message_queue(manual: true) }
```

You could also replace ```name``` by ```permalink``` in some case, it's easier:
```
Server.find_by(permalink: 'server-name').message_db.messages.where(held: 1, scope: 'outgoing').each { |m| m.add_to_message_queue(manual: true) }
```
