### ISSUE TITLE
IMAP support

### ISSUE THREAD

**Issue by DatN3xus** [atech/postal#240]
Hi,

I just explored postal and installed it on a VPS to try and test. But I don't understand how to receive mails. I didn't find neither POP3 or IMAP. What is the supposed way to handle receiving mails? I found the option "Routing" but redirecting via another SMTP server (doesn't have postal one?) or through a web API seems not to be the perfect way.

**Comment by spheron1** [comment]
You might want to take a look at #20, #51 and #132.
