### ISSUE TITLE
bounce forwarding

### ISSUE THREAD

**Issue by stukint** [atech/postal#242]
Is it possible to configure all bounces to be forwarded to another address? My mailing application doesn't currently support webhooks but can process bounces from return path address. Postal doesn't forward bounces to return path address.

**Comment by adamcooke** [comment]
Yes. You can add a route with the name `__returnpath__` and no domain and all bounces can be routed wherever you want.

**Comment by stukint** [comment]
Return path routes must point to an HTTP endpoint is. My application doesn't support webhooks at the moment. Is there any other way?

**Comment by adamcooke** [comment]
Ah - not at the moment, then I'm afraid.

**Comment by rsgehlot** [comment]
Is there any progress on this? 

We want to allow forward bounce notifcation to an external email address

**Comment by alexander-rieder** [comment]
+1

> Is there any progress on this?
> 
> We want to allow forward bounce notifcation to an external email address
