### ISSUE TITLE
Idea: Why don't you open a forum where we can support between us?

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#243]
Probably you already had this idea ("My idea", next one will be put solar panels between us and our bordering country).
You can install some forum (I recommend Discourse), where we can share support not only about Postal, also about anti SPAM programs, or all that is relevant to email sending.
Something like Litmus forum https://litmus.com/community/discussions
But not about design, just about sending.
Just that, an idea, you can close this "issue".

**Comment by JesseJHernandez** [comment]
What about a slack channel I can create and share?

**Comment by elfeffe** [comment]
I think Slack is good for real time conversations, but is not good for searching past tips, fixes.

**Comment by adamcooke** [comment]
You can join the #atech IRC channel on Freenode. @catphish and I are usually around in there if you need simple real-time help.
