### ISSUE TITLE
Return Path being added forcefully by postal

### ISSUE THREAD

**Issue by johnLeads** [atech/postal#245]
I ust want to change return path to bounces@mydomain.com so i have forced this through my mailwizz application. but in header although header added in by mailiwizz but still postal forcefully adding return path from his end. check the email  source details.
#############
RC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@talentiqcorp.co header.b=L4IcdvM9;
       spf=neutral (google.com: 45.79.93.198 is neither permitted nor denied by best guess record for domain of srkaez@rp.postal.example.com) smtp.mailfrom=srkaez@rp.postal.example.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=talentiqcorp.co
####--this is added by postal
Return-Path: <srkaez@rp.postal.example.com>

Received: from mydomain.com (mydomain.com. [45.79.93.198])
        by mx.google.com with ESMTPS id q26si1763717pge.526.2017.06.27.04.29.03
        for <adeel.akhtar560@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 27 Jun 2017 04:29:03 -0700 (PDT)
Received-SPF: neutral (google.com: 45.79.91.198 is neither permitted nor denied by best guess record for domain of srkaez@rp.postal.example.com) client-ip=45.79.91.198;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@talentiqcorp.co header.b=L4IcdvM9;
       spf=neutral (google.com: 45.79.91.198 is neither permitted nor denied by best guess record for domain of srkaez@rp.postal.example.com) smtp.mailfrom=srkaez@rp.postal.example.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=talentiqcorp.co
Resent-Sender: srkaez@rp.postal.example.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=talentiqcorp.co; s=postal-qo9NkG; t=1498562943; bh=7ZNBVeRwqhiw63Bc3aU4b2l3HuLIcmjKLDXrml+NeeU=; h=message-id:date:subject:from:to; b=L4IcdvM9RbnAgv6y+feHKEHCLIvYWd15dp8D94C78PQaOmoD3TZQNkL4pUcsd9MmOogad2KkrKg37Xz5NRdFpOVEgZ4yVk4ahF1us6zlVHlogolCpWlXgXMBgm6JiH+hEFeCb4QGFP2sgkqW6HROepX1bAdC3vbIKjpuLrAQxE0=
X-Postal-MsgID: QpWPcCbCmx2p
Received: from portal.mydomain.com (::ffff:50.116.12.27 [::ffff:50.116.13.27]) by mydomian.com with SMTP; Tue, 27 Jun 2017 11:29:02 +0000
###--this is added by mailwizz
Return-Path: <bounces@mydomain.com>

**Comment by johnLeads** [comment]
I just want to use bounces@mydomain.com  nothing else

**Comment by mattmartincouk** [comment]
I'm not sure you can do this.

Have you skipped adding the reverse path DNS record so that it does not validate. Does that still make the change?

**Comment by johnLeads** [comment]
I just want to force this bounces@mydomain.com email address. MX record against mydomain.com already in place for incoming mails.

**Comment by mattmartincouk** [comment]
Yes I get that.

Please answer the earlier question regarding the DNS check.


--
m: +44 (0) 7774 277255
f: facebook.com/mattm
twitter / instagram / flickr: mattmartincouk

**Comment by johnLeads** [comment]
No I have not added any CNAME record. Guide me about that what it requires to set bounces@mydomain.com as return path for all outgoing emails regardless of domains

**Comment by mattmartincouk** [comment]
In that case, I don’t think it is possible.... and I’ll take a stab in the dark, probably not what the software was ever going to do, but the guys will be along to say otherwise.

You can always modify the code yourself though, but you’d be on your own.


--
m: +44 (0) 7774 277255
f: facebook.com/mattm
twitter / instagram / flickr: mattmartincouk

**Comment by johnLeads** [comment]
Can you tell me where in the code or file that return path is being added by postal so i can change directly in it to desired one.

**Comment by mattmartincouk** [comment]
I can’t... without looking myself.

Search for things like returnpath etc. Otherwise you might need to wait for the authors to come along.


--
m: +44 (0) 7774 277255
f: facebook.com/mattm
twitter / instagram / flickr: mattmartincouk

**Comment by catphish** [comment]
Unfortunately, Postal does not currently support using a static return path. Postal generates dynamic return paths for emails to allow bounces to be handled. I can't think of any reason why a static return path couldn't be supported, but this isn't currently the case.

I note that your sending domain appears to be set to "rp.postal.example.com" so you definitely have some misconfiguration with your sending domains.

**Comment by stukint** [comment]
Just to chip into this. I use mailwizz too and i experience the same problem. Cannot update bounces in the application. I observed that the return path is generated once and remains the same for each mailserver. I know there is the returnpath routing but restricted to http endpoint. Lets say my returnpath is "returnpath@psrp.example.com" and i add the domain psrp.example.com. Then i create my address endpoint and configure route returnpath with the "psrp.example.com" domain i added earlier. Would the bounces then be forwarded to my address endpoint?

**Comment by adamcooke** [comment]
I've added issue #255 which will allow messages to the return path to be sent to other email addresses or smtp servers as well as HTTP. This is preferable to a statically configured return path.

**Comment by ppadron** [comment]
Would Postal accept a patch that allows setting the Return-Path "by hand"? This is useful for me too, because my own app handles bounces and I use specific ID as the localpart to identify the bounce.

https://github.com/templateria/postal/commit/d5941a99ffbfe7c49bcbeb4aea6ac05d2e1b9c42

Also: #382
