### ISSUE TITLE
Question about ISPs' Sending Policies

### ISSUE THREAD

**Issue by sbusso** [atech/postal#246]
How are ISPs' Sending policies managed (if they are) ? 

For example, yahoo will not accept more than n emails per second from a domain / ip, else they will defer upcoming emails. ISPs

**Comment by mattmartincouk** [comment]
They are not.

Generally, the other end will soft reject the message and postal will keep trying, increasing the time between attempts.

Overtime as your volume grows, Yahoo et all, will increase the rate you can send to them up.

Known as warming up the IPs.

Either way, a soft reject won't cause you many issues if dealt with correctly - which postal does.

**Comment by sbusso** [comment]
In my experience it does cause issues with big enough lists. If you dont follow yahoo policies your smtp ip could get temporary blocked, not just soft rejected. Then sending to 20 000 yahoo subscribers, with increasing time, would get email staying days in deferred queue.

**Comment by catphish** [comment]
If you send a large number of emails at once from a brand new IP address, then yes, it is very likely you will see temporary blocks. This may take the form of graylisting (temporary rejectons) causing email to be delayed by hours or days, or it may result in the IP being temporarily blacklisted, and emails being hard rejected, in which case they will not be re-attempted.

In any case, there is no standard policy for ISPs, you must simply start with smaller volumes of email until ISPs know they can trust you. If you send the same email to thousands of people at once, you're far more likely to see problems.

Of course most important of all, don't send spam.

**Comment by sbusso** [comment]
Yahoo, Hotmail and even Gmail do have policies. Many ISPs have. Please check. If you have a subscriber list with many 100s thousand subscribers, that is situation for a lot of companies (the average sending for big companies in the world is about 5 000 000 a month), you are facing those issues and need to implement 'slower' queues depending on the ISP. So I guess from your answers high volume sending havent been addressed in Postal.

**Comment by catphish** [comment]
It might be that some ISPs have specific limits. Please could you provide some links to examples of these ISP-specific policies?

I'm afraid Postal has no options to pre-program those limits. Instead, we currently simply recommend a slow ramping up of sending over the course of days to weeks. Doing this absolutely addresses the problem, however if there is a faster and more accurate way to achieve this by programming specific limits, I'm afraid we have not yet implemented it.

Generally a gradual migration of message to a new pool of sending addresses is not a big problem.

**Comment by sbusso** [comment]
Sorry for late reply was moving house...

I dont have official information, but few years of dealing with throttling with various ISPs, the most difficult one being yahoo. Here is an example of message from french provider on a daily newsletter sent to 1000 subscribers with sendgrid and dedicated IP. Sendgrid deos not manage throttling, and recommend to do it from client. 

![image](https://user-images.githubusercontent.com/346/27815873-f0b60e22-60b1-11e7-82e4-beab3ebd9ddb.png)

and here is configuration i have setup for Postfix and yes this linked to #247

![image](https://user-images.githubusercontent.com/346/27815903-2999ac76-60b2-11e7-98ee-3cd19bde2802.png)

**Comment by mattmartincouk** [comment]
Could you not smarthost postal from your postfix server so the limits are obeyed as a temporary workaround?

We actually do this for all our outbound email from our app servers in case our postal is down or busy and works very well - although we don't need to rate limit like you are.

**Comment by catphish** [comment]
It's interesting that people have found this to be necessary, as we have never experienced issues with it, as long as email delivery rates were ramped up slowly. It does look like a delivery rate limit, either globally, per-destination-domain, or more fine-grained would be useful though.

**Comment by mattmartincouk** [comment]
Same here. We've found the automatic retry over time works just fine. Guess it could be due to the content too as our emails are mostly transactional.

**Comment by sbusso** [comment]
yes transactional is not an issue, it is for bulk sending. There are a lot of situation for rate limitation, content, complaints, and ISP policies. At yahoo you may have different rates if your are registered or not to their service. This configuration is for a 4 years old installation sending an average of 100 000 emails during week ends. A per domain rate limit would be interesting or maybe easier per server with a routing rules per domain.

**Comment by longhorninmd** [comment]
@sbusso the commercial MTAs have tuned delivery configurations, but you're paying for them.  With an open-source product like Postal, there's obviously a trade-off.

**Comment by sbusso** [comment]
Actually they mostly don't. They usually recommend to throttle sending from the client, that is IMO absurd. But yes this is not an easy problem to solve.

**Comment by longhorninmd** [comment]
Who recommends that?

**Comment by sbusso** [comment]
Sendgrid to give one

**Comment by longhorninmd** [comment]
That's a service.

I was referring to commercial MTA software that ESPs use within their
"plumbing."  Commercial alternatives to Postal...

**Comment by sbusso** [comment]
Some Commercial MTA do have throttling. So to go back to your first comment and my initial question, to know how postal is managing it. I have got my answer. thanks.

**Comment by sbusso** [comment]
PS: i have never considered open source as a trade off to commercial products, for me, open source is often better.

**Comment by adamcooke** [comment]
For the record, Postal was designed for sending transactional emails and not bulk messages. Very little consideration has been given to sending bulk mail through it.

**Comment by sbusso** [comment]
thanks for the information, apart of throttling, do you see other limitation by design that could refrain using Postal for bulk sending ? (like speed, load, ...)

**Comment by andris9** [comment]
Handling target specific rules is anyway a difficult problem. For example in [ZoneMTA](https://github.com/zone-eu/zone-mta) I have implemented zone based throttling (eg speed limits for messages sent through a specific virtual MTAs) and also target specific connection rules (eg. max 3 parallel connections against yahoo.com and max 20 parallel connections against gmail.com) and it is still not enough – a lot of email domains end up to the same MX but to know that I'd have to resolve the DNS entries beforehand while on larger sending loads DNS resolving is a major part of the job so I would not want to do it before creating the actual connection.
