### ISSUE TITLE
How do i enable click tracking

### ISSUE THREAD

**Issue by steliosmilidonis** [atech/postal#248]
I see that there is an option to get"Message click events"from webhooks, how do i enable click tracking?

**Comment by ne0c0de** [comment]
This is what i'm working on it now.

It's documented here: https://github.com/atech/postal/wiki/Click-&-Open-Tracking

But i think that is the documentation is little poor on this issue. I'm just trying to configure nginx config file in order to server both management panel and the click service.  Currently i didn't get success there..

**Comment by willpower232** [comment]
@steliosmilidonis click tracking requires the fast server to be enabled in `postal.yml` with a secondary IP address on your server. Then all you have to do is add tracking domains to the domains you want to click track.

@ne0c0de the click service has its own web server since it binds to a different IP address than nginx. it handles its own SSL so theres no benefit in adding it to nginx

**Comment by steliosmilidonis** [comment]
@ne0c0de @willpower232 thanks guys will be trying it out today

**Comment by ne0c0de** [comment]
Hello @Ben-Honeywill 

I take an help from this issue: https://github.com/atech/postal/issues/215

Now both of management panel and click service is looks like working.

Bu when i send an email that is the content (of course html):

``
test mail content here and the link: <a href="http://www.example.com/">http://www.example.com</a>
``

it's not converting the links to the own links. How can i check this problem source? (for example, do i need to send an additional API parameter)

**Comment by willpower232** [comment]
have you added a tracking domain?

**Comment by ne0c0de** [comment]
Where? on postal.yaml ?

If yes, yes i added it. By the way my nginx configuration was wrong. i fixed that and now click url is not serving any more.

Here's my configuration:

nginx:

``
server {
    listen [::]:80;
    listen 10.1.0.12:80;
    server_name mailer.social-internet.co;
    return 301 https://$host$request_uri;
}

server {
    listen [::]:443 ssl;
    listen 10.1.0.12:443 ssl;
    root /opt/postal/app/public;
    server_name mailer.social-internet.co;
``

postal.yaml:

``
fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address: 10.1.0.13

dns:
  track_domain: eclick.social-internet.co
``

10.1.0.12 is the private address of a public ip which belongs to management panel
10.1.0.13 is the private address of a public ip which belongs to eclick.social-internet.co

Am i doing something wrong?

**Comment by willpower232** [comment]
you must remove `listen [::]:443 ssl;` and `listen [::]:80;` then restart nginx and restart postal

as per my edit, refer to https://github.com/atech/postal/issues/189 and change your link a little

**Comment by ne0c0de** [comment]
When i remove those lines from nginx config, postal management url is giving

    502 Bad Gateway

error.  When i executge postal stop && postal start command i see this result:

    Started Procodile supervisor with PID 2483

then i try ``postal restart`` and saw this result:

Restarted web.1
Restarted fast.1 -> fast.2
Restarted worker.1 -> worker.2
Restarted cron.1 -> cron.2
Restarted smtp.1
Restarted requeuer.1 -> requeuer.2

i suspect that web server for management service is not working right now, also fast server is not reachable :(

**Comment by ne0c0de** [comment]
correction:
After waiting few minutes, both management panel and redirection link is looks like working. now i'm trying to send a test mail

**Comment by willpower232** [comment]
You have to go into the postal interface, next to Domains on the mail server will be a Tracking Domains tab.

You have to add a Tracking Domain which is a subdomain that is a CNAME to eclick.social-internet.co

**Comment by ne0c0de** [comment]
I just tried to send this content:

mail click test",'test mail content here and the link: <a href="http://www.example.com/">http://www.example.com</a>
<a href="http://www.google.com">http://www.google.com</a>
<a href="http://www.google.com/?q=abc">http://www.google.com/?q=abc</a>
<a href="http://www.google.com/search/">http://www.google.com/search/</a>
<a href="http://www.google.com/">http://www.google.com/</a>

none of the links are converted to tracking link. any log that i can check?

**Comment by ne0c0de** [comment]
> You have to go into the postal interface, next to Domains on the mail server will be a Tracking Domains tab.

Thank you for this, now the links are converted to tracking domain. This is great 💯 

However when i click the converted link, it's redirecting to the original url by adding 

    &gws_rd=cr&ei=8A9WWZS9Jsv0arPXgdAH

to end of the url. is there a way to disable it?

**Comment by willpower232** [comment]
Apparently that is appended because you're visiting google. If you change the link to one of your own, it should work properly.

**Comment by steliosmilidonis** [comment]
Hi i have tried teh changes however after updating postal to the latest version smtp in no longer working
 Although i specify smtp in the con file

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525

and can see its running
|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      19:05        pid:31590    respawns:0      port:-        tag:-


i cannot see port 2525 open anywhere, this was working before i updated

root@postal:/opt/postal/config# netstat -nlptu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      31584/[postal] web.
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      1554/beam.smp   
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1685/mysqld     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1435/nginx -g daemo
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      1319/epmd       
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      2229/0          
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1435/nginx -g daemo
tcp        0      0 0.0.0.0:7711            0.0.0.0:*               LISTEN      1150/sshd       
tcp6       0      0 :::5672                 :::*                    LISTEN      1554/beam.smp   
tcp6       0      0 :::80                   :::*                    LISTEN      1435/nginx -g daemo
tcp6       0      0 :::4369                 :::*                    LISTEN      1319/epmd       
tcp6       0      0 :::25                   :::*                    LISTEN      31590/[postal] smtp
tcp6       0      0 ::1:6010                :::*                    LISTEN      2229/0          
tcp6       0      0 :::443                  :::*                    LISTEN      1435/nginx -g daemo
tcp6       0      0 :::7711                 :::*                    LISTEN      1150/sshd

**Comment by webhostinggeek** [comment]
Can we only track email open without adding any URL? 99% emails will not have URL's but we want to track who opened and who did not open.

**Comment by Smriti225** [comment]
To enable click and open tracking for all emails, can we use a single tracking domain  or do we need to add each sending domain separately for tracking in the Postal UI?
