### ISSUE TITLE
Domains / Users

### ISSUE THREAD

**Issue by ThatDeveloper** [atech/postal#249]
Hello, I have two questions about postal.

1. Why do organizations and a mail servers have domains? What is the difference? (Do I have to add my domain on both?)
2. I have the domain, for example, hello.com. How can I create a account, e.g. thatdeveloper@hello.com, and how can I log into it with e.g. Outlook? Because I can only find routes but I don't want to route, I want to create user accounts for my users (NOT for postal, for mailserver) I would like to create accounts for all my people.

Thank you for your help. :)

**Comment by willpower232** [comment]
1. if you want a domain to be available for multiple mail servers you can add it at the organization level, this means you can track and manage email in multiple servers whilst sending using the same domain

2. please see https://github.com/atech/postal/issues/204, postal is only for sending emails from a service much like Mailgun or Sendgrid (but better)

**Comment by ThatDeveloper** [comment]
@willpower232 Is there an alternative to postal then who can provide this feature I would like?

And what is the purpose of postal then?

**Comment by willpower232** [comment]
If you have developed a web application or server-based system or just want your website to be able to send emails that you can track, Postal is a self hosted solution to do so.

If you want to give users email accounts that they can send and receive email from, you should look into an email service such as Office 365 or Google Apps.

**Comment by ThatDeveloper** [comment]
"If you have developed a web application or server-based system or just want your website to be able to send emails that you can track, Postal is a self hosted solution to do so."

Can you provide an example? Routes or whatever?

**Comment by willpower232** [comment]
If you're running a system that invoices people for example, postals tracking can be integrated into your system so that
- you don't need to run an email server on your server
- you can send as many messages as you want for minimal cost
- you can integrate click tracking with your system and show your customers when their messages were received, opened, clicked, blocked etc etc

**Comment by ThatDeveloper** [comment]
Hmm, tahnk you. But why does postal not provide this feature? I mean they already have user management for organizations? This would be perfect, because postal is the best looking tool ever I saw for mail. I don't ask for webmail. I ask for accounts. e.g. thatdeveloper@mydomain.com

**Comment by spheron1** [comment]
Because that's not what postal is designed to do - Postal is an MTA, not an MDA.
