### ISSUE TITLE
Adding external SMTP server within Postal?

### ISSUE THREAD

**Issue by ravimantri** [atech/postal#251]
Dear Team,

Thanks for the amazing application, which is interactive and easy to install. I just wanted to know I've one server with PowerMTA and I want to connect/configure that external server within Postal.

Looking for your help.

Thanks

**Comment by mattmartincouk** [comment]
Do you mean have Postal send messages to PowerMTA? or have PowerMTA send messages in the Postal and then on to their destinations.

**Comment by ravimantri** [comment]
Hey @mattmartincouk, Thanks for your message.

I mean Postal send messages to PowerMTA ;)

Because I feel it can work extremely with blend of both systems.

**Comment by mattmartincouk** [comment]
I don't think it can - it's not designed to do that (afaik) and it is designed to be the end point instead of something in between that and another gateway.

Of course, you have the code and can change as you wish but that's very much down to you to do/diagnose/test etc.

**Comment by ravimantri** [comment]
I feel you're right, but with adding ability in Postal for managing/forwarding to other MTA like Postfix, PowerMTA, etc. it will a great feature for easy and much better management.

Imagine you've 5 different servers and want to use one Postal installation only then this is the need of the scenario.

Thanks

**Comment by mattmartincouk** [comment]
It would actually make some of the features in Postal useless. Like the exact tracking of messages from being received to being sent to the remote MX. Your host would then be the MX for every message and then you'd have to search your own logs to see rejection reasons etc.

I don't see this happening and if anything, would be a step backwards. There are ways to increase the volumes that postal deals with as already documented but I see the only way of doing what you want is to intercept SMTP traffic from the server and force it through to another by firewall rules or the like but completely NOT recommended.

**Comment by ravimantri** [comment]
Thanks for your suggestion. I understand what you're saying but what I'm thinking about Postal that it is a MTA but it can be a complete Email Traffic Management suite. Thanks

**Comment by adamcooke** [comment]
You can configure Postal to relay all its outgoing messages through another relay however this isn't really recommended as you'll lose lots of features from Postal. 

However, the following configuration can be added to your `postal.yml` if you do REALLY want to do it.

```
smtp_relays:
  -
    hostname:
    port: 25
    ssl_mode: Auto
```

**Comment by Power-MTA** [comment]
latest version powermta / pmta available with lifetime license key.
+ another tools available
Skype: salimrezabd04
Telegram: salimrezabd
Telegram: salimrezabd1
