### ISSUE TITLE
How to bulk force messages that are stuck in queue to release now?

### ISSUE THREAD

**Issue by ravimantri** [atech/postal#252]
Dear Team,

Thanks for the amazing application, which is interactive and easy to install. I just wanted to know how to bulk force messages that are stuck in queue to release now?

Looking for your help.

Thanks

**Comment by mattmartincouk** [comment]
Held messages? If so, this is briefly discussed in #239 if so.

**Comment by ravimantri** [comment]
Hey @mattmartincouk, Thanks for your message.

I saw that, but the issue I've about 100K emails stuck with status "held". So the main thing is how can delete all or force all to deliver?

Thanks

**Comment by adamcooke** [comment]
See #239 for an example of how to release them using the console.
