### ISSUE TITLE
Persistent Delivery Error

### ISSUE THREAD

**Issue by longhorninmd** [atech/postal#259]
I have been getting this error for some recipients:

553 #5.1.8 Domain of sender address <nwq7bw@xxxx.xxxxx.net> does not exist

We host on AWS and I've set up RDNS and also all TXT & CNAME DNS records are set up per Postal instructions and verified to be correct.  When I test delivery using the Mail-Tester tool, I get a 10/10.

Thx in advance!

**Comment by mattmartincouk** [comment]
Can you post what xxxx.xxxxx.net  is and then edit it out later?

**Comment by adamcooke** [comment]
That isn't an error that's generated by Postal itself so it must be coming from the server you're sending messages to. It would be useful to know the service/server that you're sending the message to.

**Comment by catphish** [comment]
xxxx.xxxxx.net does indeed not exist :slightly_smiling_face:

**Comment by longhorninmd** [comment]
Please see attached...

<img width="448" alt="screen shot 2017-07-10 at 10 41 15 pm" src="https://user-images.githubusercontent.com/133784/28048799-44f3883e-65c1-11e7-8b3d-0fe048091fd6.png">
<img width="643" alt="screen shot 2017-07-10 at 10 42 11 pm" src="https://user-images.githubusercontent.com/133784/28048800-45050bf4-65c1-11e7-89e0-222b84c40d78.png">

**Comment by catphish** [comment]
I've checked the DNS. I'm not certain what it triggering this issue, but I did spot one error in your configuration. I'm not sure why the automated checks didn't pick this up.

```
rp.mta.migo01.net mail is handled by 10 mx.mta.migo01.net.
```

I believe this should be `mta.migo01.net.` as `mx.mta.migo01.net` does not exist.

**Comment by longhorninmd** [comment]
Ok, I've updated the MX record per your comment.

**Comment by mattmartincouk** [comment]
Does it work after the changes?

**Comment by longhorninmd** [comment]
Don't know yet.  We'll be monitoring the queue & any errors.
