### ISSUE TITLE
Mails going into spam folder

### ISSUE THREAD

**Issue by c3x** [atech/postal#26]
Hi,
I'm new to this. I install Postal today. Thanks for the good documentation.

I setup my first testserver and send out an testmail. This mail are going directly into the spam folder of the receipient.
Any ideas why? 

When I send through MailGun, I have no issues.

Torsten

**Comment by adamcooke** [comment]
Send over some headers of the email and I might be able to tell you why that's happening.

**Comment by c3x** [comment]
Hmm ... I just setup an 2nd domain and there it's working fine. 
I will check it with a few more domains into the nexr days. If I got still errors, I will post the headers.

Thanks.

**Comment by adamcooke** [comment]
Righto.
