### ISSUE TITLE
LE Expiry Notices

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#260]
Should the LE engine automatically renew the certificates?

We're getting expiry notices for all the self-generated SSLs for the links in the postal app.

I can't spot a renewal command anywhere though but would have thought this would be automagic.

**Comment by adamcooke** [comment]
Postal will renew tracking certs automatically. You can check the renewal dates for your certs in the `track_certificates` table which should show their expiry date plus the date scheduled to renew them.

**Comment by mattmartincouk** [comment]
It may be worth bringing down the renewal time to make it happen sooner otherwise messages are going to be sent out reminding that you need to renew when this will happen automatically.

We have 31 entries in that table, so that's 31 unnecessary reminders.

Can it be changed via a config option?

**Comment by adamcooke** [comment]
It's not configurable but I will add another issue to lower it because, as you say, the reminders are rather unnecessary.
