### ISSUE TITLE
Slow queue due to softfails

### ISSUE THREAD

**Issue by Accueil14** [atech/postal#262]
Hi,

I'm confused with the processing of the queue. 
When an email is softfailed, it's put back in the queue, with pending emails. 
Why don't pending emails get processed before softfailed ones ? 

How do I limit the number of softfail retries ? 

Thanks

**Comment by catphish** [comment]
Pending emails should be processed immediately. I would not expect them to be stuck behind soft failed emails, unless those soft failed emails are due to be retried.

You can configure the maximum number of retries in postal.yml:

```
general:
  maximum_delivery_attempts: 18
```

**Comment by Accueil14** [comment]
> Pending emails should be processed immediately. I would not expect them to be stuck behind soft failed emails, unless those soft failed emails are due to be retried.

shouldn't pending email be processed before retried email ? Is it manageable

**Comment by catphish** [comment]
Once retried email is considered due for retry it is handled in exactly the same manner as new email. It is currently not possible to prioritize new email over email being retried. If you find you are experiencing trouble with this, the best immediate solution is simply to run more workers. This will mean there are enough available to connect to working destination while some workers are tied up trying to connect to broken destinations.

**Comment by Razva** [comment]
> Once retried email is considered due for retry it is handled in exactly the same manner as new email. It is currently not possible to prioritize new email over email being retried.
Any way to change this behaviour, or have it as a option? I think that most of us prefer to process all outgoing mail asap, than begin retrying failed. In this way messages that are OK will not be stalled by bounces/fails.

**Comment by therealelyayo** [comment]
ypdate on this have same issue
