### ISSUE TITLE
Incoming Route to SMTP Endpoint: SSL certificate verify failed

### ISSUE THREAD

**Issue by igerzog** [atech/postal#272]
Hi,
I am trying to send incoming messages for email address to another external SMTP server and always receive SSL_connect error. 25, 465, 587 - no difference. The sender log:

[2017-07-14T01:12:15.904] INFO -- : [WSZU0XWK] Cannot connect to **smtp endpoint ip**:587 (**smtp endpoint hostname**) (OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed)
[2017-07-14T01:12:15.909] INFO -- : [WSZU0XWK] -> No SMTP server available for **my verified domain**
[2017-07-14T01:12:15.909] INFO -- : [WSZU0XWK] -> Hostnames: ["**smtp endpoint hostname**"]
[2017-07-14T01:12:15.909] INFO -- : [WSZU0XWK] -> Errors: ["SSL_connect returned=1 errno=0 state=error: certificate verify failed"]
[2017-07-14T01:12:16.044] INFO -- : [WSZU0XWK] Finishing up

**Comment by catphish** [comment]
I would initially assume that the issue is indeed the problem that the error message claims. The server `smtp endpoint ip` is configured for SSL but is not returning a valid certificate for `smtp endpoint hostname`. Is this your email server? I am obviously not able to verify this.

**Comment by igerzog** [comment]
> Is this your email server?

Yes, it's mine. SSL to 465 and STARTTLS to 25 and 587 work fine while I can send letters from mail apps and receive them from external smtp servers. The hostname is `mail.sevmos.net`.

**Comment by igerzog** [comment]
Well, the problem was solved by switching SMTP Endpoint's ssl mode to `Auto`. Choosing `STARTTLS` or `TLS` with appropriate ports produces the mentioned error - `certificate verify failed`.

**Comment by catphish** [comment]
To clarify, when specifying `TLS` or `STARTTLS` we assume that you want a secure connection and will only ever negotiate a fully secure connection. When selecting `Auto`, Postal will use TLS if it is available, but will fall back to an insecure connection if TLS is not available, or will negotiate encryption with an insecure certificate if necessary. I do wonder why the connection is failing though if you are seeing a valid certificate with the openssl command line.

**Comment by igerzog** [comment]
To tell the truth I have not seen any errors or warnings regarding to SSL routines in my logs since then. But as a matter of fact all the sent webhooks to RequestBin no matter of payload type contain the same statement: `"sent_with_ssl":false`. And from the other hand - this screenshot. Trying to dig through the code.

![screen shot](https://user-images.githubusercontent.com/18285761/28242817-ccf4d11a-69be-11e7-967f-c776877c3c3e.png)

**Comment by igerzog** [comment]
I returned to the idea to force encryption while sending messages to SMTP Endpoint or while relaying to external server. The encryption only works when I state `ssl_mode` to `Auto`. And does not work at all when:
- `ssl_mode` is set to `TLS` and `port` is `465`
  - error is `SSL_connect returned=1 errno=0 state=error: certificate verify failed`
- `ssl_mode` is set to `Auto` and `port` is `465`
  - error is `end of file reached`

`openssl s_client -connect hostname:465 -tls1_2 -crlf -debug` works correctly from the postal ip in terminal.

**Comment by igerzog** [comment]
Is there any new information about this ssl issue?

**Comment by igerzog** [comment]
The problem is still not resolved. I tried different solutions but can't find the exact variant for postal. Most of recommendations relayed to `X.509.Store` and `ca_file` directives. I can make some tests but really need a point in postal code to start from.
