### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ravimantri** [atech/postal#273]
Hello Mates & Team (@adamcooke @catphish) from today morning I'm receiving the following error:

502 Bad Gateway

What to do? Looking for your urgent help! Thanks

**Comment by ravimantri** [comment]
Oh! Solved by running "postal start" because my server was automatically restarted.

**Comment by ravimantri** [comment]
Now all emails are going in Pending and nothing happening and at my EMA side I'm getting:

Here is a transcript of the error message:
++ Swift_SmtpTransport started
>> MAIL FROM:<info@*********>
<< 250 OK
>> RCPT TO:<web-****@mail-tester.com>
<< 250 OK
>> DATA
<< 354 Go ahead
>> 
.
<< 
!! Expected response code 250 but got code "", with message "" (code: 0)

**Comment by ravimantri** [comment]
Good news! Solved with 2nd time restart :)

**Comment by catphish** [comment]
Please refrain from tagging me in tickets.

**Comment by catphish** [comment]
PS. glad to hear you were able to resolve this. I'm not sure if there is a another ticket somewhere regarding starting Postal at boot.
