### ISSUE TITLE
email go in spam fixed

### ISSUE THREAD

**Issue by billyprice1** [atech/postal#276]
email only go in spam when i use postal any help

**Comment by igerzog** [comment]
Place here any raw message delivered to spam folder to get the opportunity to make analysis.

**Comment by billyprice1** [comment]
oh it fixed i forgot to setup a record also how do i send with smtp

**Comment by igerzog** [comment]
Ok. Check the syntax first

**Comment by billyprice1** [comment]
Oh i need to send emails from ibilly.me so i cant send it from sentora.ibilly.me that was the problam
