### ISSUE TITLE
keep original sender when relaying email internally?

### ISSUE THREAD

**Issue by jaitnt** [atech/postal#292]
This is my setup:
Postal -> E.F.A. -> Exchange
My problem is that on E.F.A. every email shows up as "From: swp7td@rp.domain.xxx". Is it possible to keep the original sender when relaying mails internally?

**Comment by jaitnt** [comment]
I swapped postal and E.F.A. Now E.F.A is working correctly but I think postal is much more efficient in dropping email with unknown recipients.

**Comment by catphish** [comment]
The quick answer is that Postal doesn't support this. We have had a couple of requests for the possibility of not modifying the return path, but the current design of Postal revolves around dynamically generated return paths. Note that the actual From address is not changed, if this isn't shown in EFA, maybe this is an easy change to make on their side.

**Comment by jaitnt** [comment]
No problem. E.F.A. -> Postal -> Exchange solved it.
Postal is great!
