### ISSUE TITLE
Using Postal in Virtualbox

### ISSUE THREAD

**Issue by yeah-nothing** [atech/postal#298]
Could I install Ubuntu 16.04 and Postal in Virtualbox? Is there a third party service that would allow me to assign public ip addresses to my Virtualbox server? I guess my question is this. Can I host Postal locally?
If so what would I need to do? The computer I'm using has about 8gb of RAM

**Comment by willpower232** [comment]
The IP addresses would be controlled by either your hosting company or your ISP, depending on where your computer is. Unless you have a fixed static IP address for your postal server to the internet, you will probably not have a great experience.

There is nothing stopping you hosting postal locally, technically it will run on any Ubuntu 16.04 server, but it is likely most of your email would end up in recipients spam folders.

**Comment by catphish** [comment]
As WIll says, you can definitely host is locally, and it will send emails, but for various reasons, you will likely not have the best experience running it in this way. Without a public IP address, it will not be able to receive email, and unless you control the DNS for your public facing IP address, you are very likely to get blocked by every spam filter you reach. If you simply wish to play with the software, it will work fine on VirtualBox. If you configure it for bridged networking, it will get an IP on your local network, so you should be able to connect to it and send email to it.
