### ISSUE TITLE
VPSdime

### ISSUE THREAD

**Issue by yeah-nothing** [atech/postal#299]
I found what appears to be a really cheap VPS service. It's called VPSdime. They offer a 6gb RAM vps for $7.99 a month.However they don't like mass mailing. Is there a workaround? Can anybody recommend some cheaper alternatives that allow mass mailing? 

Amazon AWS seems like it would be a great way to install Postal. However somebody on Git Hub told me that Amazon AWS does email filtering.

**Comment by willpower232** [comment]
If you host postal with AWS, I direct you to my issue https://github.com/atech/postal/issues/192. Going on that link and filling in their form should allow you to operate postal properly.

If you are looking to mass mail a large amount of people, I might suggest mailchimp as an alternative email solution provider. Their free tier covers a lot of usage.

**Comment by gthb1** [comment]
Considering that Postal was designed with a number of organizations being able to send through it, would that not be the point of reasonable mass email?

**Comment by willpower232** [comment]
Postal was designed for transactional email, i.e. sending someone a signup email or forgotten password email or monthly invoice etc etc, emails that the customer will definitely be interested in.

Mass email would traditionally imply marketing messages sent to many people instantly when requested by the company, emails that the customer may not be interested in right now and may file to spam later.

**Comment by gthb1** [comment]
If you want to have an MTA (Postal) to send for some announcement lists or discussion lists, similar to Yahoo or Google Groups, but kinda private, like your own MailMan, MajorDomo, ListServ, that would work as well, or not?

**Comment by catphish** [comment]
Postal does not really mind what kind of email it is sending, however it was designed to send transactional email. This has a couple of implications.

1) Postal saves every email sent through it. This is very useful when you are sending lots of unique emails and want to see what was sent. It is a needless overhead if you are sending large quantities of identical email. It would be saving thousands of copies of the same email.
2) We have little interest in the sending of marketing emails and are happy to leave this task to alternative providers / software

I don't know about mailing list management, but this is not something that Postal currently handles itself. There is no functionality for list management for forwarding emails to lists of users.

With regard to providers, the best option is always to explain your requirements and ask their opinion on the suitability of their service. I'm afraid I don't know about specific VPS services, but I'm sure many (especially the cheaper ones) are fed up with people signing up purely for the purposes of sending spam, so most likely you will have more trouble with trying to send email from such providers.

**Comment by gthb1** [comment]
How would one go about configuring the amount of data kept by postal?
