### ISSUE TITLE
Sone sort of external authentication support

### ISSUE THREAD

**Issue by evaryont** [atech/postal#3]
There are a number of protocols in this space that all have fairly wide deployments, so pretty much any of these choices isn't too bad.

Namely, I don't want to have to manage another credential pair. I just want to be able to point this app to a IDM of some sort, like FreeIPA, Active Directory or Gluu, and use those credentials.

Common protocols:
* SAML
* LDAP
* OpenID Connect
* OAuth
* Trusting specific headers, to let some authentication proxy like bitly's oauth_proxy handle it for you

Otherwise, I'm super excited about this! It looks really well done.

**Comment by michielboekhoff** [comment]
I especially second the addition of OAuth. I'd be willing to create a PR for this if there's interest.

**Comment by evaryont** [comment]
Probably the easiest way is to migrate postal to using OmniAuth. That way deployments can use any of the multitudes of strategies.

**Comment by theos-space** [comment]
Any progress made on this ticket? I'm interested in using Postal, but the lack of LDAP support is the only thing stopping me :/

**Comment by adamcooke** [comment]
I'm afraid there are no plans to work on any external authentication for this at the moment.

**Comment by seboudry** [comment]
Hi! Any chance to put this requests in backlog again?

**Comment by AndrewBucklin** [comment]
This is the only thing lacking from Postal. With today's requirement for managed identities and the security controls implemented by the identity provider (adaptive 2FA, account lockout, suspicious logins, etc), it's important to allow for external identity providers. Not to mention, having a single identity makes it much easier to onboard and offboard users.
