### ISSUE TITLE
SMTP using self-signed

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#30]
Not that i've been able to find, the SMTP server uses self-signed SSL.

We can assign the same real SSL we are testing the web/admin interface with but can't seem to find anywhere to link the key/cert to.

Cannot spot anything in the docs I might have missed either.

**Comment by adamcooke** [comment]
The certificate & key for the SMTP server should be in `/opt/postal/config/smtp.crt` and `/opt/postal/config/smtp.key`. They are generated as self signed but can be replcaed. 

Is that what you're after?

**Comment by mattmartincouk** [comment]
Yes yes, thank you. I did find those but didn't want to fiddle :)

**Comment by adamcooke** [comment]
I'll document the purposes of all the generated config files shortly.
