### ISSUE TITLE
How to change data directory?

### ISSUE THREAD

**Issue by vishnus** [atech/postal#302]
Hi everyone,

How to change the default data directory? I have an attached storage, i'd like to move all messages to that drive since root drive is just 10gb.

**Comment by willpower232** [comment]
As per https://github.com/atech/postal/issues/268, the messages are kept in the database so you would have to figure out how to move the databases to the attached storage.

Alternatively, you could host the databases on a second, larger server.

**Comment by catphish** [comment]
As @willpower232 says, all data is stored in MySQL. You should look up how to move your MySQL data directory to your attached storage. This should be as simple as stopping MySQL, moving the /var/lib/mysql directory, and updating the MySQL config files accordingly. A guide can be found here: https://www.digitalocean.com/community/tutorials/how-to-move-a-mysql-data-directory-to-a-new-location-on-ubuntu-16-04

**Comment by vishnus** [comment]
yes done. thanks :) 
Incase someone else is also looking for the same, move /var/lib/mysql and /var/log/mysql
