### ISSUE TITLE
Two "postal.yml" files - which one should we set?

### ISSUE THREAD

**Issue by Razva** [atech/postal#303]
Hey,

Fresh install. Here's something interesting:
```
root@server:~# locate postal.yml
/opt/postal/app/spec/config/postal.yml
/opt/postal/config/postal.yml
root@server:~#
```
Which is the "correct" postal.yml file? Both have the same content.

Thanks

**Comment by rsgehlot** [comment]
Hi Razva,

I have multiple instances in staging mode, and always used /opt/postal/config/postal.yml.  

Regards,
Rahul

**Comment by Razva** [comment]
Ok, thank you! Any idea what /opt/postal/app/spec/config/postal.yml does?

**Comment by rsgehlot** [comment]
Not sure, may be someone else should help you. I am also looking for same now.
