### ISSUE TITLE
Back-off Mode Based on ESP DSN erros

### ISSUE THREAD

**Issue by rsgehlot** [atech/postal#304]
Hello,

Hope you are doing good !

Do we have specific ticket or a section where we talked about Backoff mode, i am just worried to use the system in production before backoff settings are not take care.

What i am looking for is, if i get temp deferred from mailbox provider, i would like to manage the further emailing such as (Hold emails, Reduce hourly limit, or route from other IP) for that particular ESP. If the mailxbox provider DSN errors are not carefully taken, the entire IP/Domain range may blacklisted.

Regards,
Rahul

**Comment by catphish** [comment]
I'm afraid Postal does not currently have any custom / intelligent back-off functionality like this.
