### ISSUE TITLE
Different IP per domain

### ISSUE THREAD

**Issue by Razva** [atech/postal#305]
Hey,
Is there any way to use a specific IP for a specific domain, on the same Postal install?
Thanks,
Razvan

**Comment by rsgehlot** [comment]
Hey Razvan,

Yes
- First you need to create one or many IP pools ( by giving IP and RDNS details)
- Assign IP pools to the organization 
- Go to the organization 
- Go to settings - Server setting - IP Rule 

Hope this will help you, more details you can see on postal official documents

Regards,
Rahul

**Comment by Razva** [comment]
@rsgehlot please [check this out](https://www.screencast.com/t/JqktWqMIcRNp). I'm logged in as Admin and I really cannot see anything about IP Rules. Also I cannot find any place from where could I add IPs to organization. Any hint on what I'm doing wrong?
