### ISSUE TITLE
SMTPSTARTTLS: 502 TLS not available

### ISSUE THREAD

**Issue by Razva** [atech/postal#307]
Hey,

I've successfully setup Postal and created the necessary Let's Encrypt SSL certificate (everything is fine via webui).

Still, when trying to connect a SMTP client, with StartTLS, I get:

```SMTPSTARTTLS: 502 TLS not available```

I've also tried to use SSL instead of StartTLS and I get "```First record does not look like a TLS handshake```" so I guess StartTLS is the correct option.

Please note that I already ran "```postal register-lets-encrypt my@email```" and restarted Postal.

Thank you,
Razvan

**Comment by mattmartincouk** [comment]
Have you enabled in your configuration file?

https://github.com/atech/postal/blob/master/config/postal.defaults.yml

It is disabled by default.

**Comment by Razva** [comment]
@mattmartincouk as usual it gets a little confusing. Here are the files generated by Certbot: ```cert.pem  chain.pem  fullchain.pem  privkey.pem```

I guess that ```tls_private_key_path:``` should point to ```privkey.pem```, but any idea of what should I use for ```tls_certificate_path```?

**Comment by willpower232** [comment]
when using letsencrypt, 9 times out of 10 you will use fullchain.pem and ignore cert.pem and chain.pem and this is true here
