### ISSUE TITLE
How to speedup queue delivery

### ISSUE THREAD

**Issue by Razva** [atech/postal#309]
Hey,
Is there any way to speedup the delivery process? I'm looking for something like...2 messages per second.
Any hints?
Thank you,
Razvan

**Comment by willpower232** [comment]
have you added more workers as per https://github.com/atech/postal/issues/290 ?

**Comment by Razva** [comment]
Can you please let me know what is the difference between "quantity" and "threads"? I couldn't find anything in the Docs.

**Comment by willpower232** [comment]
Each worker is a process on the system and each worker process can have many threads.

The default is for one worker so you probably want to increase the quantity to begin with.

We haven't increased the threads per worker yet but read this issue for some helpful information https://github.com/atech/postal/issues/235
