### ISSUE TITLE
"Link" feature

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#31]
I did an upgrade to get the latest files (to fix the HELO issue) and it appears the domain link option has gone.

http://scrn.at/wI167.png

Unless it has been moved?

**Comment by mattmartincouk** [comment]
Oddly, the ports don't appear open any more after a restart.

**Comment by adamcooke** [comment]
Oh. Yes - I made a rather breaking change to make the fast server disabled by default. You can enable it again and then restart and it should jump back into life. I tidied the example config file too so you might want to reconfigure from scratch by copying it from [here](https://github.com/atech/postal/blob/master/config/postal.example.yml).

```yaml
fast_server:
  enabled: true
```

**Comment by mattmartincouk** [comment]
That fixed it!

p.s Is there a way to force through/check the "SSL setup in progress" - these seem to take a long time without anyway to really check what is going on behind the scenes.

**Comment by adamcooke** [comment]
There's no trivial way to do it button can do it in the console. By default, it runs once an hour at **:45.

To run it in the console, just run `postal console` then run:

```ruby
RenewTrackCertificatesJob.perform
```

**Comment by joaoreis81** [comment]
I get this: 
Loading production environment (Rails 5.0.2)
irb(main):001:0> RenewTrackCertificatesJob.perform
=> []
irb(main):002:0>

**Comment by mattmartincouk** [comment]
See #281 as that will explain why you get that and what to do.
