### ISSUE TITLE
A lot of messages in queue, not being sent

### ISSUE THREAD

**Issue by Razva** [atech/postal#310]
Hey,

It seems that most messages that are in queue are not being delivered. I've checked the newsletter app, it sent 38k messages; right now the Postal queue is 35k. In 12 hours Postal delivered only 3k messages, which is impossibly slow.

So, at this point, Postal is not sending just accumulating queue. Any idea on how to fix this?

Thanks,
Razvan

**Comment by Razva** [comment]
I can see that a lot of messages soft failed so I guess that Postal is stuck retrying rather than delivering?

I've set ```maximum_delivery_attempts: 2``` and restarted, but queue is still huge (100k) and slow (4 messages/minute).

Any way to delete the softfails?

**Comment by willpower232** [comment]
If you are sending that volume of email as the first thing you have done with postal, its probably worth checking your IP address isn't listed on any black lists and your server hosting company is happy to let you do this.

If you are sending newsletters as the main reason for using postal, I'd suggest that you would get better results from something like mailchimp.

**Comment by Razva** [comment]
@willpower232 thank you for your advice, but this doesn't has anything to do with the ISP. My problem is with Postal not delivering messages in the queue, not with my ISP blocking anything (I have my own AS, own IP classes etc).

**Comment by catphish** [comment]
This issue is being discussed privately elsewhere so I will close this ticket. My findings will likely result in some improved documentation on how to run Postal with large numbers of workers on high performance servers.

**Comment by therealelyayo** [comment]
any news on this am experiencing same currently
