### ISSUE TITLE
Commercial support available?

### ISSUE THREAD

**Issue by Razva** [atech/postal#313]
Does the Dev team offer any paid support? I lost my entire weekend trying to make Postal work so I rather pay somebody to explain me what I'm doing wrong than loosing 2-3 more days "digging".

**Comment by catphish** [comment]
Please email hello@atech.media with as much information as possible and we'll see what we can do to help. We don't have arrangements for official support contracts yet, but we should be able to help on an ad-hoc basis :slightly_smiling_face:
