### ISSUE TITLE
User invite not working

### ISSUE THREAD

**Issue by vishnus** [atech/postal#314]
Hi there,

When I add new user and invite, the invite email doesnt go through. PFB the trace:

[web.1:8139] [2017-08-14T15:32:49.980] INFO -- : Processing by UsersController#create as JSON
[web.1:8139] [2017-08-14T15:32:49.980] INFO -- :   Parameters: {"utf8"=>"✓", "invite"=>"", "organization_user"=>{"email_address"=>"myemailid@gmail.com", "admin"=>"true"}, "commit"=>"Add User", "org_permalink"=>"orgname"}
[web.1:8139] [2017-08-14T15:32:49.996] INFO -- :   Rendering app_mailer/user_invite.text.erb
[web.1:8139] [2017-08-14T15:32:49.996] INFO -- :   Rendered app_mailer/user_invite.text.erb (0.1ms)
[web.1:8139] [2017-08-14T15:32:50.243] INFO -- : Sent mail to myemailid@gmail.com (246.4ms)
[web.1:8139] [2017-08-14T15:32:50.243] INFO -- : Completed 500 Internal Server Error in 263ms (ActiveRecord: 3.3ms)
[web.1:8139] [2017-08-14T15:32:50.244] FATAL -- :   
[web.1:8139] [2017-08-14T15:32:50.244] FATAL -- : ArgumentError (mail destination not given):
[web.1:8139] [2017-08-14T15:32:50.244] FATAL -- :   
[web.1:8139] [2017-08-14T15:32:50.244] FATAL -- : app/controllers/users_controller.rb:19:in `create'

What could be the issue here? Other emails are working fine.

**Comment by minicolo** [comment]
I've got the same issue, where can I trace it ?

**Comment by jnbtje** [comment]
@vishnus did you configure the local smtp ?
smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.

after the setup it worked here

**Comment by vishnus** [comment]
Hey @jnbtje 

Thanks for pointing this out :) Got it fixed!
