### ISSUE TITLE
Unable to send or receive any email

### ISSUE THREAD

**Issue by BlastFM** [atech/postal#316]
I am unable to send or receive any email. The server is at: blastfm.email and the SMTP settings are:
`smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once
  # your installation has been set up.
  host: mail.blastfm.email
  port: 25
  username: blastfm-ltd-internet-radio-stations/blastfm-ltd-central-email-server
  password: <removed>
  from_name: mail.blastfm.email
  from_address: mail@blastfm.email`

I get the error message:

`Error: Net::SMTPAuthenticationError (530 From/Sender name is not valid
)

  SMTP Host: mail.blastfm.email
  SMTP Port: 25
  SMTP Username: blastfm-ltd-internet-radio-stations/blastfm-ltd-central-email-server
  SMTP Password:`

I have tried all combinations of from/sender name I can think of.

I have not received an email yet either, I have made several attempts to send email to the server and as far as I know, the domains/SMTP endpoints are right.

Can anyone help me get this server working please?

**Comment by willpower232** [comment]
The domain you have added to `blastfm-ltd-internet-radio-stations/blastfm-ltd-central-email-server`, is it mail.blastfm.email or blastfm.email?

**Comment by BlastFM** [comment]
I don't have a domain setup for blastfm.email as I thought I wouldn't need that. I have other domains setup to test the system and they are passing all the checks.

**Comment by willpower232** [comment]
Postal will only send email for domains it has added to it so you need to set up a server within postal using `blastfm.email` or add `blastfm.email` to the central email server you have created a credential in.

**Comment by BlastFM** [comment]
I have blastfm.email for the server name and credential name, the credential name has now gone active for the first time so something must have worked somewhere but the error message is still the same:

> Error: Net::SMTPAuthenticationError (530 From/Sender name is not valid
)

  SMTP Host: mail.blastfm.email
  SMTP Port: 25
  SMTP Username: blastfm-ltd-internet-radio-stations/blastfm-ltd-central-email-server
  SMTP Password: HIDDENPASSWORD

**Comment by BlastFM** [comment]
BlastFM Ltd Internet Radio Stations → Domains actually has no domains in it, do I need to add one? and if so, what should it be please?

**Comment by BlastFM** [comment]
Thanks for that. I have added the domain blastfm.email to the organisation and verified that the DNS passes all checks, that's the good news, the bad news is, I now have a new error message:

Message was not delivered successfully to SMTP server.
Error: EOFError (end of file reached)

  SMTP Host: mail.blastfm.email
  SMTP Port: 25
  SMTP Username: blastfm-ltd-internet-radio-stations/blastfm-ltd-central-email-server
  SMTP Password: HIDDEN

**Comment by BlastFM** [comment]
I have also now secured the site with SSL (apache). Does postal need to know where the certificates are?

**Comment by BlastFM** [comment]
Is anyone able to offer any assistance?

**Comment by igerzog** [comment]
In order to make proper configuration of postal you should provide your `postal.yml` and `DNS settings` or give access to mail server and DNS control panel. How can we get in contact?

**Comment by willpower232** [comment]
I'm not sure how you've involved apache in this?

the SMTP server will need to know your certificates if you wish to enable TLS. See the following `postal.yml` settings:

```
smtp_server:
  port: 25
  tls_enabled: false
  tls_certificate_path: # Defaults to config/smtp.crt
  tls_private_key_path: # Defaults to config/smtp.key
```

**Comment by BlastFM** [comment]
Hi, I am happy to give access to the server and DNS, we manage our own DNS settings.
Thanks Will for the TLS settings, I will try them.
I can also give SSH access if required.

**Comment by BlastFM** [comment]
![untitled](https://user-images.githubusercontent.com/30941076/29486620-76f6b6f4-84e2-11e7-9515-f8a48e19c4fe.jpg)

**Comment by igerzog** [comment]
I'll be back in an hour. You may email me at arst@itel.pro

**Comment by igerzog** [comment]
As the first step please check your dns settings regarding to my last post here https://github.com/atech/postal/issues/301

**Comment by BlastFM** [comment]
Thanks, I have updated the DNS to match your settings from your post #301.

dns:
  mx_records:
    - mail.blastfm.email
  smtp_server_hostname: mail.blastfm.email
  spf_include: spf.mail.blastfm.email
  return_path: rp.mail.blastfm.email
  route_domain: routes.mail.blastfm.email
  track_domain: track.mail.blastfm.email
  dkim_identifier: psrp
  domain_verify_prefix: psrp-verification
  custom_return_path_prefix: psrp

**Comment by igerzog** [comment]
Good. Have you made proper DNS records in addition to yours that you sent here earlier?

**Comment by BlastFM** [comment]
I think they are right yes

**Comment by igerzog** [comment]
Ok, please check that you have added these four records:
`spf.mail.blastfm.email TXT v=spf1 ...`
`rp.mail.blastfm.email TXT v=spf1 include:spf.mail.blastfm.email ~all`
`rp.mail.blastfm.email A 212.71.232.6`
`rp.mail.blastfm.email AAAA ...`

**Comment by BlastFM** [comment]
They are there but I'm not sure about the first one: spf.mail.blastfm.email TXT v=spf1 ...
What should this be? Thanks.

**Comment by igerzog** [comment]
Well this is the main SPF record. It defines only those ip addresses or hosts that have permission to send emails from your domain. And you must correct your previosly set record for main domain:
'spf.mail.blastfm.email TXT v=spf1 a mx -all'
'blastfm.email TXT v=spf1 include:spf.mail.blastfm.email ~all'

**Comment by igerzog** [comment]
I have received your message. Will check your configuration in an hour.

**Comment by BlastFM** [comment]
You are doing a great job. Thank you :)

**Comment by catphish** [comment]
Glad you got this resolved :slightly_smiling_face:

**Comment by BlastFM** [comment]
Thanks for all the help so far:

I am using up a lot of hard disk space and I'm not sure why, it looks like a lot of it is SQL database stuff, does Postal require large database sizes or is it something else?

**Comment by igerzog** [comment]
And this is the real truth. All the data like messages or webhooks, certificates or any other useful for postal service information is stored in MySQL. As to me I have mentioned that my MySQL server uses 1.5 GB of RAM as well.

**Comment by BlastFM** [comment]
It appears that df -h and webmin were reporting the disk space wrongly, I upgraded the server disk space and it is now only using about 5% so it was probably ok before if it had been reporting the correct amount of available disk space.

Postal is not too heavy at all on disk space.

**Comment by catphish** [comment]
All messages are stored in the MySQL database. You can expect your disk usage to be almost exactly the size of your retained messages. In order to keep disk usage accountable and prevent fragmentation, Postal creates a separate MySQL database for each mail server, and within that it created a separate table for each day's messages. Therefore by using the "du" tool on the mysql data directory, you should be able to see *exactly* where the space is being used. You can also easily adjust the disk space requirement by changing the message retention on a per-mailserver basis.

**Comment by hadifarnoud** [comment]
I have the same issue. this is kinda confusing for me. so, let me explain how I understood it:

I install Postal on a domain, that would be my primary SMTP domain for use in apps. in this case the server domain is `mail.kamva-files.com` whilst postal is accessible from `postal.kamva-files.com`

there are a few places you can add domains. there is one in `Organization -> Domains` and one in `Mail Server -> Domains`

1. I want to use this server in `camva.ir` app. where should I add `camva.ir` as domain?
2. What is the difference between Mail Server domains and Organization domains?

**Comment by willpower232** [comment]
Please open a new issue rather than commenting on closed ones.
