### ISSUE TITLE
Dns and IP Pool

### ISSUE THREAD

**Issue by LaurentGruber** [atech/postal#326]
Hi,

Wich dns configuration is needed for using ip pool (for every ip of the ip pool) ?

Thanks

**Comment by mattmartincouk** [comment]
Your query isn't too clear.

What do you mean?

**Comment by catphish** [comment]
It's really up to you what names you wish to assign to your IP addresses. What's important is:

* Every IP address has a valid reverse DNS entry
* This name has a forward DNS entry back to the IP address
* Postal knows the DNS hostname of the IP

**Comment by LaurentGruber** [comment]
@catphish thank you for your answerd, it's was my questions
