### ISSUE TITLE
bounces, complaints, deliveries, sent emails, and rejected emails

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#33]
I can't understand how to track:
bounces, complaints, deliveries, sent emails, and rejected emails

I see it has events for bounce, deliveries, sent emails on webhooks, so you track it.
But what about complaints and rejects?

**Comment by adamcooke** [comment]
For failures the `MessageDeliveryFailed` webhook be invoked when a message hard fails or soft fails too many times. If there's a soft fail you'll get `MessageDelayed` event.

There is no built-in support for handling feedback loops or handling `List-Unsubscribe` however both of these would be useful additions.

What exactly do you mean by "rejects"?

**Comment by elfeffe** [comment]
I just copied all the events that Amazon SES list on their system, the most important part is complaints, that can be very usefull.

**Comment by adamcooke** [comment]
Complaints are usually delivered using a feedback loop. You can register for these with providers like Hotmail, AOL, Yahoo etc... and they'll send you an email whenever one of their users marks your message as spam in their applications. At the moment, Postal has nothing in place to accept these emails and link them back to an original message that was sent.

The other type of "complaint" can be triggered using the `List-Unsubscribe` header which webmail providers use to notify you when someone wants to unsubscribe from your list. This is usually best handled by your mailing list application though as that is where you'll need to be updating your records to reflect the unsubscription.

**Comment by elfeffe** [comment]
I fully agree

**Comment by benstaf** [comment]
> . We don't see that many because we're quite cautious about who we send messages to.

it doesn't matter how cautious you are, there will always be people who will prefer to click on the spam button instead of unsubscribe

Those complaints harm IP reputation the most, and need to be handled automatically at scale (like bounces)
