### ISSUE TITLE
demo online?

### ISSUE THREAD

**Issue by GildedHonour** [atech/postal#332]
setting it up locally is a lot of effort, is there a demo online?

**Comment by willpower232** [comment]
There isn't a demo online but theres nothing stopping you using AWS free tier to try it out. You wouldn't get full production performance but you would be able to try out the UI and send a few messages.

**Comment by GildedHonour** [comment]
> There isn't a demo online but theres nothing stopping 

how do you know?

**Comment by mattmartincouk** [comment]
Will means that the software is free to use and just requires your time (and server) to do so. If that is a lot of effort, you probably want a SaaS solution like Amazon SES, Sendgrid, MailJet etc as the work does not stop after you've installed the software - there is general server maintenance to do, including tweaking, if required.

**Comment by GildedHonour** [comment]
no, I just wanted a demo.
