### ISSUE TITLE
Any guide for backup mx

### ISSUE THREAD

**Issue by mhf-ir** [atech/postal#334]
I need to know is there any documentation or guide for add postal on another server for backup mx solution?

**Comment by willpower232** [comment]
Short answer, not at the minute.

Long answer:
At the minute postal is designed to be on one server with all of its dependencies and sets itself up as such.

I suppose you could host the queue and database separately but I'm not sure that would have a good affect on performance and reliability and I don't know if postal would be okay handling the queue in this way.

**Comment by catphish** [comment]
Actually Postal is fully clusterable. You would need a separate RabbitMQ and MySQL instance (or cluster), and then any number of application servers. I don't believe there is currently a guide to setting this up though.

**Comment by mhf-ir** [comment]
what about Maildir ? any glusterfs or nfs guide for mirror ? 

https://wiki2.dovecot.org/MailboxFormat/Maildir
http://www.qmail.org/man/man5/maildir.html

**Comment by catphish** [comment]
Nope, none of that, Postal uses MySQL for data storage.
