### ISSUE TITLE
Email Sending Issues to External Domains

### ISSUE THREAD

**Issue by AirpayMatt** [atech/postal#342]
Hi 

I am getting Soft Failures while sending email to certain domain, the errors are as given below

550-Verification failed for <tyhyow@psrp.airpay.co.in> 550-Unrouteable address 550 Sender verify failed

550-Verification failed for <tyhyow@psrp.airpay.co.in> 550-The mail server could not deliver mail to tyhyow@psrp.airpay.co.in. The account or domain may not exist, they may be blacklisted, or missing the proper dns entries. 550 Sender verify failed 

550 5.2.0 <tyhyow@psrp.airpay.co.in> From: Domain is invalid. Please provide a valid From: IB506 <http://x.co/srbounce> 

Greatful for Any help to resolve this issue

Matt

**Comment by mattmartincouk** [comment]
casper:~$ host psrp.airpay.co.in
Host psrp.airpay.co.in not found: 3(NXDOMAIN)

You need to add the correct DNS entries - currently they don't exist.

**Comment by AirpayMatt** [comment]
Thanks Matt , That resolved the issue

Matt
