### ISSUE TITLE
Messages failing DKIM

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#343]
DKIM/DMARC is setup correctly for our mail and validated using various online testers.

Some customers are getting messages being caught by DKIM failures etc and checking everything they appear fine but very random in their rejection. DKIM key is not changing and is the original one issued.

Maybe this is related to #339?

Anyone else seen similar results?

**Comment by catphish** [comment]
I saw this happen once. I was never able to explain it. I will definitely look into fixing #339 though in case this is the cause. Thanks.
