### ISSUE TITLE
Expert advise - Journaling support !

### ISSUE THREAD

**Issue by rsgehlot** [atech/postal#355]
Was thinking..if we can enable journaling option on postal. 

I have an internal requirement to forward a copy of each email to postsmater@xyz.com to meet some sort of compliance requirements. However, couldn't find it in postal. 
@vscool19

Regards,
Rahul

**Comment by willpower232** [comment]
This isn't really a feature for Postal. It is designed to simply send what it is given.

An appropriate way of achieving what you want would be to BCC your postmaster address for each message sent to Postal.

Postal would then send one copy to the original address and a second copy to your postmaster.

**Comment by rsgehlot** [comment]
Thanks for your response, so when you say BCC postmaster...Do you mean configure BCC while sending an email at client application? because our requirement is to get a CC or BCC of any e-mail going out of postal instance ( irrespective to the client)

**Comment by willpower232** [comment]
Yes, you should BCC when sending email from your software.

Postal cannot currently send a BCC automatically.

If you are a ruby developer (or know one), you could add that feature but I doubt it will get added to the default Postal.

**Comment by catphish** [comment]
As above, this is not currently supported, so you'd need to write the code if you want it I'm afraid.
