### ISSUE TITLE
IP Pools

### ISSUE THREAD

**Issue by manjeshpv** [atech/postal#356]
Is there any way setup ip pools to utilize IP's of other servers IP in same datacenter.

I have a setup  of 20 servers in same data center. One is POSTAL and others are db, app, etc etc

**Comment by mattmartincouk** [comment]
Not at this time as far as I know.

**Comment by willpower232** [comment]
I believe that Postal would need to see all the addresses so you would have to create some kind of clustered set up. If you are already using the servers for other purposes, this would likely have a negative affect on your systems overall performance.
