### ISSUE TITLE
Domain DNS checks failing after update

### ISSUE THREAD

**Issue by vishnus** [atech/postal#358]
Hi team,

I did an auto update on our postal set up few days back. Today morning I'm noticing that all the domains in all the smtp servers are reporting misconfigured DNS and when I click "Check my dns are correct" button its just an endless spinner. What could be the issue? Emails are going fine though.

**Comment by steliosmilidonis** [comment]
I am having the same issue , and i haven’t updated , still on 9e91c75157c86416f1f80841b3ec598bdeefa726

**Comment by willpower232** [comment]
@steliosmilidonis We're on https://github.com/atech/postal/commit/a63c62ba6276be968a9a16fd6905c1b770cc4e2d (10 Aug) and aren't having this issue.

@vishnus if you do `git log` in `/opt/postal/app` then you'll see which commit you're on or if you're not on the git version at all, thats also good to know

**Comment by steliosmilidonis** [comment]
@willpower232 its very odd that 2 people on different versions are having the same issue on the same day. something must be wrong , how does postal check dns records? because i checked my dns records and they are fine

**Comment by willpower232** [comment]
Unless told otherwise, it will use the server its running on to make its DNS queries so you should be able to run `nslookup` and test your records manually from the server to see if the records are properly propagated.

**Comment by vishnus** [comment]
@willpower232 i used ubuntu quick install to install it. Git log doesnt seems to be there. Any other way to get version?

PS: nslookup works for our domain from the server.

**Comment by vishnus** [comment]
It magically worked. I guess .. right after I did nslookup command, I went to postal and clicked on Check my dns and it worked :) not sure what went wrong earlier though..

**Comment by willpower232** [comment]
The more recent installs come from an atech compressed file so its tricky to tell how up to date it is with the repo.

`nslookup` might have caused some kind of update but who knows, probably some inner server voodoo. You could see which DNS resolvers your server queries by looking in `/etc/resolv.conf` as it might have been a minor issue with them.

**Comment by vishnus** [comment]
@willpower232 yeah that should explain. I have ec2 default resolver which is of amazon.. i'll check if its ideal to use that or switch to Google DNS. 

Thanks for support.. Closing the issue hence..

**Comment by steliosmilidonis** [comment]
@willpower232 and @vishnus same here, issue resolved after checking using nslookup

**Comment by vnkrish90** [comment]
I ran `dnslookup`  still the same issue. I'm using `1.0.0-2595481b26-stable`
