### ISSUE TITLE
Blocked when changing default email

### ISSUE THREAD

**Issue by xoco70** [atech/postal#36]
Hi, 

I just installed postal, very nice software!

I sent my first test mail, and it went ok.

But now, I tried to change default user to my email, email is not sent, and now I have a blocking screen asking for me a code that never came. 

Is it posible to see this code anywhere in my server? or how should I do it??? I can't use system  anymore :(

**Comment by matthewmgamble** [comment]
I ran into this issue as well - you can get the code from the MySQL database by doing a query like select email_verification_token from users where email_address = 'user@domain.tld';

**Comment by adamcooke** [comment]
You could verify the user manually using the console. Run `postal console` and then run the following to verify the first user.

```ruby
User.first.verify!
```
