### ISSUE TITLE
monthly limitation per organization

### ISSUE THREAD

**Issue by joaoreis81** [atech/postal#361]
How to limit the total SEND per month per organization? 
I can easily create a script querying the database to determine how much outgoing messages are sent by each SMTP server of an organization, and then suspend the server.

Is there any ready to go alternative? Thanks.

**Comment by palash76** [comment]
Yeah. This feature will be very useful. Please add it in the roadmap.

**Comment by willpower232** [comment]
Postal is only designed to send email, it is unlikely this will be added as a feature.

You could create it in a system that sends its email via Postal however.

**Comment by navinp** [comment]
thanks for pointing me to this topic @willpower232 
I guess no build-in feature for this

**Comment by webcoreinc** [comment]
No way to set a monthly sending limit? this is a joke, right?
