### ISSUE TITLE
How to configure gmail account?

### ISSUE THREAD

**Issue by betimd** [atech/postal#365]
Hi,

I want to add my gmail account to send and receive emails, what's the best way to configure within postal?

**Comment by igerzog** [comment]
To tell the truth Postal does not support external mail accounts. It can be configured to use your own private domains only and not gmail or something like that.

**Comment by bslavin** [comment]
The reason for this is DKIM and SPF records. Gmail will not approve of an IP outside of their range to "send" emails FROM gmail.com - the remote servers (your recipients) will reject this mail. 

Unless you authenticate and send outbound mail with your Gmail account you will not be able to reliably deliver if your From is Gmail (or really any other big isp)

**Comment by catphish** [comment]
Actually Postal can now be configured to use a relay host for outbound mail. See `smtp_relays` in the config file.

**Comment by engrpeters** [comment]
You all need to update postal server to allow password smtp_relays . It is very important .
