### ISSUE TITLE
Not able to build a new mail server from UX

### ISSUE THREAD

**Issue by deepakmonster** [atech/postal#368]
Hi, 

I have just installed postal and trying to configure it, while creating new server i am getting this new error. We encountered same kind of error earlier doing "postal initialize"  did some changes in ''/usr/share/mysql/charsets/Index.xml' managed to get passed it, not able to figure out why this is happening again since utf8 entry already exists in Index.xml. I am a perl programmer and new to this postal and ruby, help would be appreciated.

Thankyou
********************************************************
[2918] [2017-10-04T17:24:10.258] INFO -- : Started POST "/org/test-org/servers" for 10.216.204.139 at 2017-10-04 17:24:10 +0530
[2918] [2017-10-04T17:24:10.262] INFO -- : Processing by ServersController#create as JSON
[2918] [2017-10-04T17:24:10.262] INFO -- :   Parameters: {"utf8"=>"✓", "server"=>{"name"=>"POSTAL MAIL SERVER", "permalink"=>"", "mode"=>"Development"}, "commit"=>"Build server", "org_permalink"=>"test-org"}
Character set 'utf8' is not a compiled character set and is not specified in the '/usr/share/mysql/charsets/Index.xml' file
[2918] [2017-10-04T17:24:10.301] INFO -- : Completed 500 Internal Server Error in 39ms (ActiveRecord: 10.0ms)
[2918] [2017-10-04T17:24:10.303] FATAL -- :
[2918] [2017-10-04T17:24:10.303] FATAL -- : Mysql2::Error (Can't initialize character set utf8 (path: /usr/share/mysql/charsets/)):
[2918] [2017-10-04T17:24:10.303] FATAL -- :
[2918] [2017-10-04T17:24:10.304] FATAL -- : lib/postal/message_db/mysql.rb:10:in `new'

**Comment by willpower232** [comment]
Did you install Postal on a fresh Ubuntu 16.04 server?

**Comment by deepakmonster** [comment]
We are working on centos 6.9

**Comment by deepakmonster** [comment]
Can you please suggest any help related to my current configuration as I was provided new centos instead of Ubuntu cannot afford to spend time again for reinstalling on new Ubuntu.

**Comment by willpower232** [comment]
Unfortunately Postal is primarily developed for Ubuntu 16.04 so support will be difficult.

I can tell you that by default it installs and runs on MariaDB 10.1.28 so it might be that your local MySQL server is either out of date or configured differently by default. If you can get access to a different/newer database server, you could move the databases to it and update `postal.yml` to look at the different database server.

As per https://github.com/atech/postal/issues/338 there are a few quirks on Centos 7 but you might have a better time on that version of Centos if you have to use Centos.

**Comment by deepakmonster** [comment]
Hey Will, its working now did a fresh installation on new centos 6.9, earlier i might have configured mysql differently.

**Comment by GhaziTriki** [comment]
@deepakmonster I have a similar issue but Under Ubunut 18. Isn't Ubuntu 18 supported yet?

**Comment by willpower232** [comment]
@GhaziTriki it should work but there are a few quirks, have a look at #777 and #755

**Comment by GhaziTriki** [comment]
Amazing support.

After checking the logs I have this error.

```
[34m[web.1:4362][0m [2019-11-25T12:28:00.606] INFO -- : Completed 500 Internal Server Error in 15ms (ActiveRecord: 4.3ms)
[34m[web.1:4362][0m [2019-11-25T12:28:00.607] FATAL -- :   
[34m[web.1:4362][0m [2019-11-25T12:28:00.607] FATAL -- : Mysql2::Error (Access denied for user 'postal'@'localhost' to database 'postal-server-11'):
[34m[web.1:4362][0m [2019-11-25T12:28:00.607] FATAL -- :   
[34m[web.1:4362][0m [2019-11-25T12:28:00.607] FATAL -- : lib/postal/message_db/database.rb:319:in `query_on_connection'
lib/postal/message_db/database.rb:311:in `block in query'
lib/postal/message_db/mysql.rb:20:in `client'
lib/postal/message_db/database.rb:342:in `with_mysql'
lib/postal/message_db/database.rb:310:in `query'
lib/postal/message_db/provisioner.rb:46:in `drop'
lib/postal/message_db/provisioner.rb:13:in `provision'
app/models/server.rb:86:in `block in <class:Server>'
app/controllers/servers_controller.rb:36:in `create'
```

**Comment by GhaziTriki** [comment]
I am sure I put the right password and suer with the right permissions.

**Comment by GhaziTriki** [comment]
The issue I have seems to be related to those #648 & #840

**Comment by GhaziTriki** [comment]
By the way I use mariaDB.

**Comment by willpower232** [comment]
if restarting your postal/server doesn't help, please open a new issue
