### ISSUE TITLE
Not sending e-mail

### ISSUE THREAD

**Issue by hugohomesquita** [atech/postal#369]
Guys, what is the reason for this problem?

Ipv6 disabled:
`execution expired, Cannot assign requested address - connect(2) for "2404:6800:4003:c00::1b" port 25, Cannot assign requested address - connect(2) for "2404:6800:4008:c06::1b" port 25, Cannot assign requested address - connect(2) for "2607:f8b0:400e:c04::1b" port 25`

Ipv6 enabled:
`execution expired
Support Ref: P2MDYM7X`

both with this error too:

`No SMTP servers were available for gmail.com. Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com`

I'm using digitalocean vps, ubuntu 16.04.

**Comment by mohan-nishit** [comment]
Digitalocean blocks traffic on port 25 by default. You need to raise a
ticket with their support, who will in turn transfer you to their trust and
safety team.

The reason for this is to preserve the reputation of their IPs.

**Comment by catphish** [comment]
This does indeed seem like a firewall issue.

**Comment by navinp** [comment]
For anyone having this same issue, try sending your test email to a different provider. 

In my case, sending to Gmail, gives me this error, but sending to Live, does not give any error, and the email gets delivered... -_-

**Comment by akshaychauhan7737** [comment]
No SMTP servers were available for gmail.com. 

Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com

No firewall is configured.

execution expired
Support Ref: XQ1FXXXN

server setup at  server.primebachat.com

Please Help

**Comment by catphish** [comment]
This is almost always caused by your ISP blocking connections to port 25. Please ask them to confirm if this is the case.
