### ISSUE TITLE
API fails if charset is set as part of the content type

### ISSUE THREAD

**Issue by matthewmgamble** [atech/postal#37]
I'm writing a Java API client and found an issue with the API endpoints only when the charset is specified as part of the Content Type header.

If the content type in the HTTP request is set to Content-Type: application/json then the API works as expected, however, if you add the charset parameter, such as Content-Type: application/json; charset=UTF-8 the API fails to parse the request body and fails with an error that "There are no recipients defined to received this message"

I haven't had a chance to look at the postal code yet to track down the issue, but I can easily reproduce it now using postman.

**Comment by adamcooke** [comment]
That certainly sounds like a plausible issue that actually lies within [Moonrope](https://github.com/adamcooke/moonrope) which is the library that handles the API. I will investigate shortly.

**Comment by adamcooke** [comment]
Specifically [here](https://github.com/adamcooke/moonrope/blob/master/lib/moonrope/request.rb#L123) where it isn't very forgiving about the content of the `Content-Type` header.

**Comment by adamcooke** [comment]
I've put a basic fix into Moonrope for this (although it needs further expanding in the future to actually handle character sets) and I'll get it into Postal tomorrow.
