### ISSUE TITLE
Can't access the app with quick install process

### ISSUE THREAD

**Issue by iamarmanjon** [atech/postal#386]
Hi there, I'm quite confused on how to run the app. 

So I did all the things in the instructions, I did a clean 16.04 Ubuntu, with 8gb of ram.  Ran the install script and created a user. But when I access the app via my IP, I'm only welcome by the nginx page. Tried logging in with `ip:5000`, not working. Not sure what to do.

**Comment by iamarmanjon** [comment]
<img width="892" alt="screen shot 2017-10-23 at 5 40 35 am" src="https://user-images.githubusercontent.com/7567758/31866604-d547cb44-b7b4-11e7-9ae7-924e1a5f9573.png">

This is the status when I run `postal status`

**Comment by iamarmanjon** [comment]
Found the solution in https://github.com/atech/postal/issues/362. 

> You will need to edit /etc/nginx/sites-enabled/default and replace .crt with .cert

**Comment by willpower232** [comment]
Indeed, atech need to run a new build of the software unfortunately.

**Comment by catphish** [comment]
I thought we'd done this :( I'll check!

**Comment by catphish** [comment]
I've pushed out the new version. Apologies for the delay! This should now be fixed.
