### ISSUE TITLE
SMTP authentication and credentials

### ISSUE THREAD

**Issue by masihfathi** [atech/postal#388]
I am very new to postal, had a basic question, Is it possible to create a Transactional Email service (api and SMTP) like mailgun.com, sendgrid.com. 
And, if possible, What needs to know? I think I can make the API with PHP and handle API, But I do not have any idea to build SMTP accounting and authentication, For example, build and monitor an SMTP account (bounce, deliver ...)
Thanks!

**Comment by masihfathi** [comment]
I need to handle with API in PHP, cause I'm not well in ruby language .

**Comment by willpower232** [comment]
Postal is already exactly what you describe, it works like mailgun and sendgrid.

If you wanted to build a PHP-based system to interact with it there is a PHP library (https://github.com/atech/postal-php) and you would probably make extensive use of webhooks (https://github.com/atech/postal/wiki/Webhook-Events-&-Payloads) which can report to your system what happens to the messages (i.e. bounces and delivery)

**Comment by masihfathi** [comment]
I'm afraid that the project will be canceled. Currently appmail is down :(
I need to learn ruby for develop this for myself, And if postal does not go on, it's practically useless.

**Comment by spheron1** [comment]
Isn't the whole reason that aTech open sourced Postal because they announced that they were shutting down AppMail?

**Comment by willpower232** [comment]
@masihfathi @spheron1 is correct, Postal is the continuation of AppMail and will go on supported by myself and others, don't worry too much!
