### ISSUE TITLE
Postal web UI https isn't valid

### ISSUE THREAD

**Issue by theratris** [atech/postal#39]
I'm getting a problem when I visit my site where the HTTPS isn't valid. The website still works if I bypass the warning.

**Comment by mattmartincouk** [comment]
Do you mean the admin GUI?

You'll need to add your own certificate in the configuration for nginx.

**Comment by adamcooke** [comment]
As @mattmartincouk said, the instructions just generate a self signed certificate. You'll need to replace `/etc/nginx/ssl/postal.crt` and `/etc/nginx/ssl/postal.key` with new values for a real certificate suitable for the domain you're accessing the UI from.

**Comment by theratris** [comment]
I thought I generated a Let's Encrypt cert as part of the installation process.

**Comment by mattmartincouk** [comment]
LE does the link hosts - not the admin GUI.

**Comment by theratris** [comment]
Hmm, any suggestions on a way to have a cert that auto renews?

**Comment by mattmartincouk** [comment]
Yes, use LE to do that - very easy to do and it'll achieve what you want.

**Comment by adamcooke** [comment]
Let's Encrypt is just used for click & open tracking domains. For example if you want to track links on emails you send from `yourdomain.com`, to improve deliverability we recommend using a subdmomain like `click.yourdomain.com` for tracking. Postal will manage certificates for this domain and renew them automatically.

If you want to set up LE for your management UI you can use something like [CertBot](https://certbot.eff.org/) with nginx.

**Comment by theratris** [comment]
I haven't heard of certbox before! That is awesome :)

Thanks for the quick advice as always!

**Comment by adamcooke** [comment]
You'll need something like the below to generate the cert.

```
sudo certbot certonly --webroot -w /opt/postal/app/public -d mail.yourdomain.com
```

You'll also need to update the cert paths in the nginx configuration to the new certs that LE generates for you.

**Comment by theratris** [comment]
This information should defiantly be added as a note in the installation process I think.

**Comment by adamcooke** [comment]
I agree. Will add a note about this tomorrow.

**Comment by theratris** [comment]
Is there any way I can commit to the Github wiki? I would gladly offer some edits I think would be more clear about certain things.

**Comment by adamcooke** [comment]
Sadly it appears there's no way to submit pull requests to the wiki on GitHub. Please feel free to just add issues for any updates and I'll get them updated.

**Comment by theratris** [comment]
After running Certbot it only gave me a single .pem file. Is that correct?

**Comment by adamcooke** [comment]
You should find a few files in `/etc/letsencrypt/live/domain.com`. You should have `fullchain.pem` and `privkey.pem`.
