### ISSUE TITLE
Domain setup MX record

### ISSUE THREAD

**Issue by farhadhf** [atech/postal#395]
The documentation/help text for MX Records in domain setup (in mail server and organization) is too vague. 

> If you wish to receive incoming e-mail for this domain, you need to add the following MX records to the domain. You don't have to do this and we'll only tell you if they're set up or not. Both records should be priority 10. 
>
> `mail.postalserver.com`

What are "both records"? Let's say I want to add a new domain to a mail server on postal (`example.com`). What DNS records should I be adding? What if `example.com` already has an MX record for `mail.example.com` to handle incoming emails through another mail server?

**Comment by hieunba** [comment]
@farhadhf If you wish to track email messages via Postal, adjust priority to the existing MX record, and set up routes policy accordingly.

**Comment by farhadhf** [comment]
Just tried that - added a new MX record with higher priority than the existing MX record for `mail.example.com` pointing to `mail.postalserver.com`, but it didn't work. Postal still says 

> None of the MX records for this domain point to us. Incoming mail won't be sent to us.

**Comment by willpower232** [comment]
@farhadhf this would seem to be a typo, I believe you only need one record.

Can you try using https://www.whatsmydns.net/ to see if your MX record changes have propagated? It might take a little while for the DNS your server accesses to update.

**Comment by farhadhf** [comment]
It had propagated, but seems like I needed to set the MX record for the top level domain, i.e.

```
example.com.		300	IN	MX	10 mail.postalserver.com.
```

So, what I have now is

```
example.com.		300	IN	MX	5 mx.example.com.
example.com.		300	IN	MX	10 mail.postalserver.com.
```

Should the priority value for `mail.postalserver.com` be less than the priority for `mx.example.com` (which is 5) or higher?

**Comment by hieunba** [comment]
Higher priority value means less important, in this case, messages will go directly to `mx.example.com` instead of `mail.postalserver.com`.

**Comment by willpower232** [comment]
MX records are for delivering ALL your email. If you want all your email to be delivered to Postal you don't need the other record at all.

If you were expecting to split your email between Postal and something else, I don't think that would go very well.

**Comment by farhadhf** [comment]
OK - I think I figured it out.

Just in case someone else wants to do something similar: 

If you need to receive emails for `@example.com` email addresses through a separate email server (that you can access through Outlook, etc), create two domains in the mail server (postal interface):

* example.com (for sending emails where we don't need email responses - i.e. send emails from `welcome@example.com`)
* reply.example.com (for sending emails where we need to handle responses through postal - i.e. send emails from `notification@reply.example.com`)

DNS records for `example.com` would be
```
example.com.					300	IN	TXT 		"v=spf1 a mx include:spf.mail.postalserver.com ~all"
postal-xxxxx._domainkey.example.com.		300	IN	TXT 		"v=DKIM1; t=s; h=sha256; p=....."
psrp.example.com.				300	IN	CNAME		rp.mail.postalserver.com.
```
*Note*: No MX record for `example.com` - we don't want to receive emails through postal for `@example.com` email addresses.

In additional to above DNS records, the following records are necessary for `reply.example.com`

```
reply.example.com.				300	IN	TXT		"v=spf1 a mx include:spf.mail.mailoon.ir ~all"
postal-XXXXX._domainkey.reply.example.com.	300	IN	TXT		"v=DKIM1; t=s; h=sha256; p=....."
psrp.reply.example.com.				300	IN	CNAME		rp.mail.postalserver.com.
reply.example.com.				300	IN	MX	10	mail.postalserver.com.
```

Then in your application code, make sure to send all emails that will receive replies using `@reply.example.com` email addresses.

**Comment by hieunba** [comment]
@farhadhf this is a different thing. But glad you figured out a way. Usually, you have to use subdomain because there is an existing email system that is available for zone apex. And you do not want to touch the existing one.
