### ISSUE TITLE
Postal cannot handle email addresses with plus in

### ISSUE THREAD

**Issue by willpower232** [atech/postal#398]
I was reviewing one of our integrations which actively filters out the plus part of email addresses for compatibility with SendGrid.

On a whim, I sent a plus email address to Postal and received a 500 Internal Server Error response.

I've had a look in the log files but can't figure out if incoming messages even appear in the logs let alone the exception.

**Comment by Mayeu** [comment]
Did you find out the issue here? I just installed postal and found out about this issue afterward. I really pretty heavily on using plus on my emails :/

**Comment by willpower232** [comment]
You can filter out the plus part in your app code before sending it to Postal which means the messages get delivered but obviously with the slightly incorrect address, see https://github.com/SynergiTech/fuelphp-postal/blob/a6270d86a01e8a95097b2793e45f198c9a2cd5af/classes/sendmessage.php#L87 for a PHP example.

(Also if you're only sending yourself emails with Postal, you might find something else like Postfix or Mailgun more useful)

At this point, I'm kind of hoping someone more familiar with Ruby (or someone from atech) hops in with some debugging questions. I'm hoping its an easy to fix issue within Postal as opposed to an upstream library but without a steer, this issue is going to hang around a while.

**Comment by Mayeu** [comment]
Hello,

I just tried the following scenarii:
- Sending an email to an address managed by another server with a plus in it via Postal SMTP
- Sending an email to an address with a plus in it that is routed by Postal (in this case, routed to one of my email)
- Sending an email to an address with a plus in it that is routed by Postal to an address with a plus in it.

In all those case I used the SMTP server, and I can't seems to trigger the 500 error.

Can you elaborate on the scenario that triggered the issue for you?

**Comment by willpower232** [comment]
Ah thanks for trying it out. We primarily use the API with the PHP library.

Based on your experience, I guess this issue only happens with how the API parts handle the email address.

**Comment by willpower232** [comment]
I have done some digging and I am completely unable to replicate the problem so I'm guessing I had some other issue buried in my code and was sending Postal a bad API call.

Will close for now.
