### ISSUE TITLE
Can send test email, but not any other mail

### ISSUE THREAD

**Issue by xoco70** [atech/postal#40]
Hi, 

I'm just configuring the system. 

Sending email is successful when sending test email through:

Server > Messages > Send Message

from test at kendozone.com To julien at t4b.mx

Now, When I try to change admin email, I don't receive anything. ( I should receive code )

In Nginx log, I can't see anything. Is there any logs I can use to debug?

In /opt/posal/config/postal.yml I have:

```smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: kz/my-mail-server
  password: *****************
  from_name: Test
  from_address: test@kendozone.com
```

Any Idea how should I do?

**Comment by mattmartincouk** [comment]
All interesting logs are in.. /opt/postal/app/log/

We had similar issue, firstly with non-trusted SSL on the SMTP server and then non-valid sending domain which had to be added.

**Comment by adamcooke** [comment]
Check the SMTP server log in `/opt/postal/app/log/smtp.log` or you can check for other errors in `/opt/postal/app/log/production.log` at the time Postal tries to send an email.

**Comment by theratris** [comment]
I'm also having this issue, when I look at the SMTP log there are no records of the emails being sent there.

**Comment by xoco70** [comment]
I checked logs, and in smtp_sender.log, I get those:


```
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:02:13.481] INFO -- : [JJCBSWTI] Connected to 173.194.66.26:25 (aspmx.l.google.com)
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:02:13.482] INFO -- : [JJCBSWTI] Sending message 2::2 to julien@t4b.mx
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:02:13.948] INFO -- : [JJCBSWTI] Message sent #2 to aspmx.l.google.com (173.194.66.26) for julien@t4b.mx
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:02:14.045] INFO -- : [JJCBSWTI] Finishing up
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:16:38.473] INFO -- : [JURIEGUE] Cannot connect to 52.200.15.116:25 (smtp.kendozone.com) (Errno::ECONNREFUSED: Connection refused - connect(2) for "52.200.15.116" port 25)
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:16:38.477] INFO -- : [JURIEGUE] -> No SMTP server available for kendozone.com
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:16:38.477] INFO -- : [JURIEGUE] -> Hostnames: ["smtp.kendozone.com"]
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:16:38.477] INFO -- : [JURIEGUE] -> Errors: ["Connection refused - connect(2) for \"52.200.15.116\" port 25"]
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:16:39.069] INFO -- : [JURIEGUE] Finishing up
^[[32m[worker.4:18189]^[[0m [2017-04-27T15:21:16.962] INFO -- : [INI4UL8S] Cannot connect to 52.200.15.116:25 (smtp.kendozone.com) (Errno::ECONNREFUSED: Connection refused - connect(2) for "52.200.15.116" port 25)
```

**Comment by mattmartincouk** [comment]
Is smtp.kendozone.com your postal server address?

**Comment by xoco70** [comment]
Yes, it is.

I used as mentioned in docs : 

``` 
sudo iptables -t nat -I PREROUTING -d 52.200.15.116 -p tcp -m tcp --dport 25 -j REDIRECT --to-ports 2525
sudo  iptables -I INPUT -p tcp -m tcp -d 52.200.15.116  --dport 2525 -j ACCEPT

```

Is there anything else I should do?

**Comment by mattmartincouk** [comment]
@theratris look in the database, you'll find the code you need to enter when this happens in there.

@xoco70 I had the same issue. I used the following rules instead.

`iptables -A PREROUTING -t nat -p tcp -d x.x.x.y --dport 25  -j DNAT --to-destination x.x.x.y:2525
iptables -A PREROUTING -t nat -p tcp -d x.x.x.z --dport 80  -j DNAT --to-destination x.x.x.z:5010
iptables -A PREROUTING -t nat -p tcp -d x.x.x.z --dport 443  -j DNAT --to-destination x.x.x.z:5011`

Probably nicer ways of doing it but i'm just playing with it.

**Comment by xoco70** [comment]
I should have made a confusion. How should I know the " postal server address".

In postal, I defined the SMTP Endpoint to smtp.kendozone.com in port 25

But in DNS config, MX is defined to rp.mail.kendozone.com

Should it be the same?

**Comment by mattmartincouk** [comment]
Your config sounds wrong. The MX should not be the return path address.

I would recommend starting with a new config file.

You will need to check the iptrables rules though too as port 25 is not open on your server but port 2525 is.

**Comment by xoco70** [comment]
I get it from docs: https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration

I have 2 MX configs, RP and Routes.


Now, in config.yaml, I have it configured to: `mx.mail.kendozone.com`

Now, When I try to telnet, I get:

```telnet localhost 25
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
forge@KZ:~$ telnet localhost 2525
Trying 127.0.0.1...
Connected to KZ.
Escape character is '^]'.
220 mail.kendozone.com ESMTP Postal/ELOIWU
```

I don't understand why it is responding with `mail.kendozone.com`

**Comment by mattmartincouk** [comment]
It is set in the config file.

`
smtp_server_hostname
`

**Comment by xoco70** [comment]
ok, I think I got the issue.
Ahh, ok, you're right.

In production.log, I have:

Sent mail to julien@t4b.mx (278.6ms)
I, [2017-04-27T18:40:59.679468 #11071]  INFO -- : [00c3edeb-5d8f-42b1-9604-daf518810a74] Completed 500 Internal Server Error in 312ms (ActiveRecord: 19.3ms)
F, [2017-04-27T18:40:59.680056 #11071] FATAL -- : [00c3edeb-5d8f-42b1-9604-daf518810a74]
F, [2017-04-27T18:40:59.680119 #11071] FATAL -- : [00c3edeb-5d8f-42b1-9604-daf518810a74] OpenSSL::SSL::SSLError (hostname "127.0.0.1" does not match the server certificate):

Don't really know why is it happening...

**Comment by adamcooke** [comment]
The iptables rules provided will not actually expose port `25` on the same machine. You can connect directly to port `2525` though. This is what should be set in the config.

**Comment by adamcooke** [comment]
The reason you're having issues with the "server certificate" error is because Postal shipped with a self signed certificate for SMTP TLS. This has actually now been removed and TLS disabled by default on the SMTP server. Administrators will be expected to enable it when they generate a suitable working certificate for their server.

**Comment by xoco70** [comment]
Now works well! Thanks for your help!
