### ISSUE TITLE
Documentation domain lapsed

### ISSUE THREAD

**Issue by willpower232** [atech/postal#401]
The "Sending E-Mail" help page links to gopostal.io which appears to have lapsed or never existed.

Is it possible to restore it or put the documentation into another github repository?

**Comment by adamcooke** [comment]
I actually don't think that page ever existed and we should remove the link to it from the UI itself.

**Comment by adamcooke** [comment]
Sorry - I lied - the documentation for that link is here: https://github.com/atech/postal/wiki/Using-the-API

**Comment by willpower232** [comment]
Thanks!
