### ISSUE TITLE
Scalability/Redundancy 

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#41]
As this is very much a single box deployment - is there scope to have multiple real SMTP servers just in case the current (main/only) one fails?

We were testing Postmark/MailGun/random-mail-service which have some degree of this built in but being able to control is nicer (and more private).

Setting up two servers and replicating the database has it's own issues as far as I could work out but would like to at least have another server just in case it fails meaning apps cannot inject email.

**Comment by adamcooke** [comment]
There are a few ways to scale & make Postal more redundant. We plan to run our own Postal install on a pair of servers with a one active and one passive. I will try to document this properly when we set it up but it will be something like this:

* Replicate the MySQL database across two hosts.
* Replicate the RabbitMQ queue across two hosts.
* Use `keepalived` to manage the IP addresses on the hosts.

The application will be deployed to both hosts although only running on the active one. If the active host fails, keepalived will move the IPs to the other host, and start Postal itself. There will be a short period of downtime while the app starts but it will be minimal.

There are other ways to run it in a far more redundant way with multiple active hosts. This helps avoid downtime and allows for horizontal scaling to increase performance. This is how we run AppMail. We have separate database hosts (in pairs) and multiple app servers with a load balancer in front of them. Workers run across all app servers and connections for web & SMTP are routed to any app server.
