### ISSUE TITLE
ClamAV setup instructions

### ISSUE THREAD

**Issue by mohan-nishit** [atech/postal#410]
While I know that this is a milestone for v1.0, a basic instruction set for enabling ClamAV scans would be helpful. 

For instance, I have been able to get ClamAV up and running on the server, but cannot fathom how to get postal to connect to it. I added the following to my `postal.yml` file:

```
clamav:
  enabled: true
  host: 127.0.0.1
  port: 2000

```
I've tried searching for existing issues that can help, or ClamAV docs, but to no avail. FYI, I can run clamdscan on the server normally, and clamd.conf has `TCPSocket 2000` and `TCPAddr 127.0.0.1` added.

**Comment by willpower232** [comment]
What makes you think its not working?

We don't run clamav on our setup but it looks like Postal only tells you when a message is a threat and doesn't confirm that a message is clean.

**Comment by mohan-nishit** [comment]
I tried sending the Eicar test string in an email, and it had no additional
threat headers added to the email.

**Comment by willpower232** [comment]
did you send the test string as the contents of the email or as an attachment?

**Comment by mohan-nishit** [comment]
As the plain text body. Gmail refused to accept the email as it recognised
the eicar string within the email.

**Comment by willpower232** [comment]
Interesting, I wouldn't have thought that the contents of an email message body could be executable and therefore a threat but obviously Google knows everything.

[This](https://easyengine.io/tutorials/mail/server/testing/antivirus/) suggests that clamav is capable of warning if the EICAR file is attached to an email so could you test the file as an attachment and see if there is any difference?

**Comment by igerzog** [comment]
Check your /var/log/clamav/clamav.log
Is there any mention about found treat?

Have you configured your `clamd.conf`?
- `TCPSocket 2000`
- `TCPAddr 127.0.0.1`

You can download a test eicar file from the official site to your home directory by wget and check it with clamav:
`telnet 127.0.0.1 2000
SCAN /home/path/to/test/file`

Please tell about the result.
