### ISSUE TITLE
IP pool not working

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#411]
Hello

i set pool ip and i send email to my own different id to check header but i can see only system ip. so can you please tell me what's wrong and why it's not going with pool ip address ?

Thanks

**Comment by willpower232** [comment]
Can you send some screenshots or details of your settings? It is impossible to see whats wrong otherwise.

**Comment by sahilsunesara** [comment]
Please check below link

https://imgur.com/a/vRvPc

**Comment by zeeshanjamal16** [comment]
Provide more information for your ip pools settings.
Paste the output for
`ip a`
Also try to change the hostnames for your ip pools like mail1.mailleaders.com, mail2.mailleaders.com and so on.

**Comment by sahilsunesara** [comment]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:4a:9b:d7 brd ff:ff:ff:ff:ff:ff
    inet 192.xx.xx.133/24 brd 192.99.xx.xx scope global ens3
       valid_lft forever preferred_lft forever
    inet 192.xx.xx.133/32 brd 192.xx.xx.133 scope global ens3
       valid_lft forever preferred_lft forever
    inet 66.xx.xx.191/32 brd 66.xx.xx1.191 scope global ens3:0
       valid_lft forever preferred_lft forever
    inet 142.xx.xx.84/32 brd 142.xx.xx.84 scope global ens3:1
       valid_lft forever preferred_lft forever
    inet 142.xx.xx.85/32 brd 142.xx.xx.85 scope global ens3:2
       valid_lft forever preferred_lft forever
    inet 142.xx.xx.86/32 brd 142.xx.xx.86 scope global ens3:3
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe4a:9bd7/64 scope link
       valid_lft forever preferred_lft forever

**Comment by zeeshanjamal16** [comment]
Had you enabled ip pool from postal.yml?
