### ISSUE TITLE
Postal Worker

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#412]
Hi

i got error when i try to open postal it's show
 We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

when i check status it's show below status why some worker, fast.2 and requeuer.2 is not working what will be the reason ?

i have 8GB ram 2core Processor VPS server 

Procodile Version   1.0.17
Application Root    /opt/postal/app
Supervisor PID      2450
Started             2017-11-22 00:16:01 -0500

 * fast.2 is not running (Failed)
 * worker.9 is not running (Failed)
 * worker.10 is not running (Failed)
 * worker.11 is not running (Failed)
 * worker.12 is not running (Failed)
 * worker.13 is not running (Failed)
 * worker.14 is not running (Failed)
 * worker.15 is not running (Failed)
 * worker.16 is not running (Failed)
 * requeuer.2 is not running (Failed)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      00:16        pid:2568     respawns:1      po                                          rt:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.2           Failed       00:17        pid:2769     respawns:5      po                                          rt:-        tag:-

|| worker
|| Quantity            8
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.9         Failed       00:17        pid:2817     respawns:5      po                                          rt:-        tag:-
|| => worker.10        Failed       00:17        pid:2819     respawns:5      po                                          rt:-        tag:-
|| => worker.11        Failed       00:17        pid:2799     respawns:5      po                                          rt:-        tag:-
|| => worker.12        Failed       00:17        pid:2801     respawns:5      po                                          rt:-        tag:-
|| => worker.13        Failed       00:17        pid:2803     respawns:5      po                                          rt:-        tag:-
|| => worker.14        Failed       00:17        pid:2806     respawns:5      po                                          rt:-        tag:-
|| => worker.15        Failed       00:17        pid:2821     respawns:5      po                                          rt:-        tag:-
|| => worker.16        Failed       00:17        pid:2825     respawns:5      po                                          rt:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.2           Running      00:16        pid:2552     respawns:0      po                                          rt:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      00:16        pid:2570     respawns:1      po                                          rt:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.2       Failed       00:17        pid:2793     respawns:5      po                                          rt:-        tag:-

**Comment by willpower232** [comment]
> If you are the application owner check the logs for more information.

Please check the files in `/opt/postal/log/` to see if there is anything that might be a problem.

**Comment by sahilsunesara** [comment]
i think postal not able to handle 8000 email per hour

because i have 90GB Disk, 8 GB RAM 5 Dedicated IP and it's show something wrong error in application manytime

**Comment by zeeshanjamal16** [comment]
Check your resource usage and assign number of workers accordingly. It looks like you have assigned more workers than required. Also try to run postal first before start. Run "postal run" command and check if there are any error produced. Please post if any errors are there in this command.

**Comment by sahilsunesara** [comment]
can you please send me postal.yml

so i can check what things i need to add and what thing not

**Comment by zeeshanjamal16** [comment]
I have customized my postal.yml according to my additional requirement. It can break your application if you copy the same. Was there any error when you run "postal run" command?

**Comment by sahilsunesara** [comment]
Error: Cannot be started in the foreground because supervisor already running

Please send me i just want look what thing you have added in your postal.yml for future reference
thank you

**Comment by zeeshanjamal16** [comment]
Run following commands:
sudo postal stop
sudo rm -vf /tmp/postal/pids/*
sudo postal run

**Comment by sahilsunesara** [comment]
root@vps130988:~# sudo rm -vf /tmp/postal/pids/*
root@vps130988:~# sudo postal run
05:47:41 system          | Procodile supervisor started with PID 11747
05:47:41 system          | Application root is /opt/postal/app
05:47:41 system          | Automatic respawning is disabled
05:47:41 system          | Reloading configuration
05:47:41 control         | Listening at /tmp/postal/pids/procodile.sock
05:47:41 web.1           | Started with PID 11751
05:47:41 worker.1        | Started with PID 11753
05:47:41 worker.2        | Started with PID 11755
05:47:41 cron.1          | Started with PID 11758
05:47:41 smtp.1          | Started with PID 11760
05:47:41 requeuer.1      | Started with PID 11763
05:47:42 web.1           | => Puma starting in single mode...
05:47:42 web.1           | => * Version 3.8.2 (ruby 2.3.5-p376), codename: Sassy Salamander
05:47:42 web.1           | => * Min threads: 5, max threads: 5
05:47:42 web.1           | => * Environment: production
05:47:48 cron.1          | => [cron.1:11758] [2017-11-22T05:47:48.329] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
05:47:48 cron.1          | => [cron.1:11758] [2017-11-22T05:47:48.662] INFO -- : Starting clock for 8 events: [ every-1-minutes every-15-minutes every-15-minutes every-15-minutes every-15-minutes every-hour every-hour every-day ]
05:47:48 cron.1          | => [cron.1:11758] [2017-11-22T05:47:48.678] INFO -- : Triggering 'every-1-minutes'
05:47:49 requeuer.1      | => [requeuer.1:11763] [2017-11-22T05:47:49.027] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
05:47:49 smtp.1          | => [smtp.1:11760] [2017-11-22T05:47:49.091] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.134] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
05:47:49 requeuer.1      | => [requeuer.1:11763] [2017-11-22T05:47:49.360] INFO -- : Running message requeuer...
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.405] INFO -- : Worker running with 4 threads
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.438] INFO -- : [SWVDW9T3XX] Started processing RequeueWebhooksJob job
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.439] INFO -- : Joined main queue
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.441] INFO -- : [YEA7YLNBJR] Started processing SendNotificationsJob job
05:47:49 smtp.1          | => [smtp.1:11760] [2017-11-22T05:47:49.469] INFO -- : Listening on port 25
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.650] INFO -- : [AU6YNDIAPB] Started processing WebhookDeliveryJob job
05:47:49 web.1           | => [web.1:11751] [2017-11-22T05:47:49.703] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.768] INFO -- : [SWVDW9T3XX] Finished processing RequeueWebhooksJob job in 0.330202719s
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.769] INFO -- : [YEA7YLNBJR] Finished processing SendNotificationsJob job in 0.328155806s
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.775] INFO -- : [4] Sending webhook request to `http://apps.mailleader.in/index.php/dswh/postal`
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.786] INFO -- : Joined outgoing-1 queue
05:47:49 worker.1        | => [worker.1:11753] [2017-11-22T05:47:49.787] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.794] INFO -- : Joined outgoing-2 queue
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.802] INFO -- : Joined outgoing-3 queue
05:47:49 worker.2        | => [worker.2:11755] [2017-11-22T05:47:49.810] INFO -- : Joined outgoing-4 queue
05:47:49 web.1           | => * Listening on tcp://127.0.0.1:5000
05:47:49 web.1           | => Use Ctrl-C to stop
05:47:49 worker.1        | => [worker.1:11753] [2017-11-22T05:47:49.915] INFO -- : Worker running with 4 threads
05:47:49 worker.1        | => [worker.1:11753] [2017-11-22T05:47:49.932] INFO -- : Joined main queue
05:47:49 worker.1        | => [worker.1:11753] [2017-11-22T05:47:49.957] INFO -- : Joined outgoing-1 queue
05:47:49 worker.1        | => [worker.1:11753] [2017-11-22T05:47:49.959] INFO -- : Joined outgoing-2 queue
05:47:49 worker.1        | => [worker.1:11753] [2017-11-22T05:47:49.960] INFO -- : Joined outgoing-3 queue
05:47:49 worker.1        | => [worker.1:11753] [2017-11-22T05:47:49.961] INFO -- : Joined outgoing-4 queue
05:47:50 worker.2        | => [worker.2:11755] [2017-11-22T05:47:50.032] ERROR -- : [4]   -> Received 301 status code. That's not OK.
05:47:50 worker.2        | => [worker.2:11755] [2017-11-22T05:47:50.032] INFO -- : [4]   -> Will retry 2017-11-22 10:50:49 UTC (this was attempt 2)
05:47:50 worker.2        | => [worker.2:11755] [2017-11-22T05:47:50.049] INFO -- : [AU6YNDIAPB] Delivery failed
05:47:50 worker.2        | => [worker.2:11755] [2017-11-22T05:47:50.123] INFO -- : [AU6YNDIAPB] Finished processing WebhookDeliveryJob job in 0.472744802s

**Comment by zeeshanjamal16** [comment]
It looks like a problem configuring your webhook at "http://apps.mailleader.in/index.php/dswh/postal". It is not properly configured. Also it is redirecting with 301. Try sending an email manually from Postal web panel and check by disabling this webhook.

**Comment by sahilsunesara** [comment]
i have correct webhook.. i forget s in HTTPS.. thanks

one more question.. why my sending speed is slow ?

**Comment by zeeshanjamal16** [comment]
Sending speed depend on email sending rate and number of workers assigned for it. Check your server resources and increase number of workers accordingly to speed up.

Mark this thread as close if issue is resolved.

**Comment by sahilsunesara** [comment]
thank you..
