### ISSUE TITLE
Disk Space

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#415]
Hi

i am using 40GB Disk Space and i just sent 70K email and now it's shows there is no space and showing error 500

What will be the problem ?

**Comment by willpower232** [comment]
You need to log in to your server with SSH and use the `du` command to figure out which directory is too big.

**Comment by sahilsunesara** [comment]
Hi

I remove all log fine the now it's working.. remove from postal/log 

do i need to remove regularly ? or there is something wrong ?

**Comment by aniket-s** [comment]
Just go to Advance Setting in Postal and change the-
Message retention days & Raw message retention days to less days. It will eventually remove logs after those days

**Comment by willpower232** [comment]
If your logs were responsible for filling up your hard drive, you almost definitely have a problem.

If your database was the main problem then you will need to change your retention settings.

**Comment by sahilsunesara** [comment]
I did retention setting to 1 day but still i can see this much of GB used..if i keep 1 day this it should be 0 after a day am i right ?

i am talking about postal top of the right side GB details

**Comment by willpower232** [comment]
That should be the way it happens yes. Can you send some screenshots if it isn't happening?

**Comment by sahilsunesara** [comment]
https://imgur.com/a/xrk8e

**Comment by willpower232** [comment]
You are sending quite a lot of emails and if they have attachments or embedded imagery, that would take up a fair amount of space.

Out of curiousity, can you try setting it to 2 days and see what happens?

Also please read https://github.com/atech/postal/issues/353 as there can be accidental deletion of unsent messages as the size limit setting takes priority over the day limit setting.

**Comment by catphish** [comment]
40GB is really not much disk space, but should definitely be sufficient. The best thing to do would be to use `du` to determine where the space is used. In particular, it might be used by the app (by logs) or by MySQL. the solution may depend on where the space is being used.
