### ISSUE TITLE
Mail sent and received immediately but received mail headers show (Delivered after 17998 seconds)

### ISSUE THREAD

**Issue by shanzo** [atech/postal#417]
I have a server in Berlin and a mail server with postal in New York. I am using API to send email. Every thing works perfectly ok except the received mails header show (Delivered after 17998 seconds) in case of Gmail which is completely wrong.

 I am not sure If i have to tune some settings in postal, at least I have tried different timezone in web interface to Eastern time, Pacific time and of course UTC, but seems its not working at all. Here is a snippet of header for your information. Your help will be highly appreciated. Thanks you

`Received: by 10.176.79.32 with SMTP id n32csp3666046uah;
        Sat, 25 Nov 2017 14:27:06 -0800 (PST)
X-Google-Smtp-Source: AGs4zMYYNF2Y7XGwX1zv0T/4bqpvJODf5e4UJTLkNl9aex9k/KCLyX8XJUr1osZSEWnHN+vHkKg/
X-Received: by 10.107.188.68 with SMTP id m65mr35289718iof.255.1511648826596;
        Sat, 25 Nov 2017 14:27:06 -0800 (PST)`

**Comment by willpower232** [comment]
Where are you seeing "Delivered after 17998 seconds"?

Is the server timezone for your Postal server set to Berlin or is it on its default?

**Comment by shanzo** [comment]
Its in my gmail account received email headers. Attach is the screen shot.

Server timezone is set to default.

Checked in Postal Web UI, the timezone is set to UTC (default one). Server its is located in New York so it has its own timezone based in New York USA.
![screenshot-mail google com-2017-11-27-13-14-15](https://user-images.githubusercontent.com/100032/33264281-8f87e94a-d375-11e7-82d9-ca8590db95a7.png)

**Comment by willpower232** [comment]
Could you download the message from Postal and show us those headers too?

**Comment by shanzo** [comment]
I am attaching fresh sent messages headers from Postal and Gmail. The email arrives immediately but the time (Delievered after 17999 seconds) is wrong. Please check attached snaps. 
![screenshot-mail google com-2017-11-27-15-49-42](https://user-images.githubusercontent.com/100032/33269869-d4729fae-d38a-11e7-9cb9-974f91e54cc4.png)
![screenshot-mail onestream live-2017-11-27-15-48-31](https://user-images.githubusercontent.com/100032/33269870-d4942872-d38a-11e7-8c01-78c6d1741f83.png)

**Comment by willpower232** [comment]
I meant you should be able to download the original message from Postal as an EML file, the headers in there should be more verbose

![image](https://user-images.githubusercontent.com/1619102/33270047-9d2924e2-d37a-11e7-87cd-f39be5838997.png)

**Comment by shanzo** [comment]
I have put xxxx for "to" in email. Below are the downloaded headers.


`DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=onestream.live; s=postal-odzjcA; t=1511772492; bh=mvuu3b9qEfdaZCSaVxLvRSqKbMB5YN4qxRCRw5FtvuE=; h=date:from:to:message-id:subject; b=nybFnkv6+dVgMueP8gRVHIqGvsTn2By+evo5JNmTY7AV91CQ5cSpP5tWAyyFsq6GevRraRUYeha+BaYHylqGpjL9QYNWrhh1rZrxgMKqr33saAVu6AcDgzmbao4Rg95PzDeozUp1i9nnDjKivWryo2oyQRvJm10yY67xijJ4nDc=
X-Postal-MsgID: Jhoa3M48kSWF
Received: from web-ui (nginx-proxy.nginx_proxy_network [172.19.0.4]) by Postal with HTTP; Mon, 27 Nov 2017 08:48:12 +0000
Date: Mon, 27 Nov 2017 08:48:12 +0000
From: shanzo@onestream.live
To: xxxxxx@gmail.com
Message-ID: <4198894b-ed85-4d7c-8e3b-1470f26b4544@rp.mail.onestream.live>
Subject: Test Message at November 27, 2017 08:47
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

This is a message to test the delivery of messages through Postal.`

**Comment by willpower232** [comment]
Okay, I think there is a weirdness in timezones as 17999 seconds is nearly 5 hours but everythings got the same headers so far.

Can you scroll down in your Gmail view and see the textual headers from the message? That might highlight a slightly different time...

**Comment by shanzo** [comment]
Here is the full headers of gmail. I have put XXXXX for my email.

Thank you

Delivered-To: XXXXX@gmail.com
Received: by 10.176.79.32 with SMTP id n32csp1615538uah;
        Mon, 27 Nov 2017 05:48:10 -0800 (PST)
X-Google-Smtp-Source: AGs4zMYf4NT6QtURXsH8oKqwnnjHyVtwM7Ug22CDIs8kFhHWp0gsYz5EbSKh8yLDDKo3VAiTwo9d
X-Received: by 10.36.48.82 with SMTP id q79mr30999088itq.75.1511790490493;
        Mon, 27 Nov 2017 05:48:10 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1511790490; cv=none;
        d=google.com; s=arc-20160816;
        b=0mKfXTCWuPqPjZcbBU9oFmuSyk4dSqbzyd/9/VkkbAWvGd3vSUByNIIwdLgqCHskib
         xN1BPEmzy2vKRSPw7U2tEKkPYvNXapFBfsQuDGa1tBQIfkoyE6sshUjCdEuMw5fyKyvG
         8OtDyOC4AMPY/MzWCUHjlEqv3t/ySfE4WdDngh5OWKQmlwe/YMc6v/C7zFq70dtRzPPO
         7vWFSnzXmwWzvlChrNTeZJ+DSgT/WyMMtr/iYZPQMS6jPsxIJij1nW3EP2o85ZtzwgjU
         CNbPqTIl3FAFe9D4AT+n1kQ/ZUBrRHDqC82Q5rpB9w1AetF1jXNVjbrI66sshRT5Axfv
         NmqA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=content-transfer-encoding:mime-version:subject:message-id:to:from
         :date:dkim-signature:resent-sender:arc-authentication-results;
        bh=mvuu3b9qEfdaZCSaVxLvRSqKbMB5YN4qxRCRw5FtvuE=;
        b=MpWbgPQ3JtZXJz7KMPfea+AiytUTzrOB7Rl3+lLBbYxzl5u6vQOLalZzHx5JKkE0Hp
         0Lt8gHIw+usNJMl9g9t6U5OyTqtAINO/oe1C66CiBWpd7alfaqdCx7nIw24DN7tKEWPt
         MjPqhde1EQm+POrjKzQrrdrCgEQsOJXaKE/9NVzu/2jOsrCpERcXl9j/vmfda7OOFaQQ
         RNGgAOHpvu1TfvjZJpmMCEKAkR42LOzP8HBoktKepLt6mu3fJDNme663a3QTs2MbMBjV
         r2BtNKhQWW5PmqKlNI7jNROd3pMcaWg8/Z9WgKBws01JYkbekPFj7zu50r6rzHvz7Luj
         uZ8w==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@onestream.live header.s=postal-odzjcA header.b=nybFnkv6;
       spf=pass (google.com: domain of jzamay@psrp.onestream.live designates 23.94.27.157 as permitted sender) smtp.mailfrom=jzamay@psrp.onestream.live;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=onestream.live
Return-Path: <jzamay@psrp.onestream.live>
Received: from mail.onestream.live (mail.onestream.live. [23.94.27.157])
        by mx.google.com with ESMTPS id i1si13495696itf.160.2017.11.27.05.48.09
        for <XXXXXX@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Mon, 27 Nov 2017 05:48:10 -0800 (PST)
Received-SPF: pass (google.com: domain of jzamay@psrp.onestream.live designates 23.94.27.157 as permitted sender) client-ip=23.94.27.157;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@onestream.live header.s=postal-odzjcA header.b=nybFnkv6;
       spf=pass (google.com: domain of jzamay@psrp.onestream.live designates 23.94.27.157 as permitted sender) smtp.mailfrom=jzamay@psrp.onestream.live;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=onestream.live
Resent-Sender: jzamay@psrp.onestream.live
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=onestream.live; s=postal-odzjcA; t=1511772492; bh=mvuu3b9qEfdaZCSaVxLvRSqKbMB5YN4qxRCRw5FtvuE=; h=date:from:to:message-id:subject; b=nybFnkv6+dVgMueP8gRVHIqGvsTn2By+evo5JNmTY7AV91CQ5cSpP5tWAyyFsq6GevRraRUYeha+BaYHylqGpjL9QYNWrhh1rZrxgMKqr33saAVu6AcDgzmbao4Rg95PzDeozUp1i9nnDjKivWryo2oyQRvJm10yY67xijJ4nDc=
X-Postal-MsgID: Jhoa3M48kSWF
Received: from web-ui (nginx-proxy.nginx_proxy_network [172.19.0.4]) by Postal with HTTP; Mon, 27 Nov 2017 08:48:12 +0000
Date: Mon, 27 Nov 2017 08:48:12 +0000
From: shanzo@onestream.live
To: XXXXXX@gmail.com
Message-ID: <4198894b-ed85-4d7c-8e3b-1470f26b4544@rp.mail.onestream.live>
Subject: Test Message at November 27, 2017 08:47
Mime-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

This is a message to test the delivery of messages through Postal.

**Comment by willpower232** [comment]
Interesting, its still not immediately obvious. The only thing I can think of is that somehow the Postal server is including the timezone from the server itself as NYC uses GMT-5 which could be a basis for the 17999 seconds.

Could you try putting Postal into the same timezone as the server? Or changing the server to be in UTC?

Having had a quick look at the source code, I'm not convinced changing Postal will help but you should be able to change the server itself. Either way, if Postal and the server are in the same timezone, we'll know for sure whether its Postals fault or gmail getting the wrong end of the stick.

**Comment by shanzo** [comment]
Changed server time to UTC and Postal Organization settings -> Timezone to UTC. Same result.

Changed Server time to US New York and Postal Organization Settings -> Timezone to US Eastern time. Same result. 

I even rebooted Postal and still nothing ...

**Comment by willpower232** [comment]
Interesting.

I don't believe Postal has seen much in the way of testing in different timezones (https://github.com/atech/postal/issues/327) so unless someone from atech comments, I'm not sure what to suggest sorry

**Comment by shanzo** [comment]
Thank @willpower232 . I will wait if some one from Postal can comment on this. The only reason i am pursuing this is that some mail servers simply rejects these kind of emails as they think that email has been received very late.

**Comment by adamcooke** [comment]
I've tried to replicate this myself but cannot seem to do so. I have pushed a couple of changes to the way the received header works but I'm not sure that'll solve this issue. A puzzler!

**Comment by willpower232** [comment]
Me neither, I'm half tempted to set up a DO droplet in Frankfurt and NY to see if it still happens...

**Comment by shanzo** [comment]
@willpower232 we actually moved the postal server to Berlin and set the time zone as Berlin and now its working ok. It seems like my vps was located in Los angelas (even though it was advertised as located in New York) and the time zone i set was for New York. Could that be reason? But all in all thanks for the help. I hope some body might get some help with this discussion if they face the same situation. By the way Postal is Awesome :+1:  I am closing this issue. Thanks for the heads up :)))
