### ISSUE TITLE
Migrate domain data to new postal instance

### ISSUE THREAD

**Issue by agnibha** [atech/postal#418]
I was trying to migrate to an upgraded machine with the same postal setup. Is there a way I can use the existing Domain information from the older one? I couldn't find documentation for it. Is there a config file or something I could copy to make it work?

**Comment by willpower232** [comment]
All data is kept in a plural of MySQL databases and is processed through the queue.

If you are happy with a period of downtime, you could stop your existing Postal, install it on another server, migrate every database and your config files, and start Postal on the new server.

For running multiple servers simultaneously, have a look at https://github.com/atech/postal/issues/41 and https://github.com/atech/postal/issues/334.

**Comment by catphish** [comment]
As @willpower232 says, a simple clone of the MySQL database (all databases on the server) is probably what you need.
