### ISSUE TITLE
What if external IP is not available on local interface?

### ISSUE THREAD

**Issue by pschiffe** [atech/postal#419]
Hello all, I'm trying to setup Postal on OpenStack and I see one issue - in my OpenStack setup I have external IP addresses available only as a floating IPs - they are not available directly on local network interfaces.

Most services I encountered didn't have a problem with that - sometimes I had to use some configuration like `external_ip`, but mostly not even that. For my main webserver I use mailcow, where I just configured hostname and it get external ip automatically.

Now to my question - how to deal with this in postal? I've tried ip pool, but it seems that it doesn't work. Without ip pool the mail get sent, but there is a local ip of instance in the mail headers.

**Comment by willpower232** [comment]
I don't use Openstack but presumably the OS sees some kind of internal IP address?

Postal doesn't need to know the public IP address to function. Postal/nginx can bind to the internal address and then its down to you to access it on the corresponding public IP address. This is how floating IPs work in AWS EC2.

**Comment by pschiffe** [comment]
Sorry, I double checked, and it is working correctly, without ip pool. I was concerned about the `Received:` header, but it does show correct external ip. I presume that this ip is filled by receiving smtp..
