### ISSUE TITLE
Is the "fast server" required for Postal to work?

### ISSUE THREAD

**Issue by deanpcmad** [atech/postal#42]
Hey Adam,
Great work on open sourcing this 😄 
If I didn't want click or open tracking, is the "fast server" still required? Is there a way to disable it?

**Comment by adamcooke** [comment]
Nope - it's not required. In fact, the default configuration file has it disabled. See [the config file](https://github.com/atech/postal/blob/master/config/postal.example.yml) for details. You can just set `fast_server.enabled` to false and it won't be started and tracking will be hidden in the UI.

**Comment by deanpcmad** [comment]
Ah sweet, so just 1 IP is required for basic usage?
