### ISSUE TITLE
Limit MAIL FROM address

### ISSUE THREAD

**Issue by braun1928** [atech/postal#420]
Hi all,
Is there any way to enforce which address can be used on each domain, for each user? Even though I'm with "send as any" disabled, I still can send as anything@mydomain, which is not so interesting in my case.
Thanks!

**Comment by willpower232** [comment]
That is not a feature at the minute. "Send As Any" only refers to the domain part of the address and requires a trusted domain to be part of a separate "Sender" header.

If you were using the API only, you could create a relaying bit of code to enforce the exact address.

**Comment by braun1928** [comment]
Hmm okay. I've told people here about that, so we'll monitor first to see if any abuse happens. If I have the availability to learn Ruby I'll do the changes and make a PR later :)
Thanks!
