### ISSUE TITLE
Is there a way to pull the heather data into my app?

### ISSUE THREAD

**Issue by Mr-Binary** [atech/postal#421]
Hi I would like to know if I can pull this data into my app, and trying to decide if it even makes sense to do so.

![postal heather](https://user-images.githubusercontent.com/34069064/33427628-3b2dd51e-d5c6-11e7-8608-049fe8a021e3.png)

I understand I can calculate all these results locally by using webhooks and counting messages, but since postal is already doing all this work, would it make sense to pull the data from postal? And if it does, How can I do that?

**Comment by Mr-Binary** [comment]
Then in the screenshots posted in the wiki I can see "Sending via shared IP Pool" Is that something I can get via API or webhook?

BTW, this piece of information is not showing on my own install, is that due to my configuration or has it been removed lately?

**Comment by willpower232** [comment]
There isn't a statistics API so unfortunately this information is not available outside of Postal.

Nothing is displayed in that spot unless you are sending from an IP Pool. If you would like to send from multiple IP addresses then have a look [here](https://github.com/atech/postal/wiki/Configuring-IP-Pools).

**Comment by Mr-Binary** [comment]
Thank you @willpower232, do you think it makes sense to make this a feature request or since it can be calculated locally it´s utterly unnecessary or useless?

**Comment by willpower232** [comment]
There is a wider issue about the lack of general information from Postal. IMHO it would always be better to get the stats from the source rather than calculate it yourself.

**Comment by Mr-Binary** [comment]
Agreed, should I close this issue and open a new one for feature request or it´s better to keep it all in one place?

**Comment by willpower232** [comment]
Better to leave this one open I would have said

**Comment by adamcooke** [comment]
I've made a new enhancement issue for this #453
