### ISSUE TITLE
How can I interface with the Espect web service from my app?

### ISSUE THREAD

**Issue by Mr-Binary** [atech/postal#422]
Short version:
How can I interface with the Espect web service from my app?

Long version:
I need to check the content quality of our own outgoing promotional emails before sending them.

I think using spamassassin for my use case is ideal and i can read here that "Espect is a tiny web service that accepts e-mails, runs them through SpamAssassin and ClamAV and returns JSON. "

In my case, checking every single email sent is not needed, as these are promotional emails and once created they get sent to a chunk of our database, **the emails need to be checked for "content quality" just once after creation.**

My questions are:
Would it make sense to use espect as standalone?
Is this even a possibility since it´s been merged with postal?

If it can be used as standalone, could you give some guidance as how to do this?
If it must be used as part of postal, Can I enable it for this use case I just explained but keep spamassassin disabled for postal (to save resources as I don´t think I need incoming emails checked for spam, or do i?)

**Comment by willpower232** [comment]
Postal only knows how to send an email to SpamAssassin, if there was another service running on your system that accepted the same input format and returned the same output format that could work transparently.

Postal is mainly designed to just send what it is given, it would be better to use espect yourself as necessary to verify the message before giving it to Postal. I suspect that this would allow you multiple attempts as well.

**Comment by Mr-Binary** [comment]
Great, yes I am sure one single email would be tested several times upon reaching a satisfactory rate.

Question remains tho, how do you interface with the Espect web service from an external APP?

**Comment by willpower232** [comment]
Sorry I completely misunderstood your request.

I don't think you can work with espect externally, it has been embedded into Postal as per https://github.com/atech/postal/commit/f779e45f451cc8f822f9a4196cb9106b5a2eedf9

The spam and virus checking helps mainly when integrating Postal with contact forms, if you want to verify how spammy a message is after you have prepared it, you might get on better with https://www.mail-tester.com/.

If you rely on Postal to vet the messages, it wouldn't be as obvious or detailed as third parties would be.

**Comment by Mr-Binary** [comment]
I understand, for now I would be more than happy if I could just get a basic "spam rate" to show within my app.

I guess I could send an email to postal using my own email address and then route it to my app via http endpoint?

**Comment by willpower232** [comment]
I can't remember if the Postal spam score is included in the email headers but if the message goes past the threshold for spam, it won't be sent at all.

**Comment by Mr-Binary** [comment]
It is my understanding that right postal uses Spamassassin, and Spamassassin can pass an email along with some data about what´s its opinion is about an email without aking any action upon it, so I´m guessing would´t be that hard to tell Espect to behave in the same way.

**Comment by willpower232** [comment]
As per my earlier message, the espect code has been fully immersed into Postals so it isn't a separate queryable entity.

Postal is primarily just an email sender so including a Check My Message function would need a completely separate path through the system and probably falls under https://github.com/atech/postal/wiki/FAQs#can-you-add-mailing-list-feature

**Comment by Mr-Binary** [comment]
Agreed!
