### ISSUE TITLE
Any plans for DMARC?

### ISSUE THREAD

**Issue by Mr-Binary** [atech/postal#424]
I was impressed when I saw that you get your SPF and DKIM records automatically built for you within the postal UI, very practical for beginners. However I was also surprised that DMARC was missing. Is DMARC really that useless?

Are there any plans on making postal compliant with DMARC policy?

**Comment by willpower232** [comment]
I am not aware of any plans. I'm not really familiar with the DMARC spec but it looks like integration might be pretty easy as it seems based on similar things to what is already in place for SPF and DKIM.

**Comment by Mr-Binary** [comment]
Yes it's very simple, it just states a "process" for DKIM and SPF compliance, or rather tells a mail server owner what to do when someone does not abide to that statement. Anyone not compliant with your SPF and DKIM records is probably using your identity to forge emails.

Does not really add new technology, it uses proper organization as means to improve security, if properly implemented (beyond just adding a dns record) it can help a lot identifying spammers and hackers using your identity without consent and without you being able to know about it otherwise.

**Comment by willpower232** [comment]
I've done a bit more digging and I understand that DMARC requires you to create a DNS record describing how to trust messages from that domain.

That could affect all emails the organisation sends, not just from Postal, so it is outside the scope of Postal.

From what I can tell, Postal is DMARC-friendly by including your domain in the right places so there is not much more it could do.

**Comment by Mr-Binary** [comment]
That´s right, the DNS entry is more or less like the one you use for SPF in terms of complexity, just has more parameters usually. This is half of the solution, for full compliance then you should be able to accept messages sent to you in response of of your DNS statement and act upon them, much like you do with bounces, these can be handled manually or automatically. For full support tho, you should also be able to read other people´s DMARC records, just like you read DKIM and confirm signatures, the main difference being you are supposed to report back to the DNS entry administrator in case something doesn´t add up, and that`s precisely what makes DMARC unique, we all participate in finding spammers and forgers and we report them directly to the domain administrator. It´s a huge improvement because after implementation, you start receiving reports and gain huge insight of what´s happening around the world with YOUR own domain, if anything is trying to use your domain name for spam or trying to forge email addresses in your name, you are notified immediately. Any other DMARC compliant email service becomes your eyes and ears and helps you protect your own domains.

**Comment by catphish** [comment]
@Mr-Binary As far as I know, Postal is DMARC compliant. It sends all email with appropriate SPF and DKIM, so if you enable it in your DNS it should work fine.

**Comment by catphish** [comment]
I'm going to close this ticket, but please feel free to open a new ticket if there are any problems with this, or a pull request if you would like to add some documentation about DMARC anywhere.

**Comment by benstaf** [comment]
> I'm going to close this ticket, but please feel free to open a new ticket if there are any problems with this, or a pull request if you would like to add some documentation about DMARC anywhere.

That would help to add documentation on DMARC and also DKIM (now buried in the Return Path section: https://docs.postalserver.io/getting-started/dns-configuration )

**Comment by lubosstrejcek** [comment]
Hello, any luck with documentation of DMARC & DKIM?
