### ISSUE TITLE
'mail destination not given' error

### ISSUE THREAD

**Issue by cmmata** [atech/postal#425]
Hello,

I have been configuring Postal in our Centos7 production server, and I'm unable to send emails. I have followed all the install guide and the 'DNS' section in the wiki, and I have the web interface working, I can 'send' a mail through Thunderbird using this Postal instance, but the mail queue don't process.

The error is Soft Fail: `An error occurred while sending the message to X.X.com (X.X.X.X)`
If I click on show technical details, I see `mail destination not given`.
My logs:
$ tail log/smtp_server.log  -f
```
[smtp.1:5462] [2017-12-01T13:36:22.746] DEBUG -- : [OBKLCX]    Connection opened from ::ffff:X.X.X.X
[smtp.1:5462] [2017-12-01T13:36:22.746] DEBUG -- : [OBKLCX]    Client identified as ::ffff:X.X.X.X
[smtp.1:5462] [2017-12-01T13:36:22.746] DEBUG -- : [OBKLCX] <= EHLO X.X.com
[smtp.1:5462] [2017-12-01T13:36:22.762] DEBUG -- : [OBKLCX] => 250-My capabilities are
[smtp.1:5462] [2017-12-01T13:36:22.762] DEBUG -- : [OBKLCX] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:5462] [2017-12-01T13:36:22.804] DEBUG -- : [OBKLCX] <= MAIL FROM:<xdc05s@psrp.x.com>
[smtp.1:5462] [2017-12-01T13:36:22.804] DEBUG -- : [OBKLCX] => 250 OK
[smtp.1:5462] [2017-12-01T13:36:22.804] DEBUG -- : [OBKLCX] <= RCPT TO:<email@x.com>
[smtp.1:5462] [2017-12-01T13:36:22.813] DEBUG -- : [OBKLCX] => 530 Authentication required
[smtp.1:5462] [2017-12-01T13:36:22.813] DEBUG -- : [OBKLCX] <= RSET
[smtp.1:5462] [2017-12-01T13:36:22.813] DEBUG -- : [OBKLCX] => 250 OK
[smtp.1:5462] [2017-12-01T13:36:22.830] DEBUG -- : [OBKLCX] <= QUIT
[smtp.1:5462] [2017-12-01T13:36:22.830] DEBUG -- : [OBKLCX] => 221 Closing Connection
[smtp.1:5462] [2017-12-01T13:36:22.831] DEBUG -- : [OBKLCX]    Connection closed
```
$ tail log/smtp_sender.log  -f
```
[worker.1:5454] [2017-12-01T13:38:16.543] INFO -- : [T1RCJ9TK] Connected to X.X.X.X:25 (x.x.com)
[worker.1:5454] [2017-12-01T13:38:16.545] INFO -- : [T1RCJ9TK] Sending message 2::3 to email@x.com
[worker.1:5454] [2017-12-01T13:38:16.555] INFO -- : [T1RCJ9TK] ArgumentError: mail destination not given
[worker.1:5454] [2017-12-01T13:38:16.578] INFO -- : [T1RCJ9TK] Finishing up
```
DNS section in Postal web interface says it's all correctly configured. The only other thing I have is that fast server isn't working, but I think that can be the next step when I can send emails.

So what else can be wrong? Or where can I try to find the error? Thanks in advance.

**Comment by willpower232** [comment]
Are you able to send other emails from Postal from within the web interface?

Have you configured a server for Postal to send emails from in `postal.yml`? https://github.com/atech/postal/issues/314#issuecomment-323524157

**Comment by cmmata** [comment]
If I go to mail server > Messages > Send message and try to send an email, I have the same problem as if I send it with Thunderbird. I had seen issue #314 this morning before opening this issue, but I have configured `postal.yml`. I'm using the postal server itself, with a user and password I have generated in the web interface. Is this correct? If I execute `/opt/postal/app/bin/postal test-app-smtp email@x.com`, the result is `Message has been sent successfully.`.

**Comment by willpower232** [comment]
Thats correct. Do you receive the email sent by `test-app-smtp`?

**Comment by cmmata** [comment]
Okay, I'm near. If I send a mail to the same domain as the postal server by the `test-app-smtp`, it fails with the 'mail destination' error. I have sent two more emails to one gmail address and one in outlook.com, and both have been sent. Gmail works correctly, outlook goes to spam folder. So the problem must be in DNS records. Can I debug somewhere which DNS record is missing or wrong? I have checked another time in DNS verify in Postal and it tells me they are ok.

**Comment by willpower232** [comment]
Have you set the main MX record for your email to be delivered to Postal?

Presuming you have and that was intentional, Postal does not have mailboxes so needs a route to do something with that message. You can configure routes for each server in Postal in the web interface

![image](https://user-images.githubusercontent.com/1619102/33513704-2da07a66-d740-11e7-9a93-ca2c5d095af7.png)

**Comment by cmmata** [comment]
That's it! Public DNS have a MX record pointing to our outlook inbox provider, but I totally forgot that record wasn't in our internal DNS and it was delivering to Postal. I have added the MX record in the internal DNS and now it's sending to any domain. Thank you for your support! And of course, for this great product! 😄

**Comment by catphish** [comment]
Looks like this is resolved.
