### ISSUE TITLE
`550 Invalid server token` if RCPT_TO  starts with custom_return_path_prefix

### ISSUE THREAD

**Issue by yogesum** [atech/postal#426]
If I am sending mail with domain example.com with `custom_return_path_prefix` as `email` then any recipient starting with `email.` fails with code `550 Invalid server token`.

**Example mail:** return path domain `email.example.com`
```sh
RETURN PATH: <wazup@email.example.com>
MAIL FROM: <support@example.com>
RCPT TO: email.otherdomain.co.in
// => 550 Invalid server token
```

**Note:** Relevant piece of code [code](https://github.com/atech/postal/blob/master/lib/postal/smtp_server/client.rb#L257:L270)

Also, RegExp check similar to above is also done [here](https://github.com/atech/postal/blob/master/lib/postal/message_db/message.rb#L490)

**Comment by yogesum** [comment]
No, It is someone else's mail receiving server.

**Comment by willpower232** [comment]
I don't think Postal will let you add someone elses domain name onto an address in the email headers, Postal has to know about all the domain names that go through it.

**Comment by yogesum** [comment]
I am already sending mail to other email addresses. but when I send email to `someone@email.iimcal.ac.in` it fails.
I think fault lies in this [code](https://github.com/atech/postal/blob/master/lib/postal/smtp_server/client.rb#L257:L270) which check the rcpt_to with regex to ensure it is not `return_path`. It is wrongly classifying mails being sent to address `someone@email.iimcal.ac.in` as return path.

**Comment by willpower232** [comment]
Sorry I misunderstood your issue.

Can you show us exactly what you set your `custom_return_path_prefix` to? How are you sending messages?

Is there any particular reason you set your `custom_return_path_prefix` away from `psrp`?

I am unable to replicate your problem BUT I do see some slightly weird behaviour in that Postal thinks _all_ email with the return path prefix at the start of its domain name is a returned message.

![image](https://user-images.githubusercontent.com/1619102/33611044-03b5a9b0-d9c5-11e7-8a02-8490dcbcbb71.png)

**Comment by yogesum** [comment]
- postal.yaml settings
```yaml
custom_return_path_prefix: email
```
- `psrp` to `email` was done for `mailed-by:` shown in gmail show details
- Emails are being sent over `SMTP` by `CakeEmail` of cakephp

Error can be reproduced for default setup of postal in which `custom_return_path_prefix` is `psrp` over [telnet](https://technet.microsoft.com/en-us/library/aa995718(v=exchg.65).aspx)
> _User input is starts with `>`_
```bash
telnet
telnet> o mx.postal.domain.com 25
Trying xxx.xxx.xxx.xxx...
Connected to mx.postal.domain.com.
Escape character is '^]'.
220 postal.domain.com ESMTP Postal/QS6BKJ
> EHLO localhost
250-My capabilities are
250 AUTH CRAM-MD5 PLAIN LOGIN
> AUTH LOGIN
334 VXNlcm5hbWU6
> base64(org/server)
334 UGFzc3dvcmQ6
> base64(password)
235 Granted for org/server
> MAIL FROM:<test@domain.com>
250 OK
> RCPT TO:<yogesh@psrp.gmail.com>   
550 Invalid server token
```

**Comment by willpower232** [comment]
OK I can replicate and I have verified that is the piece of code causing the issue.

This seems to be a complete block SMTP only which calls into question why that particular bit of code is there. Using the API, the UI is incorrect but it still sends.

It might be handy to have some feedback from @adamcooke or @catphish on this one as it certainly affects a big bit of the system.

For now, you could try using the API client since CakePHP is composer-friendly (https://packagist.org/packages/postal/postal) or switching back to `psrp`. Could you send a screenshot of the bit in Gmail that you were trying to avoid? I couldn't spot it in mine.

**Comment by yogesum** [comment]
![screenshot-2017-12-5 this is a test ignore - yogesum gmail com - gmail](https://user-images.githubusercontent.com/2473279/33618978-021a50a2-da0a-11e7-83d5-0d2e940ca6b4.png)

**Comment by adamcooke** [comment]
The custom return path prefix should be unique and not likely to be used. Postal needs to take responsibility for this domain. In our installation we use `psrp` as our prefix as we know we won't have any domains that start with that. In fact, that's the default.

**Comment by yogesum** [comment]
@adamcooke  Problem is when we send email to some external host with subdomain same as `psrp` it will fail. Like sending email to address `yogesum@psrp.gmail.com` or `yogesum@psrp.yahoo.com` fails.
