### ISSUE TITLE
OpenSSL SSLError SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol

### ISSUE THREAD

**Issue by michielkalle** [atech/postal#428]
On incoming mail i got this error: 
`OpenSSL SSLError SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol`

It looks like it does not support SSLv2/v3 
Maybe you have a fix?

**Comment by igerzog** [comment]
Have you installed the latest version of Postal? Have you made proper config entries regarding #387 and #336?

**Comment by michielkalle** [comment]
yes, i did an upgrade:
`postal auto-upgrade`

and updated my config postal.yml to the latest version.

`smtp_server:
  port: 25
  tls_enabled: false
  tls_certificate_path: /etc/letsencrypt/live/<hostname>/cert.pem
  tls_private_key_path: /etc/letsencrypt/live/<hostname>/privkey.pem
  tls_ciphers:
  ssl_version: SSLv23
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14 # size in Megabytes`

with `tls_enabled: true` it is not even receiving:
`Error: Errno::ECONNRESET (Connection reset by peer - SSL_connect)

  SMTP Host: 127.0.0.1
  SMTP Port: 25
  SMTP Username: <username>
  SMTP Password: <password>`

with `tls enabled: false` i got the outcomig mail but the same  SSL error for incoming mail.

**Comment by igerzog** [comment]
If I am not mistaken your paths to certificate and key must be presented like this:
- `tls_certificate_path: /etc/letsencrypt/live/cert.pem`
- `tls_private_key_path: /etc/letsencrypt/live/privkey.pem`

Does Postal have access permissions to these files?

**Comment by michielkalle** [comment]
I gave Postal permissions, to read the .pem files.
And i have turned on `tls_enables = true`. i can send with tls now.

But still got the SSL error for incoming mail.

**Comment by igerzog** [comment]
Try to stop Postal by `postal stop` and then start it in test mode by `postal run`. Send a message to Postal to see the logs in real time on the screen. Sometimes it is very helpful to find an error.

**Comment by willpower232** [comment]
Can you show us where you are seeing that error message?

**Comment by michielkalle** [comment]
Log:
https://stack.michielkalle.nl/s/vmMDxhYJnv1xV8r

Postal:
https://stack.michielkalle.nl/s/glWP3mLqNbTyKZN

**Comment by igerzog** [comment]
Please check you have made proper DNS configuration for your mail domain regarding to [Domains-&-DNS-Configuration](https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration)
And one more thing. In case you are using Let's Encrypt you must add to `/etc/letsencrypt/live/{hostname}/cert.pem` an intermediate certificate to make the chain validated properly.

**Comment by willpower232** [comment]
Are you sending an email to yourself or are you trying to make Postal send you an email?

**Comment by michielkalle** [comment]
Send from my hotmail account to postal mail:
<pre>
[smtp.1:2655] [2017-12-11T19:42:58.065] DEBUG -- : [WU1J8O] <= EHLO EUR01-HE1-obe.outbound.protection.outlook.com
[smtp.1:2655] [2017-12-11T19:42:58.087] DEBUG -- : [WU1J8O] => 250-My capabilities are
[smtp.1:2655] [2017-12-11T19:42:58.087] DEBUG -- : [WU1J8O] => 250-STARTTLS
[smtp.1:2655] [2017-12-11T19:42:58.087] DEBUG -- : [WU1J8O] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:2655] [2017-12-11T19:42:58.206] DEBUG -- : [WU1J8O] <= STARTTLS
[smtp.1:2655] [2017-12-11T19:42:58.207] DEBUG -- : [WU1J8O] => 220 Ready to start TLS
[smtp.1:2655] [2017-12-11T19:42:58.339] DEBUG -- : [WU1J8O] <= EHLO EUR01-HE1-obe.outbound.protection.outlook.com
[smtp.1:2655] [2017-12-11T19:42:58.345] DEBUG -- : [WU1J8O] => 250-My capabilities are
[smtp.1:2655] [2017-12-11T19:42:58.345] DEBUG -- : [WU1J8O] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:2655] [2017-12-11T19:42:58.458] DEBUG -- : [WU1J8O] <= MAIL FROM:<michiel.kalle@hotmail.com> AUTH=<>
[smtp.1:2655] [2017-12-11T19:42:58.460] DEBUG -- : [WU1J8O] => 250 OK
[smtp.1:2655] [2017-12-11T19:42:58.492] DEBUG -- : [WU1J8O] <= RCPT TO:<hi@michielkalle.nl>
[smtp.1:2655] [2017-12-11T19:42:58.781] DEBUG -- : [WU1J8O] Added route 2 to recipients (tag: nil)
[smtp.1:2655] [2017-12-11T19:42:58.782] DEBUG -- : [WU1J8O] => 250 OK
[smtp.1:2655] [2017-12-11T19:42:58.892] DEBUG -- : [WU1J8O] <= DATA
[smtp.1:2655] [2017-12-11T19:42:58.899] DEBUG -- : [WU1J8O] => 354 Go ahead
[smtp.1:2655] [2017-12-11T19:42:58.931] DEBUG -- : [WU1J8O] <= DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=hotmail.com;
[smtp.1:2655] [2017-12-11T19:42:58.932] DEBUG -- : [WU1J8O] Not logging further message data.
[smtp.1:2655] [2017-12-11T19:42:59.708] DEBUG -- : [WU1J8O] => 250 OK
[smtp.1:2655] [2017-12-11T19:42:59.742] DEBUG -- : [WU1J8O] <= QUIT
[smtp.1:2655] [2017-12-11T19:42:59.742] DEBUG -- : [WU1J8O] => 221 Closing Connection
[smtp.1:2655] [2017-12-11T19:42:59.744] DEBUG -- : [WU1J8O]    Connection closed

==> ../log/smtp_sender.log <==
[worker.2:2651] [2017-12-11T19:43:29.740] INFO -- : [AQCMONDL] Cannot connect to 2a01:7c8:fff8:11b::1:25 (mail.michielkalle.nl) (Net::OpenTimeout: execution expired)

==> ../log/smtp_server.log <==
[smtp.1:2655] [2017-12-11T19:43:29.746] DEBUG -- : [KJN6HS]    Connection opened from ::ffff:136.144.143.66
[smtp.1:2655] [2017-12-11T19:43:29.746] DEBUG -- : [KJN6HS]    Client identified as ::ffff:136.144.143.66

==> ../log/smtp_sender.log <==
[worker.2:2651] [2017-12-11T19:43:29.748] INFO -- : [AQCMONDL] Cannot connect to 136.144.143.66:25 (mail.michielkalle.nl) (OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol)
[worker.2:2651] [2017-12-11T19:43:29.749] INFO -- : [AQCMONDL] -> No SMTP server available for michielkalle.nl
[worker.2:2651] [2017-12-11T19:43:29.749] INFO -- : [AQCMONDL] -> Hostnames: ["mail.michielkalle.nl"]
[worker.2:2651] [2017-12-11T19:43:29.749] INFO -- : [AQCMONDL] -> Errors: ["execution expired", "SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol"]

==> ../log/smtp_server.log <==
[smtp.1:2655] [2017-12-11T19:43:29.750] DEBUG -- : [KJN6HS] => 502 Invalid/unsupported command
[smtp.1:2655] [2017-12-11T19:43:29.752] DEBUG -- : [KJN6HS] => 502 Invalid/unsupported command

==> ../log/smtp_sender.log <==
[worker.2:2651] [2017-12-11T19:43:29.759] INFO -- : [AQCMONDL] Finishing up

==> ../log/smtp_server.log <==
[smtp.1:2655] [2017-12-11T19:43:29.767] ERROR -- : [KJN6HS] An error occurred while processing data from a client.
[smtp.1:2655] [2017-12-11T19:43:29.767] ERROR -- : [KJN6HS] Errno::EPIPE: Broken pipe
[smtp.1:2655] [2017-12-11T19:43:29.768] ERROR -- : [KJN6HS] /opt/postal/app/lib/postal/smtp_server/server.rb:166:in `write'
[smtp.1:2655] [2017-12-11T19:43:29.768] ERROR -- : [KJN6HS] /opt/postal/app/lib/postal/smtp_server/server.rb:166:in `block (3 levels) in run_event_loop'
[smtp.1:2655] [2017-12-11T19:43:29.768] ERROR -- : [KJN6HS] /opt/postal/app/lib/postal/smtp_server/server.rb:163:in `each'
[smtp.1:2655] [2017-12-11T19:43:29.768] ERROR -- : [KJN6HS] /opt/postal/app/lib/postal/smtp_server/server.rb:163:in `block (2 levels) in run_event_loop'
[smtp.1:2655] [2017-12-11T19:43:29.768] ERROR -- : [KJN6HS] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `select'
[smtp.1:2655] [2017-12-11T19:43:29.768] ERROR -- : [KJN6HS] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `block in run_event_loop'
[smtp.1:2655] [2017-12-11T19:43:29.768] ERROR -- : [KJN6HS] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `loop'
[smtp.1:2655] [2017-12-11T19:43:29.768] ERROR -- : [KJN6HS] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `run_event_loop'
[smtp.1:2655] [2017-12-11T19:43:29.769] ERROR -- : [KJN6HS] /opt/postal/app/lib/postal/smtp_server/server.rb:259:in `run'
[smtp.1:2655] [2017-12-11T19:43:29.769] ERROR -- : [KJN6HS] /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
[smtp.1:2655] [2017-12-11T19:43:29.769] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
[smtp.1:2655] [2017-12-11T19:43:29.772] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
[smtp.1:2655] [2017-12-11T19:43:29.772] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
[smtp.1:2655] [2017-12-11T19:43:29.772] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
[smtp.1:2655] [2017-12-11T19:43:29.772] ERROR -- : [KJN6HS] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[smtp.1:2655] [2017-12-11T19:43:29.772] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
[smtp.1:2655] [2017-12-11T19:43:29.772] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
[smtp.1:2655] [2017-12-11T19:43:29.773] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
[smtp.1:2655] [2017-12-11T19:43:29.773] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
[smtp.1:2655] [2017-12-11T19:43:29.773] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
[smtp.1:2655] [2017-12-11T19:43:29.773] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
[smtp.1:2655] [2017-12-11T19:43:29.773] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
[smtp.1:2655] [2017-12-11T19:43:29.773] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
[smtp.1:2655] [2017-12-11T19:43:29.773] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
[smtp.1:2655] [2017-12-11T19:43:29.773] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
[smtp.1:2655] [2017-12-11T19:43:29.774] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
[smtp.1:2655] [2017-12-11T19:43:29.774] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
[smtp.1:2655] [2017-12-11T19:43:29.774] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
[smtp.1:2655] [2017-12-11T19:43:29.774] ERROR -- : [KJN6HS] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
</pre>

I will double check my DNS.

**Comment by igerzog** [comment]
Well as I can see from the logs you are sending a message from your Hotmail to Postal. And Postal successfully excepts this message. But then it is trying to connect to itself in order to resend this message. I wonder have you configured any route in Postal for your incoming mail?

**Comment by michielkalle** [comment]
Route:
https://stack.michielkalle.nl/s/G5nvaCbOQXFRtJD

Domain:
https://stack.michielkalle.nl/s/THKojrERhw1TDkk

**Comment by igerzog** [comment]
Please show your SMTP endpoint configuration for this route. What kind of ssl mode have you set there?

**Comment by michielkalle** [comment]
I reconfigured everything.
And now its working correctly!

Thanks for finding out!
