### ISSUE TITLE
Slow loading of outgoing messages page and exporting data

### ISSUE THREAD

**Issue by vishnus** [atech/postal#429]
Hi team,

We have processed few million emails so far using Postal. We have a raw message retention for 7 days and meta data for 180 days. The outgoing messages page is extremely slow because of the number of messages. I can see that its loading all messages and then its paginated which is probably why its this slow. Can this be paginated and fetched first and loaded instead of just a UI pagination? The UI takes atleast 3-4 minutes to load (had to increase server timeouts drastically)

Also we'd like to download few reports like suppression email ids, bounce list etc. Is it possible to export them without having to use webhooks? (feature request:) )

**Comment by willpower232** [comment]
There is a general lack of reports and metrics from Postal at the minute, I'm not sure if that will be picked up. I'd like to see some more stats in the UI and some customisations.

The page loading issue is interesting though, can you send us a screenshot of the pagination to get an idea of the numbers involved?

Something like 
![image](https://user-images.githubusercontent.com/1619102/33936340-217343da-dff7-11e7-8763-9b7d212818fb.png)

I'd like to think that its just the page count that is falling apart but will need to have a look at the code for it first.

**Comment by vishnus** [comment]
Just the chrome network tab for outgoing:
![image](https://user-images.githubusercontent.com/598121/33936793-c2e99d16-e026-11e7-954f-e806a499f5d9.png)


And the screenshot you requested:
![image](https://user-images.githubusercontent.com/598121/33936818-e40729dc-e026-11e7-8840-fe839e7b79a1.png)

**Comment by vishnus** [comment]
Another interesting thing is, if we give a search term, say just email, which is not a valid filter it shows this red banner

![image](https://user-images.githubusercontent.com/598121/33937077-0455ab72-e028-11e7-9b98-ba20f80694c5.png)

But again, this shows up after 2-3 minutes of fetching data which shouldnt be the case. Validation of input should be done in front end also i suppose?

**Comment by willpower232** [comment]
Without reworking the page to include an ajax loaded list (similar to [jQuery DataTables](https://datatables.net/)) theres not really a lot that can be done in the short term.

**Comment by adamcooke** [comment]
Postal just stores messages in the MySQL database so making queries for messages depends on the speed of the MySQL server itself. We have added indexes for common searches but there may be some missing and/or simply too much mail to handle quickly. We've seen some speed issues with loading message lists on servers that handle lots of mail so we may be able to investigate this ourselves. I've made a note of this on our internal task tracking and we'll try and take a look soon.

**Comment by shopglobal** [comment]
Sorry if this is not be the place to ask..  How are you getting the API to
work with external applications?

So far we got everything working and test emails are ok! But when
attempting to use external platform with the API it's not working.. any
tips appreciated!

**Comment by willpower232** [comment]
@shopglobal please open a new issue with the problems you are experiencing

**Comment by shopglobal** [comment]
#306 #293 please offer any assistance. Thanks

On Jan 13, 2018 2:05 PM, "Will Power" <notifications@github.com> wrote:

@shopglobal <https://github.com/shopglobal> please open a new issue with
the problems you are experiencing

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/atech/postal/issues/429#issuecomment-357458359>, or mute
the thread
