### ISSUE TITLE
Porting database

### ISSUE THREAD

**Issue by shawntremere** [atech/postal#430]
I have installed Postal on clean server, and everything worked fine. I was looking to move the database out of the server, and add it to my server where all the other databases are.  After the install I see that postal uses two databases, postal, and postal-server-1. I see where I can set the configuration for the postal database, but I'm not sure about postal-server-1. Is this configured anywhere? Or did I miss a step?

**Comment by willpower232** [comment]
`postal-server-1` is created automatically by Postal and holds the messages for your first email server within Postal.

Postal will continue to create databases as you add more email servers within it.

If you are moving databases to a different server, you should move all of them.

**Comment by shawntremere** [comment]
So I'm likely only going to have one email server within my instance of Postal.
So I move postal, and postal-sever-1 to a different database server. I can change the configuration for the postal database server in the postal.yml file, how will 'Postal' know about the location of postal-server-1 database? Does that need to be configured as well?
Apologises if I'm making this more confusing than necessary.

**Comment by willpower232** [comment]
I presume that Postal assumes responsibility for any database starting `postal-` and the one database called `postal`.

It uses the same MySQL user for all so theres nothing to reconfigure for the subsequent databases.

Make sure that you import the permissions correctly from the current MySQL user so that if you choose to add more mail servers in the future, you don't break that functionality.

**Comment by shawntremere** [comment]
Thanks. I believe I understand. 
I can change the config for the postal database in postal.yml, and  I can add a new email server and it will add to the database server correct? Assuming I ported permissions over correctly.

**Comment by willpower232** [comment]
Correct :-)
