### ISSUE TITLE
Postal ISSUE with HTML body messages

### ISSUE THREAD

**Issue by anasiou** [atech/postal#431]
Since we have successfully install and use Postal, we cannot find the way of sending right HTML messages. We tried with the specific parameter html_body you define on API but the result was a disaster, HTML didn’t work. Could you please send me an example anybody of sending an HTML message?

**Comment by willpower232** [comment]
Can you confirm which coding language or client library you are using?

**Comment by anasiou** [comment]
We make the implementation using Curl and Postman.

**Comment by willpower232** [comment]
Here it is working in Postman.

![image](https://user-images.githubusercontent.com/1619102/33987252-2d563984-e0b8-11e7-9ef0-ca9ce5f85f7b.png)

When you say it was a disaster, do you mean the email looked wrong or the response from Postal was not success?

**Comment by anasiou** [comment]
I meant the email looked wrong! I will check again the html code performing some tests and I'll come back if the issue insist, thanks.

**Comment by willpower232** [comment]
Try using the W3C validator on the HTML to highlight any coding issues http://validator.w3.org/#validate_by_input

If you are having issues with CSS, have a look at https://www.campaignmonitor.com/css/ for quirks with styling.

**Comment by anasiou** [comment]
Thank you very much for your guidance and your time. Issue has solved, some styling HTML code with CSS cracked the JSON.
