### ISSUE TITLE
Hotmail/Yahoo help?

### ISSUE THREAD

**Issue by theraw** [atech/postal#433]
Hello,

Can i have some help to make this work with hotmail/yahoo please because messages are not received to all hotmail or yahoo emails :confused: 

And Thank you For this project! Is really helpful

About my problem error which i get 
```bash
550 5.7.1 Unfortunately, messages from [*******] weren't sent. Please contact your Internet service provider since part of their network is on our block list (AS3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors. [AM5EUR03FT018.eop-EUR03.prod.protection.outlook.com]

Time: 0.01s

Support Ref: K8YXBEMJ
```

that says my ip is on block list but problems with hotmail/live/yahoo are not just for me i tried lots of ips the same problem i readed this : https://community.ovh.com/en/t/microsoft-hotmail-outlook-live-mail-delivering-problems/126

so i think i'm not the only one having problems. so can anyone here help about this please?!

**Comment by tmikaeld** [comment]
I have a lot of OVH servers and e-mail delivery works just fine.

First of all, make sure that you have configured and verified rDNS, SPF, MX, DKIM.

Then you need to register on JMRP program.

[You can do that here](https://postmaster.live.com/snds/JMRP.aspx?wa=wsignin1.0)

[Then go here](https://support.microsoft.com/en-us/getsupport?oaspworkflow=start_1.0.0.0&wfname=capsub&productkey=edfsmsbl3&ccsid=635688189955348624&wa=wsignin1.0) to clear your IP of listing, follow the instructions to the letter.

DO NOT submit multiple times, MS takes some time to respond and if you submit multiple times you WILL get permanently blocked.

**Comment by theraw** [comment]
@tmikaeld thank you
