### ISSUE TITLE
Soft fail when trying to send to same domain

### ISSUE THREAD

**Issue by braun1928** [atech/postal#434]
Hi guys,
We've changed our Postal setup, removing the relay we had, to a new deploy in a new data center. I got the DNS working correctly -- I can send e-mails from my domain to gmail, perfectly.
But if I try to send to the same domain, I get a soft fail:

Temporary SMTP delivery error when sending to mx.mydomain.redacted (ipv6:of:my:public:mx) 

452 4.5.2 Could not resolve sender domain.
Time: 0.03s
Support Ref: JO3UUCVL 

The VM is using Google's public DNS, it has IPv6 support enabled, but no address (except fe80::). The domain is correctly resolved to the IPv6 address in the error message. Everything is configured as the default in postal.yml, except the DNS address entries.

Should it happen like this, or do I have to alter any other configuration that I'm missing so far?

Thanks!

**Comment by willpower232** [comment]
I would presume that if the VM does not have a real and public IPv6 address, it will not be able to communicate to `mx.mydomain.redacted`.

I would work with your VM provider to prove, fix or remove the IPv6 connection.

**Comment by braun1928** [comment]
The thing is that the MX is dual stack. Although the VM is dual stack enabled, it only has fe80:: address, non routeable. So even if it resolves AAAA and A, it shouldn't only try to connect to the IPv6 address; it should prefer v6, but fallback to v4, as most apps do.
I've tried to find something Ruby related on this, but got no luck so far.

**Comment by adamcooke** [comment]
That looks like an error generated by a remote SMTP server. `4.5.2 Could not resolve sender domain` is not an error generated by Postal at all and is just being reported by the remote server. You might want to check your DNS configuration.
