### ISSUE TITLE
Can't connect to 25 from outside

### ISSUE THREAD

**Issue by inrobin** [atech/postal#435]
Hi,

By some reason, I can't connect to SMTP via port 25. DigitalOcean droplet. There is no firewall configured.

```
telnet mail.myhost.com 25
Trying 2a03:1010:0:b0c0::c3:c001...
Trying 178.162.226143...
telnet: Unable to connect to remote host: Connection refused
```

```
netstat -lnpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      28275/nginx: master
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      11721/epmd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      894/sshd
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      28275/nginx: master
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      30683/[postal] web.
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      11798/beam
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      10968/mysqld
tcp6       0      0 :::80                   :::*                    LISTEN      28275/nginx: master
tcp6       0      0 :::4369                 :::*                    LISTEN      11721/epmd
tcp6       0      0 :::22                   :::*                    LISTEN      894/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      30689/[postal] smtp
tcp6       0      0 :::443                  :::*                    LISTEN      28275/nginx: master
tcp6       0      0 :::5672                 :::*                    LISTEN      11798/beam
```
Any help would be appeciated.

**Comment by inrobin** [comment]
Info from DigitalOcean:

> Nothing on our end is blocking regular SMTP traffic. That said, I tried preforming a telnet to your server and it looks like your mail server is attempting to use IPv6 over SMTP. Please see below:
> 
> haley$ telnet mail.myhost.com 25
> Trying 2a03:1010:0:b0c0::c3:c001...
> 
> We currently block all IPv6 SMTP traffic. We suggest using an IPv4 Droplet for hosting a mail server. Alternatively, you can edit the /etc/gai.conf file to prioritize IPv4. You will want to remove the comment (#) from the following line:
> 
> #precedence ::ffff:0:0/96 100
> 
> In order to modify this file, you will need to connect to the server as the root user. You can do this via SSH or SFTP. For SSH, please see our guide on connecting to your droplet:
> 
> https://www.digitalocean.com/community/tutorials/how-to-connect-to-your-droplet-with-ssh 
> 
> For SFTP, please see this tutorial:
> 
> https://www.digitalocean.com/community/tutorials/how-to-use-sftp-to-securely-transfer-files-with-a-remote-server
> 
> To provide you with some context: the main reason why we have chosen to block these ports by default is due to how blacklists handle IPv6 spam complaints. Blacklists will block the full /64 subnet of reported address in the event of a spam complaint. This impacts a whole range of customers and Droplets unaffiliated with incriminating Droplet/user.

Is there any way to make Postal to listen on IPv4 address instead of IPv6?

**Comment by inrobin** [comment]
Disabled IPv6 on droplet:
```
nano /etc/default/grub
GRUB_CMDLINE_LINUX="ipv6.disable=1"
update-grub2
```

But now Postal SMTP process is not starting:
```
   CGroup: /system.slice/postal.service
           ├─1371 [procodile] Postal (/opt/postal/app)
           ├─1377 [postal] web.1
           ├─1379 [postal] worker.1 (i
           ├─1381 [postal] cron.1
           └─1385 [postal] requeuer.1
```

**Comment by inrobin** [comment]
nginx, SSH and other processes are listening on both IPv4 and IPv6 addresses. It would be good to have Postal listening on both IPv4 and IPv6 too, not on IPv6 only.

**Comment by willpower232** [comment]
Having checked our Postal servers, it seems that the IPv4 smtp server doesn't appear on `netstat` output.

Can you try `postal status` and see what that says?

**Comment by inrobin** [comment]
Postal by default appears in IPv6 on `netstat` - see "tcp6".

Made Postal listen to IPv4 by replacing '::' with '0.0.0.0' in https://github.com/atech/postal/blob/master/lib/postal/smtp_server/server.rb (line 52)

**Comment by willpower232** [comment]
For your information, processes listening on IPv6 (tcp6) can listen on IPv4 (tcp) simultaneously which is why it only appears once in netstat.

As you have disabled IPv6 server-wide, I would imagine that means the SMTP is unable to start without the modification you made above.

If possible, you could recreate your droplet without an IPv6 address which will then allow Postal to function normally. This may be an issue if Postal gets an update as it could revert the change you made.

**Comment by catphish** [comment]
@willpower232 is correct. The best solution if they're going to block ipv6 is simply to remove the public IPv6 address from the machine. Your solution will work, but may be clobbered by updates.

**Comment by Igcorreia** [comment]
Worked today,

> Postal by default appears in IPv6 on `netstat` - see "tcp6".
> 
> Made Postal listen on IPv4 by replacing '::' with '0.0.0.0' in https://github.com/atech/postal/blob/master/lib/postal/smtp_server/server.rb (line 52)

**Comment by smsohagbd** [comment]
hello i face same problem mail automatically send from ipv6 address . i tried but can not find [server.rb] file . which path I will find this ? 

Thanks

**Comment by moviezhou** [comment]
It's the tcp6 bind address problem, serve you app at 0.0.0.0 should work.

**Comment by purpleraven** [comment]
> It's the tcp6 bind address problem, serve you app at 0.0.0.0 should work.

Hi @moviezhou , could you describe in more details how I can do it. I see env SERVER_FD , but how can I use it? I can't find anything in the documentation =(

**Comment by Igcorreia** [comment]
@purpleraven I have manually changed line 52 to: 
![image](https://user-images.githubusercontent.com/1076409/206148358-e3047061-798a-48e2-b4ce-0768f1342de6.png)
