### ISSUE TITLE
Automatic bouncing processing

### ISSUE THREAD

**Issue by inrobin** [atech/postal#436]
Does Postal has some internal list of recipients which have been hard bounced before?

Will Postal try to send a message to the recipient which has been hard bounced before (for example with the following message: "550 5.1.1 Recipient address rejected: User unknown in virtual alias table")?

**Comment by inrobin** [comment]
I see that after about 3rd attempt to send an email to non-existing recipient this recipient is added to suppression list: "Recipient added to suppression list (too many hard fails)."

Maybe it would be better to add hard failed recipients to the suppression list right after the 1st bounced email?

**Comment by willpower232** [comment]
It is possible for hard fails to be short lived so I imagine that is the reason it takes a few consistent hard fails to be added to the suppression list.

The suppression list also claims `Recipients are removed from the list after 30 days.` so it only functions as a short term stop gap but I have found no evidence of addresses being removed after 30 days so it may well be a bug...

**Comment by inrobin** [comment]
>  I have found no evidence of addresses being removed after 30 days so it may well be a bug
Actually it is a good bug. I would leave it like this.
