### ISSUE TITLE
Holding period

### ISSUE THREAD

**Issue by inrobin** [atech/postal#437]
I have a message which is held due to the SEND LIMIT:

> December 31, 2017 15:36
> HELD
> Message held because send limit (1) has been reached.

and there is the following info for the message:

> This message has been held. By releasing the message, we will allow it to continue on its way to its destination. It will be held until January 07, 2018 15:36.

Does it mean that held messages are being automatically released after 1 week and Postal will try to send it?

**Comment by willpower232** [comment]
Messages that are held can only be released manually before the date and time mentioned. After that time, I believe you are unable to send that message and would have to re send it from your application.

Was there a reason you lowered the sending limit to 1?

**Comment by inrobin** [comment]
Ok. Thank you. It would be good to have some option allowing to enable automatic sending of Held messages after 60 min.

> Was there a reason you lowered the sending limit to 1?
Just for testing to figure out how it works.

**Comment by willpower232** [comment]
Postal is designed to send messages, if you want to not send them for 60 minutes, you should handle that in your app.

When Postal holds messages it is because the credential has been set to or something has gone wrong, timing is down to you.
