### ISSUE TITLE
Email Processing

### ISSUE THREAD

**Issue by shawntremere** [atech/postal#438]
If I have a couple a thousand of emails that I would like to send at one time, how is this processed. 
I currently have workers set to 10. 
vCPU: 4
RAM: 8 GB
HDD: 25 GB
How many messages does it process at a time? What is the process it follows? I didn't see this in the issue board, so if it has been answered before, here or somewhere else, the link where it was answered would be greatly appreciated. 

Thanks.

**Comment by willpower232** [comment]
It is difficult to calculate how many messages will be processed at a time, there are too many factors involved.

You may be interested in https://github.com/atech/postal/issues/290 which has a bit of a discussion around experiences with large volumes of email and different hardware combinations.

**Comment by shawntremere** [comment]
Thanks for response!
