### ISSUE TITLE
Postal won't send emails from external server

### ISSUE THREAD

**Issue by theratris** [atech/postal#44]
So Postal can send test emails from the admin UI just fine, but when I attempt send emails from a remote server via SMTP nothing happens. I suspect this is related to the Postal admin email sending issue.

**Comment by theratris** [comment]
Here is the connection attempt from the external server that ends up failing.

```
[smtp.1:6681] [2017-04-27T22:09:25.413] DEBUG -- : [WU5N5C]    Connection opened from ::ffff:198.245.60.80
[smtp.1:6681] [2017-04-27T22:09:25.414] DEBUG -- : [WU5N5C]    Client identified as ::ffff:198.245.60.80
[smtp.1:6681] [2017-04-27T22:09:25.434] DEBUG -- : [WU5N5C] <= EHLO localhost.localdomain
[smtp.1:6681] [2017-04-27T22:09:25.439] DEBUG -- : [WU5N5C] => 250-My capabilities are
[smtp.1:6681] [2017-04-27T22:09:25.439] DEBUG -- : [WU5N5C] => 250-STARTTLS
[smtp.1:6681] [2017-04-27T22:09:25.439] DEBUG -- : [WU5N5C] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:6681] [2017-04-27T22:09:25.499] DEBUG -- : [WU5N5C] <= STARTTLS
[smtp.1:6681] [2017-04-27T22:09:25.514] DEBUG -- : [WU5N5C] => 220 Ready to start TLS
[smtp.1:6681] [2017-04-27T22:09:25.555] DEBUG -- : [WU5N5C]    Connection closed
```

**Comment by theratris** [comment]
The strange this is it says 
```
[smtp.1:6681] [2017-04-27T22:09:25.499] DEBUG -- : [WU5N5C] <= STARTTLS
[smtp.1:6681] [2017-04-27T22:09:25.514] DEBUG -- : [WU5N5C] => 220 Ready to start TLS
```
but my external system uses PLAIN authentication...?

**Comment by jduncanator** [comment]
@theratris Make sure the SMTP SSL Certificate was generated correctly (and that at the time of generation, you had correctly set DNS configuration in postal.yml). I found that if you generate SSL certificates at the incorrect time, the certificate is generated with a common name subject that is incorrect, and whilst most SMTP clients will accept self-signed certificates, they won't accept a certificate with an incorrect common name. Check that the common name matches the hostname you are connecting to the SMTP server with.

**Comment by jduncanator** [comment]
@theratris The SMTP certificate is generated with a subject that is incorrect (hard coded to all "Test"), and whilst most SMTP clients will accept self-signed certificates, they won't accept a certificate with an incorrect common name. You'll want to look for an option to ignore invalid certificates in your SMTP client, or alternatively, manually generate a self signed certificate and replace `/opt/postal/config/smtp.cert` with it.

@adamcooke Perhaps asking for the CN etc. in [generate_initial_config.rb](https://github.com/atech/postal/blob/2ad3eb92aa594c35981b7e926ac5c6cd194e3fcf/script/generate_initial_config.rb) might be a better option than hard coding values?

**Comment by theratris** [comment]
I suppose I am confused because I was under the impression LE was being used for all of this.

**Comment by jduncanator** [comment]
Nope, LE is only used for the Link tracking URL. You'll need to generate your own certificate for both the nginx reverse proxy and the SMTP server.

**Comment by theratris** [comment]
Ah okay, this explains a lot! Any reason not to automate LE setup for all the components?

**Comment by jduncanator** [comment]
LE is not designed (at the moment) to generate certificates for non-HTTP services. Whilst it's technically possible, and they have plans to automate it, I don't believe it supports generated certificates for SMTP servers yet.

You _could_ host a HTTP server on the domain you plan to run your SMTP server under, get LE to issue a certificate for it, then destroy the HTTP server and run the SMTP server with the certificate that LE generated for you, but you'd need to repeat the process every 90 days to renew the certificate.

**Comment by adamcooke** [comment]
I think it might be best not to generate any SSL for the SMTP and just leave it disabled until someone puts their own valid cert into place. Should help with getting started.

**Comment by theratris** [comment]
I generated my own cert but still having issues. I used:
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365`
to generate the cert and overwrote the old smtp certs and restarted Postal but it isn't working. I am a noob with SSL :(

How do I go about fixing that or just disabling SSL entirely for SMTP?

**Comment by adamcooke** [comment]
I have made a change to the default configuration so that TLS on SMTP is disabled until manually enabled. The initial self signed SMTP certificates will also not be created when the config is initialised.

To enable TLS you can do so using in the config file. 

```yaml
smtp_server:
  tls_enabled: true
```

**Note:** any existing installations will no longer support TLS until this has been enabled in their config file.
