### ISSUE TITLE
Email Delivered without SPF, DKIM pass

### ISSUE THREAD

**Issue by vscool19** [atech/postal#440]
Hi folks,

I just observed that emails are getting delivered for any non verified domain using return path. There are three conditions which i tested :- 1. If domain is not verified - then it is delivered via return path of an application.(return path configured in postal.yml file)
2. If domain is not there and you add sender header with verified domain - then it is delivered via sender
3. If domain is not there and you add sender header with non - verified domain - then it is delivered via return path of an application.(retrun path configured in postal.yml file)

**Comment by rsgehlot** [comment]
Yes, I have also faced the problem, looking for some experts comment now.

We really don't want unverified domains to send any emails unless send as any and sender verified domain both conditions are not satisfied.

**Comment by rsgehlot** [comment]
@willpower232

**Comment by willpower232** [comment]
Can you please explain how you tested it so we can replicate?

**Comment by rsgehlot** [comment]
How I tested -

1- Deployed postal instance 
2- Configured Return Path eg: rp.rahul.com and verified RP related DNS records
3- Added one domain eg : abc.com, but didn't configure SPF/DKIM/ MX/ RP records in DNS server
4- Disabled Allow Sender Header in advance settings
5 - Used API credentials to send email using from address as info@abc.com, and it got delivered (as via rp.rahul.com), "I was expecting that it should not be delivered as abc.com's DNS records are not verified"

**Comment by willpower232** [comment]
@rsgehlot If you are logged in as a "superadmin" which you created from the command line, you are able to add domains without verification. If you are logged in as a user created from within the UI, you have to verify the domain before adding it which covers the security from this perspective.

Obviously it is possible for DNS records to be made incorrect during their lifetime so Postal shouldn't completely flip out if this happens.

@vscool19 are you experiencing the same thing as described above or are you testing differently?

**Comment by vscool19** [comment]
@willpower232 yes I am experiencing the same thing as described above with same conditions

**Comment by willpower232** [comment]
Thanks for confirming.

As I described above, verification is not always required to add a domain to Postal. This is mentioned in an issue somewhere but I cannot find it for the life of me.

In any case, anyone can send an email from any address they like, with and without Postal so preventing Postal from sending emails when the domains aren't set right is likely to cause more harm than good.

If you are letting other people into Postal and don't want them to add any old domain to the system, you would have to create a user within the UI that would force them to verify domains before adding.

**Comment by vscool19** [comment]
@willpower232  Thanks for your reply.

**Comment by adamcooke** [comment]
To confirm, any admin user who adds a domain does not have to verify it before it will work. All other users will need to perform verification first.
