### ISSUE TITLE
how do i solve this error//

### ISSUE THREAD

**Issue by Ishma59** [atech/postal#442]
postal bundle /opt/postal/vendor/bundle
There was an error while trying to write to `/opt/postal/app/.bundle/config`. It
is likely that you need to grant write permissions for that path.

**Comment by willpower232** [comment]
> It is likely that you need to grant write permissions for that path.

Are you running it as root?

**Comment by Ishma59** [comment]
Yes was running as root but I have changed to a non-root but still getting the same problem

**Comment by willpower232** [comment]
You may need to stay as root but try running this first `sudo mkdir -p /opt/postal/app/.bundle`

**Comment by Ishma59** [comment]
# sudo mkdir -p /opt/postal/app/.bundle
# postal bundle /opt/postal/vendor/bundle
There was an error while trying to write to `/opt/postal/app/.bundle/config`. It
is likely that you need to grant write permissions for that path.

**Comment by Ishma59** [comment]
am still getting the same error

**Comment by willpower232** [comment]
Can you make sure that the postal user is the owner and group of /opt/postal? I'm having no trouble running that command.

![image](https://user-images.githubusercontent.com/1619102/34614038-fd69c200-f227-11e7-8b24-356aa4fb0588.png)

**Comment by Ishma59** [comment]
thankyou for the help .... solved by adding a file named config manually in the /.bundle directory
and then did
sudo chmod 777 /opt/postal/app/.bundle/*

**Comment by willpower232** [comment]
Glad you found a solution. For your general security, you should switch it back to 755 when you are done just in case.

**Comment by Ishma59** [comment]
Thanks for that am now at the postal initialize alot of errors on the database connection

**Comment by Ishma59** [comment]
here is another problem i am new to rails guys

 postal initialize
Initializing database
rake aborted!
Mysql2::Error: Access denied for user 'postal'@'localhost' (using password: YES)
/opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `connect'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `initialize'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'

**Comment by willpower232** [comment]
If you're having issues during install, I strongly recommend re creating your server and following the quick install process https://github.com/atech/postal/wiki/Quick-Install as all of the complicated steps are handled by the script.

"Access denied" suggests the wrong password has been entered in your configuration.

**Comment by Ishma59** [comment]
Thanks alot man the problem was the postal user thanks I just solved
