### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by shawntremere** [atech/postal#445]
Hello,
I have production postal server set up, and I keep on getting an error.

This is the error that is showing in the rails.log file:
[web.1:2605] [2018-01-09T08:34:59.442] INFO -- : Completed 500 Internal Server Error in 27ms (ActiveRecord: 11.1ms)
[web.1:2605] [2018-01-09T08:34:59.443] FATAL -- :
[web.1:2605] [2018-01-09T08:34:59.443] FATAL -- : Mysql2::Error (Too many connections):
[web.1:2605] [2018-01-09T08:34:59.443] FATAL -- :
[web.1:2605] [2018-01-09T08:34:59.444] FATAL -- : lib/postal/message_db/database.rb:319:in `query_on_connection'

Can anyone provide me more detail on what could be causing this error.

I have a test postal server set up and it is working as expected.  I have moved the databases for both postal servers to a different database server. This is the only changes I would of made on my end.
Restarting postal allows me to use postal again.

Let me know if more detail is needed.

**Comment by willpower232** [comment]
It sounds like you need to increase the max connections in mysql.

Edit `/etc/mysql/my.cnf` and increase the `max_connections` setting.

**Comment by willpower232** [comment]
Also you should have a look here for other settings worth increasing https://github.com/atech/postal/issues/324#issuecomment-323538575
