### ISSUE TITLE
DNS configs

### ISSUE THREAD

**Issue by Ishma59** [atech/postal#446]
I'm getting this error on my domain settings  please advice on where  I'm going wrong.
SPF Record

WARNING An SPF record exists but it doesn't include spf.mail.mydomain

You need to add a TXT record at the apex/root of your domain (@) with the following content. If you already send mail from another service, you may just need to add include:spf.mail.mydomain to your existing record.

v=spf1 a mx include:spf.mail.mydomain ~all
DKIM Record

WARNING No TXT records were returned for postal-atMcrz._domainkey.domaintosendmail

You need to add a new TXT record with the name postal-atMcrz._domainkey with the following content.

v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDnE2mAe58m7mF6DlrR/Zoxl6KfALYey7B/6fDwOwp29ZBe1mYrkyiAKjsRNGtYdYPdkY70XVDCJkO3CwyZEHtpG1PF8Mn/MsIadDP6igCfnghsJ8T0okIMDPbrOD62hIXI0ex7g9fBoD5ZFQ5hIxJ3xDbakD35/8R+d1GRK/txBQ

Here are my DNS records [not good at this] and i think its where im going wrong

;A records
postal.mydomain    IN  A  192.168.1.120
mail.mydomain        IN  A  192.168.1.110

;TXT records
@                     IN  TXT    "v=spf1 a mx include:spf.mail.mydomain ~all"
spf.mail.mydomain  IN  TXT   "v=spf1 a mx include:spf.mail.mydomain ~all"

rp.mail.mydomain.      IN    A     192.168.1.110
rp.mail.mydomain.      IN    MX    10 mx.mail.mydomain
rp.mail.mydomain.      IN    TXT   "v=spf1 a mx include:spf.mail.mydomain ~all"
postal._domainkey.rp.mail.mydomain   IN      TXT  "v=DKIM1; h=rsa-sha256; k=rsa; s=email;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+FkU86OQbjCEOmK+SILvKi2STioAkJdTBlwpsSVXSi2K1nRqRebxpEiKMyONaEbDhaiRyviKP/2XvTGdDOC4mLcCXoSEf6lyL3D/1dXfb3dV5m3mfVVv+lC1XzliXjgbz6WYlPnhipFOg1vRajuUohLfzFZNDZVoSgiarVquQpLgdG/WaCEVHmlZwftFtlnHC/XLexSNYRXE8zXshsixFBvivNlSqe5/Upp408hRFkKpJnjJhXJth1SU8cifGFzLyz+UGZLa7Z3wBTJxBzSyvNFyS9539uF4uZ/LWezasgTj2v6jxnAYKFcgXI0UI/m2yxSm4GT5qFc2P7DglTcN9QIDAQAB"
track.mail.mydomain     IN    A    192.168.1.120

**Comment by willpower232** [comment]
Have you put the records on `domaintosendmail`? Thats where they need to be.

**Comment by Ishma59** [comment]
The domainsendmail is the domain that i set after i have created the organization.....now i cant understand what you mean by  putting the records to the domaintosendmail. Do you mean that if i want to send mails for organization A with example.com and organization B with linux.test i'll have to alter the dns records on their domains?

**Comment by willpower232** [comment]
If you want your Postal to send emails from other peoples domain names, you will need to add records to their DNS.

i.e. your Postal server should have DNS records like this

```
postal.yourdomain.com A 12.34.56.78
spf.postal.yourdomain.com TXT "v=spf1 ip4:12.34.56.78 ~all"
```

And your clients should have DNS records like this

```
@ TXT "v=spf1 include:spf.postal.yourdomain.com ~all"
```

**Comment by Ishma59** [comment]
what about the DKIM record? I'm  I also supposed to add it on my clients dns record

**Comment by willpower232** [comment]
Yes.

Something along the lines of 

```
postal-REF._domainkey.yourclient.com TXT "v=DKIM1; t=s; h=sha256;..."
```
