### ISSUE TITLE
Worker and web instance keep on failing.

### ISSUE THREAD

**Issue by yassersheikh** [atech/postal#447]
> * web only has 2 instances (should have 1)
>  * web.2 is not running (Failed)
>  * smtp only has 2 instances (should have 1)
>  * smtp.2 is not running (Failed)

Worker keeps on failing after running for a while.

Getting these two errors on worker.log.

`ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were in use`

`RuntimeError: Circular dependency detected while autoloading constant Queued Message`

I am running 8 workers.

Getting **502 gateway** error on trying to access on web

**Comment by willpower232** [comment]
Have you tried restarting your server? How much memory do you have on the server?

**Comment by yassersheikh** [comment]
Yes tried that, but its fixed now.i have upgraded the version.
