### ISSUE TITLE
Disable raw message storage

### ISSUE THREAD

**Issue by TheChef23** [atech/postal#450]
Hey,

Is there a way for administrators to disable the storage of raw messages in postal. We've set the storage term to 0 days and with 0 mb, however, this does not stop new message from having readable raw messages.

Is there a config option to disable the storage of raw messages. This is needed for certain compliance rules.

**Comment by willpower232** [comment]
At the minute I don't think this is a feature. Can you clarify the compliance rules you need to comply with?

Postal copes with the eventual deletion of raw messages so adding this option (or fixing the behaviour) should be possible.

**Comment by TheChef23** [comment]
Thanks for your response!

Basically we use postal to sent information to customer using email. We do not want the maintainers of postal to be able to read the messages themselves, which could include links to reset password or limited personal information.

Also, by keeping these emails in a separate database we are potentially opening up attack surface for this information to be leaked. All would be better if we could disable the raw saving of the messages.

**Comment by TheChef23** [comment]
I'm sorry, I am not that familiair with Ruby. Would it not be simple to create something like an if statement around [https://github.com/atech/postal/blob/master/app/models/incoming_message_prototype.rb#L51]( this line) which refers to a config option?

**Comment by willpower232** [comment]
I believe that part would only cover messages from the API so wouldn't be completely accurate as messages could still be sent to Postal from SMTP.

In fact I misunderstood your request completely, Postal keeps raw messages for a certain period of time. I presume you would want the plain text and HTML bodies not kept when currently both them and the rest of the message data are kept for a separate period of time.

Out of curiousity, have you changed the "Message Retention Days" setting as well?

**Comment by TheChef23** [comment]
Yes i'm sorry. I meant for no message contact to be stored at all. 'meta data' is fine, like from en to header, but the message itself should not be stored.

I have changed the message retention days to 0. But I guess this is only used by the cronjob that runs every night at 03:00 [in this file](https://github.com/atech/postal/blob/master/config/cron.rb#L27). So the messages are being kept until 03:00.

**Comment by willpower232** [comment]
I wonder what atech would say would be the proper solution but in the mean time, you could modify the UI to hide the message bodies from view in these places:

https://github.com/atech/postal/blob/2f0155747c5c058afb83856ce5c3c8d5f8cad341/app/views/messages/_message_header.html.haml#L34-L35

https://github.com/atech/postal/blob/53475abf553a65d7aaac91cf99e74b104e7bd9cb/app/controllers/messages_controller.rb#L85-L87

https://github.com/atech/postal/blob/f6784238d37d053b2f63a1c83d6066ca162b302c/app/views/messages/plain.html.haml#L17

https://github.com/atech/postal/blob/f6784238d37d053b2f63a1c83d6066ca162b302c/app/views/messages/html.html.haml#L17

**Comment by adamcooke** [comment]
Messages must be stored in the application otherwise it can't be delivered to its final endpoint. When you give the message to Postal, it has to keep it until it's been delivered. If the receiving server is offline, we keep it and try again later which means we need to know what to actually send when the time comes.

The correct solution to cope with any compliance issues would be to remove the message after successful delivery however it will still be available to anyone with access to the application until such time as this has been successfully delivered. Plus anyone with access to the server would still have access to it in the period while it was present plus they could easily engineer something to copy it elsewhere upon arrival.
