### ISSUE TITLE
sending messages

### ISSUE THREAD

**Issue by Ishma59** [atech/postal#454]
why is it that all my messages sent from the platform are pending? no sent or anything else
dns configs ,the spf and the dkim records are okay.......what can be the problem?

**Comment by willpower232** [comment]
Please run `postal status` and confirm all your processes are running. You may need to restart your Postal and server as necessary to get everything running.

**Comment by Ishma59** [comment]
* worker.1 is not running (Failed)
 * smtp.1 is not running (Failed)
 * requeuer.1 is not running (Failed)

this the error i found

**Comment by willpower232** [comment]
> You may need to restart your Postal and server as necessary to get everything running.

**Comment by Ishma59** [comment]
okay let me try i'll get back to you thank you

**Comment by Ishma59** [comment]
restarted postal and stopped postfix which was the other conflicting thing i still get this in red
 * smtp only has 2 instances (should have 1)

**Comment by willpower232** [comment]
Postal works best on its own server, you do not need postfix or anything that is not installed by default.

How much memory does your server have on it?

**Comment by Ishma59** [comment]
12gb

**Comment by willpower232** [comment]
Could you try `systemctl disable postfix` and restarting the server?

**Comment by Ishma59** [comment]
everything is now running fine but cant still send a message

**Comment by Ishma59** [comment]
after disabling postfix everything is running perfectly but still my mails are pending and after some minutes when i run the status command again i get :
* worker.4 is not running (Failed)
 * requeuer.4 is not running (Failed)

**Comment by willpower232** [comment]
You will have to check the files in `/opt/postal/log` to find out what the issue is.

**Comment by Ishma59** [comment]
or is there a setting I'm missing ....i only added the spf and the dkim records on my dns...apart from that any setting i should apply on the postal server?

**Comment by willpower232** [comment]
> You will have to check the files in `/opt/postal/log` to find out what the issue is.

If the services aren't started on the server, you will not be able to send emails.

**Comment by Ishma59** [comment]
found out there is a problem with my rabbitmq authentication am sure when i solve the problem postal will be fine thank-you for the help

**Comment by Ishma59** [comment]
thank you  just did it thanks willpower you  great man
