### ISSUE TITLE
Uncaught ReferenceError: Postal is not defined

### ISSUE THREAD

**Issue by deanpcmad** [atech/postal#46]
In the web console I'm getting `Uncaught ReferenceError: Postal is not defined`

![](https://files.deanpcmad.com/2017/024a2806-22d3-441c-b57d-f54285198ab7/chrome_2017-04-27_23-08-36.png)

**Comment by theratris** [comment]
It looks like your admin UI files aren't being served correctly. Did NGINX give you any errors?

**Comment by deanpcmad** [comment]
All the CSS & JS files are loading fine. It's when it loads this file - https://github.com/atech/postal/blob/master/app/assets/javascripts/application/modules/helpers.coffee - `Postal.Helpers` that is has issues with

**Comment by jduncanator** [comment]
By looking at the hash on the end of your application file, it looks like it's different to mine. Try regenerating the bundle and see if that fixes the issue. For reference, hashing my application.js file results in a hash of `355ffd7890e3b4a9a0464507204b1896349e384ed6021e54aef9`

**Comment by jduncanator** [comment]
It's interesting. I never had this issue and couldn't reproduce it, and then I went to pull the latest version of the repository, and the error popped up. Then, reverting back to the old commit I was on, the error remained.

I can't see any files changed between the two commits I was using that would have affected this, so I suspect it was present in the original commit I was using and somehow didn't crop up.

I'll submit a PR to resolve this.

**Comment by jduncanator** [comment]
@adamcooke I don't think anything is actually using [helpers.coffee](https://github.com/atech/postal/blob/2f0155747c5c058afb83856ce5c3c8d5f8cad341/app/assets/javascripts/application/modules/helpers.coffee).

Just removing this file should resolve the issue.
