### ISSUE TITLE
how to disable ipv6

### ISSUE THREAD

**Issue by Terabyte918** [atech/postal#468]
hello
how to disable `ipv6` please i don't even have a ipv6 still postal is trying to send emails from ipv6
```
[worker.2:42127] [2018-01-18T11:56:56.869] INFO -- : [D9OY3K9N] Cannot connect to 2607:f8b0:400d:c01::1b:25 (gmail-smtp-in.l.google.com) (Errno::ENETUNREACH: Network is unreachable - connect(2) for "2607:f8b0:400d:c01::1b" port 25)
```

**Comment by Terabyte918** [comment]
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:00:00:05:cb:cf brd ff:ff:ff:ff:ff:ff
    inet 54.**.**.**/24 brd 54.**.**.** scope global eth0
       valid_lft forever preferred_lft forever
```
```
eth0      Link encap:Ethernet  HWaddr 02:00:00:05:cb:cf  
          inet addr:54.**.**.**  Bcast:54.**.**.**  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5782 errors:0 dropped:2313 overruns:0 frame:0
          TX packets:1332 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:690419 (690.4 KB)  TX bytes:666362 (666.3 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1339 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1339 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:548821 (548.8 KB)  TX bytes:548821 (548.8 KB)
```


Ipv6 It's disabled on kernel configs and also on grub the same as that issue, tried `postal run` got this output :confused: 
```
12:53:37 smtp.1          | => Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2) for "::" port 25
12:53:39 smtp.1          | Process has stopped. Respawning not available.
12:53:39 smtp.1          | Removed PID file
```

**Comment by blburns** [comment]
# Disable ipv6 for apt
echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4


# Disable ipv6 completely (optional)
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf

# Enabel ipv6
echo "net.ipv6.conf.all.disable_ipv6 = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.lo.disable_ipv6 = 0" >> /etc/sysctl.conf

**Comment by Terabyte918** [comment]
@blburns thank you for your help but problem is
```
12:53:37 smtp.1          | => Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2) for "::" port 25
12:53:39 smtp.1          | Process has stopped. Respawning not available.
```
Not how to disable or enable ipv6! after the disable of ipv6 Postal is not working.

**Comment by willpower232** [comment]
@Terabyte918 please note there was a modification to the Postal code as well https://github.com/atech/postal/issues/435#issuecomment-354847432

**Comment by Terabyte918** [comment]
@willpower232 thank you and sorry i didn't read carefully! i think, should be a option to postal.yml to enable or disable ipv6? i think it will be very helpful! 

My problem is solved after replacing :: so i'm closing this issue!

**Comment by willpower232** [comment]
Its a great question and I'm slightly surprised it hasn't come up sooner as an issue given Gmails bias for IPv6. Does your server provider not issue IPv6 addresses?

**Comment by Terabyte918** [comment]
is not all about i have or not.
Emails are going as spam when i configure ipv6 :confused:
