### ISSUE TITLE
Favicon still showing AppMail letters

### ISSUE THREAD

**Issue by deanpcmad** [atech/postal#47]
Maybe change it to a P, email icon or something?

**Comment by jduncanator** [comment]
How about using the outgoing mail icon?

![outgoing-mail-cd8e1aeb5f58ad29175f1cbfc6de839a4d232c365541ececb6bebd5c3614b81e](https://cloud.githubusercontent.com/assets/1518948/25514567/45c0f6a4-2c21-11e7-83ac-d88a762a7175.png)
