### ISSUE TITLE
Invalid server token when sending to owned domain

### ISSUE THREAD

**Issue by laci84** [atech/postal#471]
I get  "Invalid server token" message when sending from xy@example.com to yz@example.com.

My domain settings:
 mx_records:
    - mx.example.com
  smtp_server_hostname: mail.example.com
  spf_include: spf.example.com
  return_path: example.com
  route_domain: route.example.com
  track_domain: track.example.com

Sending to other domain is working.
What means this message?

**Comment by willpower232** [comment]
"Invalid server token" typically means the credential you are using does not correspond to the domain name you are trying to send from or has a typo in it

**Comment by laci84** [comment]
I have one organization with 3 domain, 1 credential. Got login from Help page and auto generated password.

**Comment by willpower232** [comment]
Do you only have one mailserver in Postal with the three domains in? Does the credential type match how you are sending? (i.e. is it an SMTP or API credential and is that how you're using it?)

**Comment by laci84** [comment]
Yes, one mailserver with three domains. Credential type format is: 
username: example/live
pass: random

So the username that is lower case organization name matching domain name, is it the problem?

**Comment by willpower232** [comment]
As long as you're matching the case shown in Postal, it shouldn't be a problem.

On the list of credentials on the top left of each credential will be a small label either dark blue or cyan which says in the middle either SMTP or API.

Are you using an SMTP credential with SMTP or an API credential with the API?

**Comment by laci84** [comment]
Yes, they exactly match and no error message sending to foreign domains just to owned domains.
Im using SMTP credential.

**Comment by willpower232** [comment]
Something isn't right somewhere. Can you send a screenshot of where you experience the error message?

**Comment by laci84** [comment]
Full settings:

Organization long name: Exam Ple
Organization short name: example

Organization long name: Live
Organization short name: live

Owned domains:
example.com
examplle.com
exam.com

**Credential**
Name: test-web
Key: ZtMMLj......hkkFzZgH

**Help page output**
Sending using SMTP
These instructions explain how to send messages using the SMTP server.
SMTP Server Address
mail.example.com
Port
25 or 2525
The SMTP service supports STARTTLS if you wish to send messages securely. Be aware that security cannot guaranteed all the way to their final destination.
Username
example/live
Password
ZtMMLj......hkkFzZgH
Create more credentials
Authentication Methods
PLAIN, LOGIN or CRAM-MD5

**dns:**
  mx_records:
    - mx.example.com
  smtp_server_hostname: mail.example.com
  spf_include: spf.example.com
  return_path: example.com
  route_domain: route.example.com
  track_domain: track.example.com

**Thunderbird SMTP settings**
server: mail.example.com
port: 2525
username: example/live
pass: ZtMMLj......hkkFzZgH
error message: https://ibb.co/nFZ5ww

**Comment by willpower232** [comment]
The only other thing I can think of is trying a different authentication method.

Its also worth noting that Thunderbird isn't the intended client for Postal so that might also be a problem.

**Comment by laci84** [comment]
I think SMTP is more platform independent. It not just Thunderbird related: .Net SmtpClient also receives this message, I used Thunderbird just for testing.

**Comment by laci84** [comment]
okay, the problem was using example.com for return_path
changing to rp.example.com error message not shown
