### ISSUE TITLE
 comparison with haraka 

### ISSUE THREAD

**Issue by masihfathi** [atech/postal#472]
Is it possible compare postal with haraka and other MTA? (a fair comparison)

**Comment by willpower232** [comment]
Postal, Sendgrid, Mailgun, and Postmark are focused on transactional email, they record messages as they go through and detect if the message is opened or a link it clicked and report what they know. These can also be controlled via their respective UIs. Messages can also be created programatically via an API.

Haraka, exim, postfix and similar simply send emails they are given. They don't typically do much verification of a message prior to sending and are controlled with config files or extensions/plugins.

You may be interested in https://github.com/atech/postal/wiki/Features

Are you looking for anything in particular?

**Comment by masihfathi** [comment]
I want to create a service like Sendgrid. But I'm afraid postal For features like Credentials and SMTP authentication ... (Why did you use ruby? 👎 )
Although I installed it and worked well.
