### ISSUE TITLE
Use External SMTP Relays

### ISSUE THREAD

**Issue by jduncanator** [atech/postal#48]
It would be nice to be able to configure Postal to use a set of external email relays rather than rely on the internal SMTP implementation and IP Pools.

This would allow separation of the actual delivery infrastructure from Postal and allow Postal to become more of an "interface" to send, receive and administrate email. It would also allow Postal to be "dropped" on top of existing installations and work out of the box without too much reconfiguration.

In our use case, we already have a large email delivery infrastructure in place that uses multiple Postfix servers and a SMTP load balancer. We'd like to keep this installation in place, along with their relatively complex configurations that have evolved over the years, but use Postal as an interface to this to allow sending email via HTTP and SMTP, but also give much greater insight into what and how much email is being sent and delivered. We currently aggregate this information from mail logs and display it on a Grafana dashboard.

I'd imagine this could be implemented as an extension of the current IP Pools functionality. If this is something you'd be open to, I'm happy to work on a PR to get this merged in.

**Comment by adamcooke** [comment]
I have added support for relaying outgoing SMTP through external hosts (except in the case when an incoming e-mail is forwarded to another SMTP server). By doing this, however, you will lose some functionality from Postal (including the suppression list).

To configure SMTP relay hosts you can add the following to your config file:

```yaml
smtp_relays:
  -
    hostname: othersmtp.yourdomain.com
    port: 25
    ssl_mode: Auto
```

`ssl_mode` can be `None`, `Auto`, `STARTTLS` or `TLS`. Same as the options available when configuring an SMTP endpoint for incoming e-mail.

Please give this a go and let me know how you get on.

**Comment by mr119** [comment]
What about authentication on SMTP relays?

**Comment by adamcooke** [comment]
That isn't supported. You should configure your relay to allow connections from the IP of your Postal server.

**Comment by brainiers** [comment]
Hello We arrying to relay outbound emails from Postal to another server. The main reason is that with postal we cannot manage the VMTAs like we can with PowerMTA. We have tried the code below:

smtp_relays:
hostname: othersmtp.yourdomain.com
port: 25
ssl_mode: Auto
We have tried to configure 10 SMTP relays but none is working. We have disabled username and password. The SMTP for POstal Emails is working perfectly.

HOw can we achieve this?

**Comment by Manishjodhani** [comment]
@brainiers did you find any things about SMTP relays authentication

**Comment by jduncanator** [comment]
@Manishjodhani You should be using whitelists for your authentication. Allow your SMTP relay to accept mail unauthenticated from your Postal server's IP address.

If you are trying to relay email via Gmail (or other consumer mail relays that require authentication), I would highly recommend you seek an alternative. They are not designed to be used for this use case, and you'll most likely get your account throttled or banned.

If you really _MUST_ have authentication to an external SMTP relay (eg. SendGrid or another platform designed for delivering transactional/bulk email) then you can setup a local mail relay without authentication on your Postal server (something like sendmail), and then configure it to relay mail via your external mail relay with authentication. I have configured a Postal install with this setup, and it works surprisingly well, albeit with higher maintenance.

**Comment by Manishjodhani** [comment]
"then configure it to relay mail via your external mail relay with authentication." what do you mean by this...???
I use as smtp relays like postfix or pmta. In config file there is no define of authentication.
Is there any method to get authentication by programming in postal..that's it.... i really want to know yes or no ??

**Comment by jduncanator** [comment]
I'm not sure what question you are asking anymore. Are you trying to authenticate with an external mail relay?

**Comment by Manishjodhani** [comment]
Yes....kind of

**Comment by jduncanator** [comment]
You'll need to be more specific than "kind of" if you are looking for any valuable advice.

Postal does not support this out of the box, so the best bet is to augment it with a local mail relay. The general idea is to setup a local SMTP relay that accepts mail (without authentication) on 127.0.0.1. Configure Postal to use this SMTP relay. Then, in the local SMTP relay, configure it to relay mail to your external SMTP relay that requires authentication, and configure your authentication in there.

Using postfix as an example, you can configure a `relayhost` (and proper access control) in your `main.cf`. For example:
```nginx
relayhost = [smtp.sendgrid.net]:587

# Only allow relaying mail from the local machine
mynetworks = 127.0.0.0/8, [::1]/128
smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination
```

Then, you can configure a SASL authentication file that holds the username and password for your SMTP relay:
```nginx
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
```

Your `/etc/postfix/sasl_passwd` file would look something like:
```
[smtp.sendgrid.net]:587 username:password
```

Of course this all depends on your installation and requirements, and one would hope that if you were going down this path, you knew what you were doing and would know what all of the mentioned configuration options do. The last thing we need is another open mail relay on the internet! 😄

**Comment by Manishjodhani** [comment]
Thanks for this
I will try this on postfix.
And but in pmta there is no SASL Authentication.So what about in Pmta ???

**Comment by jduncanator** [comment]
I don't use PMTA so I can't help you there, I'd recommend you look into their documentation on how to authenticate with mail relays. It looks like [this SO answer](https://stackoverflow.com/a/47042856/1339896) has the correct configuration syntax, but I'm not sure how correct or applicable this is as I've never used PMTA before.

**Comment by Manishjodhani** [comment]
Thanks @jduncanator

**Comment by rsgehlot** [comment]
How will the bounce data reflect in the postal dashboard?

**Comment by jduncanator** [comment]
@rsgehlot From my understanding, bounce data depends on the Return-Path header of the email. So long as the Return-Path email address is setup (and you have setup incoming email for Postal) the bounce data should still get tracked correctly when using an external SMTP relay.

**Comment by imanudin11** [comment]
Hello,

Sorry to open again this issue. Is it possible to relay over API on POSTAL? My topology like below :

Postal -> Relay to External server using API -> My Server Application

On my server application (like newsletter server/mail campaign), we have some information like :

- email open
- email sent
- email click link
- email bouncing
- Graphic
- Client access to check report

My goal is to records all email that sent from client to my application server. Maybe the topology like below :

Email server on my client -> Relay to Postal using Auth -> Postal relay to my application using API -> My application records all email that sent from Postal

**Comment by jduncanator** [comment]
@imanudin11 You shouldn't need to relay mail _into_ your application. You should be able to access the appropriate information _from_ your application via the Postal API.

If the Postal API doesn't expose enough of the information you'd like, then I'd recommend opening a feature request for those features to be added to Postal.

Alternatively, you could implement an SMTP server in your application that listens on the SMTP port, and then set Postal up to relay email there.

As a comment on your initial request, I don't think it is inside the scope of Postal to support arbitrary external application APIs, as your API is likely different from the next persons, who is different from the next persons. Perhaps this could be resolved by some sort of Webhook functionality being added to Postal, that allows specific information about certain events in Postal being POSTed to an external application by means of a web request? That said, this is the topic for another issue...

**Comment by imanudin11** [comment]
Hello @jduncanator ,

Thanks for your information and advice. I've tried to install SMTP on my application server. But, every email that sent from the SMTP, not recorded on my application. Such as from, subject, to and etc.

I need a feature like Postal. That have SMTP and all email transaction recorded on the web application.

I see Postal have own SMTP server. Not Postfix or Sendmail that familiar to me :)

**Comment by willpower232** [comment]
Postal can either send email for a domain that is configured to anywhere or receive email for a domain that is configured from anywhere but I'm not sure if that fits your requirements exactly.

Have a look at the Routes tab in your Postal and if you have any more questions, please open a new issue.

**Comment by karankashyap208** [comment]
> Postal can either send email for a domain that is configured to anywhere or receive email for a domain that is configured from anywhere but I'm not sure if that fits your requirements exactly.
> 
> Have a look at the Routes tab in your Postal and if you have any more questions, please open a new issue.

Hy will,
I want to know how i can set routes in my postal mail server. I want all incoming emails on that server to another domain email.
Like i am using domain1.com for sending email and domain1.com is linked with postal in domain DNS.
I want to receive replies of all emails from that domain1.com sending using postal mail server on domain2.com mail server that is on godaddy shared server.
How i can route incoming email to domain2.com emails ???

**What entires I need to exactly put in Routes and what are for SMTP Endpoints ??**

and please share the solution with the real values that i need to put in the route and SMTP endpoints sections.

As i tried almost everything in this and still receiving of emails if not working.

Thanks in advance for this.

**Comment by willpower232** [comment]
@karankashyap208 each endpoints page has a short description of what it does if you haven't added any entries, routes connect incoming email messages to the endpoints. It sounds like you need an address endpoint for domain2.com. Please open a new issue if you are stuck rather than commenting on old issues.

**Comment by windware-ono** [comment]
I really wanted to have SMTP auth as I was relaying emails to an external email delivery service such as SendGrid when IP reputation can't be fixed by a private effort.

So, in my structure, Postfix accepts emails from email clients, postfix relays toward Postal and then Postal should be relaying to SendGrid.

It turned out to be the SMTP auth implementation is quite simple to do that and I just modified 5 lines to accomplish it.

Within `postal-worker-1` container, this is the diff for [/opt/postal/app/lib/postal/smtp_sender.rb](https://github.com/postalserver/postal/blob/2e7aaaba5a9a37f32bdff9a9fde0379834b2a4db/lib/postal/smtp_sender.rb)

```
66c66
<             smtp_client.start(@source_ip_address ? @source_ip_address.hostname : self.class.default_helo_hostname)
---
>             smtp_client.start(@source_ip_address ? @source_ip_address.hostname : self.class.default_helo_hostname, server[:user], server[:password])
261c261,263
<             :ssl_mode => relay.ssl_mode
---
>             :ssl_mode => relay.ssl_mode,
>             :user => relay.user,
>             :password => relay.password
```

which I mounted with,

`        - /opt/postal/smtp_sender.rb:/opt/postal/app/lib/postal/smtp_sender.rb`

in the docker-compose `volumes` section and just placed the modified version at `/opt/postal/smtp_sender.rb` on the host and done `docker restart postal-worker-1`.

You can place your SMTP auth parameters in the `postal.yml` in the `smtp_relays` section by adding `user` and `password`, which would look like this for SendGrid,

```
smtp_relays:
  -
    hostname: smtp.sendgrid.net
    port: 587
    ssl_mode: Auto
    user: apikey
    password: YOUR-API-KEY
```

Hope someone with more insight into the code base review it and add it in an official release.

**Comment by jpvaillancourt** [comment]
@windware-ono Thank you so much!

**Comment by Weijtmans** [comment]
> I really wanted to have SMTP auth as I was relaying emails to an external email delivery service such as SendGrid when IP reputation can't be fixed by a private effort.
> 
> So, in my structure, Postfix accepts emails from email clients, postfix relays toward Postal and then Postal should be relaying to SendGrid.
> 
> It turned out to be the SMTP auth implementation is quite simple to do that and I just modified 4 lines to accomplish it.
> 
> Within `postal-worker-1` container, this is the diff for [/opt/postal/app/lib/postal/smtp_sender.rb](https://github.com/postalserver/postal/blob/2e7aaaba5a9a37f32bdff9a9fde0379834b2a4db/lib/postal/smtp_sender.rb)
> 
> ```
> 66c66
> <             smtp_client.start(@source_ip_address ? @source_ip_address.hostname : self.class.default_helo_hostname)
> ---
> >             smtp_client.start(@source_ip_address ? @source_ip_address.hostname : self.class.default_helo_hostname, server[:user], server[:password])
> 261c261,263
> <             :ssl_mode => relay.ssl_mode
> ---
> >             :ssl_mode => relay.ssl_mode,
> >             :user => relay.user,
> >             :password => relay.password
> ```
> 
> which I mounted with,
> 
> ` - /opt/postal/smtp_sender.rb:/opt/postal/app/lib/postal/smtp_sender.rb`
> 
> in the docker-compose `volumes` section and just placed the modified version at `/opt/postal/smtp_sender.rb` on the host and done `docker restart postal-worker-1`.
> 
> You can place your SMTP auth parameters in the `postal.yml` in the `smtp_relays` section by adding `user` and `password`, which would look like this for SendGrid,
> 
> ```
> smtp_relays:
>   -
>     hostname: smtp.sendgrid.net
>     port: 587
>     ssl_mode: Auto
>     user: apikey
>     password: YOUR-API-KEY
> ```
> 
> Hope someone with more insight into the code base review it and add it in an official release.

This works like a charm! Why don't you submit a pull request?

**Comment by engrpeters** [comment]
> > I really wanted to have SMTP auth as I was relaying emails to an external email delivery service such as SendGrid when IP reputation can't be fixed by a private effort.
> > So, in my structure, Postfix accepts emails from email clients, postfix relays toward Postal and then Postal should be relaying to SendGrid.
> > It turned out to be the SMTP auth implementation is quite simple to do that and I just modified 4 lines to accomplish it.
> > Within `postal-worker-1` container, this is the diff for [/opt/postal/app/lib/postal/smtp_sender.rb](https://github.com/postalserver/postal/blob/2e7aaaba5a9a37f32bdff9a9fde0379834b2a4db/lib/postal/smtp_sender.rb)
> > ```
> > 66c66
> > <             smtp_client.start(@source_ip_address ? @source_ip_address.hostname : self.class.default_helo_hostname)
> > ---
> > >             smtp_client.start(@source_ip_address ? @source_ip_address.hostname : self.class.default_helo_hostname, server[:user], server[:password])
> > 261c261,263
> > <             :ssl_mode => relay.ssl_mode
> > ---
> > >             :ssl_mode => relay.ssl_mode,
> > >             :user => relay.user,
> > >             :password => relay.password
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which I mounted with,
> > ` - /opt/postal/smtp_sender.rb:/opt/postal/app/lib/postal/smtp_sender.rb`
> > in the docker-compose `volumes` section and just placed the modified version at `/opt/postal/smtp_sender.rb` on the host and done `docker restart postal-worker-1`.
> > You can place your SMTP auth parameters in the `postal.yml` in the `smtp_relays` section by adding `user` and `password`, which would look like this for SendGrid,
> > ```
> > smtp_relays:
> >   -
> >     hostname: smtp.sendgrid.net
> >     port: 587
> >     ssl_mode: Auto
> >     user: apikey
> >     password: YOUR-API-KEY
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope someone with more insight into the code base review it and add it in an official release.
> 
> This works like a charm! Why don't you submit a pull request?

How do I achieve this what docker command do I need to run , I was able to get into the interactive terminal of the worker , but changes I make don't persist when I exit . I guess it has to do with mount, how do I achieve this please ?

**Comment by marc5feb** [comment]
> I really wanted to have SMTP auth as I was relaying emails to an external email delivery service such as SendGrid when IP reputation can't be fixed by a private effort.
> 
> So, in my structure, Postfix accepts emails from email clients, postfix relays toward Postal and then Postal should be relaying to SendGrid.
> 
> It turned out to be the SMTP auth implementation is quite simple to do that and I just modified 4 lines to accomplish it.
> 
> Within `postal-worker-1` container, this is the diff for [/opt/postal/app/lib/postal/smtp_sender.rb](https://github.com/postalserver/postal/blob/2e7aaaba5a9a37f32bdff9a9fde0379834b2a4db/lib/postal/smtp_sender.rb)
> 
> ```
> 66c66
> <             smtp_client.start(@source_ip_address ? @source_ip_address.hostname : self.class.default_helo_hostname)
> ---
> >             smtp_client.start(@source_ip_address ? @source_ip_address.hostname : self.class.default_helo_hostname, server[:user], server[:password])
> 261c261,263
> <             :ssl_mode => relay.ssl_mode
> ---
> >             :ssl_mode => relay.ssl_mode,
> >             :user => relay.user,
> >             :password => relay.password
> ```
> 
> which I mounted with,
> 
> ` - /opt/postal/smtp_sender.rb:/opt/postal/app/lib/postal/smtp_sender.rb`
> 
> in the docker-compose `volumes` section and just placed the modified version at `/opt/postal/smtp_sender.rb` on the host and done `docker restart postal-worker-1`.
> 
> You can place your SMTP auth parameters in the `postal.yml` in the `smtp_relays` section by adding `user` and `password`, which would look like this for SendGrid,
> 
> ```
> smtp_relays:
>   -
>     hostname: smtp.sendgrid.net
>     port: 587
>     ssl_mode: Auto
>     user: apikey
>     password: YOUR-API-KEY
> ```
> 
> Hope someone with more insight into the code base review it and add it in an official release.

Hy, with some minor adjustments i have it working in the latest version of postal.

the edit around line 66 is unchanged. But i did make a change on the second part as shown below.

          hostname: relay.hostname,
          port: relay.port,
          ssl_mode: relay.ssl_mode,
          user: relay.user,
          password: relay.password

super thanks for the info!

**Comment by davidpiccinini** [comment]
Compatibility lost due new Postal v3.x upgrades. In v3.3 not works

**Comment by Power-MTA** [comment]
🙌🙌🙌 latest version powermta / pmta available with lifetime license key.
+ another tools available
Skype: salimrezabd04
Telegram: salimrezabd
Telegram: salimrezabd1

**Comment by Power-MTA** [comment]
> I have added support for relaying outgoing SMTP through external hosts (except in the case when an incoming e-mail is forwarded to another SMTP server). By doing this, however, you will lose some functionality from Postal (including the suppression list).
> 
> To configure SMTP relay hosts you can add the following to your config file:
> 
> ```yaml
> smtp_relays:
>   -
>     hostname: othersmtp.yourdomain.com
>     port: 25
>     ssl_mode: Auto
> ```
> 
> `ssl_mode` can be `None`, `Auto`, `STARTTLS` or `TLS`. Same as the options available when configuring an SMTP endpoint for incoming e-mail.
> 
> You can add as many relays as you want. They will be tried in order until accepted.
> 
> Please give this a go and let me know how you get on.

🙌🙌🙌 latest version powermta / pmta available with lifetime license key.
+ another tools available
Skype: salimrezabd04
Telegram: salimrezabd
Telegram: salimrezabd1

**Comment by Power-MTA** [comment]
> Hello We arrying to relay outbound emails from Postal to another server. The main reason is that with postal we cannot manage the VMTAs like we can with PowerMTA. We have tried the code below:
> 
> smtp_relays: hostname: othersmtp.yourdomain.com port: 25 ssl_mode: Auto We have tried to configure 10 SMTP relays but none is working. We have disabled username and password. The SMTP for POstal Emails is working perfectly.
> 
> HOw can we achieve this?

🙌🙌🙌 latest version powermta / pmta available with lifetime license key.
+ another tools available
Skype: salimrezabd04
Telegram: salimrezabd
Telegram: salimrezabd1

**Comment by 099912** [comment]
I am trying to add aws ses smtp to postal so I can check all the email outgoigs but on web therre is no  option wher ei can connect it to my aws ses smtp and my issue is when I run this command to check smtp connection 
ERROR
postal test-app-smtp afshal.ahmed49@gmail.com
Message was not delivered successfully to SMTP server.
Error: Net::SMTPAuthenticationError (530 Must issue a STARTTLS command first
)
version: 2

postal:
  web_hostname: postal.domain.com
  web_protocol: https
  smtp_hostname: postal.domain.com

main_db:
  host: 172.17.0.2
  username: root
  password: postal
  database: postal

message_db:
  host: 172.17.0.2
  username: root
  password: postal
  prefix: postal

smtp_server:
 # default_bind_address: "::"
  default_bind_address: "0.0.0.0"  # Forces IPv4
  port: 587
  tls_enabled: true
  tls_certificate_path: /opt/postal/config/smtp.cert
  tls_private_key_path: /opt/postal/config/smtp.key
  max_message_size: 50
dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.postal.infogito.com
  spf_include: spf.postal.domain.com
  return_path_domain: rp.postal.domain.com
  route_domain: routes.postal.domain.com
  track_domain: track.postal.domain.com

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: email-smtp.us-east-1.amazonaws.com
  port: 587
  username: AWS SMTP USERNAME
  password: AWS SMTP PASSWORD
  from_name: Infogito
  from_address: sales@infogito.com
  authentication: login
  tls_enabled: true
#  authentication: plain
  open_timeout: 30                 # Increase timeouts
  read_timeout: 30
  disable_delivery: false  # Stops direct delivery attempts
  always_use_smtp_relay: true  # Forces all mail through SES
rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key:
