### ISSUE TITLE
How to Configure SSL on the Web and SMTP?

### ISSUE THREAD

**Issue by moskoweb** [atech/postal#481]
I have read some of the already open posts on this subject, but I have not yet been able to properly enable SSL on the Web.

And I would also like to enable SSL on the SMTP server.

Any tutorial or easy to understand method?

**Comment by timraybould** [comment]
In case it helps someone looking at this: it took me some time to figure out that the nginx configuration referenced above happens in `/etc/nginx/sites-available/default` update the hostname in there too.

**Comment by timraybould** [comment]
FYI, my certs renewed nicely with this method, however, I had to manually reload nginx via `sudo systemctl reload nginx` to get it to "see" the new cert after renewal.

**Comment by shinebayar-g** [comment]
If you're using certbot and its default automatic renewal method, I guess certbot will reload nginx.

**Comment by willpower232** [comment]
In our experience, the cron job that certbot uses to generate the new certificates doesn't reload the services by default but adding in the necessary `&& systemctl reload ...` to `/etc/cron.d/certbot` isn't a big task.

We also use certbot directly from pip to access some plugins which means the cron file doesn't get created so thats another reason to manage the cron file yourself.

**Comment by The-3x** [comment]
facing problem in 2022. i think the path of public folder is different now. what can be done?

**Comment by Luca-Castelnuovo** [comment]
@The-3x same

**Comment by Luca-Castelnuovo** [comment]
I tried the following, it unfortunately didn't work.

*My steps*
1. run `sudo certbot certonly --manual --preferred-challenges dns -d "postal.example.com"`

2. `mkdir /opt/postal/config/certs`
3. `ln -s /etc/letsencrypt/live/postal.example.com/privkey.pem  /opt/postal/config/certs/privkey.pem`
4. `ln -s /etc/letsencrypt/live/postal.example.com/fullchain.pem  /opt/postal/config/certs/fullchain.pem`

5. edit `/opt/postal/config/postal.yml`
```yaml
smtp_server:
  port: 25
  tls_enabled: true
  tls_certificate_path: config/certs/fullchain.pem
  tls_private_key_path: config/certs/privkey.pem
```

6. `postal stop`
7. `postal start`

*The error*
`Errno::ENOENT: No such file or directory @ rb_sysopen - config/certs/fullchain.pem`

**Comment by Luca-Castelnuovo** [comment]
This didn't work because my misunderstanding of `ln`. I thought the contents of the files would be passed to the container. but in reality the symlink was passed which didn't resolve (naturally).

**Comment by Luca-Castelnuovo** [comment]
My solution can be found here: https://github.com/Luca-Castelnuovo/email.ltc.
It isn't automated. Every 90days I have to manually renew the certificate and update `postal.yaml`.

**Comment by j-p9** [comment]
> I tried the following, it unfortunately didn't work.
> 
> **My steps**
> 
> 1. run `sudo certbot certonly --manual --preferred-challenges dns -d "postal.example.com"`
> 2. `mkdir /opt/postal/config/certs`
> 3. `ln -s /etc/letsencrypt/live/postal.example.com/privkey.pem  /opt/postal/config/certs/privkey.pem`
> 4. `ln -s /etc/letsencrypt/live/postal.example.com/fullchain.pem  /opt/postal/config/certs/fullchain.pem`
> 5. edit `/opt/postal/config/postal.yml`
> 
> ```yaml
> smtp_server:
>   port: 25
>   tls_enabled: true
>   tls_certificate_path: config/certs/fullchain.pem
>   tls_private_key_path: config/certs/privkey.pem
> ```
> 
> 6. `postal stop`
> 7. `postal start`
> 
> **The error** `Errno::ENOENT: No such file or directory @ rb_sysopen - config/certs/fullchain.pem`

How did you fix `Errno::ENOENT: No such file or directory @ rb_sysopen - config/certs/fullchain.pem` ?

**Comment by Luca-Castelnuovo** [comment]
You can see my solution here: https://github.com/Luca-Castelnuovo/mail.ltc/blob/main/README.md
