### ISSUE TITLE
configure content transfer encoding for HTML & TEXT body

### ISSUE THREAD

**Issue by amitsquare** [atech/postal#482]
Can we alter the transfer encoding from postal app. 
As i would like to have different encoding for HTML & Text body part of mail message .

Little direction will be appreciated .

**Comment by willpower232** [comment]
Can you tell us what different encoding you need and why?

**Comment by amitsquare** [comment]
I was comparing my mails headers with one of the ESP mail's header .
Where they have encoded text part of mail having content-transfer-encoding header value as 7bit & HTML part having 8bit as content-transfer-encoding .

So i was willing to achieve the same type of encoding of mail messages .
I tried to alter content-transfer-encoding parameter of file "message_parser.rb" .
But it doesn't seems to be working .
So thought of putting this as issue .

**Comment by willpower232** [comment]
I don't believe theres actually a problem caused by this at all, are you experiencing any issues in your email program(s)?

Theres a nice summary of the different `content-transfer-encoding`s available here https://stackoverflow.com/a/28531705

**Comment by amitsquare** [comment]
Hi Will , thanks for this quick reply .
just want to know that whether through postal content transfer encoding can be altered or not ?

**Comment by amitsquare** [comment]
I was under the impression that this change might be helping in messages going into the SPAM folder .
I think this doesn't help at all .
Still out of curiosity , i would like to know about it .

Plus can you also direct me about the debugging the application as well .

**Comment by willpower232** [comment]
Messages will be going into the spam folder because of incorrect DNS settings, spam-like content, or the email providers own preferences. The content encoding of the message is a standard so shouldn't be related.

If you're experiencing issues, the logs are very comprehensive in `/opt/postal/log`.

**Comment by amitsquare** [comment]
Just want to know is there any way to achieve through postal ?

**Comment by willpower232** [comment]
What are you looking for specifically?

**Comment by amitsquare** [comment]
Sorry for my misunderstanding ..
Closing this issue .
