### ISSUE TITLE
nginx 403 forbidden error .

### ISSUE THREAD

**Issue by amitsquare** [atech/postal#487]
> directory index of "/opt/postal/app/public/" is forbidden
This is error log entry .
Can you direct me how to tackle this .

However i try to change nginx user &&  try changing user group as well. Nothing seems to be working .

Please direct me here .

**Comment by willpower232** [comment]
The owner and group of the entire postal directory should be `postal` and the permissions value should be 755

![image](https://user-images.githubusercontent.com/1619102/35918927-597ff54e-0c0b-11e8-8e07-e9a11e2dc734.png)
