### ISSUE TITLE
Include suppressed & dropped mails in the overview graph

### ISSUE THREAD

**Issue by cybermancy** [atech/postal#49]
I'm sure this is already planned but it would be useful to see this additional info on the graph. If I have time this summer I might look into adding this feature myself.

**Comment by jduncanator** [comment]
@adamcooke I've taken a look and expanded the data available in the graph (see referenced commit) however it doesn't look like the two explicitly requested data sets are stored anywhere (suppressions and drops).

I've also noticed that a held message is counted as both a held message and an outgoing message so the two graph points overlay when there are only ever held messages (eg. in a development server). This could cause confusion on the graph as they both draw in the same area:

![image](https://cloud.githubusercontent.com/assets/1518948/25514086/a11959c8-2c1d-11e7-99ba-d25f40c1987d.png)

Which is made up of both the outgoing and held series:

![image](https://cloud.githubusercontent.com/assets/1518948/25514115/d7087dde-2c1d-11e7-9470-a7465aa6b3c3.png)

![image](https://cloud.githubusercontent.com/assets/1518948/25514128/eaa82df8-2c1d-11e7-8ae1-d8cd4998a6c6.png)

**Comment by adamcooke** [comment]
Messages are counted as soon as they are created as either `outgoing` or `incoming` so if a message then goes on to being spam, held, suppressed etc... it will still have been counted. Putting the data on the same graph may not be very practical for this reason. It would be nice to have a graph that included all this information (perhaps another graph).
