### ISSUE TITLE
transport connection

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#491]
Hi,
I'm new using postal.
When i send mails 
```
Failure sending mail.
Unable to read data from the transport connection: net_io_connectionclosed.
```
anybody can help me in this

**Comment by willpower232** [comment]
Where are you seeing this error message?

**Comment by Manishjodhani** [comment]
in mail transfer application

**Comment by willpower232** [comment]
Can you send a screenshot?

**Comment by Manishjodhani** [comment]
This problem is solved you can closed this issue.

**Comment by willpower232** [comment]
Good to hear, you can close the issue as I can't :-P
