### ISSUE TITLE
SPF didn't pass in mails

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#496]
Hi,
I have verfied spf and dkim but when i send the mails and check they pass or not.
Dkim is passed but spf none. 
How to solve this problem??
Received-SPF: none (zoho.com: 101.259.12.282 is neither permitted nor denied by domain of postal.example.com)
You can also check the attachments.
![screenshot from 2018-02-13 14 35 59](https://user-images.githubusercontent.com/28861157/36141603-4da434aa-10cb-11e8-8de4-a61fa2b6803d.png)

**Comment by willpower232** [comment]
Make sure that the domain names mentioned in your SPF records exist and that one of them relates to the IP address of the server.

(Your screenshot doesn't really hide the domain names you're using so I can tell you that the domain name in your SPF record has no IP address when I use `nslookup` on it)

**Comment by Manishjodhani** [comment]
Ok i will provide you my domain and ip pools.

**Comment by Manishjodhani** [comment]
I using this ip pools ip4:145.239.22.192/27  ip4:54.38.131.224/27
and  my postal hostname : rmta.gonode.tech.
my sender domain : rccess.tech.
Have a look also in screen hots.
http://prntscr.com/ie1m3t

**Comment by Manishjodhani** [comment]
please tell me soon sir..???

**Comment by willpower232** [comment]
The SPF record for rccess.tech links to spf.rmta.gonode.tech

![image](https://user-images.githubusercontent.com/1619102/36145020-e9eb08d0-10a7-11e8-892f-ae448a79f40d.png)

BUT there are currently no records for spf.rmta.gonode.tech so thats probably where you're going wrong.

![image](https://user-images.githubusercontent.com/1619102/36145124-4bb34000-10a8-11e8-81f0-e7135aeb772c.png)

Make sure you have created all the main records as per https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration

**Comment by Manishjodhani** [comment]
v=spf1 a mx include:spf.rmta.gonode.tech ~all 
i have add this record in gonode.tech.....but still not pass the spf.
So, please can you this check again.

**Comment by willpower232** [comment]
spf.rmta.gonode.tech doesn't exist, it needs to exist otherwise your SPF record is pointless

**Comment by Manishjodhani** [comment]
I have add the record it will take time.I will update you.
can you tell me that how can i remove mails id from suppression list.

**Comment by Manishjodhani** [comment]
I have updated the record but still. Spf did not pass.
check the screenshot
http://prntscr.com/ie2slr

**Comment by willpower232** [comment]
> spf.rmta.gonode.tech doesn't exist, it needs to exist otherwise your SPF record is pointless

**Comment by Manishjodhani** [comment]
Please check once again. I have done the update records.
And please take a look in screen shot.
![screenshot_1](https://user-images.githubusercontent.com/28861157/36188741-111d7c7c-1174-11e8-9810-8ec2168bd703.png)

**Comment by willpower232** [comment]
Thats slightly better but the record needs to include your IP addresses, NOT the record.

**Comment by Manishjodhani** [comment]
please check after the include ip addresses but still no progress, spf did not pass.
![screenshot_3](https://user-images.githubusercontent.com/28861157/36197111-e5b38de0-1198-11e8-86fc-3c6dcd69f27a.png)
![screenshot_2](https://user-images.githubusercontent.com/28861157/36197112-e5ee2aea-1198-11e8-8f9f-02c6da39fc28.png)
here my sender domain is hostcot.com and my postal host name is rmta.gonode.tech 
please check where i was going wrong.

**Comment by Manishjodhani** [comment]
Please check it ASAP. Please Sir.

**Comment by willpower232** [comment]
You need to remove `include:spf.rma.gonode.tech` as it makes no sense when the record has the same name.

**Comment by willpower232** [comment]
hostcot.com -> "v=spf1 a mx include:spf.rmta.gonode.tech ~all"

spf.rmta.gonode.tech -> "v=spf1 ip4:145.239.22.192/27  ip4:54.38.131.224/27 ~all"

**Comment by Manishjodhani** [comment]
i have done as you said but still no progress.

**Comment by willpower232** [comment]
Can you send a screenshot of the SPF error you are receiving?

**Comment by Manishjodhani** [comment]
Here you can see what i have done 

![screenshot_4](https://user-images.githubusercontent.com/28861157/36200719-97e8a874-11a3-11e8-91f3-c0b75ece71b4.png)

screenshot of my mail box
http://i.prntscr.com/bUWSF8PdQDi-fB1UmY-EEw.png

**Comment by Manishjodhani** [comment]
Can you rectify what are thing i'm missing??

**Comment by alexroosenstein** [comment]
Make sure you also add a SPF record for rp.rmta.gonode.tech.

**Comment by Manishjodhani** [comment]
@alexroosenstein

Yes, i try what you said but still no progress 

have a look in screenshot

![screenshot_5](https://user-images.githubusercontent.com/28861157/36203762-b2cf3c2e-11ae-11e8-8ec9-4dad4b7c7664.png)

**Comment by alexroosenstein** [comment]
Could you paste the latest email headers?

**Comment by Manishjodhani** [comment]
have a look @alexroosenstein .
![screenshot_7](https://user-images.githubusercontent.com/28861157/36204162-1be3eef2-11b0-11e8-9520-c044e82b5e3e.png)

**Comment by alexroosenstein** [comment]
My bet is now that there's some sort of cache, try again in an hour or so, it should be resolved then.

**Comment by igerzog** [comment]
You have a mistake! In some places I see gonode.tech and somewhere - gondoe.tech

**Comment by Manishjodhani** [comment]
Thanks @igerzog

**Comment by Manishjodhani** [comment]
Thanks @willpower232 now it working...:)
