### ISSUE TITLE
Which exactly functionality is missed if external SMTP relays enabled?

### ISSUE THREAD

**Issue by anasiou** [atech/postal#497]
#48 here the suppression list is mentioned, is there anyone who has explored the whole issue?
Thanks in advance!

**Comment by willpower232** [comment]
The relay server presumably wouldn't report on the delivery of the message in question so Postal has no idea if the message succeeded in delivery which would account for the suppression list so I'd also imagine that some of the webhooks would also be affected and anything else that cared about that level of information.

**Comment by anasiou** [comment]
Thanks for the prompt reply!
