### ISSUE TITLE
Tracking pixel

### ISSUE THREAD

**Issue by kennuzzo** [atech/postal#499]
Hi, 
I saw from https://github.com/atech/postal/blob/master/lib/postal/fast_server/interface.rb that there is a tracking pixel functionality, but i couldn't find any information from the [docs](https://github.com/atech/postal/wiki/Click-&-Open-Tracking) on how to use it. 

Any help? Thank you!

**Comment by kennuzzo** [comment]
Hi @willpower232 thanks for the reply, 

ive added a tracking domain with ssl working, while the links are working as expected, i dont see the tracking pixel, unless gmail is removing it ?

**Comment by willpower232** [comment]
The tracking pixel is added at the end of the HTML message and looks something like this:

![image](https://user-images.githubusercontent.com/1619102/36417346-9b7c35b2-1623-11e8-9195-a52ce0985910.png)

You can also look at the activity tab inside the message you have sent.

**Comment by kennuzzo** [comment]
Indeed it works fine, ive discovered that the reason why it didn't work the first time, is that after a while the fast server started to complain about too many connections and returning a 502. ive temporarely fixed it with a `wait_timeout` while looking on what ive misconfigured ;)

As for this issue then is all good! thank you again @willpower232
