### ISSUE TITLE
Soft failed

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#500]
Hello,
I purchase a new domain and add in postal and so,its reputation is also low.
then i send mail. and check it's status is "soft failed".
and my Message Rate
0.26 messages/minute
@willpower232 please tell me how to increase the sending rate..?

**Comment by willpower232** [comment]
Please read https://github.com/atech/postal/issues/290 with regards to increasing the number of workers on your system.

If the status of your message is "soft fail" you should check the error message on the email to see what the problem is there.
