### ISSUE TITLE
Can we flush the queue mails?

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#501]
Hi,
I want to flush all queue mails for more than 2 days.
it's shows me previous mails of 3-4 days in pending state.
if i want to flush them all mails how can i do this...????

**Comment by willpower232** [comment]
You may be interested in https://github.com/atech/postal/issues/287

**Comment by Manishjodhani** [comment]
I check the issue but not solved my issue....??

**Comment by Manishjodhani** [comment]
I try that...you can see in the screen shot. But not solved my problem.
https://prnt.sc/ih9azj

**Comment by willpower232** [comment]
Did you get to https://github.com/atech/postal/issues/287#issuecomment-331081922?

**Comment by Manishjodhani** [comment]
NO
