### ISSUE TITLE
Postal Upgrade

### ISSUE THREAD

**Issue by igerzog** [atech/postal#504]
If I had installed Postal from a package `latest.tgz` would it be possible to safely upgrade it to the latest version of the repository by `git pull`?

**Comment by catphish** [comment]
I believe so, as long as the normal upgrade steps (bundle, database migrations, etc) are followed. It's worth noting that due to a recent upgrade of Rails, libffi-dev is now a system dependency, so you may wish to install this before upgrading. Update this ticket if you have any trouble with it.

**Comment by igerzog** [comment]
I have just prepared myself to upgrade process :) One more thing before I start. Initially postal was installed from a package `latest.tgz`. Now I am going to upgrade it to master branch from GitHub. What is the correct path for the contents of `postal-master.zip`? Should it be `/opt/postal/app` or `/opt/postal/app/postal-master` subfolder? This is the cause of that the command `wget https://postal.atech.media/packages/stable/latest.tgz -O - | sudo -u postal tar zxpv -C /opt/postal/app` puts the archive's content to `/opt/postal/app/latest`.

**Comment by igerzog** [comment]
As a matter of fact upgrade completed successfully. 👍

**Comment by willpower232** [comment]
Your `/opt/postal/app` directory should look like the following when you're done:
![image](https://user-images.githubusercontent.com/1619102/38239600-1e5bf52c-3725-11e8-8622-b2075b0b1360.png)

Did you also run `postal bundle /opt/postal/vendor/bundle` and `postal upgrade`?

**Comment by igerzog** [comment]
> Did you also run postal bundle /opt/postal/vendor/bundle and postal upgrade?

Exactly. Everything was ok and Postal started normally.
