### ISSUE TITLE
Multiple Issue (pending,hard fail,queue....etc)

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#506]
Hello everyone,
I'm using good configuration server **(32 GB RAM | 2TB HDD | 64 IPs)** and i have done all possibilities to send queue mails of stuck since 7 days.
and i have follow all the previous issue related pending and hard fails and other issue of related to queues but none of it success.

You can check my previous closed issue #490 #500 #498 #501

**Issues are following;**
1 Send all the queued mails;
2 Pending mails were not deliver (#498, #287 ,#290)
3 Hard fails.
( when i send mails to it shows hard fails due to low reputation but when i send that mails with that 
domain from other build server. it successfully send and domain have all text records ex **DKIM ,SPF,DMARC** and Even my domain and IPs not blacklisted any where)

Please reply me....and give a proper guide and not reference.
Thanks

**Comment by willpower232** [comment]
Have you run `postal status` from your terminal to verify that all of Postal is running properly?

**Comment by Manishjodhani** [comment]
yes i have run postal status...there seem no error
you can see on the screen shots 
![screenshot_1](https://user-images.githubusercontent.com/28861157/36712380-7db3d1da-1bae-11e8-8a10-c9c36e053107.png)
![screenshot_2](https://user-images.githubusercontent.com/28861157/36712381-7dee92d4-1bae-11e8-9e1f-fa6f6cc99529.png)

**Comment by willpower232** [comment]
Could you send some screenshots from the top of the postal UI that shows the total in the queue and being sent etc?

**Comment by agbryenton** [comment]
I am having a similar issue. One of my colleagues did some testing when we first implemented postal and now we have 364 messages in the queue sitting at "pending". We need a way to purge them from the system. We tried deleting them manually from the messages table in the database but that didn't work and resulted in some errors.

**Comment by Manishjodhani** [comment]
Here you can check the queue in the screen-shot.
![screenshot_3](https://user-images.githubusercontent.com/28861157/36958341-09c2d2aa-2061-11e8-89d9-0100674e4161.png)

**Comment by Manishjodhani** [comment]
Here the queue.
![screenshot_4](https://user-images.githubusercontent.com/28861157/36958408-9aa09cd0-2061-11e8-8086-e9440b2484bc.png)

**Comment by willpower232** [comment]
If you're sending at 68 messages a minute, I'd presume all the messages would get sent eventually. If you are sending 0 messages a minute and you still have some queued, that would be a problem.

**Comment by Manishjodhani** [comment]
Here is another screen shot. Have a look.
![screenshot_5](https://user-images.githubusercontent.com/28861157/36970214-c1a2d3a8-208d-11e8-8536-c9d32c5e23af.png)

**Comment by willpower232** [comment]
Is this from the same page as before? Do you have other domains in your Postal sending email at the same time?

**Comment by Manishjodhani** [comment]
This is from other domain i use in postal.

**Comment by Manishjodhani** [comment]
Here you can check i'm using two other domain here another screen-shot.
Have a look on them too.

![screenshot_6](https://user-images.githubusercontent.com/28861157/36970928-2f4205bc-2090-11e8-92a3-ee298fb454f7.png)
![screenshot_7](https://user-images.githubusercontent.com/28861157/36970948-40ee6044-2090-11e8-96b8-15318ff195eb.png)

and also with different ip pools.
