### ISSUE TITLE
Having issue to integrate postal with clamav

### ISSUE THREAD

**Issue by wackoen** [atech/postal#507]
I already setup clamav. 
The problem is whenever I set 
clamav:
  enabled: true
  host: 127.0.0.1
  port: 2000

In my log /var/log/mail.log
I will get this error amavis[2261]: (02261-01) SMTP: 500 5.5.2 Error: bad syntax; detail you can see on my screenshot attach.

When this happen virus will be send to email without being filter/block.
I'm stuck. Hope I can get help from you guys.

Thank you.

<img width="1221" alt="screen shot 2018-02-23 at 6 01 21 am" src="https://user-images.githubusercontent.com/2288864/36566627-06bbc8c8-185f-11e8-8b0e-a329ff6c4f33.png">

**Comment by igerzog** [comment]
You are using amavis but not pure clamav. This is the cause.

**Comment by wackoen** [comment]
Ok will change to pure clamav. Thank you very much.
