### ISSUE TITLE
About ip rotation

### ISSUE THREAD

**Issue by ashish244268** [atech/postal#509]
Hello,

I have successfully setup everything.
I have also added ip pools.
but ips are rotation or not and after how much time?
or on what basis ips are rotating.

thanks

**Comment by ashish244268** [comment]
I have already done all this 
https://github.com/atech/postal/wiki/Configuring-IP-Pools

**Comment by phelset** [comment]
https://github.com/atech/postal/issues/104

**Comment by ashish244268** [comment]
actually I have already seen this
I have added ip pool in web interface and then also created a records and rdns for them.
also assigned that ip to a mail server 
in mail server >  settings > server settings 
also made changes in postal.yml 
and then I have sent 20 mails but all mails are going from same ip.
I am not facing any issue with email authentication  everything is working fine 
so let me know if I missed something 
if not them help in this issue
thanks

**Comment by phelset** [comment]
If you created your IP pool after the mailserver, try recreating the mailserver from scratch (eg try creating a "test" mailserver and see what happens).

**Comment by ashish244268** [comment]
yeah this trick worked 
thanks

**Comment by navinp** [comment]
After much testing I got this working today, only downsize (for me) is that a different IP will be using the same root domain, so it means that the reputation of the root domain can and will be damaged easily if one customer goes and sends spam email. (suppose it avoids Spamasassin, which I have seen happening with phishing emails)

An ideal situation would be different IP and also different hostname ... I suppose having multiple Postal's running on different vps's would be a solution for this :/

**Comment by gitaayush** [comment]
@navinp  what is the hostname part in the IP pools ? Is it domain name or hostname of the postal server ?
should i add domain name in the hostname part in IP pools ? I am confused.

**Comment by bakgaard** [comment]
> @navinp what is the hostname part in the IP pools ? Is it domain name or hostname of the postal server ?
> should i add domain name in the hostname part in IP pools ? I am confused.

I'd like an answer for this too.

**Comment by willpower232** [comment]
@bakgaard have a look at #1329
