### ISSUE TITLE
Need Domains & DNS Configuration help

### ISSUE THREAD

**Issue by khalidelmerrah** [atech/postal#517]
Hello postal team

i need help configuring the domain and dns configuration, i'm using google cloud created the vm, and set up the ubuntu 16, everything is great but i can't configure the postal.yml file, what to use for those records.
i'm gonna use this domain : travelsize.co provided by godaddy.

so what should i put and where should i put it.

this is the internal ip :  10.164.0.* 
this is the external ip :  35.204.133.1**

please instruct me what to do. thank you

**Comment by willpower232** [comment]
If your VM can only see the 10.* address, use that in `postal.yml`.

Your DNS records should always point at your external IP address.

**Comment by khalidelmerrah** [comment]
@willpower232  thank you bro i got it now.
