### ISSUE TITLE
any idea for ban?

### ISSUE THREAD

**Issue by theraw** [atech/postal#526]
If you start to publish your email ppl will start spamming for no reason.

Does anyone here have any idea how to ban those? i think it will be a good idea if postal can have a `deny` method for `@domain.com` wildcard or single `user@domain.com`

however i haven't seen a email service who have a way to ban like this (even paid ones). so if this is not possible please don't take me as an idiot because i don't know too much about emails :joy: 

thanks

i have think ex ban ip. idk if this work but i was just thinking about it so even if it works it will not be good because some ppl use shared hosting for emails and if you ban their ip then you've deny everyone from that host :confused:

**Comment by willpower232** [comment]
I believe at the minute you would have to filter the incoming email in your application outside of Postal but it could be handy if the incoming routes/webhooks could be set to only accept certain email addresses.

IP address blocking wouldn't work so well as it would cause more problems but you could always firewall out certain IP addresses to see if that helps you.

**Comment by theraw** [comment]
well thank you for info
