### ISSUE TITLE
How to receive en forward email? 

### ISSUE THREAD

**Issue by xoco70** [atech/postal#53]
Hi, 

What I want and can't achieve is receive an email from an external system, and forward it to another email. 

I understand postal has no IMAP / POP, but forwarding is great enough for me.

As you know, there is not so much free emails that allow you to use custom domain, so this would be my use case. Also would use it to blacklist emails and optimize bounce rate.

Now, I try to create the email : test@kendozone.com

When an external system send an email to test@kendozone.com, it should be redirected to : another_real@email.com

I Created an address Endpoint : another_real@email.com

Then I created a route: 
Name : test@kendozone.com
Endpoint: another_real@email.com

My MX Domain is green : mx.mail.kendozone.com

But when I send an email from Mac Mail, I get : `550 5.1.1 <test@kendozone.com> User unknown`

What am I forgetting?

**Comment by adamcooke** [comment]
Probably a DNS cache. That error isn't from the Postal SMTP server.

**Comment by adamcooke** [comment]
Looking at the DNS for `kendozone.com` you have two MX records. One for `mx.zoho.com` and another for `mx.mail.kendozone.com`. A message could be sent to either of these servers.

**Comment by xoco70** [comment]
Can't I use both? I actually use zoho to send my emails, I would love to replace it with Postal, but I wouldn't like to interrupt system.

**Comment by xoco70** [comment]
Ok, I deleted my olds MX records. I will wait now...

**Comment by xoco70** [comment]
When I make a try in Send Message > Incoming, I get : 

```
550-Verification failed for <wxsqjq@psrp.kendozone.com> 550-The mail server could not deliver mail to wxsqjq@psrp.kendozone.com. The account or domain may not exist, they may be blacklisted, or missing the proper dns entries. 550 Sender verify failed
Time: 0.42s
Support Ref: ZDDCWXVX
```

In DNS, I have : `psrp CNAME rp.mail.kendozone.com`

So it should be ok.

**Comment by mattmartincouk** [comment]
Your DNS is broken/wrong/incorrect.

pob:~$ host psrp.kendozone.com
pob:~$

That does not resolve to anything, which is probably why you're getting that error.
