### ISSUE TITLE
Putting a max number of messages per month per organisation

### ISSUE THREAD

**Issue by navinp** [atech/postal#531]
Hello,

I'm very new to Postal and really loving it <3 

I just couldn't figure out how to put a monthly Send cap on organisations, for example maximum 10.000 messages per month for a organisation. So on a monthly basis the particular organisation could only send max 10,000 messages. 

I have only seen the option for an hourly Send limit.

**Comment by willpower232** [comment]
Please see https://github.com/atech/postal/issues/361
