### ISSUE TITLE
failed restarting nginx ... what should i do ? 

### ISSUE THREAD

**Issue by khalidelmerrah** [atech/postal#534]
hello Github,

i couldn't restart nginx, i had this issue many many times, and followed several tutorials, this time i followed this one : [How to Create a Fully Featured Mail Server using Postal](https://www.howtoforge.com/tutorial/how-to-create-a-fully-featured-mail-server-using-postal/)

please tell me what to do i'm not a sysadmin but i really need postal

```
root@postal:~# systemctl restart nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl  status nginx.service" and "journalctl  -xe" for details.
root@postal:~# ^C
root@postal:~# systemctl  status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-03-22 20:32:19 UTC; 4min 41s ago
     Docs: man:nginx(8)
  Process: 12252 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, s
 Main PID: 11515 (code=exited, status=0/SUCCESS)
      CPU: 11ms

Mar 22 20:32:19 postal systemd[1]: Starting A high performance web server and a reverse proxy server
Mar 22 20:32:19 postal nginx[12252]: nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/mail.nasdail
Mar 22 20:32:19 postal nginx[12252]: nginx: configuration file /etc/nginx/nginx.conf test failed
Mar 22 20:32:19 postal systemd[1]: nginx.service: Control process exited, code=exited status=1
Mar 22 20:32:19 postal systemd[1]: Failed to start A high performance web server and a reverse proxy
Mar 22 20:32:19 postal systemd[1]: nginx.service: Unit entered failed state.
Mar 22 20:32:19 postal systemd[1]: nginx.service: Failed with result 'exit-code'.
```

**Comment by willpower232** [comment]
At a glance I would say that it seems your certificate file is missing. Please try running `nginx -t` and reply with the output to confirm what is wrong.

**Comment by khalidelmerrah** [comment]
i did install let's Encrypt certificate but doesn't seem to exist when i checked through the ftp ... and the command u asked for :

`root@postal:~# nginx -t
nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/mail.nasdaily.us/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/mail.nasdaily.us/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed
`

**Comment by willpower232** [comment]
I would imagine the certbot process did not complete successfully. If you re run the command it should tell you what went wrong or if it succeeded.

The instructions you linked to are not official but I believe its possible that you need to stop the nginx service before trying the standalone method from certbot.

**Comment by khalidelmerrah** [comment]
i just checked the dns settings was incorrect, now after restarting nginx successfully i get a 502 Bad Gateway
nginx/1.12.1 (Ubuntu)

how to debug or find out the problem please ? thank you

**Comment by khalidelmerrah** [comment]
here is what the log says about nginx : 

`rsa-key-20180313@postal:~$ tail -f /var/log/nginx/error.log
2018/03/22 21:12:26 [error] 2366#2366: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 105.154.22.154, server: mail.nasdaily.us, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "35.196.143.7"
2018/03/22 21:12:54 [notice] 2410#2410: signal process started
2018/03/22 21:12:57 [error] 2411#2411: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 105.154.22.154, server: mail.nasdaily.us, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "35.196.143.7"
2018/03/22 21:13:07 [error] 2411#2411: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 105.154.22.154, server: mail.nasdaily.us, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "mail.nasdaily.us"
2018/03/22 21:16:58 [error] 2411#2411: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 105.154.22.154, server: mail.nasdaily.us, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "mail.nasdaily.us"
2018/03/22 21:17:00 [error] 2411#2411: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 105.154.22.154, server: mail.nasdaily.us, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "mail.nasdaily.us"
2018/03/22 21:17:02 [error] 2411#2411: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 105.154.22.154, server: mail.nasdaily.us, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "mail.nasdaily.us"
2018/03/22 21:17:18 [error] 2411#2411: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 105.154.22.154, server: mail.nasdaily.us, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "mail.nasdaily.us"
2018/03/22 21:18:25 [error] 2411#2411: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 105.154.22.154, server: mail.nasdaily.us, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "mail.nasdaily.us"
2018/03/22 21:20:17 [error] 1093#1093: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 105.154.22.154, server: mail.nasdaily.us, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "mail.nasdaily.us"`

**Comment by willpower232** [comment]
502 means that postal is not running or is not accessible to nginx.

Run `postal status` to verify what is happening.

**Comment by khalidelmerrah** [comment]
yess thank you so much, postal wasn't running, quick question i need to use other port other than 25, for sending, since this is a test envirement on google cloud i want to use it for now .. how can i change the port ? from postal.yml ? or other configuration file 

will this help ? 
`iptables -t nat -A PREROUTING  -p tcp --dport 25 -j DNAT --to-destination IP_OF_EXTERNAL_MTA:2525
`

**Comment by willpower232** [comment]
iptables will help you if you want to run on both 2525 and 25 simultaneously, have a look at https://github.com/atech/postal/issues/212#issuecomment-306161864

If you want to run only on 2525, you will have to set that in your postal.yml, here is the default value: https://github.com/atech/postal/blob/master/config/postal.defaults.yml#L67

If google cloud will not let you connect to your Postal server on port 25 then iptables is your answer.

If your postal cannot send emails for a similar reason, you can ignore the iptables and just change the config.
