### ISSUE TITLE
Error adding domain!

### ISSUE THREAD

**Issue by sidneydevelop** [atech/postal#537]
I installed the postal, according to procedure, I added my organization and my mail server, when I add a domain is generating the following error https://snag.gy/qLJdoI.jpg! can anybody help me? already had set up another postal without problems.

**Comment by willpower232** [comment]
You will have to check the files in `/opt/postal/log` to find out what the issue is.

**Comment by sidneydevelop** [comment]
@willpower232 Thanks for answering me!
I was already checking the logs but I could not locate this problem yet, I found it very strange, because the whole system is working, until the time to add the domain! I'll try to look for something, if you have any idea what I can do to guide me! Thank you.

**Comment by sidneydevelop** [comment]
@willpower232 I was able to solve it, it was some configuration in the dns part, I re-made the settings and it worked!
Can you tell me how to send an email to the user of an organization where I added it? It looks like it does not send the email to the user!

**Comment by willpower232** [comment]
If you've added a user to an organisation, you'll have to communicate with them directly. Postal doesn't have welcome emails or anything like that. If you want Postal to send an email, you have to configure your application to send from it.

**Comment by navinp** [comment]
@willpower232 you mean it only sends the email with the verification url ? 

@sidneydevelop is this what you meant? You could change the text ...

**Comment by sidneydevelop** [comment]
@willpower232 @navinp Yes, I'm talking about the verification URL, I was able to work with only the SMTP data from sendgrid, I'm not able to use the sending of the URL by the server itself.
I have done all the settings of SPF, DKIM, he is doing the shipments without problems, my question and when I create a mail server and I use the credentials inside the postal.yml he is not doing the sending.
I'm doing the configuration tests with this command postal test-app-smtp myemail

**Comment by sidneydevelop** [comment]
about adding domains I could fix by redoing the dns configuration in postal.yml
