### ISSUE TITLE
Create users for organization

### ISSUE THREAD

**Issue by sidneydevelop** [atech/postal#538]
Where can I set up for the postal to send the email when I create the users of each organization?

**Comment by navinp** [comment]
@sidneydevelop are you testing this with a Gmail-address? 

Have you added the dns part and the smtp part? And also taken care of the dkim, spf etc?

**Comment by willpower232** [comment]
https://github.com/atech/postal/issues/537#issuecomment-375872095

Postal doesn't send welcome emails or anything like that, if you want Postal to send an email you have to tell it what to send.

**Comment by sidneydevelop** [comment]
Yes, I'm talking about the verification URL, I was able to work with only the SMTP data from sendgrid, I'm not able to use the sending of the URL by the server itself.
I have done all the settings of SPF, DKIM, he is doing the shipments without problems, my question and when I create a mail server and I use the credentials inside the postal.yml he is not doing the sending.
I'm doing the configuration tests with this command postal test-app-smtp myemail

**Comment by willpower232** [comment]
Ah right I see. Have you specified a way for Postal to send emails in postal.yml?
