### ISSUE TITLE
Messages Not Tried

### ISSUE THREAD

**Issue by longhorninmd** [atech/postal#544]
Continue to see messages in queue from two days ago that haven't even been tried.  This is why it's very hard to take Postal seriously as an MTA.  As good as the UI looks, it doesn't delivery (pun intended) on the back end.  When you mention Mailgun, SendGrid and other cloud delivery platforms and mail in queue isn't even tried for no reason whatsoever?  Pretty shaky IMO...

**Comment by longhorninmd** [comment]
What is your volume?  

Our server spec is more than what should be sufficient: 32GB RAM, multiple CPUs, 640 SSD.

**Comment by willpower232** [comment]
We're handling up to 3000 daily with 8 workers and a few GB of RAM. Have you increased your worker count?

**Comment by adamcooke** [comment]
Works fine for us too. There shouldn't be emails just in the queue that have no delivery attempts or aren't locked. Perhaps provide some details and we can take a look.

**Comment by longhorninmd** [comment]
Do you guys realize you’re working with a minuscule volume?  When you compare to Mailgun et al, they are doing many millions per day.

**Comment by willpower232** [comment]
I'm not going to debate email sending platforms here. If you would like some help, please send some screenshots of the issues you're experiencing otherwise this will be my last reply to this issue.

**Comment by adamcooke** [comment]
As you say, this could well be minuscule volume compared with other platforms. These other platforms have dedicated teams working on them with direct access to the servers actually processing the mail so can investigate issues. Postal was built to solve a purpose for us. It does that very nicely. If it doesn't work for you out of the box, then you may need to look elsewhere. :(
