### ISSUE TITLE
Ability to configure DNS nameservers

### ISSUE THREAD

**Issue by stayallive** [atech/postal#55]
It would be great to use be able to configure DNS servers or a switch to use the system nameservers instead of directly querying the domain' nameservers since on a few networks outgoing DNS traffic is blocked causing domain checks to fail (even causing 502's since it takes forever to timeout).

**Comment by adamcooke** [comment]
As far as I know, the only place the domains nameservers are directly queries is on verification and testing of domains. They shouldn't be used directly on lookups for sending messages.

For verification and DNS testing it is rather annoying when there's a cache involved because it causes delays getting domains verified quickly.

**Comment by stayallive** [comment]
I 100% agree, but as mentioned there are network restrictions that make it impossible to do this 😞 
 Only a few nameservers are accessible over IPv4. That's why it would be really great if (ofcourse optionally) it would be possible to define the nameservers to use for the domain validation.

Right now the validation just runs indefinitly since it never seems te timeout, then waiting for the cache would definitly be an improvement 😉 

Ofcourse I can change the source code myself and just return a hardcoded array but I can imagine others might have similair conditions or are running some other nameserver internally that must take precedense in an enterprise environment.

But if you feel it is not a good fit for this project also 👍  ofcourse 😄

**Comment by dattaproffs** [comment]
Agree with @stayallive it would be great if we could set the servers for the domain validation in postal.yml
I have a local developement evironment with end to end email workflow with only *.local domains and local dns servers handling that.

**Comment by adamcooke** [comment]
This is now supported by setting the following in the config file:

```
general:
  use_local_ns_for_domains: true
```

**Comment by mingfang** [comment]
I'm running Postal inside Kubernetes and the ```use_local_ns_for_domains: true``` flag was needed for DNS to work. Thanks.

**Comment by badihi** [comment]
For people struggling with kubernetes environment dns settings coming here, additional to what @mingfang mentioned, I had to add the following settings to the pod in order to make domain verification work:

```
dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
```
