### ISSUE TITLE
Install Ruby 2.3 - Ubuntu 18

### ISSUE THREAD

**Issue by ajsb85** [atech/postal#550]
ppa:brightbox/ruby-ng does not support bionic (Ubuntu 18)
No plan to update Ruby 2.?

Reference: #549

**Comment by willpower232** [comment]
Ubuntu 18.04 isn't released or stable until 26th April 2018 so its unlikely much will support it until after that date.

**Comment by adamcooke** [comment]
This sounds like an issue with the Brightbox PPA and not yet supporting 18.04. I doubt they'll support it until it's actually released.
