### ISSUE TITLE
Can't connect to MySQL server

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#551]
Whenever i start the postal and then rails logs show this.
[web.1:1999] [2018-03-30T12:24:34.045] INFO -- : Completed 500 Internal Server Error in 1ms
[web.1:1999] [2018-03-30T12:24:34.046] FATAL -- :   
[web.1:1999] [2018-03-30T12:24:34.046] FATAL -- : Mysql2::Error (Can't connect to MySQL server on '127.0.0.1' (111)):
[web.1:1999] [2018-03-30T12:24:34.047] FATAL -- :   
[web.1:1999] [2018-03-30T12:24:34.047] FATAL -- : app/controllers/application_controller.rb:76:in `append_info_to_payload'

and the status of postal 
postal status
Procodile Version   1.0.18
Application Root    /opt/postal/app
Supervisor PID      1993
Started             2018-03-30 12:11:02 +0000

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      12:11        pid:1999     respawns:0      port:-        tag:-

|| worker
|| Quantity            2
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.11        Running      12:29        pid:4229     respawns:0      port:-        tag:-
|| => worker.12        Running      12:29        pid:4231     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.4           Running      12:29        pid:4245     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      12:26        pid:3759     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.4       Running      12:29        pid:4238     respawns:0      port:-        tag:-

Please help me out??

**Comment by willpower232** [comment]
If you can't connect to MySQL, you should make sure that it is running and that you have put the correct details for the MySQL server and password in postal.yml.
