### ISSUE TITLE
can't run postal bundle 

### ISSUE THREAD

**Issue by khalidelmerrah** [atech/postal#552]
when i try to install the ruby dependencies it shows this problem.. what could have gone wrong .. thank you
```
root@localhost:~# su - postal postal bundle /opt/postal/vendor/bundle
ruby: error while loading shared libraries: libruby.so.2.4: cannot open shared object file: No such file or directory
root@localhost:~#
```

**Comment by willpower232** [comment]
You should verify that ruby has been installed correctly. Can you try running `which ruby` to see if and where it is installed?

**Comment by khalidelmerrah** [comment]
no problems occurred during the installation and this is the informations you requested : 

```
root@localhost:~# which ruby
/usr/local/rvm/rubies/ruby-2.4.1/bin/ruby
root@localhost:~# rvm -v
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
```

**Comment by willpower232** [comment]
Ah I'm not sure how well this works with rvm, I thought this had been discussed somewhere but I can't see it.

You could try switching into the postal user (e.g. `sudo -iu postal`) and seeing if it can run any ruby commands to prove it works for the user.

Failing that, the only other thing which might be related is whether the version of ruby has been chosen as default.

**Comment by khalidelmerrah** [comment]
whenever i run a ruby command on postal user it gives a warning : 

```
root@localhost:~# sudo -iu postal
postal@localhost:~$ rvm
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.4.1/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.4.1'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
Ruby enVironment Manager 1.29.3 (latest) (c) 2009-2017 Michal Papis, Piotr Kuczynski, Wayne E. Seguin

Usage:

    rvm [--debug][--trace][--nice] <command> <options>

  for example:

    rvm list                # list installed interpreters
    rvm list known          # list available interpreters
    rvm install <version>   # install ruby interpreter
    rvm use <version>       # switch to specified ruby interpreter
    rvm remove <version>    # remove ruby interpreter
    rvm get <version>       # upgrade rvm: stable, master

Available commands:
```

**Comment by willpower232** [comment]
Whilst your root user is set up for rvm, I doubt the postal user is hence the error. Can you actually run `ruby` as postal?

Is there any reason you aren't using actual ruby?

**Comment by khalidelmerrah** [comment]
the reason why i wasn't using ruby directly is i didn't know that rvm and  ruby aren't the same thing, now i rested my vps and reinstalled following the instruction on your wiki and now everything works smoothly .. thanks will for all the support
