### ISSUE TITLE
Documentation Problem

### ISSUE THREAD

**Issue by longhorninmd** [atech/postal#553]
<img width="716" alt="screen shot 2018-03-30 at 3 33 46 pm" src="https://user-images.githubusercontent.com/133784/38151111-e48217fc-342f-11e8-9246-cfbbe6d0b7ad.png">

I believe you guys mean 5.x.x errors will fail immediately, not 4xx which are temporary...

**Comment by willpower232** [comment]
Good spot, furthermore it seems Ruby will only throw the appropriate hard fail error when its a 5xx code that isn't 500.

https://github.com/atech/postal/blob/master/lib/postal/smtp_sender.rb
https://ruby-doc.org/stdlib-2.3.0/libdoc/net/smtp/rdoc/Net/SMTPFatalError.html

**Comment by willpower232** [comment]
https://github.com/atech/postal/wiki/HTTP-Payloads

**Comment by adamcooke** [comment]
Thanks. Fixed.
