### ISSUE TITLE
Activity via the message ID via the HTTP API

### ISSUE THREAD

**Issue by gordienko** [atech/postal#554]
Thank you for the wonderful platform! 

Is it possible to receive data on the activity via the message ID via the HTTP API? Interested in the events of  open and click.

**Comment by willpower232** [comment]
Hopefully you found the Click Tracking and Webhook pages in the Wiki

https://github.com/atech/postal/wiki/Click-&-Open-Tracking
https://github.com/atech/postal/wiki/Webhook-Events-&-Payloads

**Comment by ilyacherevkov** [comment]
I have FBL configured, and I receive abuse reports in .eml which contain strings like:

`Message-ID: <adbeab88-0d24-6feb-7e3e-2afe47d65c16@example.com>`

So I've wrote a script which gives me exact message_ids from bunch of raw .eml fiiles.: 

```
message_ids = []
stdin, stdout, stderr = Open3.popen3('grep "Message-ID:\| @example.com" *.eml')

until (line = stdout.gets).nil? do
  message_ids << line[/(?<=[<])[^>]*/]
end
```

Now I want to query postal API https://atech.github.io/postal-api/controllers/messages/message.html to get emails,  but it looks like only 'Id' is accepted as parameter.

Looks like i need to query DB directly.

**Comment by willpower232** [comment]
@ilyacherevkov when you send messages using the Postal API, you should get `Message-ID`'s and numeric IDs for the messages you have sent returned to you in your application so you can store those for later reference.

If you are still having problems, please open a new issue.
