### ISSUE TITLE
Documentation inconsistency Tracking domain: DNS/ipv6 breaks letsencrypt

### ISSUE THREAD

**Issue by arendvw** [atech/postal#555]
The [domains and dns configuration ](https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration) page shows the following configuration (both ipv4 and ipv6)

```
track.mail.yourdomain.com.    IN    A     192.168.0.4
track.mail.yourdomain.com.    IN    AAAA  2a00:1234:abcd:1::4
```

However, nowhere in the example files is listed that you actually require to add two ip's to `config/postal.yml` (also, the ipv6 address needs to be in quotes). Which is not a very trivial thing to figure out.

```
fast_server:
  enabled: true
  bind_address:
    - 6.7.8.9
    - "xxx:yyyy:zzz:ffff::2"
```

Having non functional ipv6 address will break let'sencrypt (see #529), which may decide to look up the ipv6 address instead of the ipv4 address.

I think it's a good idea to add the ipv6 example to the example config (or default config, as a comment).

**Comment by willpower232** [comment]
Good spot, this would definitely be an issue if your server sees its IPv6 address from a separate adapter which depends entirely on how your server company provides network connections to its servers.

**Comment by adamcooke** [comment]
I've updated the example config file about this. Thanks!
