### ISSUE TITLE
Allow additional content in webhooks

### ISSUE THREAD

**Issue by theratris** [atech/postal#56]
This may be outside the scope of a webhook, but it would be cool to be able to customize the contents of the request body. It would allow nifty features like posting to a Slack or Discord channel when there is a failure event without setting up another server to bridge the two.

**Comment by adamcooke** [comment]
I think this is likely outside the scope of the webhook. I think if you want to intergrate with other services like Slack, you will need to create a small service to accept the webhook from Postal and then re-format it for consumption elsewhere.
