### ISSUE TITLE
SMTP stopped working

### ISSUE THREAD

**Issue by navinp** [atech/postal#562]
Hello,

Everything was working fine, but it stopped since yesterday (discovered it today)

Emails are not being send. 

> root@domain:~# postal status
Procodile Version   1.0.18
Application Root    /opt/postal/app
Supervisor PID      2294
Started             2018-04-10 12:59:07 +0000

 * fast.4 is not running (Failed)
 * smtp only has 2 instances (should have 1)
 * smtp.4 is not running (Failed)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      12:59        pid:2300     respawns:0      po                                                                                        rt:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.4           Failed       13:17        pid:3172     respawns:5      po                                                                                        rt:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.4         Running      13:17        pid:3055     respawns:0      po                                                                                        rt:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.4           Running      13:17        pid:3067     respawns:0      po                                                                                        rt:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.3           Stopped      13:17        pid:3160     respawns:5      po                                                                                        rt:-        tag:-
|| => smtp.4           Failed       13:17        pid:3174     respawns:5      po                                                                                        rt:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.4       Running      13:17        pid:3069     respawns:0      po                                                                                        rt:-        tag:-
root@domain:~#

**Comment by willpower232** [comment]
Can you try stopping Postal and then running `setcap` from here: https://github.com/atech/postal/wiki/Installation#preparing-your-operating-system

**Comment by navinp** [comment]
I stopped the Postal using postal stop

After that I ran the line: 
> sudo setcap 'cap_net_bind_service=+ep' /usr/bin/ruby2.3

Don't know if it did anything, after that **postal restart** 

> root@domain:~# postal status
Procodile Version   1.0.18
Application Root    /opt/postal/app
Supervisor PID      3925
Started             2018-04-10 14:04:26 +0000

> * fast.2 is not running (Failed)
 * smtp only has 2 instances (should have 1)
 * smtp.2 is not running (Failed)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      14:04        pid:3931     respawns:0      port:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.2           Failed       14:09        pid:4253     respawns:5      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.2         Running      14:09        pid:4158     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.2           Running      14:09        pid:4172     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Stopped                   pid:4025     respawns:5      port:-        tag:-
|| => smtp.2           Failed       14:09        pid:4255     respawns:5      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.2       Running      14:09        pid:4173     respawns:0      port:-        tag:-
root@domain:~#

**Comment by navinp** [comment]
Here's the output:

root@domain:~# netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State                                                                                               PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN                                                                                              1574/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN                                                                                              2253/master
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN                                                                                              1727/nginx -g daemo
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN                                                                                              3931/[postal] web.1
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN                                                                                              1545/beam.smp
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN                                                                                              1984/mysqld
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN                                                                                              1727/nginx -g daemo
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN                                                                                              1729/epmd
tcp6       0      0 :::22                   :::*                    LISTEN                                                                                              1574/sshd
tcp6       0      0 :::25                   :::*                    LISTEN                                                                                              2253/master
tcp6       0      0 :::443                  :::*                    LISTEN                                                                                              1727/nginx -g daemo
tcp6       0      0 :::5672                 :::*                    LISTEN                                                                                              1545/beam.smp
tcp6       0      0 :::80                   :::*                    LISTEN                                                                                              1727/nginx -g daemo
tcp6       0      0 :::4369                 :::*                    LISTEN                                                                                              1729/epmd
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    P                                                                                        ath
unix  2      [ ACC ]     STREAM     LISTENING     17685    2253/master         p                                                                                        rivate/tlsmgr
unix  2      [ ACC ]     STREAM     LISTENING     17688    2253/master         p                                                                                        rivate/rewrite
unix  2      [ ACC ]     STREAM     LISTENING     17691    2253/master         p                                                                                        rivate/bounce
unix  2      [ ACC ]     STREAM     LISTENING     17694    2253/master         p                                                                                        rivate/defer
unix  2      [ ACC ]     STREAM     LISTENING     17697    2253/master         p                                                                                        rivate/trace
unix  2      [ ACC ]     STREAM     LISTENING     20038    2480/systemd        /                                                                                        run/user/0/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     17700    2253/master         p                                                                                        rivate/verify
unix  2      [ ACC ]     SEQPACKET  LISTENING     8145     1/init              /                                                                                        run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     17703    2253/master         p                                                                                        ublic/flush
unix  2      [ ACC ]     STREAM     LISTENING     17706    2253/master         p                                                                                        rivate/proxymap
unix  2      [ ACC ]     STREAM     LISTENING     17709    2253/master         p                                                                                        rivate/proxywrite
unix  2      [ ACC ]     STREAM     LISTENING     17712    2253/master         p                                                                                        rivate/smtp
unix  2      [ ACC ]     STREAM     LISTENING     17715    2253/master         p                                                                                        rivate/relay
unix  2      [ ACC ]     STREAM     LISTENING     17718    2253/master         p                                                                                        ublic/showq
unix  2      [ ACC ]     STREAM     LISTENING     17721    2253/master         p                                                                                        rivate/error
unix  2      [ ACC ]     STREAM     LISTENING     17724    2253/master         p                                                                                        rivate/retry
unix  2      [ ACC ]     STREAM     LISTENING     17727    2253/master         p                                                                                        rivate/discard
unix  2      [ ACC ]     STREAM     LISTENING     17730    2253/master         p                                                                                        rivate/local
unix  2      [ ACC ]     STREAM     LISTENING     17733    2253/master         p                                                                                        rivate/virtual
unix  2      [ ACC ]     STREAM     LISTENING     17736    2253/master         p                                                                                        rivate/lmtp
unix  2      [ ACC ]     STREAM     LISTENING     17739    2253/master         p                                                                                        rivate/anvil
unix  2      [ ACC ]     STREAM     LISTENING     17742    2253/master         p                                                                                        rivate/scache
unix  2      [ ACC ]     STREAM     LISTENING     17745    2253/master         p                                                                                        rivate/maildrop
unix  2      [ ACC ]     STREAM     LISTENING     17748    2253/master         p                                                                                        rivate/uucp
unix  2      [ ACC ]     STREAM     LISTENING     17751    2253/master         p                                                                                        rivate/ifmail
unix  2      [ ACC ]     STREAM     LISTENING     8135     1/init              /                                                                                        run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     17754    2253/master         p                                                                                        rivate/bsmtp
unix  2      [ ACC ]     STREAM     LISTENING     17757    2253/master         p                                                                                        rivate/scalemail-backend
unix  2      [ ACC ]     STREAM     LISTENING     8139     1/init              /                                                                                        run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     17760    2253/master         p                                                                                        rivate/mailman
unix  2      [ ACC ]     STREAM     LISTENING     8143     1/init              /                                                                                        run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     8152     1/init              /                                                                                        run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     40222    3925/app)           /                                                                                        tmp/postal/pids/procodile.sock
unix  2      [ ACC ]     STREAM     LISTENING     17496    1984/mysqld         /                                                                                        var/run/mysqld/mysqld.sock
unix  2      [ ACC ]     STREAM     LISTENING     13422    1/init              /                                                                                        var/lib/lxd/unix.socket
unix  2      [ ACC ]     STREAM     LISTENING     16268    1870/php-fpm.conf)  /                                                                                        run/php/php7.0-fpm.sock
unix  2      [ ACC ]     STREAM     LISTENING     13418    1/init              /                                                                                        run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     13419    1/init              /                                                                                        run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     13420    1/init              /                                                                                        run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     13421    1/init              /                                                                                        run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     11992    1499/iscsid         @                                                                                        ISCSIADM_ABSTRACT_NAMESPACE
unix  2      [ ACC ]     STREAM     LISTENING     13423    1/init              /                                                                                        var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     17674    2253/master         p                                                                                        ublic/pickup
unix  2      [ ACC ]     STREAM     LISTENING     17678    2253/master         p                                                                                        ublic/cleanup
unix  2      [ ACC ]     STREAM     LISTENING     17681    2253/master         p                                                                                        ublic/qmgr
root@domain:~#

**Comment by navinp** [comment]
Github is generating those strikethroughs -_-

**Comment by navinp** [comment]
I am not running any other applications on this server, just Postal. 

I didn't touch the server since yesterday, when it stopped working (and I discovered this just today)

So I have no idea :/

**Comment by navinp** [comment]
I also don't understand: 
Sending Test messages from the interface works fine 

But when I go to for example the Reset pw page and try to reset my pw to see if emails are being sent, I get this:

> We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by willpower232** [comment]
Your netstat suggests you are running postfix mail server and PHP which means your server is obviously doing other things.

If you stop, disable, or remove Postfix, that should alleviate some of your problems.

**Comment by navinp** [comment]
I uninstalled Postfix, it seems to be working now. 

Thanks very much.

**Comment by navinp** [comment]
Even though SMTP is working now, I get this (maybe after uninstalling php this will go better)

root@domain:~# postal status
Procodile Version   1.0.18
Application Root    /opt/postal/app
Supervisor PID      2282
Started             2018-04-10 14:42:09 +0000

 * fast.2 is not running (Failed)
 * smtp only has 2 instances (should have 1)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      14:42        pid:2288     respawns:0      port:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.2           Failed       16:19        pid:4721     respawns:5      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.2         Running      16:19        pid:4641     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.2           Running      16:19        pid:4656     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Stopped                   pid:2378     respawns:0      port:-        tag:-
|| => smtp.2           Running      16:19        pid:4647     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.2       Running      16:19        pid:4657     respawns:0      port:-        tag:-
root@domain:~#

**Comment by navinp** [comment]
Okay, here's another update:
I removed php-fpm following the instructions found in this article: https://www.howtoinstall.co/en/ubuntu/xenial/php-fpm?action=remove

This is the result (think everything is working now):

root@domain:~# postal status
Procodile Version   1.0.18
Application Root    /opt/postal/app
Supervisor PID      2282
Started             2018-04-10 14:42:09 +0000

 * fast.3 is not running (Failed)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      14:42        pid:2288     respawns:0      port:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.3           Failed       18:09        pid:6695     respawns:5      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.3         Running      18:09        pid:6626     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.3           Running      18:09        pid:6640     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.2           Running      18:09        pid:6632     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.3       Running      18:09        pid:6641     respawns:0      port:-        tag:-
root@domain:~#

**Comment by willpower232** [comment]
The fast server is for click tracking so if you don't have a second IP on your server to use for the click tracking, you should probably disable it in postal.yml to make the error go away.

**Comment by navinp** [comment]
Thanks a lot for the support man, much appreciated
