### ISSUE TITLE
No SMTP servers were available for xxxx

### ISSUE THREAD

**Issue by CrazyWr** [atech/postal#564]
hey, guys, thanks to provide  this great product, and  I have a problem using this, I can't send any emails.

postal.yml:
![image](https://user-images.githubusercontent.com/19635808/38664816-42012994-3e6d-11e8-88f1-e9062a25b7ba.png)

postal status:
`=> web.1            Running      06:19        pid:24346    respawns:0      port:-        tag:- `
`=> worker.10        Running      08:07        pid:32064    respawns:0      port:-        tag:-`
`=> cron.10          Running      08:07        pid:32075    respawns:0      port:-        tag:-`
`=> smtp.1           Running      08:07        pid:32067    respawns:0      port:-        tag:-`
`=> requeuer.10      Running      08:07        pid:32074    respawns:0      port:-        tag:-`

DNS:
![image](https://user-images.githubusercontent.com/19635808/38664792-2e5407c2-3e6d-11e8-9bcf-d3be9b48a7ad.png)

I got `Message has been sent successfully.` when I test smtp server by `postal test-app-smtp wei.aaron.sky@gmail.com`

but  I got `No SMTP servers were available for xxxx` when I test send email in website , like xxx@qq.com, xxx@gmail.com 
![image](https://user-images.githubusercontent.com/19635808/38664971-bfb46a18-3e6d-11e8-8abd-7e4788cfea10.png)

so, I don't know what's is wrong , please help me!

I think it's `Routing config` but I don't know about how it works.

**Comment by willpower232** [comment]
It might be that your server provider prevents your server from outbound SMTP connections, are you able to verify that first?

Also have you enabled any sort of firewall limiting outbound traffic?

**Comment by CrazyWr** [comment]
![image](https://user-images.githubusercontent.com/19635808/38669134-29a1ff58-3e78-11e8-9716-6a71fab9385a.png)
telnet success!
It's a new digital ocean server, the firewalls is clean, 
![image](https://user-images.githubusercontent.com/19635808/38669817-ce2de626-3e79-11e8-90c9-94cb037f30bf.png)

**Comment by willpower232** [comment]
Ah if you're using Digital Ocean and your account is brand new with them, you will need to contact them to allow sending of emails, see https://github.com/atech/postal/issues/541#issuecomment-377177814

**Comment by catphish** [comment]
Did you test outbound SMTP with telnet? Did you resolve this?

**Comment by saporus** [comment]
Hello,

I am having issue related to this, all mails sent to yahoo are not going through via one of my mailing servers on postal, I keep on getting error as seen in the screen shot. I have about 4 mailserver in postal, I have tried with another mailserver on same postal installation and there was no error.

Those IP's are on same postal server installation, I am having issue with one of the mailservers because I have just tested it with 16k subscribers but I have been getting softfail with error message No SMTP servers were available for xxxx

![image](https://user-images.githubusercontent.com/47196230/52166085-39d59b80-2709-11e9-89a8-0281ceeba795.png)

Any help?

Thanks

**Comment by raiyansarker** [comment]
I am having the same problem but I am using AWS. What can I do now?

**Comment by libracoder** [comment]
> I am having the same problem but I am using AWS. What can I do now?

Did you eventually fix this?

**Comment by willpower232** [comment]
Please don't comment on long-closed issues and feel free to open a new one.

That said, you will see from numerous issues that many server providers must give permission for messages to be sent so that is likely the best place to start.
