### ISSUE TITLE
Quick Install SSL Issue 

### ISSUE THREAD

**Issue by rccess** [atech/postal#566]
Quick install not working due to ssl expiry 

Please check and fix it

**Comment by willpower232** [comment]
Hopefully they'll be able to fix the certificate shortly but in the meantime, you could always clone the repo.

The change to the instructions looks a little like this https://github.com/atech/postal/commit/525fd8cc05fe2c866e0e4143a6a8273acd449382#diff-b43de171c710873f5067c6d50d2cfb99

**Comment by rccess** [comment]
can i get direct url like this  

curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh

**Comment by willpower232** [comment]
As per my earlier link, that file still refers to the postal.atech.media site. You could download the script and make it `git clone` then run it as a shell script.

**Comment by catphish** [comment]
Just seen this. Will get it resolved immediately.

**Comment by catphish** [comment]
This should now be resolved.
