### ISSUE TITLE
Fresh install with error

### ISSUE THREAD

**Issue by PPantaz** [atech/postal#567]
Hi,

Can someone assist with this fresh install error?
=======================================

Fetching: bundler-1.16.1.gem (100%)
Successfully installed bundler-1.16.1
Fetching: procodile-1.0.18.gem (100%)
Successfully installed procodile-1.0.18
2 gems installed
Creating vhost "/postal"
Creating user "postal"
Setting permissions for user "postal" in vhost "/postal"
--2018-04-16 01:39:57--  https://postal.atech.media/packages/stable/latest.tgz
Resolving postal.atech.media (postal.atech.media)... 185.22.208.54, 2a00:67a0:a:1::1b
Connecting to postal.atech.media (postal.atech.media)|185.22.208.54|:443... connected.
ERROR: cannot verify postal.atech.media's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to postal.atech.media insecurely, use `--no-check-certificate'.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by PPantaz** [comment]
Same issue as  Quick Install SSL Issue #566

Closing

**Comment by catphish** [comment]
This should now be resolved.
