### ISSUE TITLE
Second/Third Organisations

### ISSUE THREAD

**Issue by michaelwilding** [atech/postal#568]
I can't get any emails sent through second or third organisations added to actually send, they remain in Pending status. The primary organisation I added first works with no issues. Is there something I've missed that I need to setup in the config for sending to work with other organisations or mail servers in the front-end?

**Comment by willpower232** [comment]
Have you set up any potentially unnecessary IP pools?

**Comment by michaelwilding** [comment]
Nope, all organisations are using the same IP Pool. Unless that could be the issue?

**Comment by willpower232** [comment]
If you aren't using IP Pools, you shouldn't enable the settings.

If thats not the issue, have you looked at the logs?

**Comment by michaelwilding** [comment]
Sorry we are using IP Pools, we have one pool which is used by all organisations. Could that be the issue?

There doesn't seem to be anything in the logs relating to why they're stuck in Pending status.

**Comment by willpower232** [comment]
It might be but I'm afraid I don't know lots about Postal uses IP Pools.

Did you create the pool after creating the organisations or before?

**Comment by michaelwilding** [comment]
Interestingly I removed all the IP pools and let it rotate through the IP's itself, and this stopped the issue with sending through other organisations and also stopped a huge delay we were having in connections. We've gone from as long as 5 seconds per connection to around .10ms (which is what we were expecting). It seems there may be some issues in using the IP Pools from both an organisational point of view and an optimisation of speed. Or I'm doing something wrong, which is also highly possible.

**Comment by michaelwilding** [comment]
There were only 5 addresses in the pool. It's almost as if only one organisation can use a pool at a time, which may be the case. The bigger issue is the change in connection speed.
