### ISSUE TITLE
550 Administrative prohibition

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#571]
Hi,
Please check the screen shots.
![screenshot_30](https://user-images.githubusercontent.com/28861157/38971937-61e64ae8-43bb-11e8-91d0-6e6a90b67be3.png)

**Comment by willpower232** [comment]
For whatever reason, their email server is blocking your Postal.

See http://kb.mozillazine.org/Administrative_Prohibition or Google for more information
