### ISSUE TITLE
SPF Neutral

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#572]
Hi,
I have verified a domain In postal and when i send the mails in gmail it's show neutral 
Here is the Screen Shot . please check it.

![screenshot_31](https://user-images.githubusercontent.com/28861157/38978961-89130866-43d6-11e8-81df-d13a2cdb4508.png)

![screenshot_32](https://user-images.githubusercontent.com/28861157/38978916-6adc30fc-43d6-11e8-94a8-543415e112c1.png)
![screenshot_33](https://user-images.githubusercontent.com/28861157/38978917-6b243406-43d6-11e8-8b2a-b6ede1586e7c.png)

**Comment by willpower232** [comment]
It looks like openview.info has two TXT records for SPF. You should combine them into one record.

**Comment by willpower232** [comment]
The `redirect=` part of that SPF record points to another record which has many IP address ranges so its quite a complex SPF check. This makes it impossible to tell if that covers your Postal server without knowing its IP address. You should have a look yourself through the `_spf.rediffmailpro.com` SPF record.

**Comment by Manishjodhani** [comment]
OK Thanks
