### ISSUE TITLE
Suppression List

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#58]
The ability to remove an address from the suppression list would be nice, or to be able to configure the feature limit.

Given that Postal was more a SaaS before, I suspect this is why the limit is hard set but some of us will be using internally where that might not be required or can be artificially high.

(Ability to delete an address from the list before the 30th day would be useful too).

**Comment by adamcooke** [comment]
Recipients are added to the suppression list under two circumstances at the moment. 

1. If there are two or more `HardFail` trying to send that user a message.
2. If a message has been "delayed" (i.e. `SoftFail`) 18 times. This is the same point at which a message that was previously soft failed will be hard failed.

At present, either of these are configurable but allowing them to be wouldn't be a problem. I have added another issue to sort this (issue #59).

The ability to remove recipients from the suppression list is also an easy one to add. I've added issue #60 for that.

**Comment by sandeep28saxena** [comment]
Where can I configure HardFail limit of 2 ?

**Comment by navinp** [comment]
Is there an option to export this list? 

It would be handy for me to unlist these recipients from my mailing software...

**Comment by willpower232** [comment]
Unfortunately, I don't believe there is a webhook for it so your only option would be to explore the database and export the records.
