### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by PPantaz** [atech/postal#581]
After couple days of Postal running, I attempt to login and land on this page

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

Any ideas?

Thank you much

**Comment by Manishjodhani** [comment]
Restart mysql, ngnix and postal.
Then try

**Comment by willpower232** [comment]
If restarting the services didn't help, have a look in your log files /opt/postal/log.

I see this error if there has been a problem in the code because the database has done something screwy.

**Comment by PPantaz** [comment]
restarting nginx and postal fixes the issue.

**Comment by PPantaz** [comment]
**Here the reason, the DB crashes. Any idea if its a memory issue, perhaps my server needs more ram?**

 mariadb.service - MariaDB 10.1.32 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: failed (Result: exit-code) since Tue 2018-05-08 04:29:50 UTC; 19h ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 6297 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 6293 ExecStartPost=/etc/mysql/debian-start (code=exited, status=0/SUCCESS)
  Process: 7751 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
  Process: 7593 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment
  Process: 7585 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 7583 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 7751 (code=exited, status=1/FAILURE)
   **Status: "MariaDB server is down"**

May 08 04:29:50 mail1 mysqld[7751]: 2018-05-08  4:29:50 139767082703104 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
May 08 04:29:50 mail1 mysqld[7751]: 2018-05-08  4:29:50 139767082703104 [ERROR] Plugin 'InnoDB' init function returned error.
May 08 04:29:50 mail1 mysqld[7751]: 2018-05-08  4:29:50 139767082703104 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
May 08 04:29:50 mail1 mysqld[7751]: 2018-05-08  4:29:50 139767082703104 [Note] Plugin 'FEEDBACK' is disabled.
May 08 04:29:50 mail1 mysqld[7751]: 2018-05-08  4:29:50 139767082703104 [ERROR] Unknown/unsupported storage engine: InnoDB
May 08 04:29:50 mail1 mysqld[7751]: 2018-05-08  4:29:50 139767082703104 [ERROR] Aborting
May 08 04:29:50 mail1 systemd[1]: mariadb.service: Main process exited, code=exited, status=1/FAILURE
May 08 04:29:50 mail1 systemd[1]: Failed to start MariaDB 10.1.32 database server.
May 08 04:29:50 mail1 systemd[1]: mariadb.service: Unit entered failed state.
May 08 04:29:50 mail1 systemd[1]: mariadb.service: Failed with result 'exit-code'.

**Comment by willpower232** [comment]
If it won't start, its probably memory related unless you have loads already.

You may also be interested in the MySQL/Maria configuration changes here https://github.com/atech/postal/issues/324#issuecomment-323538575

**Comment by PPantaz** [comment]
Worst MTA ever, horrible. Plus the docs are not straight forward, not explained well, and not configured well. Very unstable platform, deleting it for the 2nd time, trashing my digital ocean server again. SCRAP

**Comment by PPantaz** [comment]
Ridiculous, i can't stop thinking about how this POSTAL busts so much, and your docs dont even explain it well, dont even reply to this post
