### ISSUE TITLE
Postal 404 on any request

### ISSUE THREAD

**Issue by tankerkiller125** [atech/postal#584]
I had postal working perfectly before, however after changing its domain (which I did properly in both config and DNS and tested working) and then rebooting my server after a Linux kernel upgrade postal now responds with a 404 error every single time. I am using the Nginx config included with postal. I have also tried opening the system from the local 5000 port that nginx proxies too and I still receive a 404 error.

The PUMA log and the nginx access log do not give me any further information.

**Comment by tankerkiller125** [comment]
Killed anything running on port 5000 and restarted postal, seems to have fixed the issue

**Comment by willpower232** [comment]
`postal status` should confirm which processes are running (or not) to point you in the right direction. You can also manually run the commands listed in `postal status` to see why they have failed.

**Comment by tankerkiller125** [comment]
@willpower232 postal status did not help at all here, it said that everything was running exactly as it should have. Only killing it via the PID worked, attempts at safe restarts did nothing.
