### ISSUE TITLE
Opening port 2525

### ISSUE THREAD

**Issue by navinp** [atech/postal#592]
A client using a vps that has its port 25 blocked, so the client tried 2525 and noticed this was not working.

I also discovered it and asked my Sysadmin to open 2525

Today we came to the conclusion that both ports cannot be open at the same time.

It has to be 25 or 2525 but not both open at the same time.

Is this true? 

Opening 2525 was way tougher than expected and still not working at the moment :/ 

Any help/suggestion is greatly appreciated

**Comment by willpower232** [comment]
Postal can only listen on one port at a time.

In your situation, I would suggest setting it to listen on port 2525 only and making sure all its users know to use that port.

Have a look at https://github.com/atech/postal/issues/461#issuecomment-358251795
