### ISSUE TITLE
Update Sentry SDK

### ISSUE THREAD

**Issue by tankerkiller125** [atech/postal#597]
I am using the integrated Sentry support to log errors and issues, something that I recently noticed is that Sentry is giving me notice that the old ruby sdk is being used, I'm not sure if this is something I can easily fix by updating a gem or something, or if this a deeper integration that needs more care with.

**Comment by cmmata** [comment]
Hi @tankerkiller125. In #466 I asked how to connect Postal to a Sentry instance but didn't receive an answer. Can you tell me how you did it? I have no idea of Ruby and didn't find it for myself.

**Comment by willpower232** [comment]
Presuming the ruby version of the library is as good as the other ones, you shouldn't encounter any issues upgrading.

If you want to give it a go, I believe you can update it using `bundle` and submit the updated `gemfile.lock` as a pull request.

**Comment by tankerkiller125** [comment]
@cmmata Unfortunately I can't SSH into my server from work, I will get back to you when I find out.

**Comment by tankerkiller125** [comment]
@cmmata You can add the following to the config to get sentry working:

```
general:
  exception_url: https://your:private@dsn.example
```

**Comment by willpower232** [comment]
Having looked into this a bit more (and integrated our Postal with Sentry with no warnings), I can see that the current `gemfile.lock` refers to version 2.7.2 which has been replaced by 2.7.3 but not that long ago https://github.com/atech/postal/blob/master/Gemfile.lock#L214

Have you updated your Postal recently?

**Comment by tankerkiller125** [comment]
@willpower232 I updated it just two days ago. It's a warning that gets sent on the sentry dashboard itself when you view an error. It's hard to spot sometimes.

**Comment by willpower232** [comment]
I'm familiar with the error message in some of our other older projects but its not appearing for the Postal issues we have detected so far.

At the bottom of the issue page, it should say what the version of raven-ruby is, are you seeing 2.7.2?

If you aren't, you could double check your own `gemfile.lock` and run `postal bundle /opt/postal/vendor/bundle` manually.
