### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by BlueHatbRit** [atech/postal#6]
It seems there's no license for the software at the moment which means it's not usable by most of us. Licensing is a pretty important part, especially within an organisation, any idea when this might be added?

**Comment by adamcooke** [comment]
Sorry - an oversight on our pair. It'll be there in the next hour or so.

**Comment by BlueHatbRit** [comment]
Oh awesome thanks!

**Comment by adamcooke** [comment]
MIT licence has been added.
