### ISSUE TITLE
Ability to remove recipients from the suppression list

### ISSUE THREAD

**Issue by adamcooke** [atech/postal#60]

**Comment by adamcooke** [comment]
Having looked into this. It is possible to remove recipients from the recipient list by successfully sending them a message. If a message is sent to someone on a suppression list it will be held. From there, you can "release" it. If it is successfully delivered, it will automatically be removed from the suppression list otherwise they will remain on the list.

I forgot this when I added this ticket.

**Comment by mackinra** [comment]
@adamcooke It would be useful to have a way to do this via the API.  i.e., deleting an email address from the suppression list, as well as a way to query to see if an email is in the list.

**Comment by longhorninmd** [comment]
There needs an ability to release "Held" messages in bulk.  The use case is for Gmail.  If you're trying to warm up a new IP, they will permanently fail messages with this error:

"550-5.7.1 [IP redacted] Our system has detected that this message is 550-5.7.1 likely suspicious due to the very low reputation of the sending IP 550-5.7.1 address. To best protect our users from spam, the message has been 550-5.7.1 blocked."

These are not true bounces.  But, Postal will put such recipients on the suppression list or in "Held" status if attempting to mail again.  However, the only way to solve this issue is to send more mail so that the reputation can be established and build up.

Maybe just a "Release All" button for now?

**Comment by blakilox** [comment]
Postal is such a great relief, at last I can get a tool in-between my mails and my Psychotic ISP, to try to figure why the hell they drop my important emails, However the ability to delete messages and remove suppressions and clear logs and delete things from the queue would be really helpful, thanks for such a promising tool

**Comment by sandeep28saxena** [comment]
Is it possible to search an email address manually from suppression list and release it ? Also can the 30 day period of retry be customised ?

**Comment by willpower232** [comment]
If you know the recipient can now receive messages, Postal should let you resend their individual messages manually which will remove them from the suppression list presuming the message is delivered.

**Comment by tchwpkgorg** [comment]
Looking at low level, the suppresions are here:

```
MariaDB [postal-server-1]> use postal-server-1;       
Database changed
MariaDB [postal-server-1]> select * from  suppressions;
(...)
MariaDB [postal-server-1]> DELETE FROM suppressions WHERE address = 'some@email';
(...)
```

So yes, we'd need something like:

- /api/v1/suppressions/add (user email; adds the user to suppressions list)
- /api/v1/suppressions/remove (user email; removes email from suppressions list)
- /api/v1/suppressions/check (user email; check if email exists on the list)

And maybe:

- /api/v1/suppressions/list (no arguments, list all emails on the suppression list)

**Comment by criskolkman** [comment]
+1 on @tchwpkgorg comment

**Comment by nenominal** [comment]
+1 on @tchwpkgorg :)

**Comment by gitaayush** [comment]
Hello i tried sending email to the recipient which was listed on suppression list. But i am not able to send emails as it shows following errors : Hard Fail

Maximum number of delivery attempts (21) has been reached. Added admin@example.com to suppression list because delivery has failed 21 times.

I have not attempted to send emails to admin@example.com 21 times. Still the recepients address is on the suppression list.

**Comment by willpower232** [comment]
@gitaayush please don't comment on issues closed a long time ago, you may not have sent 21 different emails but Postal will have retried the message repeatedly which is why it reached the limit.

**Comment by gitaayush** [comment]
any way to remove the recepients email from suppression list ??

**Comment by willpower232** [comment]
As above

> It is possible to remove recipients from the recipient list by successfully sending them a message. If a message is sent to someone on a suppression list it will be held. From there, you can "release" it. If it is successfully delivered, it will automatically be removed from the suppression list otherwise they will remain on the list.

**Comment by 40056** [comment]
@willpower232 somehow the email is in suppression but I can't release as it immediately gives me an error message.

August 28, 2023 11:47
ERROR
An internal error occurred while sending this message. This message will be retried automatically. If this persists, contact support for assistance.

FrozenError: can't modify frozen String: ""

Support Ref: J-HNAOQQZHVW

August 28, 2023 11:47
HELD
Recipient (email@domain.com) is on the suppression list (reason: too many soft fails)

**Comment by giezi** [comment]
We've exactly the same issue with retrying:

FrozenError: can't modify frozen String: ""
Support Ref: J-EVU135MXKZ

**Comment by calvez** [comment]
> @willpower232 somehow the email is in suppression but I can't release as it immediately gives me an error message. So even in suppression it is sending it and not putting on "hold" so no way to release it. Any other way without needing to learn databases?
> 
> August 28, 2023 11:47 ERROR An internal error occurred while sending this message. This message will be retried automatically. If this persists, contact support for assistance.
> 
> FrozenError: can't modify frozen String: ""
> 
> Support Ref: J-HNAOQQZHVW
> 
> August 28, 2023 11:47 HELD Recipient ([email@domain.com](mailto:email@domain.com)) is on the suppression list (reason: too many soft fails)


this one has a quick fix here: https://github.com/nicksellen/postal-fix

but sadly it won't solve the suppression release problem

**Comment by washcroft** [comment]
> There needs an ability to release "Held" messages in bulk. The use case is for Gmail. If you're trying to warm up a new IP, they will permanently fail messages with this error:
> 
> "550-5.7.1 [IP redacted] Our system has detected that this message is 550-5.7.1 likely suspicious due to the very low reputation of the sending IP 550-5.7.1 address. To best protect our users from spam, the message has been 550-5.7.1 blocked."
> 
> These are not true bounces. But, Postal will put such recipients on the suppression list or in "Held" status if attempting to mail again. However, the only way to solve this issue is to send more mail so that the reputation can be established and build up.
> 
> Maybe just a "Release All" button for now?

To release/retry all held messages, the following SQL will do the trick:

``
INSERT INTO `postal`.queued_messages (server_id, message_id, batch_key, domain, manual) SELECT XXX, id, CONCAT('outgoing-', SUBSTR(rcpt_to, INSTR(rcpt_to, '@')+1)), SUBSTR(rcpt_to, INSTR(rcpt_to, '@')+1), 1 FROM `postal-server-XXX`.messages WHERE held = 1;
``

Where XXX is the ID of your server - which you can get from: ``SELECT id, name FROM `postal`.servers;``

**Comment by arthurzenika** [comment]
We use the postal console to bulk release held messages after an incident : 

```
postal console
server=Organization.find_by_permalink('INSERT_YOUR_ORG').servers.find_by_permalink('INSERT_YOUR_SERVER_NAME')
server.message_db.messages(:where => {:held => 1,:scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }
```

**Comment by ugurtam** [comment]
> We use the postal console to bulk release held messages after an incident :
> 
> ```
> postal console
> server=Organization.find_by_permalink('INSERT_YOUR_ORG').servers.find_by_permalink('INSERT_YOUR_SERVER_NAME')
> server.message_db.messages(:where => {:held => 1,:scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }
> ```

Thank you so much, very helpfull
