### ISSUE TITLE
SSL cert expired, install script fails

### ISSUE THREAD

**Issue by oasis1234** [atech/postal#602]
Install script (https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh)
fails at wget https://postal.atech.media/packages/stable/latest.tgz
ERROR: cannot verify postal.atech.media's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’: Issued certificate has expired.
Could you use Certbot on your site, so that certs are auto renewed?

**Comment by newcombmc** [comment]
in a clean server login as root

`wget https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh`

then 

`nano ubuntu1604.sh`

edit https://postal.atech.media/ (towards the bottom) to say http://postal.atech.media/

Save and exit

then run

`sh ubuntu1604.sh`

**Comment by willpower232** [comment]
thanks for saying something, I've prodded atech directly but in the meantime, removing that S should bypass the problem but for ongoing security, it would be better to rely on there being an active certificate.

**Comment by catphish** [comment]
This was fixed. Sorry about that!
