### ISSUE TITLE
Using a proxy (instead of IP Pools or SMTP relay)

### ISSUE THREAD

**Issue by oasis1234** [atech/postal#605]
The problem is well known: you create a new VPS, install your mail server and, oh no!, your sent email goes directly to the Spam folder despite having a 10 score in mail-tester.com. SPF, DKIM, DMARC, all ok. The problem? Your IP has "bad reputation". [BTW don't even try to use a free domain .tk .ml .ga .cf] Solution? You can park your VPS with dedicated IP for 90 days, or use another one.

Option1: Use Postal's "IP Pools" feature. I didn't try it, but I understand that your host will use other IPs available. I know that some hosters allow you to buy additional IPs (do they let you try before buying?). I got no idea how to set up that configuration, but I know that you're limited to a closed network.

Option2: Use an SMTP relay. It works ok, but the only "problem" is that (as advised #497) the relay will give zero feedback about delivery.

Option3: Use a proxy. I want to "borrow" the good reputation of my other mail server's IP (no merit, just months of inactivity). I know how to do it in Windows (I run Postal in a Ubuntu VM and I can proxy with VPN or even Proxifier+Socks proxy (created with Putty).
I was researching about using ssh to create a tunnel to my other host, but then I will need a kind of proxifier (proxychains?) to intercept the client. What client? Ruby? Net::SMTP? RabbitMQ? My Linux knowledge is limited. I know how to set up a proxy in PHP code (CURLOPT_PROXY), but with Postal I got no idea.
I'm interested because my test in Windows was successful: I added the proxy IP to my domain's SPF DNS record and the email wasn't flagged as spam by Gmail, despite not matching the rDNS (PTR).
The advantage of this method over the "IP Pools" is that I can use external IPs not limited to an internal network or hoster.
I will cry for joy the day I see in postal.yml the option "proxy: 1.2.3.4".
Final thought: I know that using a ssh daemon proxy could be a bad idea for a serious approach, but I'm just testing.

**Comment by oasis1234** [comment]
I continue this conversation with myself as it seems that the dev-community is not interested in the IP of the sender mailserver. [Disclosure: yes, Gmail will mark your mgs as spam or even refuse it based on your IP] I'm a Ruby noob and I spent a long time doing trial-and-error, so don't expect an elegant solution.
With this setup you'll be able to change the originating IP of your Postal server.

First, install https://github.com/astro/socksify-ruby
$ gem install socksify
Edit /var/lib/gems/2.3.0/gems/socksify-1.7.1/lib/socksify.rb and change require 'socksify/debug' with the full path: require '/var/lib/gems/2.3.0/gems/socksify-1.7.1/lib/socksify/debug'

Finally, edit /opt/postal/app/config/initializers/smtp_extensions.rb
add:  require '/var/lib/gems/2.3.0/gems/socksify-1.7.1/lib/socksify'
change:
  def tcp_socket(address, port)
    addr = TCPSocket::SOCKSConnectionPeerAddress.new("127.0.0.1", 1080, address)
    TCPSocket.open(addr, port, self.source_address)
  end

Now you have two options:
*opt1: Use ssh port forwarding
$ ssh -D 1080 -f -C -q -N root@extserver
Problem: ssh session must be keept alive.
*opt2: Install a SOCKS server (Dante) in your VPS with good IP.
Instead of opening a local SOCKS, use one external directly, changing 127.0.0.1 with the IP of your VPS, and using it on demand.

That's it. Enjoy.
PS: Thank you dev-community for ignoring me, I've learned a lot during this weekend.

**Comment by willpower232** [comment]
Your use case is interesting, if very niche. Glad you got it resolved.

If you've got everything working, feel free to close the issue.

**Comment by mrmatthewpat** [comment]
> 
> 
> I continue this conversation with myself as it seems that the dev-community is not interested in the IP of the sender mailserver. [Disclosure: yes, Gmail will mark your mgs as spam or even refuse it based on your IP] I'm a Ruby noob and I spent a long time doing trial-and-error, so don't expect an elegant solution.
> With this setup you'll be able to change the originating IP of your Postal server.
> 
> First, install https://github.com/astro/socksify-ruby
> $ gem install socksify
> Edit /var/lib/gems/2.3.0/gems/socksify-1.7.1/lib/socksify.rb and change require 'socksify/debug' with the full path: require '/var/lib/gems/2.3.0/gems/socksify-1.7.1/lib/socksify/debug'
> 
> Finally, edit /opt/postal/app/config/initializers/smtp_extensions.rb
> add: require '/var/lib/gems/2.3.0/gems/socksify-1.7.1/lib/socksify'
> change:
> def tcp_socket(address, port)
> addr = TCPSocket::SOCKSConnectionPeerAddress.new("127.0.0.1", 1080, address)
> TCPSocket.open(addr, port, self.source_address)
> end
> 
> Now you have two options:
> *opt1: Use ssh port forwarding
> $ ssh -D 1080 -f -C -q -N root@extserver
> Problem: ssh session must be keept alive.
> *opt2: Install a SOCKS server (Dante) in your VPS with good IP.
> Instead of opening a local SOCKS, use one external directly, changing 127.0.0.1 with the IP of your VPS, and using it on demand.
> 
> That's it. Enjoy.
> PS: Thank you dev-community for ignoring me, I've learned a lot during this weekend.

Hello i can solve some issue ad me on skype : MR MATTHEW PAT

**Comment by mrmatthewpat** [comment]
> 
> 
> I continue this conversation with myself as it seems that the dev-community is not interested in the IP of the sender mailserver. [Disclosure: yes, Gmail will mark your mgs as spam or even refuse it based on your IP] I'm a Ruby noob and I spent a long time doing trial-and-error, so don't expect an elegant solution.
> With this setup you'll be able to change the originating IP of your Postal server.
> 
> First, install https://github.com/astro/socksify-ruby
> $ gem install socksify
> Edit /var/lib/gems/2.3.0/gems/socksify-1.7.1/lib/socksify.rb and change require 'socksify/debug' with the full path: require '/var/lib/gems/2.3.0/gems/socksify-1.7.1/lib/socksify/debug'
> 
> Finally, edit /opt/postal/app/config/initializers/smtp_extensions.rb
> add: require '/var/lib/gems/2.3.0/gems/socksify-1.7.1/lib/socksify'
> change:
> def tcp_socket(address, port)
> addr = TCPSocket::SOCKSConnectionPeerAddress.new("127.0.0.1", 1080, address)
> TCPSocket.open(addr, port, self.source_address)
> end
> 
> Now you have two options:
> *opt1: Use ssh port forwarding
> $ ssh -D 1080 -f -C -q -N root@extserver
> Problem: ssh session must be keept alive.
> *opt2: Install a SOCKS server (Dante) in your VPS with good IP.
> Instead of opening a local SOCKS, use one external directly, changing 127.0.0.1 with the IP of your VPS, and using it on demand.
> 
> That's it. Enjoy.
> PS: Thank you dev-community for ignoring me, I've learned a lot during this weekend.

Hello i can solve some issue ad me on skype : MR MATTHEW PAT

**Comment by RKurcan** [comment]
How can I use with auth like username password 
I try this but not worked https://rubygems.org/gems/socksify-with-auth/versions/1.7.1
`def tcp_socket(address, port,p_username = nil, p_password = nil)
addr = TCPSocket::SOCKSConnectionPeerAddress.new("ip adress", 14193,"username","password", address)
TCPSocket.open(addr, port, self.source_address)`

**Comment by RKurcan** [comment]
@oasis1234 @willpower232
