### ISSUE TITLE
Client does not have permission

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#609]
Hi,
I have install postal in fresh new server OS  Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0 x86_64)
And i have add two domain and update the records in Domain c panel.
And then last i create a credentials.
But when i used the credentials is show this.
Please have a look in screen shots.
![screenshot_1](https://user-images.githubusercontent.com/28861157/42233864-579dc56c-7f10-11e8-9349-29c4e15e435e.png)
![screenshot_2](https://user-images.githubusercontent.com/28861157/42233865-57f7d1ec-7f10-11e8-8bb6-8997b7be5038.png)

**Comment by willpower232** [comment]
The login name is not the name of the credential.

If you go back to the list of credentials and click on "Read more about sending outgoing e-mails" you should see what the username really is.

**Comment by Manishjodhani** [comment]
It have been solved i have reinstall the postal and now it's working.
Thanks for help.
