### ISSUE TITLE
top menu dont show admin link.

### ISSUE THREAD

**Issue by fsakbas** [atech/postal#61]
i cant see admin link on the top. Wiki screenshots has a login link.

![ekran resmi 2017-04-29 16 17 09](https://cloud.githubusercontent.com/assets/5522441/25555754/5c7bc820-2cf7-11e7-9e1c-e211232de46e.png)

**Comment by adamcooke** [comment]
The screenshots in the wiki is wrong. There is no admin link in Postal. Apologies for any confusion.
