### ISSUE TITLE
Postal For Dummies: The Missing Manual

### ISSUE THREAD

**Issue by oasis1234** [atech/postal#614]
This is a step-by-step guide for average guys like me. This is a guaranteed-installation manual for Debian 9 (Stretch), working as of today (Jul/2018).
My Debian system is from this ISO: debian-9.4.0-amd64-netinst.iso (https://www.debian.org/CD/netinst/).
Assuming you are root, have SSH server, nameservers configured, and working 'sudo' command.
First, don't install Postal using the script: it will fail at some unexpected point and you'll never know what happened. Instead, proceed line by line. (copy/paste).

```
apt install -y software-properties-common
apt install -y ruby2.3 ruby2.3-dev build-essential
apt install -y mariadb-server default-libmysqlclient-dev
apt install -y rabbitmq-server
apt install -y nodejs
apt install -y git
apt install -y nginx
gem install bundler procodile --no-rdoc --no-ri

# MySQL
echo 'CREATE DATABASE `postal` CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;' | mysql -u root
echo 'GRANT ALL ON `postal`.* TO `postal`@`127.0.0.1` IDENTIFIED BY "pass123";' | mysql -u root
echo 'GRANT ALL PRIVILEGES ON `postal-%` . * to `postal`@`127.0.0.1`  IDENTIFIED BY "pass123";' | mysql -u root

# RabbitMQ
rabbitmqctl add_vhost /postal
rabbitmqctl add_user postal pass123
rabbitmqctl set_permissions -p /postal postal ".*" ".*" ".*"

# System prep
useradd -r -m -d /opt/postal -s /bin/bash postal
setcap 'cap_net_bind_service=+ep' /usr/bin/ruby2.3

# Application Setup
sudo -i -u postal mkdir -p /opt/postal/app
wget https://postal.atech.media/packages/stable/latest.tgz -O - | sudo -u postal tar zxpv -C /opt/postal/app
ln -s /opt/postal/app/bin/postal /usr/bin/postal
postal bundle /opt/postal/vendor/bundle
#Note: installing nokogiri takes 5min in my host
postal initialize-config
# Update /opt/postal/config/postal.yml passwords
postal initialize
postal start

# nginx
cp /opt/postal/app/resource/nginx.cfg /etc/nginx/sites-available/default
mkdir /etc/nginx/ssl/
openssl req -x509 -newkey rsa:4096 -keyout /etc/nginx/ssl/postal.key -out /etc/nginx/ssl/postal.cert -days 365 -nodes -subj "/C=GB/ST=Example/L=Example/O=Example/CN=example.com"
service nginx reload

postal make-user
```

* **Add Postal to startup**
/etc/rc.local
```
  #!/bin/sh -e
  sudo -u postal postal start
  exit 0
```
`$ chmod 755 /etc/rc.local`

* **(Optional) Fix default IPv6-only smtp**
/opt/postal/app/lib/postal/smtp_server/server.rb
`   @server = TCPServer.open('0.0.0.0', Postal.config.smtp_server.port)`

**Comment by oasis1234** [comment]
# DNS Setup
This is the tricky part. Change example.com with your domain.
Edit /opt/postal/config/postal.yml
```
dns:
  mx_records:
    - mail.example.com
  smtp_server_hostname: mail.example.com
  spf_include: spf.mail.example.com
  return_path: rp.mail.example.com
  route_domain: routes.mail.example.com
  track_domain: track.mail.example.com
```

Now restart Postal so that changes take effect. (This takes 30s in my host)
`$ postal restart`
Go to the Postal management web on https://example.com or https://1.2.3.4, accept invalid certificate, login with the credentials created with 'postal make-user'.
'Create first organization', 'Build your first mail server'.
Go to 'Domains" and click 'Add your first domain'. Type domain and click 'Create domain'.
Now you're in the 'DNS Setup' page. Don't click 'Check my records are correct' yet!
Go to your domain's DNS table (registrar, hoster, DNS provider, etc) and enter the values below.
Change example.com with your domain, 1.2.3.4 with the public IP of your server and "postal-a1b2c3._domainkey" with the one in the "DKIM Record" section in the DNS Setup page, adding the corresponding value.
@ means root domain, normally is left blank and is completed internally.

```
Name	Type	Value
@	A	1.2.3.4
mail	A	1.2.3.4
rp.mail	A	1.2.3.4
track.mail	A	1.2.3.4
psrp	CNAME	rp.mail.example.com
@	MX	10;mail.example.com
routes.mail	MX	10;mail.example.com
rp.mail	MX	10;mail.example.com
@	TXT	v=spf1 a mx include:spf.mail.example.com ~all
postal-a1b2c3._domainkey	TXT	v=DKIM1; t=s; h=sha256; p=MIGfMA0GC...;
rp.mail	TXT	v=spf1 a mx include:spf.mail.example.com ~all
spf.mail	TXT	v=spf1 ip4:1.2.3.4 ~all
_dmarc	TXT	v=DMARC1; p=reject; sp=reject; rua=mailto:postmaster@example.com
```

Now you need to wait some time for your DNS records to propagate. Nowadays propagation is almost instant, nevertheless check your records in https://www.whatsmydns.net/
Go back to the 'DNS Setup' page and now, yes, click 'Check my records are correct'.
If everything went OK, you'll see four green ticks on SPF, DKIM, MX and Return Path. "Verified on <date>"
Your Postal mail server is ready. You can try to send a test message. Messages > Send Message. Get a test email address on mail-tester.com, isnotspam.com, dkimvalidator.com
Test incoming(inbound) email with ismyemailworking.com. First you need to create an endpoint (HTTP, SMTP or address) and then a route.

**Comment by mencargo** [comment]
## Many thanks!

The DNS guide also has the following parameters:
```
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp

```
For SSL certs, I used [acme.sh](http://acme.sh/), very simple setup.

**Comment by shinebayar-g** [comment]
Hi @oasis1234 .
I'm stuck on Domain setup step.
I've followed installation instructions step by step without errors and my **postal** is running normal.
But however I cannot figure out how to setup my domain.

I've read your [issue](https://github.com/atech/postal/issues/615) and got same problem.

After reading your instruction I still cannot verify my domain.
Only DKIM Record is green and rest are not working. Could you help me out?

**Comment by oasis1234** [comment]
Open a new issue. Post there your full postal.yml and DNS table (screenshot or exported BIND format).

**Comment by shinebayar-g** [comment]
Hey man @oasis1234,

Do you have a plan to finish the Let's Encrypt SSL section? If not, I have a few questions.
In **EXTRAS**:

1. What does **SMTP cert error** fix mean? Which error does it solve? This one?
```
Error: OpenSSL::SSL::SSLError (hostname "127.0.0.1" does not match the server certificate)
```
2. In **Enable TLS (email encryption in transit)**  you're using
```YAML
  tls_certificate_path: config/fast_server.cert
  tls_private_key_path: config/fast_server.key
```
Is there any problem using self generated keys to send email? I mean email recipient will receive any SSL related error or it's same as using Let's Encrypt's SSL?

**Comment by oasis1234** [comment]
Ok, I forgot to mention in guide the problem when installing Let'sEncrypt certs. I got that error months ago, and I've updated my guide with a fix. The difference is that I copy certs, but you change /letsencrypt directory permission (I don't know if that's ok).
Anyway, thank you for your contribution. As you may have realized **this project is almost "abandonware"**.

**Comment by evil4u** [comment]
There's missing manual.

What next after I have created HTTP and SMTP endpoint, how can I create user@domain.com and passwd?

This is missing.

**Comment by evil4u** [comment]
Att mailguna I can create user@domain.com and password to send emails with my php website.

**Comment by willpower232** [comment]
Postal does not have email addresses in the traditional sense, you will need to create an SMTP credential or use the PHP API client with an API credential.
