### ISSUE TITLE
Cron Not Running Properly

### ISSUE THREAD

**Issue by vscool19** [atech/postal#620]
@willpower232  @adamcooke I have make one job and put that into cron.rb file to run every 15 minutes. But when I am running postal through run command, it is not showing that running. Is there any problem with cron? Is cron need to run first?

**Comment by willpower232** [comment]
What are you trying to accomplish? Are you putting tasks unrelated to Postal in cron.rb?

**Comment by vscool19** [comment]
@willpower232  I made one job that will release held mails.

**Comment by willpower232** [comment]
Can you share your cron.rb file?

**Comment by vscool19** [comment]
![screenshot from 2018-07-24 20-01-36](https://user-images.githubusercontent.com/11226836/43145312-bd0a5fd8-8f7c-11e8-87fa-c9a5b6dc3a72.png)
@willpower232 This is my cron.rb file. In this I have added ReleaseHeldMessagesJob.queue(:main) job to run every 15 minutes.

**Comment by vscool19** [comment]
@willpower232 @adamcooke  can you please help me with this?

**Comment by willpower232** [comment]
sorry, I presume you added the ReleaseHeldMessagesJob code, were you able to test it outside of cron.rb?
