### ISSUE TITLE
Public sign up option

### ISSUE THREAD

**Issue by navinp** [atech/postal#627]
Does Postal have this option, for a public sign up page, where any one can register and create an organization/account? 

The user would have access to his/her organization, but not have admin rights, just regular user rights.

At the moment I create this manually, but would love to know if there's an option already for this.

**Comment by willpower232** [comment]
I don't believe this is a feature and presume atech handled registration in a separate system before releasing Postal as open source.

**Comment by catphish** [comment]
I'm afraid Postal does not support this. There is no simple solution other than creating the accounts manually, or you would need to build in your own signup flow.
