### ISSUE TITLE
Recently processed emails not showing in messages

### ISSUE THREAD

**Issue by navinp** [atech/postal#628]
Hello,

When you open a mailserver for example:
domain/org/customer-name/server/customer-name

There you will see **Recently processed e-mails**

I noticed if the emails are hard fail, they will not show up when you go to Messages.
domain/org/customer-name/server/customer-name/messages/outgoing

When I go to messages and I do status: hardfail it gives me 0 results.

**Comment by navinp** [comment]
I found these messages when doing **spam: yes**

**Comment by willpower232** [comment]
I haven't seen this before but I know that the outgoing messages list filter can be quite challenging, I have had to mess around with the query string to clear past filters and pagination so that might be related.
