### ISSUE TITLE
Organisational domains vs mail server domains

### ISSUE THREAD

**Issue by andretanguy** [atech/postal#63]
What is the reason for setting up organisational domains? From what I gather, an Organisational domain is not used by any mail servers within the organisation.

Could you clarify the use case for setting up an organisational domain and what it's used for?

**Comment by theratris** [comment]
Also curious about this, it seems to serve no function.

**Comment by deanpcmad** [comment]
Organisational domains can be used for any server in that org where as mail server domains can only be used for that mail server

**Comment by adamcooke** [comment]
As Dean has said, domains added to an organization can be used in the `From` address for any sever within the org. You can also add routes using domains from the org on any server within it. 

Having them at the org level means you only need to add a single DKIM DNS record for all servers. Adding them per-server will require one record per server.
