### ISSUE TITLE
how to delete the Held records.??

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#633]
Hi,
I want to delete held records.Please take look in the screenshots.
![screenshot_12123](https://user-images.githubusercontent.com/28861157/44018744-5c741fb4-9efa-11e8-83fb-237495dd56ed.png)
there are 850276 messages in held and i want to remove this from my database.

**Comment by willpower232** [comment]
The messages should automatically be removed from the held list after 7 days, if you open one of them, it will tell you so.

**Comment by igerzog** [comment]
Or you can simply connect to your postal database and remove these records from `suppressions` table directly.
The only thing to mention is to be careful :)
