### ISSUE TITLE
How to add user in the organization???

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#636]
Hi,
I have created organization in postal and then i try to create invite user.
But it show in pending state.
Please have a look in screen shot.
![screenshot_29](https://user-images.githubusercontent.com/28861157/44296978-8c033b80-a2e6-11e8-98ae-0332a9376c3e.png)
Please tell us where i can i check the log for this.??

**Comment by navinp** [comment]
Hello,

Is the server sending emails?

If you go to the forgot password page and tried to reset your own password, does it send the email?

**Comment by Manishjodhani** [comment]
Thanks @willpower232 .
I will try this.
