### ISSUE TITLE
Postal Upgrade Fail

### ISSUE THREAD

**Issue by blakilox** [atech/postal#640]
root@post:~# postal auto-upgrade
.
.
.
Restarting Postal
/var/lib/gems/2.3.0/gems/procodile-1.0.19/lib/procodile/control_client.rb:8:in `initialize': Pe                                               rmission denied - connect(2) for /tmp/postal/pids/procodile.sock (Errno::EACCES)
.
.
.
Failed to run: postal restart

It is working after a re-boot - may be just be a small bug with file permissions there?

**Comment by blakilox** [comment]
Ahhh - this is kind of answered in another thread - I was starting Postal incorrectly

in rc.local

change 
postal start
exit 0
to
su postal -c 'postal start'
exit 0
(i.e run it as the postal user not root)

Then the upgrade works, it all works

**Comment by catphish** [comment]
Thnks for the update!
