### ISSUE TITLE
Not listening 25 port anymore

### ISSUE THREAD

**Issue by freescout-helpdesk** [atech/postal#643]
1. Postal stuck and all outgoing messages were created as PENDING

2. Restarted Postal.

3. Postal is able to send messages now, but not listening port 25.

What can be the reason?

**Comment by freescout-helpdesk** [comment]
SMTP process is not running:
```
           ├─1338 [procodile] Postal (/opt/postal/app)
           ├─1344 [postal] web.1
           ├─1346 [postal] worker.1 (i
           ├─1348 [postal] cron.1
           └─1352 [postal] requeuer.1
```
smtp_server.log is empty

**Comment by freescout-helpdesk** [comment]
It was hosting provider issue. Anyway, it would be good to have some message in log in case smtp process can not listed on the port.

**Comment by willpower232** [comment]
Most things are already logged but it can be in a few different places.

A way of debugging the problem is to run `postal status` and then try manually running the commands it shows there so you see the error output directly on screen.
