### ISSUE TITLE
Locked message

### ISSUE THREAD

**Issue by freescout-helpdesk** [atech/postal#645]
In my postal there is a queued message which just stays there for a week:

> Message is currently being processed.
> No delivery attempts yet.

According to `_deliveries.html.haml` this message is **locked**.
What is the proper way to deal with this message?

**Comment by willpower232** [comment]
This sounds like https://github.com/atech/postal/issues/287#issuecomment-331081922

Unfortunately there isn't really a workaround at this time other than manually intervening in the database and for what its worth, so far the problem seems to be quite rare.

**Comment by freescout-helpdesk** [comment]
`update queued_messages set locked_by = NULL, locked_at = NULL, retry_after = NULL;`
