### ISSUE TITLE
Relay access denied

### ISSUE THREAD

**Issue by freescout-helpdesk** [atech/postal#647]
Some messages hard fail with **Relay access denied** error:
```
554 5.7.1 <recipint@example.com>: Relay access denied
```
```
550 relay not permitted!
```

What can be the reason? Is it my mail server configuration issue or recipient's mail server's problem?

**Comment by catphish** [comment]
Where are you seeing these messages? If it's on the delivery status of a message, then most likely this is a problem with the recipient. You can always test by sending en email to the same address from another emil service and see if it bounces with the same error.

**Comment by freescout-helpdesk** [comment]
Yes. Checked using Gmail.  The problem is with the recipient.
