### ISSUE TITLE
Emails Addresses 

### ISSUE THREAD

**Issue by khalidelmerrah** [atech/postal#651]
how can i export the database or the files where emails's status is set to : Sent

the emails i need are highlighted with yellow ink

![image](https://user-images.githubusercontent.com/24738104/44786904-8d0d5600-ab8d-11e8-9ad2-2941a9b433ca.png)

**Comment by willpower232** [comment]
You will need to use a database program such as HeidiSQL or Sequel Pro or similar.

If you look in the `messages` table of the server these emails are in, you should see a column called `status` which will contain the `Sent` value you are after.

**Comment by khalidelmerrah** [comment]
okay how can i connect to the database .. where is it located ? using HeidiSQL ..

**Comment by khalidelmerrah** [comment]
i managed to get the root user and password for database from `postal.yml` but i tried connecting through HeidiSQL it says the host `IP_Adresse` is not allowed to connect to this MySQL server ... 

ps : postal is installed inside a docker machine is it possible to connect to the mysql inside the docker machin ? .. ( the guy who set up the server is on vocation :(  )

**Comment by khalidelmerrah** [comment]
okay Will .. thanks ..
