### ISSUE TITLE
Postal did not verify the domain records?

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#658]
Hi,
I add a new domain and records are generated and i have update in my domain c panel but when i verify the records it did not checking and three dots are moving for last 1 hour.
Please take a look in screenshot.
![screenshot_38](https://user-images.githubusercontent.com/28861157/45346592-33fae480-b5c7-11e8-8df3-e3741595970d.png)

**Comment by willpower232** [comment]
Have you tried refreshing the page to see if anything has changed?

**Comment by Manishjodhani** [comment]
Yes, i tried.
Then it's  "SPF record exists but it doesn't include."
I have reinstall the postal.
