### ISSUE TITLE
Unable to send mail from MFP/skanners

### ISSUE THREAD

**Issue by pitah81** [atech/postal#663]
Hello,

I'm trying to diagnose why I'm unable to use Postal for sending email from Ricoh MFP:s. It works perfectly fine from web platforms and also using https://www.smtper.net with both secure, non secure, port 25 and 2525 using the same credentials as I'm using on the MFP:s.

Also I'm using the correct organisation/smtp-server username required by CRAM-MD5 to work but to no avail. And looking at the smtp_server.log show the following.

> EHLO ITL-OSD2-PR01.local.domain.ltd
> 250-My capabilities are
> 250-STARTTLS
> 250 AUTH CRAM-MD5 PLAIN LOGIN
> AUTH CRAM-MD5
> 334 PDAyZGI3YzBmNTU0YmFmZDU0MjAxQHNtdHByZWxheS5pdGxldi5zZT4=
> eGVsZW50L3hlbGVudC1zZSBlZTQ3NDcxMjliYzRmMTAxNzE4OGNlOTEzZTI2ZmYzMw==
> 235 Granted for organisation/domain.ltd
> QUIT
> 221 Closing Connection
> Connection closed
> Connection opened from ::ffff:200.0.43.34
> Client identified as ::ffff:200.0.43.34
> QUIT
> 221 Closing Connection
> Connection closed
> Connection opened from ::ffff:10.119.80.51
> Client identified as ::ffff:10.119.80.51

Compared to web services where it says MAIL FROM: mailadress@domain.ltd instead of QUIT so it's working for everything but the Ricoh MFP:s so it must have something to do with how the Ricoh recieves the "Granted" handshake or something. Using standard Postfix MTA works just fine but I'd rather don't want to install another SMTP-relay server just for all the printers/skanners.

When it comes to email settings on the Ricoh MFP:s I've tried all combinations.

![ricoh_smtp-settings](https://user-images.githubusercontent.com/1994575/45742884-3da1cf00-bbfb-11e8-9fc6-86ddd35151c3.PNG)

* Note all domain references and server-names have been replaced/anonymized.

Edit: Also, the only log entry found in the printer is of couse "fault" which doesn't exactly say much.

**Comment by willpower232** [comment]
We have successfully set up a printer with Postal (admittedly, not Ricoh).

At a guess, I'd say the email address the printer is trying to use doesn't match the domain name Postal has.

I'd suggest putting an email address like "mfp@domain.tld" in the email address box and seeing if that changes anything.

**Comment by pitah81** [comment]
Thanks for the tip willpower232, unfortunately I'm already using an email address with which has been added and verified to that mail-server in Postal. Actually I have 3 domains added with credentials created for the MFP in each of them and no matter which from address and no matter which domains credential I use the result is the same.

Been testing some now and the only thing that almost works is if I enter the from mail address in the mail-address authentication field and/or also enter the organisation/domain-ltd in smtp username. However if I do this I get "530 From/Sender name is not valid" so something weird is going on under the hood.

Also if I use CRAM-MD5 nothing works, PLAIN LOGIN is a must to get past "QUIT" from printer.

**Comment by willpower232** [comment]
I believe "530 From/Sender name is not valid" means that the domain it gets from the From (and Sender) header doesn't match the credentials domains so you need both a username and email address.

Are you able to see what the printer sends in its From or Sender headers?

**Comment by willpower232** [comment]
Are all three domains in the same account within Postal? You could also try using the advanced settings to allow sender header and see if that helps.

P.S. you should delete the credential for the accounts as it can be decoded from the above, sorry I should have said earlier.

**Comment by pitah81** [comment]
Yes, all the domains are added under the same organisation and same smtp-server in Postal. Also, I have enabled allow sender header for them all.

Thanks, I though as much, the credentials above are not the actual ones.

**Comment by willpower232** [comment]
Sorry for the wait, the only other thing I could suggest is decoding the authorisation yourself to double check the printer is sending the values it should be.

**Comment by pitah81** [comment]
Thanks willpower232, I would try to the decode the traffic if I had the time to do it. But in the end, I just went with using our older postfix smtp relay-solution. One thing worth noting is that many MFP:s only allow mail address for username, would it somehow be possible to add this for mail servers in Postal?

**Comment by willpower232** [comment]
If you can see the authorization base64 values in the logs, you can feed it to something like [CyberChef](https://gchq.github.io/CyberChef/) to see what values its sending.

I believe the credential usernames are computed and not stored anywhere so using an alternative format would be a big task to accomplish.
