### ISSUE TITLE
Can't verify second domain's Return Path?

### ISSUE THREAD

**Issue by shinebayar-g** [atech/postal#677]
I've setup my first domain and postal is working fine. Today I wanted to add another domain.
Here is the domain setup.

**SPF** and **DKIM** are verified fine. But **Return Path** still can't get verified.

![image](https://user-images.githubusercontent.com/3091558/46293244-7c556300-c5c5-11e8-8f54-032d13e95b62.png)

I've made CNAME record as setup suggests
![image](https://user-images.githubusercontent.com/3091558/46293580-86c42c80-c5c6-11e8-8e8e-f2b8cbcd4e23.png)

This:

![image](https://user-images.githubusercontent.com/3091558/46294117-a60f8980-c5c7-11e8-914a-2c120a24b358.png)

Anyone help?

**Comment by willpower232** [comment]
It looks like your DNS record isn't publicly available so you should discuss it with GoDaddy who currently handle the DNS.

![image](https://user-images.githubusercontent.com/1619102/46340006-2a93f380-c62c-11e8-928a-62eafe6984a0.png)

**Comment by shinebayar-g** [comment]
Ah, I thought so. I'm gonna contact Godaddy support and will let you know.

**Comment by shinebayar-g** [comment]
Hmm It should be just psrp not psrp.nmma.co in DNS settings. It worked, thanks.
