### ISSUE TITLE
Soft fail: Could not resolve IP

### ISSUE THREAD

**Issue by cmmata** [atech/postal#682]
Hello,

We have a Postal service sending almost a hundred of emails daily to our clients, but we have almost one client that doesn't receive e-mails because of IP soft fail. When I check the error, it says:
```
No SMTP servers were available for automarlop.com. Tried 195.162.18.232
Could not resolve 195.162.18.232
Support Ref: C9BWKTDV
```
If I execute `nslookup automarlop.com`, I obtain that IP address. Checking DNS from online tools return also the same IP address. So probably there's something wrong with that client domain, but the strange thing is that we are able to send him emails directly from Outlook 365 web interface. It only fails with emails sent from Postal.

Do you have any idea what can be wrong with that domain or with Postal configuration?

**Comment by willpower232** [comment]
As per the specification, MX records should be a domain name, not an IP address. See https://serverfault.com/questions/663112/why-cant-mx-records-point-to-an-ip-address for a discussion on the matter.

Why Office 365 lets you send email, I couldn't say. Its likely that other providers will fail because of this non-standard configuration.

**Comment by willpower232** [comment]
As I said, its being handled to the spec so there isn't a problem within Postal to fix.

Accurately telling the difference between a domain name made entirely of numbers and an IP address would be practically impossible.

I would say that, thankfully, its highly unlikely you'll find another person with the same problem.

**Comment by cmmata** [comment]
I was not talking about a fix because I understand it's not any bug. It was more like a configuration or maybe change in code. But don't worry, if there's any other client I'll send the same email. Thank you for your help!
