### ISSUE TITLE
How to edit the Wiki?

### ISSUE THREAD

**Issue by yasoob** [atech/postal#687]
I found a typo [in the Wiki](https://github.com/atech/postal/wiki/Click-&-Open-Tracking) "links with a new link that goes via. your Postal web server." There should not be a "." after via. But I don't know how to edit the Wiki and submit PRs. Can someone guide me and tell me whether this is even possible? 

Thanks!

**Comment by willpower232** [comment]
thanks for the heads up, unfortunately only atech can edit this particular wiki so we'll have to wait for them

**Comment by catphish** [comment]
I can update this :)
