### ISSUE TITLE
Any documentation routing?

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#690]
Hi, 
I need to know about routing feature of postal,
I read it about but it kind of confusing.I'm looking for any documentation of postal routing.
My scenario is we are using mailing application and as a Smtp we use psotal but we don't received any bounce mail(hard or soft fails).
So,any one can help me in this?
Thanks in advance

**Comment by willpower232** [comment]
So you're sending emails from your application to Postal with SMTP and Postal knows theres been bounces but your application doesn't?

**Comment by Manishjodhani** [comment]
Exactly

**Comment by willpower232** [comment]
Unless your application is capable of receiving a webhook over HTTP (https://github.com/atech/postal/wiki/Auto-Responders-&-Bounces), you're probably more interested in https://github.com/atech/postal/issues/263 and https://github.com/atech/postal/issues/255

**Comment by Manishjodhani** [comment]
But my application support only IMAP and POP3
is there anything i can do in postal to get bounce back to my application.

**Comment by willpower232** [comment]
Then I'm afraid thats not currently possible.

Does your application not send emails already itself?
