### ISSUE TITLE
how to delete mails storage?

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#692]
Hi,
I have a created a mail server but it was taking too much space of my server.
Please take a look in the screen shots.
![screenshot_6](https://user-images.githubusercontent.com/28861157/47850126-307f1f00-ddfa-11e8-9b91-deeaeea37042.png)

And i want to delete this storage.
Thanks in Advance

**Comment by willpower232** [comment]
You'll have to adjust the settings in this mail server to retain less data.

**Comment by Manishjodhani** [comment]
How?

**Comment by pschoenmakers** [comment]
Settings -> Advanced settings -> RAW MESSAGE RETENTION SIZE

**Comment by Manishjodhani** [comment]
It was already set as 2 GB by default
