### ISSUE TITLE
Multi IP DNS records

### ISSUE THREAD

**Issue by jos0405** [atech/postal#695]
I have a noobie question. I have +4 IP addresses added to my server, they are nicely visible with an ipconfig command.
Do I have to set subdomains for those ips?
(These are NS settings:)
Like:

A smtp1.domain.com 1.1.1.1.
A smtp2.domain.com 1.1.1.2.
A smtp3.domain.com 1.1.1.3.
A smtp4.domain.com 1.1.1.4.
and than refer these subdomain in the IP pool?

OR

I add them as 
A postal.domain.com 1.1.1.1.
A postal.domain.com 1.1.1.2.
A postal.domain.com 1.1.1.3.
A postal.domain.com 1.1.1.4.

And refer to them like this in the domain pool?

**Comment by willpower232** [comment]
In your IP Pool you should refer the IP address that the server is seeing, it probably won't be able to see the domain name.

The DNS is only important if you want to use those IPs to connect to your server which I imagine you don't. I imagine however you will need to set up reverse DNS for each IP.

**Comment by jos0405** [comment]
Thanks, great!
