### ISSUE TITLE
How is Postal more suitable?

### ISSUE THREAD

**Issue by xyproto** [atech/postal#7]
Hi,

> It was originally launched by us as AppMail but renamed to Postal as part of making it open source as we felt the name was more suitable.

Are you aware of the computer game with the same name, or the expression ["going postal"](https://en.wikipedia.org/wiki/Going_postal)?

The software looks promising.

Cheers!

**Comment by adamcooke** [comment]
It sounded less application specific than AppMail. I don't think people will confuse it with the game, though 😄
