### ISSUE TITLE
Filter messages using wildcard

### ISSUE THREAD

**Issue by alexroosenstein** [atech/postal#70]
Adding a wildcard to filters would enable searching for all emails sent to a specific domain (ie *@gmail.com) and filtering on tag to find related emails (client_* for all emails sent on behalf of clients for example).

I tried to look into the code (even though I'm no Ruby expert), and I guess it's possible to check for wildcards in the hash_to_sql function in database.rb (near line 371) and use a LIKE operator , but I'm not sure of the security implications of this change, nor the performance impact it would have.

**Comment by adamcooke** [comment]
There are certainly performance implications to using any sort of LIKE search here. For a moderately large mail server, it would take some time to find messages in that manner. Something that we want to add is a better index backend (something like ElasticSearch) to allow messages to be searched based on their content. If we add this, such a search on domain would be able to be added trivially.

For filtering on tag for client_, can you confirm your use case here? It might be best to have separate credentials for each client and then the ability to search based on the credential.

**Comment by adamcooke** [comment]
I see. That's currently not possible but something that could be supported with the introduction of a more powerful indexer.
