### ISSUE TITLE
No SMTP servers were available for mydomain.com

### ISSUE THREAD

**Issue by jackrobson** [atech/postal#716]
This is similar to https://github.com/atech/postal/issues/564

However, OP on that thread is talking about mx.gmail.com and I'm talking about mx.mydomain.com.

Also I can send mail to external domains, using the SMTP details inside PHPMailer.

So I think it needs a different ticket (please correct if this is wrong. I'm relatively new to Issue trackers).

Though anytime I send mail from my new email to my new email, I get a similar set of errors.

This is what it looks like:

<img width="915" alt="screen shot 2018-12-31 at 20 14 20" src="https://user-images.githubusercontent.com/20015567/50567077-b6efa880-0d38-11e9-8d11-ea50884b9d81.png">

I'll retrace my steps to get setup steps to replicate. One moment.

**Comment by jackrobson** [comment]
Steps to reproduce:


1. Created new Ubuntu 16.04 droplet on DigitalOcean.
2. Point DNS for mydomain.com to the new server’s IP address using A record.
3. ssh root@mydomain.com and connect to the new server.
4. curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh
5. postal make-user
6. Change /opt/postal/config/postal.yml to replace example.com references with mydomain.com
7. Run postal restart
8. Go to mydomain.com, login and create an organization.
9. Create a mail server.
10. Setup domain and ensure all DNS records are pointed correctly. 
11. In routing, add a SMTP endpoint at smtp.mydomain.com and ensure it also has a C Name record to point smtp to @.
12. Create email route name@mydomain.com using the SMTP endpoint we made.
13. Create credentials. 
14. Connect email client using these details:
Address: postal.mydomain.com
Port: 25
Username: example-org/mail-server-name (exact value found on the “Read about sending e-mail” page)
15. Test I can send an email to an external domain using PHP (or any scripting language) to check SMTP appears to work for outgoing.
16. Test I can send an email to mydomain.com domain using PHP (or any scripting language) to check SMTP appears to work for incoming.

FAIL

**Comment by jackrobson** [comment]
Maybe it was just a caching issue as this error is no longer apparent, and I'm getting a different error.

**Comment by willpower232** [comment]
If you experience "could not resolve" errors, you can use `dig` on your linux terminal and/or https://whatsmydns.net to make sure that the DNS record exists and is accessible around the world.

It might be that even after the record has been created, your supplier has not started resolving it for whatever reason.
