### ISSUE TITLE
Postal stopped working for certain application. (Rocketchat)

### ISSUE THREAD

**Issue by shinebayar-g** [atech/postal#718]
We've been using postal for months without problem, last month one of our domain got expired and we didn't notice it for 2 days. Since then postal stopped working for that domain..
Example: We're using rocket.chat for our internal communication and it uses postal from email notifications etc. But it doesn't work with postal anymore, if I change SMTP credentials to another SMTP provider's credentials on rocket.chat settings it works.
When I test SMTP settings from rocket.chat UI it doesn't come to postal. How should I troubleshoot this issue?

PS: Postal is working OK for other services

**Comment by willpower232** [comment]
It might be that not all of your settings or DNS records or whatever got reinstated after you got your domain back?

**Comment by shinebayar-g** [comment]
I'm using postal at `postal.mydomain.io` address. I've verified it's root domain `mydomain.io` and it's working great when sending from `whatever@mydomain.io` address.
We're sending emails to `user@mydomain.com` ( expired domain was `mydomain.com` )
In that case what should be causing issue? I don't think anything changed on `mydomain`'s settings. Because it's still working without problem except on postal OR rocket chat.

**Comment by willpower232** [comment]
You could use the `dig` command or https://whatsmydns.net and see if your MX records are still accurate which might help?

**Comment by shinebayar-g** [comment]
Checked, MX records are fine. How can we troubleshoot what's causing the issue?
When sending test email from Rocketchat SMTP settings, postal UI shows no sign of receiving it. Can I check logs somewhere?

**Comment by willpower232** [comment]
Has that resolved the issue? Another thing you could do is watch your logs to see if the server is even connected to.

**Comment by shinebayar-g** [comment]
No, I mean that happened few weeks ago if that matters. What logs should I watch?

**Comment by willpower232** [comment]
Presumably its using the SMTP connection so you should watch the SMTP server logs when emails are supposed to be sent.

**Comment by shinebayar-g** [comment]
Hi @willpower232. When I click "**Test SMTP settings**" button on rocket chat settings, and `tail -f smtp_server.log` on postal server at same time. I'm getting this logs.
```
[smtp.1:4266] [2019-01-12T16:57:50.003] DEBUG -- : [IBBY6Z]    Connection opened from ::ffff:35.197.XX.104
[smtp.1:4266] [2019-01-12T16:57:50.003] DEBUG -- : [IBBY6Z]    Client identified as ::ffff:35.197.XX.104
[smtp.1:4266] [2019-01-12T16:57:50.007] DEBUG -- : [IBBY6Z] <= EHLO [127.0.0.1]
[smtp.1:4266] [2019-01-12T16:57:50.011] DEBUG -- : [IBBY6Z] => 250-My capabilities are
[smtp.1:4266] [2019-01-12T16:57:50.012] DEBUG -- : [IBBY6Z] => 250-STARTTLS
[smtp.1:4266] [2019-01-12T16:57:50.012] DEBUG -- : [IBBY6Z] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:4266] [2019-01-12T16:57:50.056] DEBUG -- : [IBBY6Z] <= STARTTLS
[smtp.1:4266] [2019-01-12T16:57:50.056] DEBUG -- : [IBBY6Z] => 220 Ready to start TLS
[smtp.1:4266] [2019-01-12T16:57:50.069] DEBUG -- : [IBBY6Z]    Connection closed
```

But there is no logs writing in `smtp_sender.log` file at that time.

**Comment by shinebayar-g** [comment]
Alright, I did 2 things on my end.
 I removed these values from `postal.yml` file

```YAML
smtp_server:
  tls_ciphers: TLS_v1 # I'm not even sure what these values mean, I found them from github issues section to fix some error.
  ssl_version: TLS_v1
```

and restarted postal fixed the issue! Thank you.

**Comment by willpower232** [comment]
Ah interesting, it may be that the altered settings prevented rocketchat from connecting securely for whatever reason but the test doesn't actually verify the SSL connection. Will remember that for the future.
