### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by reneklacan** [atech/postal#72]
I wonder why there are no tests at all? Or am I missing something?

**Comment by catphish** [comment]
This was discussed briefly in #14 

> Tests are lacking at the moment. I plan on adding a good suite shortly. The app was put together quite quickly but tests are going to be very much needed to maintain any sort of ability to keep the project maintained well. Expect to see these in the next few weeks.

**Comment by reneklacan** [comment]
@catphish Thank you for answer!
