### ISSUE TITLE
Per-Server Send Limit

### ISSUE THREAD

**Issue by wh4u** [atech/postal#721]
Hello,
Most experienced guys, your assistance please.
Mailserver -> Settings -> Send Limit -> unlimited e-mails every 60 minutes*

This is the default setting.
When on earth is the configuration page for adjusting this limit?
Do i need to edit this via ssh? or directly on a db table?

**Comment by willpower232** [comment]
If you are logged in to the system as an administrator, there should be an "Advanced Settings" option within the "Settings" tab.

The first value on this page is the one you need to modify, a blank value indicates no limit.

![image](https://user-images.githubusercontent.com/1619102/51107918-4d67a380-17e8-11e9-9605-61dde29c7fc4.png)

**Comment by wh4u** [comment]
omg , what a rookie mistake.
thank you

**Comment by shinebayar-g** [comment]
Please close the issue, if it's resolved. This repository has full of resolved issues that stays open. :) / No offense.

**Comment by zeba121** [comment]
Hello, @willpower232 

I have also faced the issue with sending limit but I need monthly limit this hourly limit.

So how can I apply monthly limit?


Thank You

**Comment by willpower232** [comment]
Please see #361
