### ISSUE TITLE
How To Setup Open / Click Tracking

### ISSUE THREAD

**Issue by jackrobson** [atech/postal#722]
I setup my mail server using the quick install method and it's working good.

However, I can't figure out why the open and click tracking doesn't work.

The steps I took to set this up we're:

1. postal register-lets-encrypt youremail@example.com
2. updated postal.yml with 

fast_server:
  enabled: true
  bind_address: 10.16.0.17

3. postal start

What am I missing?

**Comment by jackrobson** [comment]
I'm wondering if I need to change the nginx confirguration somewhat?

It's default at present:

`server {
    listen [::]:80;
    listen 0.0.0.0:80;
    server_name postal.yourdomain.com;
    return 301 https://$host$request_uri;
}

server {
    listen [::]:443 ssl;
    listen 0.0.0.0:443 ssl;
    root /opt/postal/app/public;
    server_name postal.yourdomain.com;
    ssl_certificate      ssl/postal.cert;
    ssl_certificate_key  ssl/postal.key;

    # Generate using: openssl dhparam 4096 -out /etc/ssl/dhparam.pem
    # ssl_dhparam /etc/ssl/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:ECDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;

    location / {
       client_max_body_size 50M;
       try_files $uri $uri/index.html $uri.html @puma;
    }

    location /assets {
       add_header Cache-Control max-age=3600;
    }

    location @puma {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:5000;
    }
}
`

**Comment by jackrobson** [comment]
I see in the documentation for the manual install, you say:

For this documentation we will assume you have allocated some IP addresses:

192.168.1.3 - IPv4 address for management, SMTP and other traffic
192.168.1.4 - IPv4 address for the "fast" web server (used for tracking)

My mail server is hosted at an external IP, let's say it's 111.111.111.111

Should the fast server be 111.111.111.111 to?

**Comment by jackrobson** [comment]
Found another VPS provider:

https://www.vultr.com

You can purchase a second ipv4 in the server control panel, you must hard restart for it to be active, and you make need to follow the link in the ipv4 tab in the control panel, the one in the "Need assistance? View our networking configuration tips and examples." prompt.

I can tell it's working, cause I can ping my new ipv4 ip and it doesn't timeout.

Also, if you pick the smaller ones (make sure to choose the ipv4 options, ipv6 only is no good, and if your server's memory is low, you may fail the postal quick install, unless you add a swap file, i.e. https://devanswers.co/guide-creating-swap-space-ubuntu-16-04/

Will update after I see how it prevents the fast server from failing.

**Comment by jackrobson** [comment]
next step was to go into /etc/nginx/sites-available/default and replace 0.0.0.0 with the main ipv4 address.

sudo systemctl restart nginx

and then did postal restart and now the fast process is running, and I it stays alive, (see if it's running by doing postal status)

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.6           Running      02:34        pid:23192    respawns:0      port:-        tag:-

However, it seems mail tracking still isn't working :(

I send this message '<a href="http://wpsupportuk.xyz">wpsupportuk</a>'

But it arrives into my gmail box still as http://wpsupportuk.xyz, and there are no open tags on the mail I open. :(

*howls to the moon*

**Comment by jackrobson** [comment]
Huzzah!

The last step was to setup a tracking domain, this is done inside the mail server UI, in the domains bit. 

Everything working great. 👍 👍 👍

**Comment by willpower232** [comment]
Glad you figured this out, the secondary IP is the crucial ingredient here.

**Comment by epipheus** [comment]
Can this work with IPv6.  VPSs are stingy with secondary IPv4 addresses these days.

**Comment by willpower232** [comment]
In theory yes but you might have to configure your nginx a bit differently to guarantee access.

**Comment by zeba121** [comment]
Hello @willpower232 

The server on which the postal is installed can be taken by the additional IP of the same server for tracking.
