### ISSUE TITLE
Support for SMTPUTF8?

### ISSUE THREAD

**Issue by sperlic** [atech/postal#724]
Hello,

Recently more and more messages sent by our Postfix server to Postal is bounced with the message `status=bounced (SMTPUTF8 is required, but was not offered by host xxx.xxx.xxx ....)`. According to http://www.postfix.org/SMTPUTF8_README.html from version 3.x Postfix SMTPUTF8 support is enabled by default (our version is 3.1.8), so we resolved the problem by turning off the SMTPUTF8 using following options in Postfix `main.cf`

```
smtputf8_autodetect_classes = bounce
smtputf8_enable = no
strict_smtputf8 = no
```
Is there a possibility for Postal to support SMTPUTF8 in the near future?

**Comment by willpower232** [comment]
I wouldn't say it was impossible but I also wouldn't hold my breath based on the current state of Postal.

I don't think anyone else has mentioned this as a problem so without someone putting the work in, I don't think it will happen.

**Comment by sperlic** [comment]
Thanks for your reply @willpower232 
 
At this moment, this workaround with disabled support for smtputf8 works fine, so while better times do not come, let's go this way.

Issue can be closed for now.

**Comment by willpower232** [comment]
Alas that part is on you :-P
