### ISSUE TITLE
unable to use webhook

### ISSUE THREAD

**Issue by Rishu032** [atech/postal#726]
Hi Guys,

I'm unable to use webhook on my postal server. I have read all the webhook document from wiki but while configuring i'm getting error on portal. Where I'm missing unable to find? Can anyone help me?

![image](https://user-images.githubusercontent.com/44774765/51297146-2e198200-1a45-11e9-98e5-5fa7181530d2.png)

**Comment by Rishu032** [comment]
@willpower232 can you help me please?

**Comment by willpower232** [comment]
HTTP status code 301 means that Postal got redirected from that URL to another which could imply it was presented with a login form or you have another kind of redirect present that needs to ignore Postals IP address.
