### ISSUE TITLE
DNS records, 2 domains

### ISSUE THREAD

**Issue by Gino** [atech/postal#727]
Hi there,

I am really struggling with the DNS records.

Let's say that I have the Postal instance on domain A, I would like to have `test@a.com` but also `test@b.com` (a second domain, on the same server/ip actually).

I assume that I need the same DNS records for domain B as I do for domain A, right? I managed to fix the DNS records for domain A, but unfortunately domain B is broken now. Any mails, being sent to domain B, are staying as "Pending", everything works on domain A though.

Here is a screenshot of the DNS records:

![hi](https://i.gyazo.com/d64de2ddb65b6c41db7da8ddff433561.png)

Should I use other DNS records for domain B, instead of using the one of domain A? I am quite confused.

I hope that someone could help me here.

Thanks a lot!

**Comment by willpower232** [comment]
Hope you managed to resolve your problem. Its easier if your Postal server has its own domain/subdomain because then all domains you want to use with Postal can have the same records.
