### ISSUE TITLE
Authentication failing for certain applications.

### ISSUE THREAD

**Issue by shinebayar-g** [atech/postal#729]
I've tried to use postal credentials for [Grafana](https://github.com/grafana/grafana) project's alerting emails. When I tried to send test email it says: `535 Denied`. But my credentials definitely works for other applications. I've tried all of options of Grafana SMTP settings, no luck.
Also few week earlier, I've tried to use postal credentials for another django project, but it was failing too. But that time I just blamed my django application and thought it was bugged. But today it's failed on Grafana project too. Now I'm worried about something might be wrong on postal side.. Anyone encountered same situation?

- Anyone could verify that postal credentials is not working on Django or Grafana project?

`smtp_server.log`

```
[smtp.1:4628] [2019-01-22T01:36:54.826] DEBUG -- : [VRVQJW]    Connection opened from ::ffff:XXX.XXX.XXX.XXX
[smtp.1:4628] [2019-01-22T01:36:54.826] DEBUG -- : [VRVQJW]    Client identified as ::ffff:XXX.XXX.XXX.XXX
[smtp.1:4628] [2019-01-22T01:36:54.829] DEBUG -- : [VRVQJW] <= EHLO grafana-0
[smtp.1:4628] [2019-01-22T01:36:55.199] DEBUG -- : [VRVQJW] => 250-My capabilities are
[smtp.1:4628] [2019-01-22T01:36:55.199] DEBUG -- : [VRVQJW] => 250-STARTTLS
[smtp.1:4628] [2019-01-22T01:36:55.199] DEBUG -- : [VRVQJW] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:4628] [2019-01-22T01:36:55.243] DEBUG -- : [VRVQJW] <= STARTTLS
[smtp.1:4628] [2019-01-22T01:36:55.243] DEBUG -- : [VRVQJW] => 220 Ready to start TLS
[smtp.1:4628] [2019-01-22T01:36:55.250] DEBUG -- : [VRVQJW] <= EHLO grafana-0
[smtp.1:4628] [2019-01-22T01:36:55.615] DEBUG -- : [VRVQJW] => 250-My capabilities are
[smtp.1:4628] [2019-01-22T01:36:55.615] DEBUG -- : [VRVQJW] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:4628] [2019-01-22T01:36:55.659] DEBUG -- : [VRVQJW] <= AUTH CRAM-MD5
[smtp.1:4628] [2019-01-22T01:36:55.659] DEBUG -- : [VRVQJW] => 334 REDACTED=
[smtp.1:4628] [2019-01-22T01:36:55.661] DEBUG -- : [VRVQJW] <= REDACTED
[smtp.1:4628] [2019-01-22T01:36:55.663] DEBUG -- : [VRVQJW] => 535 Denied
[smtp.1:4628] [2019-01-22T01:36:55.665] DEBUG -- : [VRVQJW] <= *
[smtp.1:4628] [2019-01-22T01:36:55.665] DEBUG -- : [VRVQJW] => 502 Invalid/unsupported command
[smtp.1:4628] [2019-01-22T01:36:55.667] DEBUG -- : [VRVQJW] <= QUIT
[smtp.1:4628] [2019-01-22T01:36:55.667] DEBUG -- : [VRVQJW] => 221 Closing Connection
[smtp.1:4628] [2019-01-22T01:36:55.667] DEBUG -- : [VRVQJW]    Connection closed
```

**Comment by shinebayar-g** [comment]
Yea I'm wondering why auth is failing when credentials are right.
This is my grafana.ini smtp settings: 
And I'm quite sure it's right credentials.
```
[smtp]
enabled = true
host = postal.mydomain.com:2525
user = my-smtp-user
password = KHG8PnQR14Z0cKZXvb0Zz7af
;cert_file =
;key_file =
skip_verify = false          #(tried both true/false)
from_address = noreply_grafana@mydomain.com
from_name = Grafana
```

If it's possible can you reproduce the issue?
[Grafana docker installation](http://docs.grafana.org/installation/docker/) won't take longer than 5 minutes .

**Comment by willpower232** [comment]
Your log says that Postal is being connected to so there isn't a connection issue.

The problem will be with the username. Make sure that it is `something/my-smtp-user` as shown to you within the Postal UI.

**Comment by shinebayar-g** [comment]
oh shit, i see i see. Thanks a million. It works!
My username was: `org-name/smtp-server-name` combination.

Out of curiosity, I was using that `Name` field as smtp username and `Key` field as smtp password for months and it works for most of applications. Does that mean I was doing whole thing wrong all this time? Or I'm actually supposed to use `Name` field as username?

I just want to know which one is right one.

**Comment by willpower232** [comment]
Interestingly the username isn't used in the regular SMTP authentication (as per the comment I linked to).

The help page about "sending outgoing e-mails" is accurate for each server within Postal so I'd follow those instructions wherever possible.

**Comment by shinebayar-g** [comment]
Thank you @willpower232 , you're really helping a lot of people. Have a good day man.
