### ISSUE TITLE
Can´t receive messages

### ISSUE THREAD

**Issue by Patralos** [atech/postal#73]
Hi,

i am able to send mails, without any problems, all DNS checks are ok, but I can't receive mails via postal.

If I try to answer a mail, for example to test@my.domain, the server responds with 

`<test@my.domain>: host mail.my.domain[94.23.XX.XX] said: 530
    Authentication required (in reply to RCPT TO command)`

Diagnostic-Code: smtp; 530 Authentication required

Did I miss some configuration?

Thx
Patrick

**Comment by adamcooke** [comment]
This error happens if there's no route found for the given domain & alias. I assume you do have a route configured for the correct domain & alias?

**Comment by Patralos** [comment]
Thx, I thought, that every mail without an endpoint would be delivered to the incoming mail function of postal.

**Comment by jackrobson** [comment]
Hm... I'm struggling to work out another reason this can fail.

I setup a route which can be seen here:

<img width="1188" alt="screen shot 2018-12-31 at 23 49 32" src="https://user-images.githubusercontent.com/20015567/50569198-00e78700-0d57-11e9-970f-a256175e95e9.png">

But still I get bounce back :(

<img width="1115" alt="screen shot 2018-12-31 at 23 51 41" src="https://user-images.githubusercontent.com/20015567/50569204-0b098580-0d57-11e9-835c-e4a4b2da7250.png">

**Comment by jackrobson** [comment]
> This error happens if there's no route found for the given domain & alias. I assume you do have a route configured for the correct domain & alias?

Hm... I'm struggling to work out another reason this can fail.

I setup a route which can be seen here:

<img width="1188" alt="screen shot 2018-12-31 at 23 49 32" src="https://user-images.githubusercontent.com/20015567/50569198-00e78700-0d57-11e9-970f-a256175e95e9.png">

But still I get bounce back :(

<img width="1115" alt="screen shot 2018-12-31 at 23 51 41" src="https://user-images.githubusercontent.com/20015567/50569204-0b098580-0d57-11e9-835c-e4a4b2da7250.png">

**Comment by jackrobson** [comment]
Got a new droplet working with following steps:

1. Created new Ubuntu 16.04 droplet on DigitalOcean.
2. Point DNS for mydomain.com to the new server’s IP address using A record.
3. ssh root@mydomain.com and connect to the new server.
4. curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh
5. postal make-user
6. Change /opt/postal/config/postal.yml to replace example.com references with mydomain.com
7. Run postal restart
8. Go to mydomain.com, login and create an organization.
9. Create a mail server.
10. Setup domain and ensure all DNS records are pointed correctly.
11. In routing, add an address endpoint for  name@mydomain.com
12. Create credentials.
13. Update /opt/postal/config/postal.yml with SMTP settings found on the “Sending e-mail” help page.
14. Run postal restart
15. postal test-app-smtp name@myotherdomain.com works fine and incoming mail works too! 👍

**Comment by willpower232** [comment]
If you're still having this problem, please open a new issue with what you expect to happen in detail. I would imagine there is only a small confusion somewhere.
