### ISSUE TITLE
Multiple systems sending email for same domain and webhooks

### ISSUE THREAD

**Issue by teemurainio** [atech/postal#732]
Is it possible to have multiple systems sending email for same domain and so that each system receives webhooks only for emails it sent. For example - consider there are systems A, B and C sending email for domain foobar.com, A receives webhooks only for emails it sent i.e. not webhooks on emails sent by B or C?

**Comment by willpower232** [comment]
Webhooks are constrained to servers but domains can apply to a whole organization.

You could add your domain to an organization and then create a server for each system and configure the credential and webhook in each server.

That would ensure each system only receives webhooks for the emails it sends and also provide you with visibility into which system is sending what emails.

**Comment by teemurainio** [comment]
Thank You!
