### ISSUE TITLE
How to bypass From/Sender name is not valid

### ISSUE THREAD

**Issue by saporus** [atech/postal#734]
Hello @willpower232 ,

Thanks for this wonderful sofware.

I was a Mailwizz forum where I saw the admin recommending Postal. I have been battling with Posal since 5 days ago because I had never used such via Ubuntu. In fact, this is my first time of operating ubuntu.

So, I have been able to install and configure postal, I have also added and verify one domain successfully.

I have been able to use the verified domain email address to send campaign on Mailwizz app which was successful too.

My issue now is, since I am using Mailwizz Email Marketing App and the mailer is "SwifTmailer 5.4.x". I would love to use any email address/domain as "From" the sender campaign. I have read this. I have already enabled "SEND AS ANY" and also read this article https://github.com/atech/postal/issues/277 but I have not been able to do this successfully. Even in Mailwizz App, there is a place to configure "Additional headers " I did that by adding the valid domain configured at postal but still same issue.

Note: My Mailwizz App is hosted on another server different from Postal server.

Is there any other way I could bypass the  From/Sender name is not valid verification?

Looking forward to read back from you.

Thanks

**Comment by saporus** [comment]
@willpower232 could you please respond to this?

Thank you.

**Comment by willpower232** [comment]
Hope you figured this out but even with "send as any" turned on, I believe you need to supply a valid "from" address or something along those lines.
