### ISSUE TITLE
Where do quarantined messages go?

### ISSUE THREAD

**Issue by timraybould** [atech/postal#735]
I have incoming mail being routed to an HTTP endpoint and have it set for spam above threshold of 5.0 to be quarantined. There have been reports of some mail not being delivered to a users inbox, but, I see no indication of this in Postal. I suspect it's getting caught in the spam filter, but, don't know where to go to triage quarantined items.

**Comment by willpower232** [comment]
I don't believe there is a quarantine on Postals end, if the message you're after doesn't appear under Outgoing, Incoming, Queue, or Held then Postal hasn't seen the message at all.

I know it is the case with some providers, particularly Hotmail/Outlook, that the recipients email system will tell Postal that the message has been "queued for delivery" or some other successful status and then never appears in the recipients inbox.

**Comment by timraybould** [comment]
Thanks! That's good to know moving forward. It turns out the issue was that messages which were (attempting) to be sent over TLS weren't getting through, because Postal didn't have permission to access the directory where I had Certbot store the certificate. Fixed the permission issue and now emails are being delivered nicely.
