### ISSUE TITLE
Tracking image/link isn't added to new mails

### ISSUE THREAD

**Issue by Patralos** [atech/postal#74]
Hi,

I configured the TrackingFeature and the Fastserver.  

Both seem to work fine:
track.my.domain - CNAME configured correctly - SSL disabled
http://track.my.domain returns "Hello." in my browser.

Track Loads and Track Clicks is set to on.

But my test mails sent via smtp and via web interface both don't contain tracking information.

Thx
Patralos

**Comment by mattmartincouk** [comment]
Are you using plain text or HTML emails, or both?

**Comment by Patralos** [comment]
It tried both of them, html and plain.

**Comment by TadiNate** [comment]
Yes i need it.

**Comment by adamcooke** [comment]
This is likely a configuration issue. I have tested this myself and there are no other reports of it not working.

**Comment by webhostinggeek** [comment]
I am not able to get ONLY open tracking work. If I send an email with tracking URL, and user clicks on this URL, then Postal shows as Opened.

What about emails without any URL's? Can't we track normal email open? Tried both plain text and Html emails.

**Comment by willpower232** [comment]
If you have tracking enabled and your email contains a HTML part, Postal will insert a tracking image at the end of it.

If your email client blocks images initially (i.e. Outlook) then it will not be detected as open until the recipient loads the images (or presumably clicks on any link)

**Comment by webhostinggeek** [comment]
Nope. No luck. Sent HTML emails but simple open tracking does NOT work.

Same settings and when URL is added to HTML email and clicked by user, Postal shows as Opened.

I myself tested it with recipient email on Gmail/Yahoo.

**Comment by willpower232** [comment]
Can you see the source of the messages and an ampimg element at the bottom of the message?

**Comment by webhostinggeek** [comment]
<img width="965" alt="screen shot 2017-07-26 at 2 28 37 pm" src="https://user-images.githubusercontent.com/29979399/28613022-c1a5c6fe-720e-11e7-908b-c8a40f401c70.png">

Can't see any ampimg element.

**Comment by willpower232** [comment]
So if you are getting click tracking but not open tracking it sounds like everything is correct except for the settings. Check your tracking domain settings and make sure both are set to "Yes":

![capture](https://user-images.githubusercontent.com/1619102/28613711-1257de4e-71eb-11e7-9fa2-fb698965da27.PNG)

It might also be worth setting them to "No", saving, and setting them to "Yes" again.

**Comment by webhostinggeek** [comment]
Setting to "No" and then "yes" seems to have done the job.

**Comment by TadiNate** [comment]
I don't understand what can I doing these I need detail explanations

**Comment by willpower232** [comment]
@TadiNate I suggest you open a new issue with a description of what problems you are experiencing
