### ISSUE TITLE
Request for advice on webhook for bounces for MailWizz

### ISSUE THREAD

**Issue by brinnington** [atech/postal#743]
Hi,

Does anyone have a working webhook for bounces for MailWizz?

I have almost completed the installation of Postal, but the webhook for bounces has left me stumped. Any help on this would be much appreciated.

Best,

Bob

**Comment by saporus** [comment]
Hello @brinnington 

Here you go https://www.mymailwizzistallaionurl.com/dswh/postal

Just add `/dswh/postal` to your mailwizz installation url and configure the webhook at postal by adding the url to the postal webhook url filed.

If you do not want to get your server resources get bombed which would make your mailwizz app very very very slow in case you are sending large volume of email.

In the postal Event option, just choose **No - I'will choose which requests to send** then mark only this two

1. **MessageDelayed**
2. **MessageDelivery Failed**

The first one is for soft bounces while the second one is for hard bounces.

Let me know if you have more question related to this.

Thanks

**Comment by brinnington** [comment]
Hello @saporus 

Thank you very much for your help on this. 

And thanks too for the information on the postal Event option and the selection of MessageDelayed (soft bounces) and MessageDelivery Failed (hard bounces). It's much appreciated.

Best,

Bob
