### ISSUE TITLE
502 TLS not available

### ISSUE THREAD

**Issue by ccorreia64** [atech/postal#745]
Hi,

I followed this guide https://github.com/atech/postal/issues/614

The dns are well configured, from postal it tells me to send correct, but when I use PHPMailer with the TLS option to send emails I get this message in the log smtp_server.log

[smtp.1:8397] [2019-02-14T16:25:29.067] DEBUG -- : [VMX1SS]    Connection opened from ::ffff:188.93.78.75
[smtp.1:8397] [2019-02-14T16:25:29.067] DEBUG -- : [VMX1SS]    Client identified as ::ffff:188.93.78.75
[smtp.1:8397] [2019-02-14T16:25:29.068] DEBUG -- : [VMX1SS] <= EHLO newsletteruv.es
[smtp.1:8397] [2019-02-14T16:25:29.072] DEBUG -- : [VMX1SS] => 250-My capabilities are
[smtp.1:8397] [2019-02-14T16:25:29.073] DEBUG -- : [VMX1SS] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:8397] [2019-02-14T16:25:29.116] DEBUG -- : [VMX1SS] <= STARTTLS
[smtp.1:8397] [2019-02-14T16:25:29.117] DEBUG -- : [VMX1SS] => 502 TLS not available
[smtp.1:8397] [2019-02-14T16:25:29.118] DEBUG -- : [VMX1SS] <= QUIT
[smtp.1:8397] [2019-02-14T16:25:29.118] DEBUG -- : [VMX1SS] => 221 Closing Connection
[smtp.1:8397] [2019-02-14T16:25:29.118] DEBUG -- : [VMX1SS]    Connection closed

If I activate the SSL option I get this

[smtp.1:8397] [2019-02-14T17:02:45.778] DEBUG -- : [NTWIOY]    Connection opened from ::ffff:188.93.78.83
[smtp.1:8397] [2019-02-14T17:02:45.779] DEBUG -- : [NTWIOY]    Client identified as ::ffff:188.93.78.83
[smtp.1:8397] [2019-02-14T17:02:45.779] DEBUG -- : [NTWIOY] => 502 Invalid/unsupported command
[smtp.1:8397] [2019-02-14T17:02:45.780] DEBUG -- : [NTWIOY] => 502 Invalid/unsupported command
[smtp.1:8397] [2019-02-14T17:02:45.780] ERROR -- : [NTWIOY] An error occurred while processing data from a client.
[smtp.1:8397] [2019-02-14T17:02:45.780] ERROR -- : [NTWIOY] Errno::EPIPE: Broken pipe
[smtp.1:8397] [2019-02-14T17:02:45.781] ERROR -- : [NTWIOY] /opt/postal/app/lib/postal/smtp_server/server.rb:166:in `write'
[smtp.1:8397] [2019-02-14T17:02:45.781] ERROR -- : [NTWIOY] /opt/postal/app/lib/postal/smtp_server/server.rb:166:in `block (3 levels) in run_event_loop'
[smtp.1:8397] [2019-02-14T17:02:45.781] ERROR -- : [NTWIOY] /opt/postal/app/lib/postal/smtp_server/server.rb:163:in `each'
[smtp.1:8397] [2019-02-14T17:02:45.781] ERROR -- : [NTWIOY] /opt/postal/app/lib/postal/smtp_server/server.rb:163:in `block (2 levels) in run_event_loop'
[smtp.1:8397] [2019-02-14T17:02:45.781] ERROR -- : [NTWIOY] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `select'
[smtp.1:8397] [2019-02-14T17:02:45.782] ERROR -- : [NTWIOY] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `block in run_event_loop'
[smtp.1:8397] [2019-02-14T17:02:45.782] ERROR -- : [NTWIOY] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `loop'
[smtp.1:8397] [2019-02-14T17:02:45.783] ERROR -- : [NTWIOY] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `run_event_loop'
[smtp.1:8397] [2019-02-14T17:02:45.783] ERROR -- : [NTWIOY] /opt/postal/app/lib/postal/smtp_server/server.rb:259:in `run'
[smtp.1:8397] [2019-02-14T17:02:45.783] ERROR -- : [NTWIOY] /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
[smtp.1:8397] [2019-02-14T17:02:45.783] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
[smtp.1:8397] [2019-02-14T17:02:45.783] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
[smtp.1:8397] [2019-02-14T17:02:45.783] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
[smtp.1:8397] [2019-02-14T17:02:45.784] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
[smtp.1:8397] [2019-02-14T17:02:45.784] ERROR -- : [NTWIOY] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[smtp.1:8397] [2019-02-14T17:02:45.784] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
[smtp.1:8397] [2019-02-14T17:02:45.784] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
[smtp.1:8397] [2019-02-14T17:02:45.784] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
[smtp.1:8397] [2019-02-14T17:02:45.785] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
[smtp.1:8397] [2019-02-14T17:02:45.785] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
[smtp.1:8397] [2019-02-14T17:02:45.785] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
[smtp.1:8397] [2019-02-14T17:02:45.785] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
[smtp.1:8397] [2019-02-14T17:02:45.785] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
[smtp.1:8397] [2019-02-14T17:02:45.786] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
[smtp.1:8397] [2019-02-14T17:02:45.786] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
[smtp.1:8397] [2019-02-14T17:02:45.786] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
[smtp.1:8397] [2019-02-14T17:02:45.786] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
[smtp.1:8397] [2019-02-14T17:02:45.786] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
[smtp.1:8397] [2019-02-14T17:02:45.786] ERROR -- : [NTWIOY] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'

I would really appreciate the help. Thx!

Sorry for my english

**Comment by willpower232** [comment]
According to https://stackoverflow.com/questions/39280938/phpmailer-sends-with-tls-even-when-encryption-is-not-enabled, PHPMailer uses opportunistic TLS which is the best approach here (i.e. what you did first).

You either need to disable TLS in PHPMailer OR enable TLS in your Postal config.

You will need to provide an SSL certificate in order to do enable TLS. If you have a certificate in place for nginx to access the UI, you can use that one.

The values you need to set in `/opt/postal/config/postal.yml` are these ones
![image](https://user-images.githubusercontent.com/1619102/52955474-a943c000-3384-11e9-86e0-697e5bd44442.png)

**Comment by ccorreia64** [comment]
Hi, i disabled 

```
$mail->SMTPSecure = '' 
$mail->SMTPAutoTLS = false 
```

and works.

But when activating the TLS I still get the error


![data-1](https://user-images.githubusercontent.com/5826696/52965038-26caf880-33a4-11e9-8ff4-54bc1686a30b.jpg)
![data-2](https://user-images.githubusercontent.com/5826696/52965062-377b6e80-33a4-11e9-9028-d13ee6b4fc39.jpg)


I have the certificate configured with user permissions and it still does not work, what could be happening?

I have verified that the certificate is valid here [https://www.ssllabs.com/ssltest/analyze.html?d=newsletteruv.es&latest](https://www.ssllabs.com/ssltest/analyze.html?d=newsletteruv.es&latest)

Sorry for my english

**Comment by willpower232** [comment]
You'll notice in my screenshot that the settings I changed are under `smtp_server` but you have put the settings under `smtp` which is something else.

**Comment by ccorreia64** [comment]
Thank you so much! Now it is working!

Regards!
