### ISSUE TITLE
Postal intialize error

### ISSUE THREAD

**Issue by simplyprasu** [atech/postal#748]
getting the below error, please let me know the solution

postal@ubuntu-s-4vcpu-8gb-sfo2-01:~$ postal initialize
Initializing database
rake aborted!
ActiveRecord::ProtectedEnvironmentError: You are attempting to run a destructive action against your 'production' database.
If you are sure you want to continue, run the same command with the environment variable:
DISABLE_DATABASE_ENVIRONMENT_CHECK=1
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:51:in `check_protected_environments!'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:11:in `block (2 levels) in <top (required)>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:schema:load => db:check_protected_environments
(See full trace by running task with --trace)

**Comment by willpower232** [comment]
Have you already been running Postal before trying this command?

**Comment by adamcooke** [comment]
We're struggling to keep track of genuine bugs with the huge volume of user support in the issue tracker. We've created a new Google Group for user support issues which is where any support issues should be directed: https://groups.google.com/forum/#!forum/postal-support

I'll close this issue but you can re-post with a link to it in the forum if you still require assistance.
