### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by destroyer998** [atech/postal#750]
Hey,

Short questions, is this repository still being maintained?

**Comment by willpower232** [comment]
Its not absolutely perfect but I'd say it was yes.

**Comment by emielmolenaar** [comment]
Came here to ask this question :smile:

**Comment by alinalexandru** [comment]
I wanted to ask the same 2-3 weeks ago.
The reason is that there are some small PRs available that are not merged.

**Comment by willpower232** [comment]
Unfortunately, the only people with the ability to merge are atech so the most the community can do is discuss issues and make PRs right now.

**Comment by catphish** [comment]
We've been rather busy, but we're still keen to maintain it :slightly_smiling_face:
