### ISSUE TITLE
Web app sending via Postal

### ISSUE THREAD

**Issue by criskolkman** [atech/postal#753]
Hello,

I have my web app setup using Postal as relay but came across a strange issue.
I have added (smtp) credentials, but when I send mails via those credentials I get following error:

`authentication failure [SMTP: Invalid response code received from server (code: 535, response: Denied)]`

When I use the default credentials (see image below) the sending via Postal is fine.

![image](https://user-images.githubusercontent.com/17678609/53101770-b39fbe80-352a-11e9-8f3d-8a78117529b8.png)

**Comment by willpower232** [comment]
`535 Denied` only happens during an authentication failure when using `CRAM-MD5`

Make sure the username and password are spelled correctly and that you're using a from domain that is in the same server as the credentials.

If thats not the problem, it might be worth changing your type of SMTP authentication in your web app.

**Comment by adamcooke** [comment]
We're struggling to keep track of genuine bugs with the huge volume of user support in the issue tracker. We've created a new Google Group for user support issues which is where any support issues should be directed: https://groups.google.com/forum/#!forum/postal-support

I'll close this issue but you can re-post with a link to it in the forum if you still require assistance.
