### ISSUE TITLE
Everything works great, but not open or click tracking...

### ISSUE THREAD

**Issue by ip-aa** [atech/postal#754]
Hi,
I'm looking for a bit of guidance here.  I've setup the server following all the guides and everything is up and running, but for some reason, I just can't seem to get open and click tracking to work.

- Sending email via smtp and via the api are tested and working.
- All of the DNS configurations for Tracking Domain and for the Mail server are showing green
- I've enabled the Fast Web server, tested loading the server directly in a web browser and I see "Hello."
- SSL for the tracking domain doesn't seem to want to work though.  It stays in a "Processing state" so I disabled SSL.  (I've run `postal register-lets-encrypt ` and the lets-encrypt log file shows that it completed successfully)

I've tailed all the log files while sending mail (via the api and smtp) and I don't see anywhere that shows the pixel being added or the links being rewritten.

Can you point me to where I should be looking to debug this?  I can't for the life of me figure it out.

**Comment by willpower232** [comment]
If the link was successfully replaced, you should see the shortened link when looking at the HTML/Plain Text view of the message in the UI, I'm not sure how well these things get logged.

FYI if your message doesn't include a HTML body, it will not get a tracking pixel.

**Comment by ip-aa** [comment]
Here is what I am testing with.  
So this should work, correct?

```
{
	"to": [
		"test1@xxxxxx.com",
		"test2@xxxxxx.com"
	],
	
	"from": "admin@xxxxxx.com",
	"subject": "yet another test....",
	"tag": "TEST",
	"sender": "admin@xxxxxx.com",
	"html_body": "<html><head></head><body><p><a href=\"https://google.ca/\">Test Link</a></p></body></html>"
}

**Comment by willpower232** [comment]
Should be enough, can you see if the link gets replaced in the HTML view of the message in the UI?

**Comment by ip-aa** [comment]
I checked, the link doesn't get replaced unfortunately.

**Comment by willpower232** [comment]
Okay, that would imply that tracking isn't enabled for the organisation. Has the mail server definitely got a fully set up click tracking domain in the UI?

**Comment by adamcooke** [comment]
We're struggling to keep track of genuine bugs with the huge volume of user support in the issue tracker. We've created a new Google Group for user support issues which is where any support issues should be directed: https://groups.google.com/forum/#!forum/postal-support

I'll close this issue but you can re-post with a link to it in the forum if you still require assistance.
