### ISSUE TITLE
Fast_server not responding for tracking

### ISSUE THREAD

**Issue by stikekar** [atech/postal#756]
My postal management is working beautifully.

However the track.postal.membition.com does not give me the hello page. Below are some relevant outputs for review. At this time I am completely lost :(:(

I am this close to using a beautiful product in production. Please help!!!!!!!!!!

IP Address of eth0 172.31.9.182 Public IP: 52.53.74.122
IP ADdress of eth1 172.31.4.52  Public IP: 13.52.106.112

root@ip-172-31-9-182:~# netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 172.31.9.182:443        0.0.0.0:*               LISTEN      17663/nginx -g daem
tcp        0      0 172.31.4.52:443         0.0.0.0:*               LISTEN      17449/[postal] fast
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      17447/[postal] web.
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      1355/beam.smp   
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1784/mysqld     
tcp        0      0 172.31.9.182:80         0.0.0.0:*               LISTEN      17663/nginx -g daem
tcp        0      0 172.31.4.52:80          0.0.0.0:*               LISTEN      17449/[postal] fast
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      1508/epmd       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1472/sshd       
tcp6       0      0 :::25                   :::*                    LISTEN      17457/[postal] smtp

Here is the output from the postal.yml

postal@ip-172-31-9-182:~/config$ more postal.yml

opt/postal/config/fast_sweb:
  # The host that the management interface will be available on
  host: postal.membition.com
  # The protocol that requests to the management interface should happen on
  protocol: https

web_server:
  bind_address: 172.31.9.182
  port: 5000
  max_threads: 5

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address: 172.31.4.52
  port: 80
  ssl_port: 443
  proxy_protocol: false
  default_private_key_path: /etc/letsencrypt/live/postal.membition.com-0002/fullchain.pem
  default_tls_certificate_path: /etc/letsencrypt/live/postal.membition.com-0002/privkey.pem

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: XXXXXXXXXX
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: XXXXXXXXXX
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: XXXXXXXXXX
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - postal.membition.com
  smtp_server_hostname: postal.membition.com
  spf_include: spf.postal.membition.com
  return_path: rp.postal.membition.com
  route_domain: routes.postal.membition.com
  track_domain: track.postal.membition.com
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp

smtp_server:
  host: 172.31.9.182
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.membition.com-0002/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/postal.membition.com-0002/privkey.pem
  tls_ciphers: TLSv1_1
  ssl_version: TLSv1_1
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: postal.membition.com
  port: 25
  username: XXXXXXXXXXXXXXXXXXX
  password: XXXXXXXXxXXXXXXXXXXX
  from_name: XXXXXXXXXXX
  from_address: XXXXXXXXXXX

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: ae8c84af3d32840ff496d0b67b1e02e290a3277eb255fb61b3c52d86385c01fd1a81c5a9983005e01bb4cf2ebacda019f57723251aef7
7e51e469910be74fe3f3975e3cccf5fc49fdf5254ddd8c19631affe9c9148436853f1d6f6f985162a375f2b06dc54847e811d497cf135f1b491ea0245ac
8ad7310cc532b95b649be873

NGINX sites-enabled/default

server {
    listen 172.31.9.182:80;
    server_name postal.membition.com;
    return 301 https://$host$request_uri;
}

server {
    listen 172.31.9.182:443 ssl;
    root /opt/postal/app/public;
    server_name postal.membition.com;
    ssl_certificate      /etc/letsencrypt/live/postal.membition.com-0002/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/postal.membition.com-0002/privkey.pem;

    # Generate using: openssl dhparam 4096 -out /etc/ssl/dhparam.pem
    # ssl_dhparam /etc/ssl/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:E
CDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;

    location / {
       client_max_body_size 50M;
       try_files $uri $uri/index.html $uri.html @puma;
    }

    location /assets {
       add_header Cache-Control max-age=3600;
    }

    location @puma {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://172.31.9.182:5000;
    }
}

DNS records

![image](https://user-images.githubusercontent.com/21090746/53620230-0c183100-3ba7-11e9-8a89-fab64248a526.png)

**Comment by cmmata** [comment]
If you try `telnet 172.31.4.52 443`,do you connect to the server?

**Comment by willpower232** [comment]
Try running `postal status` and `netstat -lnp` to see that its running then have a look at any firewalls for that IP address.

**Comment by stikekar** [comment]
I can telnet to ip address 172.31.4.52 443 but it closes the connection,  and the `postal status` show that the fast_server is running. Here is the `netstat -lnp` output. The firewall is disabled. I checked using the command `ufw status `

root@ip-172-31-9-182:~# telnet 172.31.4.52 443
Trying 172.31.4.52...
Connected to 172.31.4.52.
Escape character is '^]'.
Connection closed by foreign host.


root@ip-172-31-9-182:~# netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 172.31.9.182:443        0.0.0.0:*               LISTEN      32354/nginx -g daem
`tcp        0      0 172.31.4.52:443         0.0.0.0:*               LISTEN      32204/[postal] fast`
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      32202/[postal] web.
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      1355/beam.smp   
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1784/mysqld     
tcp        0      0 172.31.9.182:80         0.0.0.0:*               LISTEN      32354/nginx -g daem
`tcp        0      0 172.31.4.52:80          0.0.0.0:*               LISTEN      32204/[postal] fast`
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      1508/epmd       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1472/sshd       
tcp6       0      0 :::25                   :::*                    LISTEN      32213/[postal] smtp
tcp6       0      0 :::5672                 :::*                    LISTEN      1355/beam.smp   
tcp6       0      0 :::4369                 :::*                    LISTEN      1508/epmd       
tcp6       0      0 :::22                   :::*                    LISTEN      1472/sshd       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1073/dhclient

**Comment by cmmata** [comment]
Do you see something strange in postal/log/fast_server.log? I see you've got a nginx service running, do you have it explicitly listening only on the other IP address?

**Comment by willpower232** [comment]
Netstat implies everything is working correctly as you describe.

Telnet will work on the internal IP address (13.52.106.112) because its local but the equivalent external address (13.52.106.112) is not responding which means there must be some kind of firewall present either on the server or with your server provider.

Alternatively, the 13.52.106.112 address isn't correct.

**Comment by adamcooke** [comment]
We're struggling to keep track of genuine bugs with the huge volume of user support in the issue tracker. We've created a new Google Group for user support issues which is where any support issues should be directed: https://groups.google.com/forum/#!forum/postal-support

I'll close this issue but you can re-post with a link to it in the forum if you still require assistance.
