### ISSUE TITLE
Local IP to Domain

### ISSUE THREAD

**Issue by emresaracoglu** [atech/postal#758]
Hello,

I installed Postal on my Proxmox server. But I can connect with the local IP address. Connection with domain name is not possible. 

Domain screen: 

> ERR_TOO_MANY_REDIRECTS

I updated `postal.yml` and restart container (LXC) but I still not connect via domain.

What could be the reason?
Thank you.

**Comment by willpower232** [comment]
It might be that your nginx is redirecting you into a loop, I'm not sure how LXC is involved but presumably theres some confusion at the proxy end.
