### ISSUE TITLE
unable to create Orgnasitation or logout

### ISSUE THREAD

**Issue by martandya** [atech/postal#759]
Iall done without any Error , successfully login to webhook , 
but not able to unable to create Orgnasitation or logout ...
it give error following error : -
![error_pages](https://user-images.githubusercontent.com/35959181/53831132-1329af80-3faa-11e9-9171-eb44c8ebfaa6.PNG)

[web.1:2296] [2019-03-05T19:11:35.616] INFO -- : Started POST "/organizations" for 112.133.251.190 at 2019-03-05 19:11:35 +0000
[web.1:2296] [2019-03-05T19:11:35.617] INFO -- : Processing by OrganizationsController#create as HTML
[web.1:2296] [2019-03-05T19:11:35.617] INFO -- :   Parameters: {"utf8"=>"✓", "organization"=>{"name"=>"a1", "permalink"=>"e"}, "commit"=>"Create organization"}
[web.1:2296] [2019-03-05T19:11:35.626] WARN -- : Can't verify CSRF token authenticity.
[web.1:2296] [2019-03-05T19:11:35.629] INFO -- : Completed 422 Unprocessable Entity in 11ms (ActiveRecord: 2.8ms)
[web.1:2296] [2019-03-05T19:11:35.631] FATAL -- :
[web.1:2296] [2019-03-05T19:11:35.632] FATAL -- : ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
[web.1:2296] [2019-03-05T19:11:35.632] FATAL -- :
[web.1:2296] [2019-03-05T19:11:35.632] FATAL -- : vendor/bundle/ruby/2.3.0/gems/actionpack-5.2.1/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.2.1/lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.2.1/lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'

i follow you previous post [#158](https://github.com/atech/postal/issues/158) but nothing help ...
Please suggest !!

Thank You.

**Comment by saporus** [comment]
Hello,

Firstly, your Postal login screen shouldn't be naked. That means something is wrong with your installation or config file or DB or some files there.

Thanks

**Comment by martandya** [comment]
What do you meant about naked ?
i am able to login this ?

**Comment by willpower232** [comment]
For some reason, your Postal installation is not loading its page assets like CSS, images, and javascript.

This implies your install of Postal did not succeed fully or something has since broken and it is unable to load various pages/files.

Are you able to reinstall it?

**Comment by martandya** [comment]
strange ... for whole installation i did not any error !
BTW is it might be due to nginx reconfiguration ?
Yes , i can reinstall it , even i want to install it with my all 15 servers .... so me try for another one !

**Comment by martandya** [comment]
Is it work for apache instead of nginx ?

**Comment by willpower232** [comment]
It is possible your nginx server block is incorrect which might explain the missing assets but the error you initially encountered suggests something is wrong in the Ruby.

You should be able to backup and restore or reuse your database without remaking all your servers.

**Comment by martandya** [comment]
i follow all steps of link https://github.com/atech/postal/wiki/Installation ...
without any error ... not sure where i am wrong ..
just installed another server but its same result ....

**Comment by saporus** [comment]
@martandya 
Try this installation first https://github.com/atech/postal/wiki/Quick-Install

Let's see if it would work fine.

Just try it, if same error then we would know what next step to take.

Thanks

**Comment by martandya** [comment]
@saporus 
its working now ...perfect !
Many Thanks
