### ISSUE TITLE
HTTP API Problem

### ISSUE THREAD

**Issue by mcdappdev** [atech/postal#76]
When try to send a request, I get the following error:

```json
{"status":"invalid-json","details":"A JSON text must at least contain two octets!"}
```

The data I am sending is (I've removed the sensitive data):

```json
{
  "to": [
    "EMAIL_TO_SEND_TO"
  ],
  "from": "test@test.com",
  "subject": "test email",
  "cc": [],
  "bcc": [],
  "plain_body": "this is an email!",
  "headers": {
  	"Sender": "VERIFIED_DOMAIN_EMAIL"
  }
}
```

**Comment by adamcooke** [comment]
Make sure you send the request as  POST request with the content type as `application/json` with an appropriate JSON hash in the body.
