### ISSUE TITLE
how to seet dns

### ISSUE THREAD

**Issue by laohuagnbus** [atech/postal#761]
Hello, I would like to ask how to set up DNS? According to the document set up a lot of complex things, the result of Gmail feedback is that none of the SPF dkim is through.

**Comment by willpower232** [comment]
When you add the domain into Postal, it should verify the records needed for that particular domain, tell you which ones are missing, and what they should be set to.

If its not those DNS records, then details of the records Postal needs to function are in the wiki https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration

**Comment by laohuagnbus** [comment]
@willpower232 I gave a detailed description on ＃763. can you help me ?
