### ISSUE TITLE
Is it possible to use this for cold emailing?

### ISSUE THREAD

**Issue by broskees** [atech/postal#762]
The title pretty much sums it up.

**Comment by willpower232** [comment]
Arguably you can use many different mail server software solutions, including Postal, for cold emailing but spam-like activity is highly likely to get you in trouble with your server provider or blocked by various email services or both so is unwise as an activity.

**Comment by catphish** [comment]
If I say no, will this stop you from doing it?

**Comment by catphish** [comment]
To be more serious, Postal is designed for sending and tracking transactional emails. It's fairly good at doing so in large volumes, and plenty of people use it for things like mailing lists, but there are likely better tools for mass-sending marketing emails.

**Comment by broskees** [comment]
I guess I'm more asking the question: Would it work well?

When cold emailing properly (not getting flagged for spam & being engaging, relevant, and personalized) its important to have an email sending server that has the ability to drip, so mass-sending, at least all at once, is not really what I want to do.

Basically, this just means the ability to pace the volume of emails that go out. For instance, if I was using a brand new domain and sending IP, I would want to "warm it up" - I'm hoping I can interact with Postal's API this way.
