### ISSUE TITLE
DNS settings that confuse me

### ISSUE THREAD

**Issue by laohuagnbus** [atech/postal#763]
I really tried many times, I'm sorry, maybe I misunderstood something wrong, and I haven't been able to set up DNS!
I only have ipv4. I have referred to other questions set 0.0.0.0

When I set up DNS, I encountered a problem. No matter how I set it up, it can't always pass background validation. like this:
![image](https://user-images.githubusercontent.com/40601524/54105649-a598db80-440e-11e9-968e-854f80971d33.png)

https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration

No record in the reset document is the same as the background prompt

HELP ME T-T

this what I set DNS
![image](https://user-images.githubusercontent.com/40601524/54105841-41c2e280-440f-11e9-9928-f12c354ff81a.png)
![image](https://user-images.githubusercontent.com/40601524/54105893-65862880-440f-11e9-93c5-ee8e4f67186d.png)

**Comment by laohuagnbus** [comment]
Through documentation I set up DNS like this

**Comment by willpower232** [comment]
According to whatsmydns.net, it looks like your SPF record is now working but you need to check the name of the DKIM record to include `BYlmMz` as per the instructions within Postal.

If you're having problems still, it might be that your server is unable to access the updated DNS so you might have to work with your server provider to ensure your Postal is able to see the latest DNS records.

**Comment by laohuagnbus** [comment]
![image](https://user-images.githubusercontent.com/40601524/54118016-0b945b80-442d-11e9-8b86-d4be5b280088.png)
![image](https://user-images.githubusercontent.com/40601524/54118031-13540000-442d-11e9-9664-e7a9c9dfaf6c.png)
I don't know what happened. I duplicated the value of the above graph and assigned it to DNS, but it would suggest that the number of words was too long.like this :
![image](https://user-images.githubusercontent.com/40601524/54118057-1e0e9500-442d-11e9-85bc-2d9b9085eff2.png)
This means that TXT records can only be 240 characters.

**Comment by laohuagnbus** [comment]
@willpower232 
I don't know what happened. I duplicated the value of the above graph and assigned it to DNS, but it would suggest that the number of words was too long.This means that TXT records can only be 240 characters.

**Comment by willpower232** [comment]
I was referring to the name not the value.

If the value can only be 240 characters long then I'm afraid your DNS provider will not be able to support DKIM records so you'll have to miss out that one whilst you're using this particular provider.

Has your SPF been sorted now?

**Comment by laohuagnbus** [comment]
can i build dkim by myself? change the old one? i dont know what's the SPF been sorted can you explain it? 
now, i send email to gmail tell me SPF PASS but DKIM FAILED

**Comment by laohuagnbus** [comment]
because 240 i delete the space after every ";"  . dkim lose space cant work?

**Comment by willpower232** [comment]
The actual value is a hash I believe so you won't be able to generate anything short enough to fit into your providers limit. You should ask them if its possible for this to be lifted because its likely that all their customers will suffer the same DKIM issues.

**Comment by laohuagnbus** [comment]
@willpower232 So, Which host service providers and DNS providers are officially recommended? Simple settings for PTR and can fill in DKIM freely, I realy need!

**Comment by willpower232** [comment]
PTR records should be managed by your server provider (or whoever manages your IP address), not your DNS.

I would hope most DNS providers do not have a limit on the record length so its up to you to find another one you're comfortable with or discuss the issue with your current provider.
