### ISSUE TITLE
Softfail & Web Hook

### ISSUE THREAD

**Issue by saporus** [atech/postal#768]
Hello,

I have set Postal to return "Softfail" if it continues to result to "softfail" after the maximum retry time because continuous softfail are just temporary sometimes and it shouldn't result as hardfail after the maximum retry time.

In the webhook option, I have also select the option below to trigger a webhook to my email marketing app in case of a "softfail"

> "MessageDelayed
An e-mail has been delayed due to an issue with the receiving endpoint. It will be retried automatically."

So, what I need to know now if possible is that.

How can I configure postal to only send a webhook of "softfail" if the maximum retry has been exceeded only. Because currently postal trigger a softfail result to my email marketing app for every softfail. If message softfail 18 times that means webhook result of softfail would be triggered 18 times for each message in the delivery server. Other MTA like Postfix,exim,pmta and the likes doesn't work that way. 

Looking forward to read back.

Thank you!

**Comment by willpower232** [comment]
Without further modifications to the code by yourself, I don't think this will be possible.

I would imagine there is a counter to let you know if the attempt count is greater than 18 which is possibly useful to you but you'd have to have a look at the webhook sending code.

**Comment by saporus** [comment]
Thank you.

Can you path me to the location of the webhook sending code?

Thanks

**Comment by adamcooke** [comment]
I think it is more useful to be notified immediately when a message has been delayed so your receiving application is aware that the message has been delayed straight away rather than it just disappearing into the ether without any definitive clue about what happened to it.
