### ISSUE TITLE
Unauthenticated From Address

### ISSUE THREAD

**Issue by mcdappdev** [atech/postal#77]
I am sending my data to my Postal server, and per the documentation I have included a verified email in the `Sender` header. However, when I try to pass in an email that is not on my domain in the `from` field, I get an error. Any thoughts?

**Comment by adamcooke** [comment]
You'll need to enable that for the server. If you go to the **Admin** tab under the server's **Settings** tab you should be able to enable "Allow sender header".

**Comment by mcdappdev** [comment]
I have that enabled and it's still showing me that flag both over the API and on the GUI online

**Comment by adamcooke** [comment]
What's the error you're receiving? There's no way to send a message with a `Sender` header using the GUI so I'm not sure what you're using to generate the error there.

**Comment by mcdappdev** [comment]
Over the API I get an error saying the address isn't registered at my domain.

On Tue, May 2, 2017 at 5:22 AM, Adam Cooke <notifications@github.com> wrote:
What's the error you're receiving? There's no way to send a message with a Sender header using the GUI so I'm not sure what you're using to generate the error there.

**Comment by adamcooke** [comment]
What's the actual error you're receiving?

**Comment by mcdappdev** [comment]
UnauthenticatedFromAddress

The From address is not authorised to send mail from this server

On Tue, May 2, 2017 at 7:01 AM, Adam Cooke <notifications@github.com> wrote:
What's the actual error you're receiving?

**Comment by mcdappdev** [comment]
@adamcooke Any other thoughts on this?

**Comment by adamcooke** [comment]
Not really at the moment. I will see if I can replicate this myself.

**Comment by mcdappdev** [comment]
@adamcooke great, thanks!!

**Comment by TadiNate** [comment]
It is very fine idea because of it faced me like that when i browesed by my samsung galaxy s4 android mobile phone.

**Comment by adamcooke** [comment]
Can you confirm which API method you are using?

**Comment by mcdappdev** [comment]
POST message/send

On Thu, May 4, 2017 at 6:59 AM, Adam Cooke <notifications@github.com> wrote:
Can you confirm which API method you are using?

**Comment by adamcooke** [comment]
I assume you mean `send/message`?

**Comment by mcdappdev** [comment]
Oops, yes sorry about that

On Thu, May 4, 2017 at 7:02 AM, Adam Cooke <notifications@github.com> wrote:
I assume you mean send/message ?

**Comment by adamcooke** [comment]
I'm afraid I can't replicate this myself at all. I have successfully managed to send messages using an unauthenticated `from` and an authenticated `sender`.

1. Check that it is enabled on the server. Under admin, ensure "Allow sender header" is enabled.
2. Ensure the domain has been added to the server that you're sending from (or the organization that the server belongs to).
3. Ensure that you are entering the correct address in the `sender` attribute on the request.
4. Ensure that you haven't misspelt the domain when adding it to the server/org.

Those are about the only steps I can think of.

**Comment by mcdappdev** [comment]
Would you maybe want to try it against my server? I'd be happy to give you an API key to test it. No worries if this is outside of your scope.
On Thu, May 4, 2017 at 7:09 AM, Adam Cooke <notifications@github.com> wrote:
I'm afraid I can't replicate this myself at all. I have successfully managed to send messages using an unauthenticated from and an authenticated sender .

 1. Check that it is enabled on the server. Under admin, ensure "Allow sender header" is enabled.
 2. Ensure the domain has been added to the server that you're sending from (or the organization that the server belongs to).
 3. Ensure that you are entering the correct address in the sender attribute on the request.
 4. Ensure that you haven't misspelt the domain when adding it to the server/org.

Those are about the only steps I can think of.

**Comment by adamcooke** [comment]
I'm happy to try. Can you give me an API key and user to login to the web UI with?

**Comment by andymilga** [comment]
Same issue here, @mcdappdev. Is there any feedback about @adamcooke problem?
