### ISSUE TITLE
Mail delivery failed: returning message to sender

### ISSUE THREAD

**Issue by lucrqua** [atech/postal#770]
Hi, guys! I need some help here, please. 

I create all the zone records for my postal installations and of the domains inside.

I also create Address Endpoint and the route for incoming messages to this Address Endpoint, but I can't receive any in these messages send.

For example, sending e-mail from my personal account, I received this response:

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  test@my.postal.com
    The mail server could not deliver mail to test@my.postal.com.  The account or domain may not exist, they may be blacklisted, or missing the proper dns entries.
```

Again, all zone dns data is OK, but I can't receive any messages on postal.

Any help, please?

**Comment by willpower232** [comment]
That error message implies that you do not have MX records for `my.postal.com`. Can you double check you have them?

**Comment by lucrqua** [comment]
Yes, I have:

My config. on postal is ok:
![image](https://user-images.githubusercontent.com/15186323/54542298-53116f00-497a-11e9-9107-b839067ba138.png)

My config. on cloudflare too:
![image](https://user-images.githubusercontent.com/15186323/54542391-7fc58680-497a-11e9-9e20-a5a4deed3d55.png)

And on whois: 
![image](https://user-images.githubusercontent.com/15186323/54542595-d6cb5b80-497a-11e9-9b96-76139ebdc639.png)

**Comment by willpower232** [comment]
Can you telnet to port 25 on mx.r1.whatever?

**Comment by lucrqua** [comment]
My port 25 is fine. Without any block, I can send emails but I can't receive. What can be in this case?

**Comment by lucrqua** [comment]
@willpower232 any help please?

**Comment by willpower232** [comment]
There has to be a problem with your setup, either from a connection perspective or a server issue.

If you have MX records for your domain (you can verify with whatsmydns.net) and you can telnet from your computer to port 25 on your Postal server then you will have to look at your Postal logs to see if there are any errors.

**Comment by lucrqua** [comment]
Can you show me what a 100% DNS setup would look like? A template? Because I've followed all the steps of all Wikis several times and I'm sure I did not pass on any information.

All logs do not contain any errors, just the connection and send reports when I fire some email.

The sends and all other settings are perfect, I just can not receive any email.

I'm not talking about receiving in my destination inbox. I say when I send an email from Gmail for example, to an email registered inside the postal.

**Comment by willpower232** [comment]
What you've shown us looks fine so far.

You should be able to run `nslookup mx.r1.whatever` on your computer and get an IP address. You should also be able to get the same IP address from entering `mx.r1.whatever` in whatsmydns.net.

You should be able to telnet that IP address on port 25 from your computer (not your Postal server) and see some responses from Postal.
