### ISSUE TITLE
How to start Click & Open Tracking

### ISSUE THREAD

**Issue by laohuagnbus** [atech/postal#771]
I follow the wiki

Added new IP

postal register-lets-encrypt youremail@example.comn

![image](https://user-images.githubusercontent.com/40601524/54734992-59078a00-4bde-11e9-8a8a-313054604a06.png)

and then postal status

but I can't find fast_server just
![image](https://user-images.githubusercontent.com/40601524/54735026-8d7b4600-4bde-11e9-86a5-62b5b3d40b9e.png)
![image](https://user-images.githubusercontent.com/40601524/54735045-966c1780-4bde-11e9-8450-ffca5e33ec9b.png)

 and I have two ip in my vps
![image](https://user-images.githubusercontent.com/40601524/54735066-b6034000-4bde-11e9-9893-d81bf4cbcba2.png)

and I change nginx config listen 
0.0.0.0->main ip
![image](https://user-images.githubusercontent.com/40601524/54735099-04b0da00-4bdf-11e9-9cbd-a80baf983ef2.png)

but , it don't work must be something wrong 

even when I sent email be mark Substitute by other one (Mail original text)

![image](https://user-images.githubusercontent.com/40601524/54735220-c10aa000-4bdf-11e9-8afc-db2036ab4c6a.png)

**Comment by willpower232** [comment]
Have you restarted Postal after changing the config to enable `fast_server`?

**Comment by laohuagnbus** [comment]
i use postal restart @willpower232

**Comment by laohuagnbus** [comment]
even The sender is different from the actual @willpower232

**Comment by willpower232** [comment]
If `fast_server` is missing in `postal status` then something must be wrong.

If stopping and starting doesn't help then you'll have to look in the logs to see what has happened.

**Comment by laohuagnbus** [comment]
But I saw the settings for tracking and settings in the control panel.
fast_server is still missing in postal status 
even link have changed
but don't work

**Comment by laohuagnbus** [comment]
Is there not enough running memory?
my vps is 1 core 1G
so can't start fast_server?
Is that possible?

**Comment by willpower232** [comment]
That would definitely be a problem for you. You should probably aim for 8GB RAM.
