### ISSUE TITLE
GCM or APNS Support

### ISSUE THREAD

**Issue by macmichael01** [atech/postal#773]
If I recall, GCM and APNS (Apple and Android Push) can be sent in a similar fashion as an email. Simply requires additional certificates to be generated. Does it make sense for such a feature to exist in this app? and possibly even TXT message sending support too?

**Comment by willpower232** [comment]
Re push notifications, Postal is designed to send emails so if the devices that receive the messages are capable of understanding an email format then it might work but I'd imagine there are some specifics that might require you to send messages with the raw API endpoint, assuming the messages complied with RFC2822 or make significant changes to how Postal handles messages.

I knew that some providers let you send SMS messages via email so in theory this would still work with Postal but I'm not sure how many of them still do.

In both cases, you would be infinitely better off with a software solution that was designed to carry out these functions from the ground up.

**Comment by adamcooke** [comment]
We don't have any plans to add this to Postal. We do actually have proxy apps for APNS & GCM which we use internally.

* https://github.com/adamcooke/apns-proxy
* https://github.com/atech/gcm-proxy
