### ISSUE TITLE
make install along side others applications on same vps

### ISSUE THREAD

**Issue by kdaffef** [atech/postal#775]
Hi,
I'm using **Postal** like a charm on vultr vps and it's working very nice (2-ways emails + tracking module) as expected.
vps is runing under ubuntu 16.04,

my question is :  is Postal able to run on same vps with another emailing application running uder ubuntu 16.04 like **Mailtrain** : 
- https://github.com/Mailtrain-org/mailtrain : in our case, will build emails and send send them via Postal on the same vps for best cost and a best deliverability rate!.

Problem : i have tried to install both but only one can run as nginx redirect all https traffic to Postal. I know, that it looks possible, and should may be make manual changes about reverse proxy configuration. But not expert enough, is there any tuto or explanation step-by-step to get both application working on same vps ?

Thank you for help,
Really loving Postal, so thank you a lot for this application creation!!

**Comment by willpower232** [comment]
Postal should be able to run alongside other services but there may be competition for system resources so unless your server is particularly well-specced, it would be better to run them separately.

If you read up on how nginx works, you should be able to apply hostnames to your nginx configuration to separate Postal from a domain point of view.

**Comment by kdaffef** [comment]
Hi there, to be honest, i'm not expert,  can learn with googling,
are you able to tell me which files will be involved buy theses changes ?
or to which technical direction i have to search ?
thank you!!++

**Comment by willpower232** [comment]
You'll want to create extra configuration similar to https://github.com/atech/postal/blob/master/resource/nginx.cfg to define the extra site for whatever else you want to run but you'd have to find out from them what configuration would be needed.

**Comment by kdaffef** [comment]
You re simply fantastic!!!
Will be excited to discover and try to apply to my configuration!!!

Thanks a lot

**Comment by kdaffef** [comment]
Hi,

Playing with Postal which is running like a charm on vps ubuntu 16.04!! - want to confirm email opens for html ones without links not images.  How to test this feature inside ¨Postal ? Is any email open will be registred in activity tab with time stamp ?
Will enjoy using mailtrain (self hosted email app open source), to send newsletters to customers via Postal, this will be fantastic if Postal will report all email opens and link clics. How to optimize this capability for inside Postal ?. 
Thank you for your help,

**Comment by willpower232** [comment]
Open tracking can only happen via images and Postal will re-write links in your emails to allow them to be tracked.

You should follow the setup instructions here https://github.com/atech/postal/wiki/Click-&-Open-Tracking
