### ISSUE TITLE
Method to import suppressions

### ISSUE THREAD

**Issue by anhofmann** [atech/postal#78]
We're using mailgun since a few months and are unhappy with the reputation of their ips. Also we had problems with a too high bounce rate so we had to create a API were we can check if a email address is likely to be able to receive mail. In both services we have a big list of known undeliverable mail addresses. We want to import these addresses into postal but I have no clue how postal even stores its suppressions. Can you give me a hint how to import blacklisted mail addresses?

**Comment by adamcooke** [comment]
The suppression list is stored in the mail server's own MySQL database. You can import items into the `suppressions` table. 

* `type` should be `recipient`
* `address` should be the e-mail address
* `reason` should be some text to describe why they're on the list
* `timestamp` is a unix timestamp when they were added to the list
* `keep_until` is a unix timestamp for when the address should be removed from the list

**Comment by anhofmann** [comment]
I hoped that there is a simple solution like this :) Only problem is that my installation doesn't have a suppressions table :( Do I have to wait until postal hits a hard fail because the table will created then?

**Comment by anhofmann** [comment]
Oh, never mind! I didn't realized that postal creates new dbs for every organisation. I found the suppressions table :)
