### ISSUE TITLE
How to open SMTP port 25 of my postal mail server

### ISSUE THREAD

**Issue by shaheryar2014** [atech/postal#780]
My port 25 is blocked. Is there any command in postal to open port that port

My ip is 207.180.219.95

When i try to telnet my postal host on port 25 

Trying 207.180.219.95...
telnet: Unable to connect to remote host: Connection refused

My hostname is mail.dailydeals360.com

postal status
Procodile Version   1.0.23
Application Root    /opt/postal/app
Supervisor PID      1868
Started             2019-03-29 17:44:31 +0100

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      17:44        pid:1874     respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      17:44        pid:1876     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      17:44        pid:1878     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      17:44        pid:1919     respawns:1      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      17:44        pid:1884     respawns:0      port:-        tag:-

please help me out if there is any command to open port 25 and bind that port to my IP i would be very thankful

**Comment by willpower232** [comment]
Your postal status looks good so either you have a firewall in place or your server provider is blocking the port. Its probably worth discussing the matter with your server provider.

**Comment by shaheryar2014** [comment]
just the postal installation that's it

please check my netstat status i do not have any place any firewall

 netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      1190/[postal] web.1
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      599/beam.smp
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      889/mysqld
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      757/nginx -g daemon
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      750/epmd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      640/sshd
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      757/nginx -g daemon
tcp6       0      0 :::5672                 :::*                    LISTEN      599/beam.smp
tcp6       0      0 :::80                   :::*                    LISTEN      757/nginx -g daemon
tcp6       0      0 :::4369                 :::*                    LISTEN      750/epmd
tcp6       0      0 :::22                   :::*                    LISTEN      640/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      757/nginx -g daemon
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     SEQPACKET  LISTENING     15456    1/init              /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     18752    1184/app)           /tmp/postal/pids/procodile.sock
unix  2      [ ACC ]     STREAM     LISTENING     1965     1/init              /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     1966     1/init              /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     16120    889/mysqld          /var/run/mysqld/mysqld.sock
unix  2      [ ACC ]     STREAM     LISTENING     15432    1/init              /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     15440    1/init         

and now it show worker.1 and smtp.1 status failed

postal status
Procodile Version   1.0.23
Application Root    /opt/postal/app
Supervisor PID      1184
Started             2019-03-31 13:54:07 +0200

 * worker.1 is not running (Failed)
 * smtp.1 is not running (Failed)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      13:54        pid:1190     respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Failed       13:54        pid:1286     respawns:5      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      13:54        pid:1194     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Failed       13:54        pid:1270     respawns:5      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      13:54        pid:1200     respawns:0      port:-        tag:-
 
unable to understand the what's the problem

If it would be possible that you can check the problem on my server. Please tell me when u would be needing credentials.

**Comment by willpower232** [comment]
If your Postal was working (from your first post) and no longer is, then you could try restarting your server to clean things up.

If you aren't running a firewall, you should ask your server company if you are able to send emails (i.e. use port 25) as they might have a block in place.

**Comment by shaheryar2014** [comment]
Thank for the help highly appreciated but the problem is solved after reinstalling postal from script.

**Comment by darkcohiba** [comment]
Hello @shaheryar2014 how did you solve this?
