### ISSUE TITLE
[MAIL ERROR] Expected response code 250 but got code "503", with message "503 EHLO/HELO first please

### ISSUE THREAD

**Issue by lucrqua** [atech/postal#785]
`ERROR: [MAIL ERROR] Expected response code 250 but got code "503", with message "503 EHLO/HELO first please " Log data: >> MAIL FROM:  << 503 EHLO/HELO first please  !! Expected response code 250 but got code "503", with message "503 EHLO/HELO first please " (code: 503) (send); exemple@exemple.com [] []`

Hello, I need a little help, please!

I'm trying to send e-mails to Postal through Mautic, when I send many contacts, it returns the error above. I do not know what else to do.

Could you help me, please?

**Comment by willpower232** [comment]
It looks like Mautic is misusing or reusing an SMTP connection to Postal. Is there a setting or anything to alter how it sends emails?

**Comment by lucrqua** [comment]
Hey, @willpower232 - this is my config on Mautic:

![image](https://user-images.githubusercontent.com/15186323/55564887-3e99da00-56cf-11e9-9377-90a3d83ed498.png)

Any other change would be here:

![image](https://user-images.githubusercontent.com/15186323/55564989-64bf7a00-56cf-11e9-9329-7353db6bf8a6.png)

Any other route, be it Sparkpost, Sendgrid or Amazon are shipped normally. Just in sending to the Postal shows that error.

**Comment by lucrqua** [comment]
Hey, @willpower232  - this is my config on Mautic:

![image](https://user-images.githubusercontent.com/15186323/55565182-c54eb700-56cf-11e9-9479-745fb62bf2ca.png)

Any other change would be here:

![image](https://user-images.githubusercontent.com/15186323/55565241-dd263b00-56cf-11e9-91b9-3c119c6f668f.png)


Any other route, be it Sparkpost, Sendgrid or Amazon are shipped normally. Just in sending to the Postal shows that error.

**Comment by willpower232** [comment]
Presuming you haven't made any changes to the Postal code and you're up to date, the only thing I can think is that Mautic does something slightly different with multiple addressees that Postal isn't expecting.

I can't provide any support for Mautic as I don't know it at all so if you're getting this error constantly, you will have to figure out the code behind Mautic sending the email from their github repo or get some support from them.

**Comment by catphish** [comment]
If you're able to send Postal's full SMTP log of the session, we can see what the client is trying to do. The obvious answer is that it's trying to send an email without saying HELO first, but that's unlikely as AFAIK all mail servers enforce this requirement.

**Comment by lucrqua** [comment]
@willpower232 Yes, I did not make any changes to the code.

**Comment by lucrqua** [comment]
@catphish Ok, I'm getting the log on the server. In the case, is it possible to make some changes in the Postal so that it does not need the HELO parameter for multiple emails?

**Comment by lucrqua** [comment]
@catphish this is as an exemple of error on log: 

`[32m[smtp.6:7988][0m [2019-04-02T14:50:04.606] DEBUG -- : [NUPVSG] [35m   Connection opened from ::ffff:[MYIPHERE][0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.606] DEBUG -- : [NUPVSG] [35m   Client identified as ::ffff:[MYIPHERE][0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.669] DEBUG -- : [NUPVSG] [32m<= EHLO my.mautic.com[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.700] DEBUG -- : [NUPVSG] [34m=> 250-My capabilities are[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.700] DEBUG -- : [NUPVSG] [34m=> 250 AUTH CRAM-MD5 PLAIN LOGIN[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.801] DEBUG -- : [NUPVSG] [32m<= AUTH LOGIN[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.801] DEBUG -- : [NUPVSG] [34m=> 334 VXNlcm5hbWU6[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.832] DEBUG -- : [NUPVSG] [32m<= dGVsbGVtYWlsLTEvdGVsbGVtYWlsMQ==[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.832] DEBUG -- : [NUPVSG] [34m=> 334 UGFzc3dvcmQ6[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.863] DEBUG -- : [NUPVSG] [32m<= TURodkxKejdrVmxoMzl4SnNDcG9HVkZq[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.907] DEBUG -- : [NUPVSG] [34m=> 235 Granted for mypostal-1/mypostal-1[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.938] DEBUG -- : [NUPVSG] [32m<= MAIL FROM:<myuser+bounce_5ca3a0cc1e0f7351799334@news.myuser.com>[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.939] DEBUG -- : [NUPVSG] [34m=> 250 OK[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.969] DEBUG -- : [NUPVSG] [32m<= RCPT TO:<emailforexemple@gmail.co>[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.970] DEBUG -- : [NUPVSG] Added external address 'emailforexemple@gmail.com'
[32m[smtp.6:7988][0m [2019-04-02T14:50:04.970] DEBUG -- : [NUPVSG] [34m=> 250 OK[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.001] DEBUG -- : [NUPVSG] [32m<= DATA[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.002] DEBUG -- : [NUPVSG] [34m=> 354 Go ahead[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.036] DEBUG -- : [NUPVSG] [32m<= Return-Path: <myuser+bounce_5ca3a0cc1e0f7351799334@news.myuser.com>[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.037] DEBUG -- : [NUPVSG] Not logging further message data.
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.099] DEBUG -- : [NUPVSG] [34m=> 530 From/Sender name is not valid[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.150] DEBUG -- : [NUPVSG] [32m<= MAIL FROM:<myuser+bounce_5ca3a0cd1ec4d832071204@news.myuser.com>[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.150] DEBUG -- : [NUPVSG] [34m=> 503 EHLO/HELO first please[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.194] DEBUG -- : [NUPVSG] [32m<= MAIL FROM:<myuser+bounce_5ca3a0cd2a000175362333@news.myuser.com>[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.194] DEBUG -- : [NUPVSG] [34m=> 503 EHLO/HELO first please[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.237] DEBUG -- : [NUPVSG] [32m<= MAIL FROM:<myuser+bounce_5ca3a0cd34b8f044453415@news.myuser.com>[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.237] DEBUG -- : [NUPVSG] [34m=> 503 EHLO/HELO first please[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.276] DEBUG -- : [NUPVSG] [32m<= QUIT[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.277] DEBUG -- : [NUPVSG] [34m=> 221 Closing Connection[0m
[32m[smtp.6:7988][0m [2019-04-02T14:50:05.277] DEBUG -- : [NUPVSG] [35m   Connection closed[0m`

**Comment by lucrqua** [comment]
@catphish this is an exemple of error on log.

[errorlog_smtp.txt](https://github.com/atech/postal/files/3054577/errorlog_smtp.txt)

**Comment by catphish** [comment]
Thanks for the log. The specific case here is that the client sends an email. The DATA command receives an error response:

```
530 From/Sender name is not valid
```

The client then immediately tries to send another email, assuming that the transaction has been reset. I believe this is a bug in Postal, and that it should automatically reset the transaction after a DATA error in the same way it does after a DATA success.

**Comment by catphish** [comment]
Are you able to try this fix? https://github.com/atech/postal/commit/0fb323af3f37201eed492646007ed355f3617b51

**Comment by lucrqua** [comment]
Thank you very much, I will implement and perform some tests, then return with the result.

**Comment by lucrqua** [comment]
@catphish Apparently it has been fixed, has not returned the reported error and the emails are being properly delivered.

Tomorrow I have a new mailing scheduled and I will inform the result here as well. Many thanks friend, you are awesome!

**Comment by lucrqua** [comment]
@catphish It worked very well on today's shipments, problem solved. Thank you so much!

**Comment by edgarmunin** [comment]
> Are you able to try this fix? [0fb323a](https://github.com/atech/postal/commit/0fb323af3f37201eed492646007ed355f3617b51)

Hello, @catphish 
I tried it that way, but it did not work for me.

___________________________________________________________________________________
[2019-04-18 14:52:12] mautic.ERROR: [MAIL ERROR] Expected response code 250 but got code "530", with message "530 From/Sender name is not valid " Log data: >> MAIL FROM:  << 250 OK  >> RCPT TO:  << 250 OK  >> DATA  << 354 Go ahead  >>  .  << 530 From/Sender name is not valid  !! Expected response code 250 but got code "530", with message "530 From/Sender name is not valid " (code: 530) (send);

**Comment by catphish** [comment]
That appears to be a completely unrelated issue. Check your from address :)

**Comment by JaiBansal24** [comment]
Hi,

In last 10-15 days, I have setup 5 VPS with default installations of Postal

Started getting this error soon on all VPS.   --- Expected response code 354 but got code "530"

Found this Fix, but there is no such folder ( lib/postal/smtp_server ) on my servers.   Has it moved ?/client.rb

Thanks !

**Comment by JaiBansal24** [comment]
> 
> 
> Are you able to try this fix? [0fb323a](https://github.com/postalhq/postal/commit/0fb323af3f37201eed492646007ed355f3617b51)

Hi,

Since the fix is over 1.5 years old, isn't it part of new versions we install ?

In last 10-15 days, I have setup 5 VPS with default installations of Postal

Started getting this error soon on all VPS. --- Expected response code 354 but got code "530"

Found this Fix, but there is no such folder ( lib/postal/smtp_server ) on my servers. Has it moved ?/client.rb

Thanks !

**Comment by willpower232** [comment]
@JaiBansal24 the directory is `/opt/postal/app/lib/postal/smtp_server`

**Comment by Jaisara** [comment]
@lrqxyz Same issue coming for me. I tried a test campaign for a segment contains 7 contacts. After a scheduled campaign published the email has been sent to two contacts only, for the other contact it shows the below error.
![Screenshot (6)](https://user-images.githubusercontent.com/33508497/181280734-9962cd51-409e-4197-8f3f-fc5a1a3f6a06.png)
