### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by davaxi** [atech/postal#79]
Hi,

Is it possible to use postgreSQL instead of MySQL for the database?

Thanks

**Comment by adamcooke** [comment]
No.

**Comment by dbackeus** [comment]
@adamcooke curious if there is anything in particular that would make it challenging to make Postal compatible with the Postgres AR adapter.

Would a PR to this affect be of interest or do you expect it would be a highly intrusive endeavor?

**Comment by adamcooke** [comment]
The reason we don't want to officially support it is that it's another thing to test and maintain so I don't think we'd be looking at merging a PR for it I'm afraid.

**Comment by dbackeus** [comment]
Mostly it would just fit in with our current deployment stack which doesn't support Mysql at the moment. Seemed like it might be low hanging fruit to just support any AR adapter since the app is fairly small. 

Totally see the point about it being a drag having to expand the testing matrix though 👍

**Comment by ManUtopiK** [comment]
@davaxi 
> What are your expectations for having Postgres over Mysql?

Using https://hasura.io to provide a graphql endpoint on top of postal api. Use graphql federation to merge postal data with our business logic stack...

**Comment by davaxi** [comment]
Nowadays, with all ORMs, I find it a shame not to be able to be versatile on the type of database.

When, for the same company, there is already a database infrastructure in place (postgresql, MMSQL, etc.) it is more appropriate to be able to pool the resource where backups have been put rather than adding a new database of data to the infrastructure before configuring it completely.

So my initial request was made in order to be able to pool resources and reduce the number of infrastructure elements.

**Comment by galetahub** [comment]
Thanks to the team for such a great work!
I support the idea of ​​using ORMs to allow the use postgresql as the database. 
For this I will try to move message_db stuff under AcriveRecord models with enabled multitenancy.
I'm goint to try apartment gem (https://github.com/rails-on-services/apartment)

**Comment by satoru260** [comment]
It seems the application is quite tightly bound to MariaDB, because the [docs](https://docs.postalserver.io/getting-started/prerequisites#mariadb-106-or-higher) say "We do not support using MySQL in place of MariaDB.". But I think with the AI tooling and agents we have in place now, this kind of exercise could be achieved today much easier that it would have when the issue was first opened. I vote to reopen this issue and make the system support a wider range of databases; At a minimum Postgres.
