### ISSUE TITLE
Python Send API

### ISSUE THREAD

**Issue by breimers** [atech/postal#794]
Hey guys,

I really like the idea behind Postal (thanks for open sourcing!) and have set up my server. I can send via the UI and can receive messages no problem. I think my issue lies in not correctly using the API.

Here is my current python code:
---------------------------------------
```
import requests
import json


def send_msg(to, sender, subject, html):
    api_url="https://mail.domain.io/api/v1/send/message"
    api_key="ghghhg7373732jsdf" #not a real api key :)
    params_dict= {
      "to": to,
      "from": sender,
      "subject":subject,
      "html_body": html
    }
    headers = {'Content-Type': 'application/json', 'X-Server-API-Key': api_key}
    return(requests.post(api_url, data=json.dumps(params_dict), headers=headers))

print(send_msg("bradley@otherdomain.com", "apps@mail.domain.io", "Tester", "<h1>Message</h1>"))


```

After running the script, I get `<Response [200]>`.

But nothing comes up on the server, and I never receive the messages.

Has anyone had a similar issue, or can see why this isn't working?

Thanks everyone!

**Comment by willpower232** [comment]
the API should return some data to you as well as HTTP 200, do you get a response body?

**Comment by breimers** [comment]
I don't, which is what's odd. If you have more pressing issues my boss decided to use mailgun for our project.

**Comment by willpower232** [comment]
Unless someone who knows more python can step in, I guess you'd have to tinker with the API controller in the code to see how far your request got. Sorry to not be of more use!

**Comment by breimers** [comment]
No worries, thanks for the response!
