### ISSUE TITLE
"postal auto-upgrade" with systemd

### ISSUE THREAD

**Issue by jaydrogers** [atech/postal#798]
So I have been reading through the documentation and I have noticed that `postal auto-upgrade` is **not advised** when running the services via "systemd". https://github.com/atech/postal/wiki/Starting-on-boot

This opens up a few questions:
1. Is there a suggested way to run the service?
2. I saw [these upgrade options](https://github.com/atech/postal/wiki/Upgrading#manual-upgrade-from-repository), but one has downtime and the other could potentially not be a stable release (because I am pulling from the repo, not from an official release). Am I correct with my assumptions?

Here is the exact spot in the documentation that I am talking about:
![Screen Shot 2019-04-25 at 2 58 28 PM](https://user-images.githubusercontent.com/3174134/56764773-261b5d80-676b-11e9-9b59-12ea1dce1b80.png)

**Comment by willpower232** [comment]
At the top of the starting from boot page, you'll see about adding Postal to '/etc/rc.local'. Any approach of starting Postal directly should work well.

Regardless of using systemd or not, it would always be useful to have monitoring of Postal using HTTP checks (or something more advanced if you have that option). This way you can be sure it is running and available regardless of how you have installed it.

The zero downtime approach does indeed rely on the code being functioning. Our approach is to make a testing copy of the Postal server and test any updates first. We are also using a cloned copy of the code with some unmerged PRs so we need to apply extra testing.

**Comment by jaydrogers** [comment]
Thanks @willpower232!

> Regardless of using systemd or not, it would always be useful to have monitoring of Postal using HTTP checks (or something more advanced if you have that option).

Good call! I will definitely do this.

> Our approach is to make a testing copy of the Postal server and test any updates first.

What do you mean by this, just making a backup of the `/opt/postal` folder?

How stable have updates been? Usually a good experience if you are pulling them from https://postal.atech.media/packages/stable/latest.tgz?

**Comment by willpower232** [comment]
We have Postal cloned from Github directly as we started using it before there were packages. We use AWS so its pretty easy to set up a new server just running Postal from the same point in time we are currently and do some testing of the features.

Thankfully, most of the updates have been minor refinements but there have been larger scale gem updates which made a few issues.

The actual release packages should be good and stable however the repo can be further ahead of the packages so it depends what features you're after and how patient you can be.

**Comment by jaydrogers** [comment]
Great, thanks for the explanation @willpower232! I'll use `/etc/rc.local` until there is better support for modern service management.

Thanks for your insight!
