### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by jadsonlourenco** [atech/postal#8]
I know that is a Ruby app, but an easy way to have this app running on any system is using Docker.

**Comment by adamcooke** [comment]
We don't have any experience with Docker here but we'll certainly look into it :)

**Comment by bobinson** [comment]
May be once the installation documentation is ready, someone of us can look into it @adamcooke

**Comment by adamcooke** [comment]
That would be great. We should have the installation stuff all done by the end of the day.

**Comment by kristiandrucker** [comment]
Also it would be nice with kubernetes support. When dockerfile and the image will be out I can help with that.

**Comment by jadsonlourenco** [comment]
When the installation process is documented I can create the Docker image file, and then create to Rancher catalogue.

**Comment by joshuatalb** [comment]
Also happy to chip on on either the Docker or Kubernetes side.

**Comment by adamcooke** [comment]
Thanks everyone. The installation docs are pretty much done now. I've run through them myself on a clean Ubuntu 16.04 VM and things seem to work. Obviously as I have quite a bit of knowledge about how it works, I'm biased so there might be something missing that I've overlooked. 

If anyone wants to give it a go on Docker, that'd be great. Do ask if you have any questions or run into any problems with anything or anything missing from the docs.

**Comment by andyshinn** [comment]
Using those instructions I made an example of running Postal using Docker Compose: https://gist.github.com/andyshinn/439790630a6a8040fda4100f954d829f.

**Comment by denji** [comment]
Convert docker-compose service files to Kubernetes objects https://github.com/kelseyhightower/compose2kube

**Comment by mehdibaha** [comment]
[Metabase](http://www.metabase.com) is a 'plug-and-play' BI solution, and they seemed to have perfected [the install steps](http://www.metabase.com/start/):

In 2017, I think it's great to offer at least these 3 options:
- Docker Image
- Heroku deploy
- AWS deploy

What do you think 😄  ?

**Comment by ALinuxNinja** [comment]
Another container [here](https://github.com/ALinuxNinja/docker-postal) as well.

**Comment by x86fantini** [comment]
i have succesfully installed Postal into a LXD/lxc container without any problems at all. In this way i can use ZFS for live migration or HA setup, real time snapshots and system portability, a-la docker but with a real and complete OS :+1:

**Comment by indykish** [comment]
Another one i see here
[elct9620/postal](https://hub.docker.com/r/elct9620/postal/)

**Comment by adamcooke** [comment]
Seems like people have created various Docker implementations here. At present, we don't want to maintain our own official docker image (because we haven't got much experience with it yet) but we will likely look to add this in the future when we've released v1.0.

**Comment by salviof** [comment]
@adamcooke  já estão prontos para o Docker? vocês podem homologar o docker file de alguém, a questão maior, e que possamos ter um docker que possamos confiar... sendo oficial fica mais fácil ..

**Comment by rbashish** [comment]
Is there official docker image available for [Postal](https://postal.atech.media/)?

**Comment by willpower232** [comment]
Not yet, I'm sure it will be documented when it gets to that stage. There are other priorities at the moment.
