### ISSUE TITLE
Tracking pixel is not added if HTML body is inside multipart/related part

### ISSUE THREAD

**Issue by oliverkuldmae** [atech/postal#802]
When the email's HTML body is inside a part with `Content-Type: multipart/related`, then `MessageParser` does not add the tracking pixel inside the HTML body. This is because `MessageParser` only looks for `Content-Type: multipart/alternative` when deciding if parsing nested parts is necessary.

https://github.com/atech/postal/blob/a7e3e9de79fdd0d9cf7d811d370e854dd5307da9/lib/postal/message_parser.rb#L74

This line should be changed to `elsif part.content_type =~ /multipart\/(alternative|related)/` to ensure all required parts are parsed.

**Comment by willpower232** [comment]
Ah interesting, are you sending messages via the raw endpoint? Can you share an example of the message you are sending?

**Comment by oliverkuldmae** [comment]
Yes, I'm using the raw endpoint as the regular endpoint had some shortcomings. I've created an example on [Repl.it](https://repl.it/repls/ImpressiveHastyArraylist). The current condition has been commented out and replaced with my proposed fix.

**Comment by willpower232** [comment]
Looks good to me, thanks for the demo.

Would you be able to make a PR?

**Comment by oliverkuldmae** [comment]
No problem, PR created. Any idea when these changes will be merged?

**Comment by willpower232** [comment]
Hopefully @catphish will be able to review and merge a few of the PRs soon, there is quite a few to get through!

**Comment by oliverkuldmae** [comment]
@willpower232 @catphish would it be possible to get some kind of ETA on when the currently open pull requests will be reviewed/merged?
