### ISSUE TITLE
Avoid using IPTables

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#81]
It must be me, but I can't get iptables to redirect my ports on my EC2 instance.
I don't see the reason why you redirect port 25 to 2525, probably because you have something running on port 25.
How can we change default ports for Postal?
To run it on port 25 for example

**Comment by mattmartincouk** [comment]
Postal runs as its own user, not root.

Ports below 1024 are considered privileged meaning normal users cannot use them as it can with say 2525.

Using iptables is far safer.

The rules in the docs for us didn't work so we used something like the below which did.

iptables -A PREROUTING -t nat -p tcp -d DEST_IP --dport 25  -j DNAT --to-destination DEST_IP:2525

Replace DEST_IP with your destination. Repeat for the other port mappings.

**Comment by catphish** [comment]
Just to reiterate what @mattmartincouk said, the iptables rules originally documented were incorrect, and the documentation was recently updated to match the above. Running the SMTP server on port 25 is possible but more difficult due to permissions. Can you confirm what iptables rules you are running?

**Comment by elfeffe** [comment]
The instructions here https://github.com/atech/postal/wiki/Processes had changed.
Now they give some errors (the second one, it says -t instead of --to, but gives errors anyway).
and the instructions for the second IP (fast server) has disappeared.
If I try with `iptables -A PREROUTING -t nat -p tcp -d DEST_IP --dport 25 -j DNAT --to-destination DEST_IP:2525`, replacing DEST_IP with my server public IP both times, I can't receive emails (my port 25 is opened on Amazon EC2).
I send a test email to the server itself (with mx dns, etc) and Postal.
I also opened port 2525 on Amazon Security Group, and I can connect by Telnet to port 2525 but not to 25.

**Comment by mattmartincouk** [comment]
I suspect there are other issues on your server then in that case.

The rule I posted works correctly here on an Ubuntu 16x box.

**Comment by elfeffe** [comment]
I use Ubuntu 16.04
I will check a bit more, it's strange because I can connect with telnet to port 2525 but not to 25.
If I paste your iptables, changing the IP, I do iptables -L and I get
```
iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports ssh

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain f2b-sshd (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere       
```
Sure there is something that is not working

**Comment by mattmartincouk** [comment]
`iptables -t nat --line-numbers -L`

Run that instead.

**Comment by elfeffe** [comment]
```
iptables -t nat --line-numbers -L
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    DNAT       tcp  --  anywhere             ec2-54-76-228-XXX.eu-west-1.compute.amazonaws.com  tcp dpt:smtp to:54.76.228.XXX:2525

Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
num  target     prot opt source               destination    
```
I see that destination has been changed with server domain, even when I specified IP, and that domain resolves to a LAN IP, not to public IP. Can that be the problem?

**Comment by mattmartincouk** [comment]
It'll resolve in DNS.

Add -n to remove resolution. 

Looks correct but this seems to be server related - sorry.

**Comment by catphish** [comment]
I have corrected the documentation again. I hope this is now correct.

@elfeffe please could you paste your iptables output using the command `iptables-save` instead of `iptables -L`? Also, when error do you see when trying to connect to the server on port 25?

**Comment by elfeffe** [comment]
I use
`iptables -t nat -I PREROUTING -d 54.76.228.XXX -p tcp -m tcp --dport 25 -j DNAT --to 54.76.228.XXX:2525`
And I get
```
iptables -t nat --line-numbers -nvL
Chain PREROUTING (policy ACCEPT 4 packets, 240 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1        0     0 DNAT       tcp  --  *      *       0.0.0.0/0            54.76.228.XXX        tcp dpt:25 to:54.76.228.XXX:2525

Chain INPUT (policy ACCEPT 4 packets, 240 bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination 
```
And
```
iptables-save
# Generated by iptables-save v1.6.0 on Wed May  3 15:17:06 2017
*mangle
:PREROUTING ACCEPT [5434818:4978704236]
:INPUT ACCEPT [5434814:4978703996]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1203470:18862194370]
:POSTROUTING ACCEPT [1203470:18862194370]
COMMIT
# Completed on Wed May  3 15:17:06 2017
# Generated by iptables-save v1.6.0 on Wed May  3 15:17:06 2017
*nat
:PREROUTING ACCEPT [68:4080]
:INPUT ACCEPT [68:4080]
:OUTPUT ACCEPT [11:837]
:POSTROUTING ACCEPT [11:837]
-A PREROUTING -d 54.76.228.XXX/32 -p tcp -m tcp --dport 25 -j DNAT --to-destination 54.76.228.XXX:2525
COMMIT
# Completed on Wed May  3 15:17:06 2017
# Generated by iptables-save v1.6.0 on Wed May  3 15:17:06 2017
*filter
:INPUT ACCEPT [4807753:4030248024]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1044379:16288311237]
COMMIT
# Completed on Wed May  3 15:17:06 2017

```

**Comment by willpower232** [comment]
Just got it working on an EC2 instance. I noted that `ifconfig` reported the internal 172.x.x.x IP addresses and used those when creating the iptables rules instead of the 52.x.x.x public IP addresses and it works

**Comment by willpower232** [comment]
also I skipped the `REDIRECT` rule as it didn't work (as above)

**Comment by elfeffe** [comment]
Yes, that did the trick.
There is some missing information on https://github.com/atech/postal/wiki/Processes
There was some extra setup for fast server, the secondary IP, it is not there anymore

**Comment by adamcooke** [comment]
There is more information on setting up the tracking & fast server on its own page: https://github.com/atech/postal/wiki/Click-&-Open-Tracking

**Comment by willpower232** [comment]
also I had to restart postal after applying the click tracking iptables rules, not sure if that was required or coincidental, all working nicely now!

**Comment by catphish** [comment]
@willpower232 glad you got this working. I have corrected a second error in the documentation regarding the `OUTPUT` rule. You do need this rule for some scenarios, so I'd suggest adding it. The correct format is below, and I've fixed the documentation accordingly.

```
iptables -t nat -I OUTPUT     -d 192.128.1.3 -p tcp -m tcp --dport 25 -j DNAT --to-destination 192.128.1.3:2525
```

**Comment by elfeffe** [comment]
@catphish yes, it works now
