### ISSUE TITLE
The DKIM record doesnt pass

### ISSUE THREAD

**Issue by khamrouniquestel** [atech/postal#812]
I got a DKIM error on postal when trying to configure the server. 

new installation using the quick intall guide on digitalocean

My DNS server config
![image](https://user-images.githubusercontent.com/47317068/57785869-ce04c500-7732-11e9-8ed4-509182c83afc.png)

Postal page
![image](https://user-images.githubusercontent.com/47317068/57785905-dd840e00-7732-11e9-833b-ae0e61888881.png)

Any ideas?

**Comment by willpower232** [comment]
you are missing the ; at the end 😊

**Comment by tchwpkgorg** [comment]
Also, for the future, would be easier if you've pasted at least domain names as text.

Believe it or not, my browser is unable to copy text from screenshots!

**Comment by khamrouniquestel** [comment]
Okay... Thank you for your help.
I have a little problem here: apparently, my dns provider (ovh) is removing the last ";"
Is there a workaround for that? Like modifying the verification function...?
________________________________

**Comment by willpower232** [comment]
OVH shouldn't be removing the last character, thats not good news for anyone. Are you able to discuss it with them?

Even if you modify the verification function, your recipients email cllients and servers may not be able to verify the messages so its better it is corrected in the DNS.

**Comment by 16n** [comment]
We have the same problem as explained above. A clients entreprise DNS software strips the ; from the DKIM record. After some research I found out that the ; is indeed optional. 

The RFC 4871 (https://tools.ietf.org/html/rfc4871) specifies the following rule:
tag-list  =  tag-spec 0*( ";" tag-spec ) [ ";" ]

Would accept a pull request that extends the validator function (https://github.com/atech/postal/blob/0fb323af3f37201eed492646007ed355f3617b51/app/models/domain/dns_checks.rb#L72) with a check for the entry without the ";"?

**Comment by willpower232** [comment]
Thanks for the research, its definitely worth creating a PR.

**Comment by MorneL** [comment]
I've created a PR for this issue

**Comment by catphish** [comment]
Hopefully this is fixed :)
