### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by bluebaroncanada** [atech/postal#817]
This is one of the best pieces of software I've ever used.  It's damn-near perfection.  Where can I donate?  I looked all over for a donation button.

**Comment by willpower232** [comment]
You would probably be better off contacting atech directly as there isn't anything set up right now.

**Comment by catphish** [comment]
I'm glad to hear you like Postal! This software was developed by aTech Media to support our commercial products, and was essentially built for our own use. As such, the development is funded by our other commercial activities, and we have no way to accept donations at this time.
:+1:
