### ISSUE TITLE
Tracking Issue 

### ISSUE THREAD

**Issue by freshwebs** [atech/postal#821]
I have a problem. The setup and configuration of Postal was great and easy solved. Now I come to our problem:

The e-mail tracking and URL replace works via normal e-mail from the e-mail client without any problems. It will replace the HTML parts as well as the text / plain.

We use the open-source ticket system "Zammad" in the company. Zammad sends the e-mail (mixed from PlainText and HTML) via SMTP to Postal.
In this email Postal does not manage to install the tracking pixel in front of the </ body>. Also, the links are not replaced by the tracking links.

I looked at the source code of Postal, publically he does not recognize the </ body> Tag from the emails of Zammad. It is there anyway.

What would I have to provide information so that we can change the problem?

many Greetings
Jan

**Comment by willpower232** [comment]
Are you sending the Zammad emails from the same part as your test messages?
Do they use the same domain?
If not, have you set up tracking for the domain Zammad is using?

**Comment by freshwebs** [comment]
Yes, same domain, same account, same credentials.

This is an actually e-mail from zammad trough postal, the text/plan part the links a converted to tracking links, in the text/html part no tracking pixel and no tracking links, still the original link:

`----==_mimepart_5cf62333a61ad_2502b2577b814e8239e1
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5cf62333a5d57_2502b2577b814e82372b";
 charset=UTF-8
Content-Transfer-Encoding: 7bit

----==_mimepart_5cf62333a5d57_2502b2577b814e82372b
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

[1] https://tt.[CENSORED.TLD]/zwe1at/qapqua0r

[1] https://tt.[CENSORED.TLD]/zwe1at/lKSfHRdQ
----==_mimepart_5cf62333a5d57_2502b2577b814e82372b
Content-Type: multipart/related;
 boundary="--==_mimepart_5cf62333a5e69_2502b2577b814e823895";
 charset=UTF-8
Content-Transfer-Encoding: 7bit

----==_mimepart_5cf62333a5e69_2502b2577b814e823895
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>=0D
<html>=0D
  <head>=0D
    <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF-8=
"/>=0D
    <meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge"/>=0D
    <style type=3D"text/css">=0D
      body {=0D
        font-family:'Helvetica Neue', Helvetica, Arial, Geneva, sans-serif; =
font-size: 12px;;=0D
      }=0D
      img {=0D
        outline: none;=0D
        text-decoration: none;=0D
        -ms-interpolation-mode: bicubic;=0D
      }=0D
      a img {=0D
        border: none;=0D
      }=0D
      table td {=0D
        border-collapse: collapse;=0D
      }=0D
      table {=0D
        border-collapse: collapse;=0D
        mso-table-lspace: 0pt;=0D
        mso-table-rspace: 0pt;=0D
        border: none;=0D
        table-layout: auto;=0D
        display: block;=0D
        width: 100%;=0D
        overflow: auto;=0D
        word-break: keep-all;=0D
      }=0D
      table,=0D
      pre,=0D
      blockquote {=0D
        margin: 0 0 16px;=0D
      }=0D
      td, th {=0D
        padding: 7px 12px;=0D
        border: 1px solid hsl(0,0%,87%);=0D
      }=0D
      th {=0D
        font-weight: bold;=0D
        text-align: center;=0D
      }=0D
      tbody tr:nth-child(even) {=0D
        background: hsl(0,0%,97%);=0D
      }=0D
      col {=0D
        width: auto;=0D
      }=0D
      p {=0D
        margin: 0;=0D
      }=0D
      code {=0D
        border: none;=0D
        background: hsl(0,0%,97%);=0D
        white-space: pre-wrap;=0D
      }=0D
      blockquote {=0D
        padding: 8px 12px;=0D
        border-left: 5px solid #eee;=0D
      }=0D
      pre {=0D
        padding: 12px 15px;=0D
        font-size: 13px;=0D
        line-height: 1.45;=0D
        background: hsl(0,0%,97%);=0D
        white-space: pre-wrap;=0D
        border-radius: 3px;=0D
        border: none;=0D
        overflow: auto;=0D
      }=0D
    </style>=0D
  </head>=0D
  <body style=3D"font-family:'Helvetica Neue', Helvetica, Arial, Geneva, sa=
ns-serif; font-size: 12px;"><div>=0D
<a href=3D"https://github.com/atech/postal/issues/821" rel=3D"nofollow nore=
ferrer noopener" target=3D"_blank">https://github.com/atech/postal/issues/8=
21</a>=C2=A0<br>=0D
</div><div data-signature=3D"true" data-signature-id=3D"1">=0D
<div>=0D
<p style=3D"margin: 0;">=0D
=0D
=0D
</p>=0D
<p style=3D"margin: 0;"></p>=0D
<p style=3D"margin: 0;">=0D
=0D
=0D
</p>=0D
<p style=3D"margin: 0;"></p>=0D
<p style=3D"margin: 0;">=0D
=0D
=0D
</p>=0D
<p style=3D"margin: 0;"></p>=0D
<p style=3D"margin: 0;"></p>=0D
</div>=0D
<p style=3D"margin: 0;"></p>=0D
<div></div>=0D
</div></body>=0D
</html>
----==_mimepart_5cf62333a5e69_2502b2577b814e823895--

----==_mimepart_5cf62333a5d57_2502b2577b814e82372b--

----==_mimepart_5cf62333a61ad_2502b2577b814e8239e1--`

**Comment by willpower232** [comment]
Ah looks like there is a `multipart/related` part involved so I'd imagine this is related to https://github.com/atech/postal/issues/802

There is a PR for that so you could apply that change to your Postal and see if that resolves your problem.

**Comment by freshwebs** [comment]
It works!! Thank you very much.
