### ISSUE TITLE
Strip Replies Not Working As Expected

### ISSUE THREAD

**Issue by danpastori** [atech/postal#824]
Hi!

First off, amazing piece of software! It's been a joy to implement and work with!

We only ran into one bug and it involves stripping the replies from an incoming email. I know this can be a complicated task, but it doesn't seem to be working when we have Strip Replies on an API Route selected:
<img width="622" alt="Screen Shot 2019-06-07 at 1 30 50 PM" src="https://user-images.githubusercontent.com/2365103/59131933-a4e9e580-8928-11e9-849e-3264e629ca6e.png">

Is there are some attempted regex solutions here: https://stackoverflow.com/questions/278788/parse-email-content-from-quoted-reply. Maybe if there was a way to attempt to remove it and pass it as another parameter for error checking?

Thanks again for making Postal! It really is a joy to work with!

**Comment by willpower232** [comment]
Presuming the strip replies functionality is being triggered in your case, do your messages match any of the formats listed in https://github.com/atech/postal/blob/master/lib/postal/reply_separator.rb ?

**Comment by danpastori** [comment]
@willpower232 thanks for the response! I realized I was looking at the HTML email and not the plain body. This is not a bug, it's working as expected!
