### ISSUE TITLE
Email from iCloud / @me.com not hitting server at all

### ISSUE THREAD

**Issue by timraybould** [atech/postal#827]
My mail server is running just fine for the most part, and takes receipt of email from gmail and yahoo addresses. But when I send mail from my @me.com address, it never hits my mail server. Nothing in smtp_server.log at all. I'm pretty sure this isn't a Postal issue -- rather Apple's servers are deciding not send to my domain/ip for some reason. But, maybe I'm wrong about that so I figured I'd ask if anyone has experienced this or has any tips for how to fix.

fwiw, the IP address is not blocked via proofpoint (which I know Apple uniquely uses) nor spamhaus.

**Comment by willpower232** [comment]
If your Postal is successfully receiving messages from other addresses, its more likely to be Apples end as having a problem.

At a random guess, I presume your Postal server has reverse DNS set up?

**Comment by timraybould** [comment]
It does have reverse DNS, yes.

It's gotta be something in the DNS they don't like. It's setup per instructions I'm pretty sure, but in case you spot anything off:

- A record on the subdomain, pointing to server's IP
- MX record on @ pointing to subdomain.example.com
- TXT record `v=spf1 a mx include:spf.subdomain.example ~all`
- TXT record `v=DMARC1; p=none`
- TXT record from postal UI for DKIM signature
- CNAME psrp to rp.subdomain.example.com
- A, MX, & spf TXT all repeated for rp.subdomain

Also, the server purposely does not use ipv6 for this stupid digital ocean reason: https://www.digitalocean.com/community/questions/outbound-ipv6-tcp-25-blocked-outbound

I might try to setup an entire new box with ipv6 enabled in linode or someplace.

**Comment by willpower232** [comment]
The only different thing that jumps out is your DMARC record but unless Apple are handling it badly, I can't see why it would be a problem.

It would be interesting to know the outcome of an alternative hosting provider but I guess you won't know for sure what the problem is without contacting Apple to see if you can find out what happened to your messages.

**Comment by timraybould** [comment]
Reinstalled everything on a new server and reset DNS. Linode this time, instead of Digital Ocean, to avoid the IPV6 issue. Same issue. Other mail providers are delivered fine but mail from Apple domains don't make a peep on the server. My domain itself must be on a blacklist. I'll close the issue here.
