### ISSUE TITLE
Softfail issue

### ISSUE THREAD

**Issue by x86fantini** [atech/postal#83]
Hi, just installed postal (btw it works great!) and wanted to use it with a customer. Here in italy we still have some users with emails hosted on @libero.it. now in my queue i see some "soft fail" on mails sent to @libero.it

421 smtp-28.iol.local smtp-28.iol.local No reverse DNS [smtp-28.iol.local; LIB_120]
Support Ref: THXTUF6C

No SMTP servers were available for libero.it. Tried mx.libero.it

can you please give me a hand on how and where to spot the issue? thank you
S

**Comment by adamcooke** [comment]
Sounds like you haven't set up reverse DNS for the IP that is sending your messages.

**Comment by x86fantini** [comment]
hello, good point.
finally my provider  added PTR to my ip. Should i now manually resend all the email in softbounce?

**Comment by catphish** [comment]
> Should i now manually resend all the email in softbounce?
Yes, perhaps just try one message at a time and see if it works.

**Comment by x86fantini** [comment]
retried right now, still no luck but i think it was not my PTR record faulted..

![image](https://cloud.githubusercontent.com/assets/4339939/25655047/d3de20ee-2ff3-11e7-98f8-975f88b7fb7d.png)

my setup is:
IP: 185.136.177.200
hostname: ssmtp.magehosting.it

PTR looks fine

;; ANSWER SECTION:
200.177.136.185.in-addr.arpa. 60 IN	PTR	ssmtp.magehosting.it.


i'm trying to send an email to xxxx@libero.it but message always get to soft bounce


what else can i check? thank you for support

**Comment by x86fantini** [comment]
UPDATE:
i have logged in in Postal dashboard, then from Organization i have entered the mailserver i'm using and tried "Send Message" to a @libero.it email and it worked.

i think i just need to wait few more hours for the other email to go out....

**Comment by x86fantini** [comment]
UPDATE:
my queue is now empty, and all emails went through. everything looks fine now

thank you
