### ISSUE TITLE
Is Raspbian Strech supported?

### ISSUE THREAD

**Issue by xpresservers** [atech/postal#830]
Hi,

 I am thinking to install this on Raspberry Pi 3b+ with Raspbian Strech. But I see only Ubuntu 16.04 related documentation. Is it possible to install on other OSes?

**Comment by willpower232** [comment]
Other people in the issues have it working on Centos and I've seen people using Postal in Docker/Kubernetes so theres no immediate reason it wouldn't work for you on Raspbian.

The only real requirements are Ruby 2.3 and enough memory for all the services (depending on how you're arranging your installation).

**Comment by catphish** [comment]
Unfortunately I think this will seriously struggle with 1GB of RAM :(
