### ISSUE TITLE
dns_checks.rb:73:in sanitised_dkim_record'

### ISSUE THREAD

**Issue by TuguldurJ** [atech/postal#831]
After this commit, i got an error on DNS check function. Please revert commit or fix it.

[web.1:1850] [2019-06-21T23:24:06.364] INFO -- : Completed 500 Internal Server Error in 97ms (ActiveRecord: 34.1ms)
[web.1:1850] [2019-06-21T23:24:06.366] FATAL -- :
[web.1:1850] [2019-06-21T23:24:06.366] FATAL -- : NameError (undefined local variable or method records' for ): [web.1:1850] [2019-06-21T23:24:06.366] FATAL -- : [web.1:1850] [2019-06-21T23:24:06.366] FATAL -- : app/models/domain/dns_checks.rb:73:in sanitised_dkim_record'
app/models/domain/dns_checks.rb:88:in check_dkim_record' app/models/domain/dns_checks.rb:15:in check_dns'
app/controllers/domains_controller.rb:99:in check'

**Comment by catphish** [comment]
Thanks for drawing attention to this. Please can you confirm whether the problem is now fixed by https://github.com/atech/postal/commit/bb27d8c8a1703250a080caa0a182452aa4896783

**Comment by TuguldurJ** [comment]
I will check and inform you whether problem solved, thank you for fixing this issue.

**Comment by TuguldurJ** [comment]
It fixed now. Thank you!
