### ISSUE TITLE
resend e-mails

### ISSUE THREAD

**Issue by niels-smoice** [atech/postal#84]
Hello,

it would be great to be able to resend messages from the interface. E.g when a mail failed due to a full mailbox 

THX and best wishes

Niels

**Comment by mattmartincouk** [comment]
You can do this as long as the message is a soft-fail.

If it times out (after the default 18 re-attempts), it'll fail completely.

**Comment by niels-smoice** [comment]
Okay THX 👍

**Comment by LaurensN** [comment]
Why only on a soft-fail though ?

In DeliverHQ for example, the resend button is always present.

IMO it is preferable to always be able to resend a message, regarding of its status.
