### ISSUE TITLE
Migrating install 500 error

### ISSUE THREAD

**Issue by JAP42** [atech/postal#840]
I am running postal on docker using a slightly modified catdeployed image along with mysql, rabbitmq, and nginx. 

The setup has worked great and I want to migrate everything over to my new server. I dumped the sql and restored it on the new server and started everything up. Now the service is up and running and forwarding my emails as it did before. But when I load the interface on the list of Organizations I see my existing Org, however when I click it I get an error page `something went wrong`. I tried running postal upgrade and it succeeded but still getting the same thing. 

Postal App Logs
```
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.025] INFO -- : Started GET "/org/org-name" for ****.***.***.8*** at 2019-07-01 11:58:48 +0000,
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.026] INFO -- : Processing by ServersController#index as HTML,
11:58:48 web.1              | => /opt/postal/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/mysql/database_statements.rb:34: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.,
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.026] INFO -- :   Parameters: {"org_permalink"=>"org-name"},
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.149] INFO -- :   Rendering servers/index.html.haml within layouts/application,
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.162] INFO -- :   Rendered organizations/_nav.html.haml (4.8ms),
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.173] INFO -- :   Rendered servers/index.html.haml within layouts/application (24.0ms),
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.174] INFO -- : Completed 500 Internal Server Error in 147ms (ActiveRecord: 8.9ms),
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.175] FATAL -- : ActionView::Template::Error (Table 'postal-server-3.live_stats' doesn't exist):,
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.175] FATAL -- :   ,
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.175] FATAL -- :     26:             = link_to [organization, server], :class => 'largeList__link' do,
11:58:48 web.1              | =>     27:               %span.largeList__rightLabel.label{:class => "label--serverStatus-#{server.status.underscore}"}= t("server_statuses.#{server.status.underscore}"),
11:58:48 web.1              | =>     28:               %p= server.name,
11:58:48 web.1              | =>     29:               %p.largeList__subText #{number_with_precision server.message_rate, :precision => 2} messages/minute,
11:58:48 web.1              | =>     31:         .noData.noData--clean,
11:58:48 web.1              | =>     32:           %p.noData__title No servers were found...,
11:58:48 web.1              | =>     30:       .js-searchable__empty.is-hidden,
11:58:48 web.1              | => [web.1:19] [2019-07-01T11:58:48.175] FATAL -- : lib/postal/message_db/database.rb:319:in `query_on_connection',
11:58:48 web.1              | => lib/postal/message_db/database.rb:311:in `block in query',
11:58:48 web.1              | => lib/postal/message_db/database.rb:310:in `query',
11:58:48 web.1              | => lib/postal/message_db/mysql.rb:20:in `client',
11:58:48 web.1              | => lib/postal/message_db/database.rb:342:in `with_mysql',
11:58:48 web.1              | => lib/postal/message_db/live_stats.rb:34:in `total',
11:58:48 web.1              | => app/views/servers/index.html.haml:29:in `block (2 levels) in _app_views_servers_index_html_haml___2178663824207852496_47234435697680',
11:58:48 web.1              | => app/models/server.rb:139:in `message_rate',
11:58:48 web.1              | => app/views/servers/index.html.haml:26:in `block in _app_views_servers_index_html_haml___2178663824207852496_47234435697680',
11:58:48 web.1              | => app/views/servers/index.html.haml:24:in `each',
11:58:48 web.1              | => app/views/servers/index.html.haml:24:in `_app_views_servers_index_html_haml___2178663824207852496_47234435697680',
11:58:48 web.1              | => 000.000.000.000, 172.19.0.4 - - [01/Jul/2019:11:58:48 +0000] "GET /500 HTTP/1.0" 500 1477 0.1526
```

If I start another Organization it works fine and I can do anything except I get errors if I creating something that already exists under my other org, just stating it already exists. 

Version: `1.0.0-dev`

**Comment by willpower232** [comment]
This appears to be a warning for new Ruby version (>= 2.5), currently only 2.3 is directly supported by atech so your best bet would be to either PR a fix or get an older Ruby version in your image. Presumably this will be a problem for catdeployed as well so it might be worth discussing with them.

**Comment by JAP42** [comment]
The warnings you see related to the newer version are info only at this point. The oldest official docker image is 2.4 but this uses 2.6. This issue only applies the the old organization migrated from the same setup on a different server. New Organizations work fine. 

I think the true error that stops everything is `Error (Table 'postal-server-3.live_stats' doesn't exist):,` Possibly a migration issue because I may have not had the same version on postal.

**Comment by JAP42** [comment]
OK, so i had a `postal-server-7` database with that table. So I copied all its contents to a new database `postal-server-3` Now the error shows `postal-server-2`

**Comment by JAP42** [comment]
Solved! I did not see that a new database was created for each server under my org. Thats why I only saw postal-server-7. It was the server I created to test. So I just needed to copy those databases also and all was good!

**Comment by rohitatcoffee** [comment]
> 

I am also facing the same issue. Can you please tell me how you get the server list? I am not able to find the list.

I did:
1. Deleted and created MariaDB docker and then restored old DB
2. I also did the same thing for deleted and created new rabbitmq
 
Can you please help me out?
