### ISSUE TITLE
Configure Exim to use Postal as Relay Server

### ISSUE THREAD

**Issue by imvask** [atech/postal#841]
Hi all,

Im trying to configure my Exam server to use Postal as a relay SMTP.

Im now using SendinBlue so I just have to change the credentials and smtp servers on the exam.conf file.

On postal I just created an organization with a server which have a domain registered to authorize sending mails.

I created credentials too to use them on the exam.conf file, but when I use them and restart exim, mails are not being send.

What am I missing?

**Comment by willpower232** [comment]
> mails are not being send

What do you mean by this? Can you see the messages in Postal at all or can you see errors in your Exim logs?

**Comment by imvask** [comment]
This is the error from exit while trying to send an e-mail:

**Comment by imvask** [comment]
@willpower232 
This is the error from exit while trying to send an e-mail:

`1hhvrT-0006kr-BK == email@domain.com R=send_via_vask T=vask_smtp defer (-53): retry time not reached for any host for 'domain.com'`

This are the settings on exim to relay: (This same settings are working with SendinBlue)

```
------
begin authenticators
sendinblue_login:
  driver = plaintext
  public_name = LOGIN
  client_send = : user : password (credentials created on Postal)
------
begin routers
 send_via_sendinblue:
  driver = manualroute
  domains = ! +local_domains
  transport = sendinblue_smtp
  route_list = "* smtp-relay.mydomain.com::25 byname"
  host_find_failed = defer
  no_more
-----
begin transports
 sendinblue_smtp:
  driver = smtp
  hosts = smtp-relay.mydomain.com
  hosts_require_auth = smtp-relay.mydomain.com
  hosts_require_tls = smtp-relay.mydomain.com
```

And I can not see any login attempts on Postal logs.

On postal this is what I did:

-Created Organization
-Created Mail Server for that organization
-Register the domain of the e-mails I want to relay
-Created SMTP credentials to access.

netstat -tlpn shows that postal is listening on port 25 so it should be running ok

Tried sending test mails on "Send Message" and it works, so I think the problem is that I'm missing something but I do not know what. If you need more info tell me.

Thanks!

**Comment by willpower232** [comment]
From what you've said, it sounds like the problem is in Exim, not Postal so it would be worth consulting someone who knows Exim and can tell you what is wrong.

**Comment by imvask** [comment]
Hi @willpower232 

I finally solved it, thanks for your help!

Just tried many configurations on exam and finally I have the one which works, I´ll post it here because it will may be useful for somebody.

```
begin_authenticators
remote_login:
  driver = plaintext
  public_name = LOGIN
  client_send = ": user : password"
 # server_set_id = $auth1
-----
begin routers
smarthost:
  driver = manualroute
  domains = ! +local_domains
  transport = send_remote_smtp
  route_list = * mail.domain.com
-----
begin transports
send_remote_smtp:
  driver = smtp
  hosts = mail.domain.com
  hosts_require_auth =  mail.domain.com
```

**Comment by williank** [comment]
@imvask Do you still use it today?

**Comment by williank** [comment]
> Hi @willpower232
> 
> I finally solved it, thanks for your help!
> 
> Just tried many configurations on exim and finally I have the one which works, I´ll post it here because it will may be useful for somebody.
> 
> ```
> begin_authenticators
> remote_login:
>   driver = plaintext
>   public_name = LOGIN
>   client_send = ": user : password"
>  # server_set_id = $auth1
> -----
> begin routers
> smarthost:
>   driver = manualroute
>   domains = ! +local_domains
>   transport = send_remote_smtp
>   route_list = * mail.domain.com
> -----
> begin transports
> send_remote_smtp:
>   driver = smtp
>   hosts = mail.domain.com
>   hosts_require_auth =  mail.domain.com
> ```

@imvask Do you still use it today?
