### ISSUE TITLE
ip rule settings

### ISSUE THREAD

**Issue by masihfathi** [atech/postal#842]
hi,
i want to set a ip pool just send to gmail and outlook, how is it possible to set this Rule in a to addresses field of ip rules?

**Comment by willpower232** [comment]
I don't believe this feature exists in Postal.

Presumably there is nothing stopping you from setting up a specific Organisation with an IP Pool and then only using that organisation to send gmail and outlook messages in your app.

**Comment by masihfathi** [comment]
it is possible to match domain a to addresses field of ip rule but i think it is better to match a regex pattern which user can change by his needs, user write his pattern and postal check if it is matched.
