### ISSUE TITLE
Temporarily Deferred Error Though IP Address Not on Any Blacklist

### ISSUE THREAD

**Issue by Hadeoluwah** [atech/postal#843]
The IP address (287.190.241.178) where the email is being delivered from is not on any blacklist when checked on Mxtoolbox

But I observed that the IP address hosting the "From Email Address" is on  Spamhaus ZEN Blacklist, which then auto place the "From Email Address" on Blacklist.

Can the IP address hosting the "From Email Address" affect the delivery of emails with the error 
"421 4.7.0 [TSS04] Messages from 287.190.241.178 temporarily deferred due to user complaints" ?

**Comment by willpower232** [comment]
An IP address cannot contain 287 so I'm not sure how you're getting that specific message. Are you seeing it in Postal when trying to send messages?

**Comment by Hadeoluwah** [comment]
@willpower232 I tweaked it because of public space

Please help with the your advice.

I am waiting. Thanks

**Comment by willpower232** [comment]
Are you seeing this error in Postal when trying to send messages?

**Comment by Hadeoluwah** [comment]
Yes please see the screenshot here https://m.imgur.com/gallery/HWv9JBP

**Comment by willpower232** [comment]
Its possible Yahoo is using its own blacklist or one that isn't checked by mxtoolbox. How mail servers handle blacklists is totally down to them so if they think you're spamming them, you'll have to appeal directly to them or any random blacklist you can find that you're even slightly mentioned on.

**Comment by catphish** [comment]
This error clearly states that your host has been sending spam and people have complained :(
As Will says, Yahoo will have their own internal blacklists, there's no way for you to query them.
