### ISSUE TITLE
Can I install postal on a openvz VPS with 2GB RAM and 30GB SSD?

### ISSUE THREAD

**Issue by lovelyns** [atech/postal#845]
Can I install postal on a openvz VPS with 2GB RAM and 30GB SSD?
@willpower232 @catphish @adamcooke

**Comment by catphish** [comment]
@lovelyns

**Comment by catphish** [comment]
I believe this wouldn't be enough RAM. If you look through historical tickets, you will likely find similar discussions of minimum requirements.
