### ISSUE TITLE
Forward bounces/suppressions to original sender

### ISSUE THREAD

**Issue by niels-smoice** [atech/postal#85]
Hello,

it would be great to forward bounced messages with the reason back to the sender so the sender can check what happened and correct it and resend the message.
THX and best wishes

Niels

**Comment by niels-smoice** [comment]
So to inform users for sending errors .. it would be nescessary to create a web hook and forward the error on our own ?

**Comment by mattmartincouk** [comment]
As I understand it from the docs, yes. I'm sure someone will be along to clarify though.

**Comment by adamcooke** [comment]
Bounces are sent to senders in some situations. They should be sent on hard fails and when it has been retried the maximum number of times.
