### ISSUE TITLE
ipv6 in postal.yml

### ISSUE THREAD

**Issue by epipheus** [atech/postal#851]
faster server keeps respawning before failing. The only change I've made (that I can presently think of is that I allocated an ipv6 range for the server and specified the bind address as an ipv6 ipl is that not supported?

**Comment by willpower232** [comment]
Have you had a look at the `fast_server` log file to see what is happening?

**Comment by epipheus** [comment]
I have no fast_server logs at all.

**Comment by willpower232** [comment]
Your other option is that `postal status` will tell you which commands are run for each part of Postal so you can try running that command manually and getting the direct output which will hopefully point you in the right direction.

**Comment by pjv** [comment]
```
postal status
Procodile Version   1.0.23
Application Root    /opt/postal/app
Supervisor PID      1497
Started             2019-07-19 12:38:18 +0000

 * fast.3 is not running (Failed)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      12:38        pid:1503     respawns:0      port:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.3           Failed       13:15        pid:2664     respawns:5      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.3         Running      13:14        pid:2590     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.3           Running      13:14        pid:2608     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      13:14        pid:2598     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.3       Running      13:14        pid:2607     respawns:0      port:-        tag:-
```

**Comment by pjv** [comment]
modifying the nginx conf to explicitly bind to the primary public ip fixed the above problem for me and let the fast server start:

```
server {
    listen 165.X.X.X:80;
    server_name postal.plexusllc.com;
    return 301 https://$host$request_uri;
}

server {
    listen 165.X.X.X:443 ssl;
```

**Comment by epipheus** [comment]
I've already done all that... hmm

**Comment by epipheus** [comment]
Running ` bundle exec rake postal:fast_server` yields the following for me:

`Errno::EADDRNOTAVAIL: Cannot assign requested address - bind(2) for "2604:a880:400:d0::6af:9002" port 80`

which is weird because this is the range assigned by DigitalOcean and I have DNS records pointing there and firewall clearing port 80 via their firewall UI; though I'm not sure if it does it for all IPs.  Hmmm.  I had no luck with DO's floating IP for fast_server and am using an IP from the IPv6 range DO gave.

**Comment by pjv** [comment]
rails. ☹️

**Comment by willpower232** [comment]
Can you double check that nothing else is using that port and address combination on your server?

You may also note that others in the issues have mentioned that DO doesn't allow SMTP over IPv6 anyway so have removed it from their installations.

**Comment by epipheus** [comment]
OK. Here's the deal.  DigitalOcean assign an IPv4; just forget about the floating IPs.  They also assign an IPv6 range but only the first one in the block is actually assigned; the rest are merely reserved I guess.  To change this on Ubuntu you can [follow their documentation](https://www.digitalocean.com/docs/networking/ipv6/how-to/add-additional/) but I'm also noting this here -- do the following:

sudo edit `/etc/netplan/50-cloud-init.yaml`. The example in their documentation 
```yaml
network:
    version: 2
    ethernets:
        eth0:
            addresses:
            - 203.0.113.213/20
            - your_primary_ipv6_address/64
            - your_additional_ipv6_address/64
            - 192.0.2.11/16
            gateway4: 206.189.208.1
            gateway6: ipv6_gateway
            match:
                macaddress: ce:2c:ex:am:pl:e6
```
They give you 15 IPv6 address, put as many of them from your block in that you want to use. 

According to the documentation to apply the change and test:

1. Run sudo netplan apply --debug. When the command is successful, it won’t provide output.
1. Run ping6 your_additional_ipv6_address. If you can reach the new address with ping6, it is correctly configured.
They also note that a reboot is not necessary, because the above netplan command implements the changes immediately.

Et Voilà, IPv6 working for fast_server -- or at least it isn't respawning or failing. Which is nice. 

Happy to add this to your wiki later today or tomorrow

**Comment by epipheus** [comment]
But for the fast_server isn’t smtp and requires a separate ip. So if it’s possible ipv6 is worth a shot. VPS’s give plenty of them and are quite stingy with ipv4 addresses.
