### ISSUE TITLE
new user

### ISSUE THREAD

**Issue by masihfathi** [atech/postal#852]
Hi, 
How we can create user and  assigned to a organization?
In above of create a user through web UI, it show:

> To add someone to your organization enter their e-mail address below. If they don't already have a Postal account, they'll need to create one before you can add them to your account.

> 
where we should create users? how they can create account? through cli?

**Comment by willpower232** [comment]
Firstly, make sure you have configured a way for Postal to send emails in your `postal.yml` config file.

Then if you want a user to access only one organization or only one server in an organization, use the form to send them an email.

If you want a user to access all organizations, you will need to use the `postal make-user` command in your terminal.

**Comment by masihfathi** [comment]
i added smtp connection but app emails not sent?

**Comment by willpower232** [comment]
You'll have to look in the logs to see what is happening I'm afraid.

**Comment by mudasirraza** [comment]
@willpower232 

> Then if you want a user to access only one organization or only one server in an organization, use the form to send them an email.

Hi, how can you let/add user to access only one mail server in an organization, and not all mail servers? Current invite user option will create a user with access to every mail server in an organization.
