### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by mhemrg** [atech/postal#866]
Hey, thank you for a great job.
Can you please provide a simple contribution guide and docs for development setup?
They will help a lot as a starting point.

**Comment by willpower232** [comment]
AFAIK there isn't really a separate development setup.

The best thing to do would be to install Postal using a fork of git repo and Docker or a spare Ubuntu server so you can reinstall regularly as you work on it.

You can then make PRs using your fork to contribute.
