### ISSUE TITLE
hard fail

### ISSUE THREAD

**Issue by harshweo** [atech/postal#871]
Hello Everyone
I have setup postal email server on ubuntu 18.04 ,this is hosted on aws and domain is resgistered on godaddy. after setup some time email are going in spam and when i send email to gmail it comes with hardfail erorr. my records are configured 
http://prntscr.com/ozg2p4
Error Message :
http://prntscr.com/ozg5xy
@adamcooke @adamcooke 
@catphish @darkphnx  @asterion @luizeof

**Comment by nmanley** [comment]
@harshweo have to had a look at googles postmaster tools?

https://gmail.com/postmaster/

**Comment by willpower232** [comment]
The error message you are seeing is more than useful here. Your IP is currently very low reputation, either due to past activity or not having all the reverse DNS set up or something along those lines. The tools mentioned above may help you narrow down what is going wrong but there isn't much more that can be done by those here.

**Comment by harshweo** [comment]
Thank you guys now mail goes to gmail but all the email goes in spam can you help me @nmanley  @willpower232

**Comment by nmanley** [comment]
@harshweo there are a bunch of basics you need to cover first.

I would first start with reading hotmail, aol, and gmails postmaster guides.
https://support.google.com/mail/answer/81126?hl=en
https://sendersupport.olc.protection.outlook.com/pm/
https://postmaster.aol.com/best-practices

Second, work on resolving your IPs reputation. Do you have another IP address you can send from? You can always setup a relay at Linode for $5, OVH has cheap VPSs however they do tar-pitting on port 25.
Enable IP Pooling and slowly build that reputation ip again, by sending messages to address's you know for sure are good. 

Does your IP have a negative history which tarnished it's reputation?
https://www.talosintelligence.com/reputation_center

Based on the screenshot you have Your DNS is good to go however:
Have you setup the reverse dns?
Have you implemented DMARC? If so, is your policy quarantine or higher?
Does your DMARC align with your SPF ~-+?
Is the from email your sending from a deliverable address?

Other considerations.
Are you participating in the feedback loops?
How often do you clean your email list?
    You must perform the barebones clean before sending.
    1. Email is valid
    2. MX Records exist.
    3. SMTP HELO
    4. Email isn't disposable.

    I generally do a quick clean ever 100 days. I reset the counter if the user engages.

It's honestly hard to tell without knowing your IP, Domain or any particulars.

Best of Luck,
Nathan

**Comment by harshweo** [comment]
> @harshweo there are a bunch of basics you need to cover first.
> 
> I would first start with reading hotmail, aol, and gmails postmaster guides.
> https://support.google.com/mail/answer/81126?hl=en
> https://sendersupport.olc.protection.outlook.com/pm/
> https://postmaster.aol.com/best-practices
> 
> Second, work on resolving your IPs reputation. Do you have another IP address you can send from? You can always setup a relay at Linode for $5, OVH has cheap VPSs however they do tar-pitting on port 25.
> Enable IP Pooling and slowly build that reputation ip again, by sending messages to address's you know for sure are good.
> 
> Does your IP have a negative history which tarnished it's reputation?
> https://www.talosintelligence.com/reputation_center
> 
> Based on the screenshot you have Your DNS is good to go however:
> Have you setup the reverse dns?
> Have you implemented DMARC? If so, is your policy quarantine or higher?
> Does your DMARC align with your SPF ~-+?
> Is the from email your sending from a deliverable address?
> 
> Other considerations.
> Are you participating in the feedback loops?
> How often do you clean your email list?
> You must perform the barebones clean before sending.
> 1. Email is valid
> 2. MX Records exist.
> 3. SMTP HELO
> 4. Email isn't disposable.
> 
> ```
> I generally do a quick clean ever 100 days. I reset the counter if the user engages.
> ```
> 
> It's honestly hard to tell without knowing your IP, Domain or any particulars.
> 
> Best of Luck,
> Nathan

Hi Nathan 
my Domain is mail.webexpertsonline.co
IP: 35.171.143.82
http://prntscr.com/p15tqz
http://prntscr.com/p15wsj
http://prntscr.com/p15wz8
http://prntscr.com/p15xbz
please check the screen shots i am facing these issue.

**Comment by nmanley** [comment]
@harshweo  Have you registered with google post master tools?

Also testing email to your own gmail, have you looked at the raw message "gmail terms: original"

![image](https://user-images.githubusercontent.com/3496307/64188509-cecf7d00-ce2f-11e9-8c60-97fb9e503023.png)

![image](https://user-images.githubusercontent.com/3496307/64188575-ea3a8800-ce2f-11e9-9355-638155bab547.png)

![image](https://user-images.githubusercontent.com/3496307/64188716-253cbb80-ce30-11e9-9d45-365fc7c84882.png)

Check a message in gmail that was sent from your mail server to your personal gmail.

Gmail provides a fairly decent array of info for debugging purposes.
