### ISSUE TITLE
Message Held For 7 Days Upon Reaching 1 Hour Max Delivery.

### ISSUE THREAD

**Issue by nmanley** [atech/postal#872]
Upon reaching the max hourly send limit, the emails get held, however instead of being queued to go out at the next hourly interval, they are queued for 7 days in the future.

Is this normal?

**Comment by willpower232** [comment]
> they are queued for 7 days in the future

I believe you'll find the messages are simply held for that time and then nothing happens. During those seven days you can "release" the message which will re try it. After that time, you'll have to click on "redeliver" to actually send the message as a new message in Postal.

If you want to resend the held messages, you'll have to manually go into each one. If you have a lot of these held messages, you may consider having a look at https://github.com/atech/postal/issues/144#issuecomment-498635520

If you are regularly hitting the limit, you may need to increase the limit (or ask your server administrator to if you can't change that setting)

**Comment by nmanley** [comment]
@willpower232 thanks for the feedback.

In lieu of the hold times. I've been working on a little script that re-adjusts the status of the message attempting to re-queue it when available space is sufficient as well as changing the way soft-failing handles provider greylisting.
