### ISSUE TITLE
URL sign in path

### ISSUE THREAD

**Issue by brinnington** [atech/postal#873]
I have installed WordPress on the same server as Postal. 

I was able to sign into Postal using:

mysite.com/login?return_to=%2F

But now that I have installed WordPress, I get Oops! That page can't be found.

Do you happen to know if there is an alternative URL that I could use that would take me to the Postal sign in page?

The server is running nginx on Ubuntu 16.04.

Thank you for your help.

Best,

Bob

**Comment by willpower232** [comment]
Have you created separate vhosts in nginx to cope with each website separately?

**Comment by brinnington** [comment]
Hi willpower232,

No, I haven't. The locations of postal and wordpress are:

/opt/postal/
/var/www/html/wordpress/

Best,

Bob

**Comment by willpower232** [comment]
You will currently have a file at `/etc/nginx/sites-enabled/default` which initially referred exclusively to Postal. You can access the original copy [in this repo](https://github.com/atech/postal/blob/master/resource/nginx.cfg).

In an ideal world, you would have a second file in `/etc/nginx/sites-enabled/` which referred exclusively to WordPress. Aside from the PHP configuration, you can distinguish the two by giving one of them a different `server_name` and assigning a new domain (or subdomain) to your server accordingly.

Hope this makes sense.

**Comment by brinnington** [comment]
Hi willpower232,

You were right on both counts. I edited the file at /etc/nginx/sites-enabled/default to create the subdomain postal.example.com, because /etc/nginx/sites-enabled/default had a symbolic link from /etc/nginx/sites-available/default.

The wordpress file at /etc/nginx/sites-enabled/default/wordpress and /etc/nginx/sites-available/wordpress was already set up for example.com.

I also added an A record for postal.example.com in the DNS records in Cloudflare.

However, although wordpress appears when I enter example,com in the browser, when I enter postal.example.com in the browser I get nginx 502 bad gateway. Do you happen to know why that may be?

Best,

Bob

**Comment by willpower232** [comment]
502 Bad Gateway implies that your Postal server isn't running or nginx doesn't have the right details to connect to it.

**Comment by brinnington** [comment]
Hi willpower232,

You were right - all I had to do was start Postal and - voila, the Postal sign in page appeared. 

Thank you very much for your help and advice on this. It is much appreciated.

Best,

Bob

**Comment by willpower232** [comment]
No worries, you may be interested in https://github.com/atech/postal/wiki/Starting-on-boot but close the issue if its all good :-)

**Comment by brinnington** [comment]
Hi willpower232,

Thanks very much for the start on boot reference. I have updated the re.local file as per the instructions.

Once again, thank you very much for your help and advice on this.

Best,

Bob
