### ISSUE TITLE
[Currently Urgent] Which logs to check for routing issue?

### ISSUE THREAD

**Issue by timraybould** [atech/postal#885]
Hi, I know you don't owe any support, but I'm currently experiencing an urgent issue where no mail is being delivered into my app (that's it's core function). My Postal instance is receiving the mail fine, and not interesting is happening in smtp_server.log. However every new incoming email is supposed to be routed to a webhook and that webhook is reporting as not being hit at all. No attempts, no errors, on the webhook side.

In the postal console it says 60s timeout for all of these and that it's receiving back -1's. I don't think it's actually hitting the webhooks. Where would I go in the logs to see what's happening?

Thanks!

**Comment by timraybould** [comment]
Outbound emails are processing OK, btw. But my app is 99% concerned with routing the inbound emails.

**Comment by timraybould** [comment]
this is in message_inspection.log. perhaps that's it.

`[worker.6:2100] [2019-10-04T12:20:06.188] ERROR -- : Error talking to spamd: Errno::ECONNREFUSED (Connection refused - connect(2) for "127.0.0.1" port 783)
[worker.6:2100] [2019-10-04T12:20:06.188] ERROR -- : ["/opt/postal/app/lib/postal/message_inspection.rb:64:in `initialize'", "/opt/postal/app/lib/postal/message_inspection.rb:64:in `new'", "/opt/postal/app/lib/postal/message_inspection.rb:64:in `block in scan_for_spam'", "/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'", "/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'"]`

**Comment by timraybould** [comment]
Also seeing this is worker.log

`[worker.8:2107] [2019-10-04T12:24:29.971] INFO -- : [DTC67IZU4E] Finished processing UnqueueMessageJob job in 0.207840826s
[worker.8:2107] [2019-10-04T12:24:29.971] INFO -- : [FG5RRB6NKQ] Couldn't get lock for message 9093720. I won't do this.`

**Comment by timraybould** [comment]
I think I solved the `spamd` error by restarting SpamAssassin. The message_inspection.log is now quiet. But issue remains. The webhook in the route just stopped getting hit at 10:17PM last night.

**Comment by willpower232** [comment]
What does the UI tell you about the messages?

**Comment by timraybould** [comment]
It says soft fail

**Comment by timraybould** [comment]
Received a -1 from https://us-central1-stoop-id.cloudfunctions.net/receiveEmail
Timed out after 60s
Time: 60.58s
Support Ref: TATQVUIJ

**Comment by timraybould** [comment]
Do you by chance do phone support? I'd pay.

**Comment by willpower232** [comment]
`-1` indicates a connection error, are you able to replicate the issue with something like postbin instead of your cloud function?

**Comment by timraybould** [comment]
I don't know what postbin is.

If it's connection, I wonder if it's firewall or something else up with the Digital Ocean box that it's on.

**Comment by timraybould** [comment]
OK, yeah postbin is neat!

I just did a curl request from the command line of my DO box to postbin and it went through

**Comment by timraybould** [comment]
Also the box can hit and get a response from this that I just set up https://us-central1-stoop-id.cloudfunctions.net/testHook

**Comment by timraybould** [comment]
Just added a new HTTP endpoint in the UI for that hook and a new route, and sent myself a test email and got the same -1:

Received a -1 from https://us-central1-stoop-id.cloudfunctions.net/testHook
Timed out after 5s
Time: 5.0s
Support Ref: R3IMXW1U

**Comment by timraybould** [comment]
Any other suggestions of where to look for errors? I'm totally stumped.

**Comment by willpower232** [comment]
Can you add a postbin URL as a HTTP endpoint to see if you get a different response compared to your command line?

FWIW, I think you're ending up here: https://github.com/atech/postal/blob/634d3af59d392e84bdcd2b843b427f3a79d3ff4c/lib/postal/http_sender.rb#L41-L45

**Comment by timraybould** [comment]
Interesting. That one sent!

Received a 200 from https://postb.in/1570196959061-4927191231399?hello=world
1570197046810-6636073049157
Time: 0.14s
Support Ref: DGKGEB6T

**Comment by timraybould** [comment]
Any idea why https://us-central1-stoop-id.cloudfunctions.net/testHook DOES work via curl but does not work as an HTTP endpoint via postal?

**Comment by timraybould** [comment]
@willpower232 I'd love to pay you in order to get your live assistance. Any way to make that happen?

**Comment by willpower232** [comment]
Unfortunately that would not be possible as you need someone from atech or an actual Ruby expert but at least the problem has been narrowed down now.

I suspect there is a problem with the HTTP client in the version of ruby you are running, which if you are using the standard install, is a bit old now (#755)

Looking at the code, it seems to be a fairly standard use of the HTTP client which is what makes me suspect ruby itself. It could be down to a quirk of the HTTPS connection for example.

HTH

**Comment by timraybould** [comment]
Ok. Fair enough. Would you advice upgrading anything on the box (such as the version of ruby) or do you not have advice on that?

For a totally separate project, I host an instance of postal on a Linode box. I just logged into that and setup a test route to my cloud function (https://us-central1-stoop-id.cloudfunctions.net/testHook) and it's showing the SAME -1 connection error.

So I guess that rules out digital ocean as being the problem.

I have no idea what changed. Maybe it's on the Firebase end, but, they're not even showing any logs for receiving requests to the URLs.

**Comment by willpower232** [comment]
`-1` means that it might only appear briefly in their ingress logs as a failed connection, probably wouldn't appear in your account at all.

You could try Ubuntu 18.04/Ruby 5 if you aren't already, that might introduce other problems for you as mentioned in other issues here but unless you can find someone comfortable with Ruby, you are somewhat out of luck.

**Comment by timraybould** [comment]
Got 18.04 / Ruby 2.5 running. Didn't introduce any new problems, but it didn't solve the existing one. Back to the drawing board. I think the issue must be on the receiving end (Firebase).

**Comment by timraybould** [comment]
Here's the response I'm getting "back"

`{:code=>-1, :body=>"Timed out after 5s", :headers=>{}, :secure=>nil}`

**Comment by timraybould** [comment]
Got to the bottom of it, finally. Had to add `require 'resolv-replace'` to `/opt/postal/app/lib/postal/http.rb. Found answer thanks to https://stackoverflow.com/questions/42036133/ruby-netopentimeout-execution-expired.

I can do a PR if helpful.

**Comment by willpower232** [comment]
glad you figured it out, a PR would definitely be handy if you've got the time
