### ISSUE TITLE
email are going in spam

### ISSUE THREAD

**Issue by yuvrajWeo** [atech/postal#889]
hi my email are going in spam on gmail or yahoo.
http://prntscr.com/pj215x
http://prntscr.com/pj21rt

**Comment by aaronstuder** [comment]
What is your SPF record?

**Comment by yuvrajWeo** [comment]
v=spf1 a mx include:spf.mail.webexpertsonline.co ~all

**Comment by willpower232** [comment]
Your screenshots tell you how you can improve however if that isn't sufficient, there isn't a lot you can do.
