### ISSUE TITLE
Install on 16.04 is failing - E: Unable to locate package nodejs

### ISSUE THREAD

**Issue by palica** [atech/postal#891]
Trying to install on fresh ubuntu-16.04 I get this error:

`E: Unable to locate package nodejs`

Please help.

**Comment by palica** [comment]
after adding nodesource.com with node_10.x I am getting:

```
The following packages have unmet dependencies:
 mariadb-server : Depends: mariadb-server-10.1 (= 10.1.41+maria-1~xenial) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by willpower232** [comment]
You should try using the quick install script or at least following its commands exactly.

If possible, you could recreate your server to start from scratch also.

**Comment by willpower232** [comment]
are you able to show us the whole output of the script not just the last bit? there might be an error buried in there somewhere

**Comment by palica** [comment]
well sorry for the noise, it does install ok. must have been some connectivity issue before. thanks for help.
