### ISSUE TITLE
Can't verify domain

### ISSUE THREAD

**Issue by navinp** [atech/postal#893]
- Adds new organization
- Goes to Domains > Add your first domain
- Adds domain (Verify method: DNS)

Goes to adding the records:

Hostname: postal-verification 
Value: Ax4JgRsbxF9fLj7ExhYzzoNBkFdPiLHi

- Goes back to Postal, tries to verify the domain, hits **Verify TXT record**:

**We couldn't verify your domain. Please double check you've added the TXT record correctly.**

What am I doing wrong here, or is there anything wrong with my steps? Or with my install?

**Comment by willpower232** [comment]
You can use whatsmydns.net to verify that the record is available worldwide and the `dig` command on your server to see that your server can see the record also.

**Comment by navinp** [comment]
I tried to check the txt for postal-verification.domain.com:

- whatsmydns.net 
- https://toolbox.googleapps.com/apps/dig/#TXT/

Both cases it **did** find the txt record

I tried the dig command:

dig -t txt postal-verification.domain.com

It **did** find the txt record

I tried verifying again in Postal, it still says it cannot verify.

**Comment by navinp** [comment]
It still isn't able to verify the domains, even though the TXT records are recognized when testing with online tools such as whatsmydns

Any suggestions?

**Comment by DTS-Mike** [comment]
Make sure in your dns settings that you don’t have any extra white space or something off. Who are you using for dns?

**Comment by navinp** [comment]
My server is hosted at DigitalOcean.
I checked for white space, didn’t find any. 

What could be off btw?

- when I check this with Linux command on the same server, it does show the txt record 
- when I check using whatsmydns it does show the txt record

**Comment by willpower232** [comment]
Ah it seems we've all misunderstood based on https://github.com/atech/postal/blob/master/app/models/domain/dns_verification.rb

The record should be on the same domain as you have in Postal, i.e. example.com, not postal-verification.example.com, and the value should be
`postal-verification yourverificationstringhere`.
