### ISSUE TITLE
Error when installing on Ubuntu 18.04: can't find gem bundler (>= 0.a) with executable bundle

### ISSUE THREAD

**Issue by misterunknown** [atech/postal#896]
I try to install postal on Ubuntu 18.04, but fail with the following command:
```
root@postal:/# postal bundle /opt/postal/vendor/bundle
Traceback (most recent call last):
        2: from /usr/local/bin/bundle:23:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```
I'm not familiar with ruby, could you give a hint?

Thanks you!

**Comment by willpower232** [comment]
I suspect that this is your problem https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html

You will probably have to make some of the suggested changes as Ubuntu 18.04 and Ruby 2.5 aren't directly supported yet (#777 #755)

**Comment by misterunknown** [comment]
Thanks for your immediate response! I guess I'll simply test it in an Ubuntu 16.04 container. 

Do you plan to natively support Ruby 2.5 and Ubuntu 18.04 any time soon?

**Comment by willpower232** [comment]
I just happened to be passing, I'm not directly responsible but I hope @catphish is on the case!

Technically 16.04 is supported until at least 2021 but Ruby 2.3 became EOL some months ago so hopefully official support is forthcoming.

**Comment by misterunknown** [comment]
Ok, that sounds nice. Meanwhile I managed to setup postal in a LXC container, which works like a charm.
Thanks again, for your great support!
