### ISSUE TITLE
Unauthenticated email from DOMAIN.COM is not accepted

### ISSUE THREAD

**Issue by criskolkman** [atech/postal#898]
Hello all,

I am using PRTG to monitor the SMTP roundtrip (it is sending to a Gmail account which replies back).
PRTG is relaying the emails to Postal which delivers the emails into the world.

Many times my emails are getting blocked by Gmail with below error message.
Why is is that most of the times the emails are being delivered but many times this error is generated?

All the external IPs being used by Postal are allowed in my DNS records.

`
550-5.7.1 Unauthenticated email from **domain**.com is not accepted due to domain's 550-5.7.1 DMARC policy. Please contact the administrator of **domain**.com domain if 550-5.7.1 this was a legitimate mail. Please visit 550-5.7.1 https://support.google.com/mail/answer/2451690 to learn about the 550 5.7.1 DMARC initiative. i2si1363996wrs.325 - gsmtp
`

**Comment by willpower232** [comment]
What is the `from` domain when gmail sees that email? Does it have a DMARC policy on it that needs expanding to include your Postal server?

**Comment by criskolkman** [comment]
Hello,

The from is always the same, prtg@domain.com

It has a DMARC policy which includes postal allready in the spf records.

**Comment by criskolkman** [comment]
Below a Google report with the fails.

`
<?xml version="1.0" encoding="UTF-8"?>

-<feedback>


-<report_metadata>

<org_name>google.com</org_name>

<email>noreply-dmarc-support@google.com</email>

<extra_contact_info>https://support.google.com/a/answer/2466580</extra_contact_info>

<report_id>11888836422482274127</report_id>


-<date_range>

<begin>1572048000</begin>

<end>1572134399</end>

</date_range>

</report_metadata>


-<policy_published>

<domain>domain.com</domain>

<adkim>r</adkim>

<aspf>r</aspf>

<p>reject</p>

<sp>reject</sp>

<pct>100</pct>

</policy_published>


-<record>


-<row>

<source_ip>0.0.0.231</source_ip>

<count>14</count>


-<policy_evaluated>

<disposition>none</disposition>

<dkim>pass</dkim>

<spf>fail</spf>

</policy_evaluated>

</row>


-<identifiers>

<header_from>domain.com</header_from>

</identifiers>


-<auth_results>


-<dkim>

<domain>domain.com</domain>

<result>pass</result>

<selector>postal-fjFaAL</selector>

</dkim>


-<spf>

<domain>rp.postal.domain.com</domain>

<result>softfail</result>

</spf>

</auth_results>

</record>


-<record>


-<row>

<source_ip>0.0.0.211</source_ip>

<count>13</count>


-<policy_evaluated>

<disposition>none</disposition>

<dkim>pass</dkim>

<spf>fail</spf>

</policy_evaluated>

</row>


-<identifiers>

<header_from>domain.com</header_from>

</identifiers>


-<auth_results>


-<dkim>

<domain>domain.com</domain>

<result>pass</result>

<selector>postal-fjFaAL</selector>

</dkim>


-<spf>

<domain>rp.postal.domain.com</domain>

<result>softfail</result>

</spf>

</auth_results>

</record>


-<record>


-<row>

<source_ip>0.0.0.231</source_ip>

<count>2</count>


-<policy_evaluated>

<disposition>reject</disposition>

<dkim>fail</dkim>

<spf>fail</spf>

</policy_evaluated>

</row>


-<identifiers>

<header_from>domain.com</header_from>

</identifiers>


-<auth_results>


-<dkim>

<domain>rp.postal.domain.com</domain>

<result>fail</result>

<selector>postal</selector>

</dkim>


-<spf>

<domain>rp.postal.domain.com</domain>

<result>softfail</result>

</spf>

</auth_results>

</record>

</feedback>
`

**Comment by willpower232** [comment]
You'll note that the return path domain is present in the report, is that part of the DMARC policy too?

(P.S. You should use three backticks to enclose multi line comments in GitHub)

**Comment by criskolkman** [comment]
Looks like it's solved now by expanding the SPF records.
