### ISSUE TITLE
OpenSSL certificate error with smtp

### ISSUE THREAD

**Issue by michael22312** [atech/postal#899]
[postal.txt](https://github.com/atech/postal/files/3782261/postal.txt)

Whenever I try to send a test email to my own emailaddress, I receive the following error.
What can be the cause and solution of this problem?

Message was not delivered successfully to SMTP server.
Error: OpenSSL::SSL::SSLError (hostname "5.39.185.39" does not match the server certificate)

  SMTP Host: 5.39.185.39
  SMTP Port: 25
  SMTP Username: postal

**Comment by willpower232** [comment]
Host should be the domain name, i.e. postal.yourcompany.com

Also you probably shouldn't have put your real domain name in that text file and I hope thats not a real password either?

**Comment by michael22312** [comment]
Well. I have put our existing email server as the domain name. But I still receive the same error

**Comment by willpower232** [comment]
Have you restarted Postal since changing the config?

**Comment by michael22312** [comment]
Apparently the host didn't change the config. A restart and config change are the solution.
Thank you for your help Willpower
