### ISSUE TITLE
running postal on local, is there any documentation for this.

### ISSUE THREAD

**Issue by anshulchhabra1991** [atech/postal#90]
I am trying to setup an ESP. For this I have completed the documentation requirements and install all the things.
now when I am trying to hit a mail, it is giving me this error:

root@Hp-Elitebook:~# postal test-app-smtp anshul.chhabra1991@gmail.com
Message was not delivered successfully to SMTP server.
Error: ArgumentError (SMTP-AUTH requested but missing secret phrase)

  SMTP Host: 127.0.0.1
  SMTP Port: 2525
  SMTP Username: betinc.com
  SMTP Password:

**Comment by adamcooke** [comment]
You need to configure the application to send outgoing e-mail. Once you've installed Postal, you can create a mail server within Postal itself and then add configure to send messages through itself.

**Comment by anshulchhabra1991** [comment]
**you can create a mail server within Postal itself**
Hello Adamcooke, 
  thanks for the revert.
I have installed postal , and when checking the status , it displays all of them as running as shown in screen shot.
![screenshot from 2017-05-03 17-03-49](https://cloud.githubusercontent.com/assets/12149264/25658863/9fce44a8-3022-11e7-91aa-e8ec212496f4.png)

can you please tell me how can I create a mail server within postal as a mail server is already setup on my local system.

**Comment by adamcooke** [comment]
You can create a mail server through the Postal web interface. Once created, you can generate some SMTP credentials that you can use to authenticate.

**Comment by anshulchhabra1991** [comment]
ohh, Thats great :+1:  .is there any documentation provided for initiating the Postal web interface. Thank you in advance.

**Comment by adamcooke** [comment]
Yes. Check the wiki. The installation docs explain how to set it all up.

**Comment by himi1203** [comment]
Hi, can someone please post link of documentation, that specifically focuses on running postal web interface locally, I am unable to do so. Although in netstat I can see 5000 port but it is unacessible on localhost
