### ISSUE TITLE
Sender Address Does Not Exist????

### ISSUE THREAD

**Issue by zeba121** [atech/postal#901]
Hello Postal Team,

my mails are **soft fail** or **hard fail** due to sender address does not exit.

I have added my all dns records according to this documentation https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration.
And i have add all dns record for the incoming server.

Does anyone have any ideas why some emails fail to send.

Here is the error message.
https://prnt.sc/pq40rf

Thank You
Zeba Parveen

**Comment by willpower232** [comment]
The screenshot is telling you that the return path domain does not exist. This is not required by the domains page in Postal but you need to add it in this case.

**Comment by zeba121** [comment]
Thank You @willpower232
