### ISSUE TITLE
When testing postal with an outlook client, we receive login prompt continiously

### ISSUE THREAD

**Issue by michael22312** [atech/postal#903]
Hiya,

Postal seems to be correctly configured for us.
However, we still want to test it before relaying our emails through postal.
We are testing postal by relaying emails of one outlook client through postal.

When I am changing the outgoing server in outlook I keep receiving login prompts.
If I login with my own email credentials or with the admin credentials of postal, the login prompt keeps coming back.

Could you guys help me?

[postal.txt](https://github.com/atech/postal/files/3792817/postal.txt)

![Login_Prompt](https://user-images.githubusercontent.com/36194698/67931164-9d6df600-fbc1-11e9-98ca-30f0adabe527.png)

**Comment by willpower232** [comment]
The username for the SMTP is not an email address, you will have to get the `org\server` reference from the UI but also note that Postal was not designed to work with a desktop email client so you may not have a great experience.

**Comment by michael22312** [comment]
Well, we do not have a org\server reference from the ui. We only got our root user and an user whom logs in with an emailaddress.
(I understand that postal is not designed to work with desktop clients, but I want to test postal with a desktop client before using our mail server)

In addition, creating a mail server in the UI is very slow. If I wait for two hours, the server hasn't been created yet.

**Comment by willpower232** [comment]
On the credentials page, there is a link to another page of details for how to connect.

![image](https://user-images.githubusercontent.com/1619102/67948752-49bdd580-fbde-11e9-8491-ce80375a91cb.png)

There must have been a problem creating a mail server, it should be a fairly instant process. You will have to look at the log files in `/opt/postal/logs`

**Comment by michael22312** [comment]
Thank you for your help. Our emails are now scanned through postal.

The issue with creating a new mailserver was that the permissions in mysql/mariadb were incorrect
