### ISSUE TITLE
Postal not sending towards current spamfilter

### ISSUE THREAD

**Issue by michael22312** [atech/postal#908]
Hiya,

We are testing postal on a VPS before we use it on our own mailserver.
The issue is that the IP address of the VPS is on a blacklist.

We want to send the e-mails through postal to our own spamfilter.
How do we implement this? With routes and endpoints this does not work.

**Comment by willpower232** [comment]
You can route all email from Postal to an SMTP relay server if you wish.

Have a look at https://github.com/atech/postal/issues/251#issuecomment-313349385
