### ISSUE TITLE
Can I Rotate all Domains

### ISSUE THREAD

**Issue by zeba121** [atech/postal#909]
Hello Postal Team,

I want to send email with using multiple domains in rotationally. 

When we using ip pools for ip rotation just like that i want to send emails using multiple domains in rotation.

Thank You
Zeba

**Comment by willpower232** [comment]
Postal will only send what it is given, if you want to rotate domains you will have to do this at the point of constructing the email message (i.e. your application).

You will also have to make sure that each of the domains you use is configured in Postal.

**Comment by zeba121** [comment]
Thank You @willpower232
