### ISSUE TITLE
Incorrect SMTP related iptables command?

### ISSUE THREAD

**Issue by willpower232** [atech/postal#91]
As per the attached, I believe there is a small error in the `OUTPUT` rule under https://github.com/atech/postal/wiki/Processes#listening-on-privileged-ports (mentioned in https://github.com/atech/postal/issues/81)

![capture](https://cloud.githubusercontent.com/assets/1619102/25668924/ff583bfc-301f-11e7-88b8-004c4dacd137.PNG)

**Comment by alexspurling** [comment]
Thank you for this. I was wondering why incoming mails where not being received and it turns out my iptables were not correctly set up. Hopefully your change can be made to the wiki documentation.

**Comment by willpower232** [comment]
Aha we haven't tested that feature yet so good to know I am doing the right thing!

**Comment by catphish** [comment]
Thanks for spotting this, I've fixed it in the documentation. The correct format for the rule is below, but this will generally work with the "REDIRECT" version above too.

```
iptables -t nat -I OUTPUT -d 192.128.1.3 -p tcp -m tcp --dport 25 -j DNAT --to-destination 192.128.1.3:2525
```
