### ISSUE TITLE
How many times deliveries are retried?

### ISSUE THREAD

**Issue by manuel-rodriguez-autocontrol** [atech/postal#916]
Hi.
We are using a post in our company and we would like to know how many times a failed email delivery is retried.

**Comment by franciscopaniskaseker** [comment]
According with postal.defaults.yml,

https://github.com/atech/postal/blob/634d3af59d392e84bdcd2b843b427f3a79d3ff4c/config/postal.defaults.yml#L14

**Comment by manuel-rodriguez-autocontrol** [comment]
Great!
Thanks a lot!
