### ISSUE TITLE
Global SPF Validation Issue

### ISSUE THREAD

**Issue by sheikhsherazali** [atech/postal#918]
Domain: dailydeals360.com
dailydeals360.com hosted on IP: 207.180.193.222

Sub Domain: mail.dailydeals360.com
A & MX point to 207.180.219.95
Tracking IP: 173.249.59.28 

Postal Installation IP: 207.180.219.95 

As per Documentation Guideline:
Global SPF = spf.mail.dailydeals360.com. | 14400 | IN | TXT | "v=spf1 ip4:207.180.218.0/23 ~all" //Whole netblock is considered. What if i only authorized my IP (Is this possible?)? I have placed the full netblock of my provider i.e. https://ipinfo.io/AS51167/207.180.218.0/23 if there is a better mechanism please explain.

Domain Created in Postal: vacsolution.com
SPF and DKIM record as advised by the postal are created both are marked correct in the postal here is the screenshot. http://prntscr.com/pxfpsk

The problem is that my spf is not validating when i check with the spf checker. 
http://prntscr.com/pxfumw

Its states the error Error: No valid SPF record for included domain: spf.mail.dailydeals360.com

No netblocks are found for SPF to validate the third party source spf for the domain

Plus yesterday I run a campaign of 14k email and DMARc report states that there are no valid SPF. Here is the screenshot:

http://prntscr.com/pxfyym

Thanks in advance for your support

Regards
Sheikh Sheraz Ali

**Comment by joseltorres** [comment]
`dig spf.mail.dailydeals360.com TXT`

i get this in the answer section:
```
;; ANSWER SECTION:
spf.mail.dailydeals360.com. 14399 IN	TXT	"\"v=spf1 ip4:207.180.218.0/23 ~all\""
```

you have a double-quotes in the actual TXT record in your DNS. Remove them

your answer section should look more like this
```
;; ANSWER SECTION:
spf.pescmail.com.	3599	IN	TXT	"v=spf1 ip4:45.63.86.179 ip4:45.77.6.102 -all"
```

**Comment by sheikhsherazali** [comment]
Many thanks and awesome it works like a charm.

Many thanks once again.
