### ISSUE TITLE
problem with letsencrypt

### ISSUE THREAD

**Issue by elfeffe** [atech/postal#92]
I have created my cert using instructions here
https://gist.github.com/cecilemuller/a26737699a7e70a7093d4dc115915de8

Because I can't with postal script
It says
```
postal register-lets-encrypt youremail@example.comn
Acme::Client::Error::Malformed: Registration key is already in use
```
I replace with my email
But my track.mail.xxx.xxx doesn't work with https, browser says SSL cert is invalid (common name doesn't include that domain).
HTTPS works on www.xxx.xxx (the main Postal domain)

**Comment by adamcooke** [comment]
It sounds like you have already registered your LE private key which means you don't need to do it again. For tracking, the requests must go to the fast web server. This listens on ports 5010 and 5011 and should be made publicly available on a different IP address. 

https://github.com/atech/postal/wiki/Click-&-Open-Tracking

**Comment by elfeffe** [comment]
yes, fast server is enabed, ports are redirected and track.mail.xxx.xxx says "Hello" when I visit with the browser.
But https://track.mail.xxx.ccc gives SSL error on the browser, I have checked it with an external service and it says "your commonname doesn't include track.mail.xxx.xxx, you will probably get some errors on browsers".
SSL works on the main domain (my common name is xxx.xxx, on this example), but SSl doesn't work on the fast server

**Comment by adamcooke** [comment]
There are a few things to check if you have problems with SSL

1. Check the status of the SSL on the tracking domain. It should say SSL enabled.
2. Check that requests to the domain are going to the fast server. Access the domain and it should simply reply with "Hello"
3. Check the `log/lets_encrypt.log` log file (only available in the latest commits) to see for issues issuing the certificate.
4. Restart your browser to ensure nothing has been cached or try the request using `curl`.

**Comment by elfeffe** [comment]
@adamcooke I think the problem is that I used letsencrypt directly to create the cert for the first time (I did that because I used Ubuntu 14 and your script didnt work, I updated Ubuntu to 16 after that), I have included www.xxx.xxx and xxx.xxx on the command line, but not track.mail.xxx.xxx
So I can create a new cert, but the problem is that if I add track.mail.xxx.xxx to the LE command line, it returns an error because track.mail.xxx.xxx doesn't return the well_known folder that LE needs (www domain returns it because I have prepared NGINX for that).
So, I think it can be fixed if postal register-lets-encrypt youremail@example.comn can delete my actual cert and remake it properly, or if Postal can return well_known acme challenge when I create the cert by myself.
In the other hand, I think the best is to install it in a clean server with Ubuntu 16 :)

**Comment by elfeffe** [comment]
@adamcooke I have installed everything on a Ubuntu 16 server.
I seems like it doesn't register the domain track.mail.xxx.xxx  (or track.postal.xxx.xxx) because postal doesn't return well_known acme challenge.
So SSL cert for that subdomain, doesn't work. Postal is who received the call for that subdomain, it is the fast 443 server, so I think the problem is in Postal.

**Comment by adamcooke** [comment]
Please can you upgrade to the latest version from master and check the output in the `lets_encrypt.log` file. You may wish to delete the domain you have added before and add another one, too.

**Comment by elfeffe** [comment]
I have updated using git as you say here:
And I get

> postal register-lets-encrypt xxx@xxx.com
> Acme::Client::Error::Malformed: Registration key is already in use

There is no letsencrypt.log file inside postal, there is one in var/log/letsencrypt (ubuntu logs) and it says

> 2017-05-05 12:44:53,758:DEBUG:certbot.main:Root logging level set at 30
> 2017-05-05 12:44:53,759:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
> 2017-05-05 12:44:53,759:DEBUG:certbot.main:certbot version: 0.12.0
> 2017-05-05 12:44:53,759:DEBUG:certbot.main:Arguments: ['-q']
> 2017-05-05 12:44:53,760:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
> 2017-05-05 12:44:53,770:INFO:certbot.renewal:Cert not yet due for renewal
> 2017-05-05 12:44:53,770:DEBUG:certbot.renewal:no renewal failures

**Comment by adamcooke** [comment]
Sounds like you don't need to register then. You just need to add a cert and it should generate the cert automatically. If you have the latest version you will have a log file in log folder called lets_encrypt.log.
