### ISSUE TITLE
SSL setup not completing for tracking domain

### ISSUE THREAD

**Issue by willpower232** [atech/postal#93]
As per https://github.com/atech/postal/wiki/Click-&-Open-Tracking I have enabled Lets Encrypt but the tracking domain I have added is not getting its certificate and it has been several hours.

The CNAME is working and I believe the iptables rules are working since visiting the domain name outputs hello.

Is there anywhere to see the output of lets encrypt for the tracking domain?

**Comment by adamcooke** [comment]
There is actually very little logging on the Let's Encrypt stuff however you should be able to see something about it in the `log/worker.log` file. Something like:

```
Renewing certificate for track domain (somedomain.com)
Successfully renewed
```

You can do a little debugging of your own in the console (`postal console`)

```ruby
cert = TrackCertificate.find_by(:domain => "yourdomain.com")
cert.active?   # => Is there a certificate for this or not?
cert.get       # => Attempt to verify & get the cert from LE (returns false on failure)
```

**Comment by adamcooke** [comment]
I have added a new issue to improve logging for this - see issue #94.

**Comment by adamcooke** [comment]
I've added some additional logging to Let's Encrypt. If you upgrade, you'll find that you'll get log output into `log/lets_encrypt.log` whenever certificate renewals take place.

**Comment by willpower232** [comment]
thanks adam, I removed and re added the domain and apparently that was enough to get the SSL working properly. I'll update to the logging version momentarily

**Comment by willpower232** [comment]
also is there any documentation on using the console?

**Comment by adamcooke** [comment]
There's no documentation on the console really, I'm afraid.
