### ISSUE TITLE
How to use send API?

### ISSUE THREAD

**Issue by robdeweese** [atech/postal#95]
How do I use the API? I created api credentials but how do I authenticate as a server? The link to the api documentation on the "org/dfn/servers/dfn/help/outgoing" page currently sends me to "https://gopostal.io/~/http-sending", a url that does not exist.

**Comment by adamcooke** [comment]
Apologies for the lack of documentation about this. I'll get that updated ASAP. In the meantime, you can authenticate to the API by sending the `X-Server-API-Key` header with your request.

Additional information is available here https://appmail.io/documentation/sending-messages/sending-over-the-http-api (although it relates to AppMail, the same applies with Postal)

**Comment by adamcooke** [comment]
I've copied the information over to our wiki here: https://github.com/atech/postal/wiki/Using-the-API

**Comment by theraw** [comment]
@adamcooke hello can you please tell me where can i find "X-Server-API-Key" ?

**Comment by willpower232** [comment]
You need to make a credential in the credentials section of a mail server 

![image](https://user-images.githubusercontent.com/1619102/34917180-c57d5022-f93a-11e7-8ecb-80eac4e48b00.png)

**Comment by theraw** [comment]
@willpower232 thank you
