### ISSUE TITLE
Feature request: Use rspamd instead of spam-assassin

### ISSUE THREAD

**Issue by pratik60** [atech/postal#96]
What are thoughts on using [rspamd](https://rspamd.com/) as an alternative instead of spam assassin? 

Been really impressed with its continuous development, and performance. Are there any plans to do the same? Have you discarded it for any reason?

Website: https://rspamd.com/
Github Repo: https://github.com/vstakhov/rspamd

**Comment by adamcooke** [comment]
I had no idea that it existed. We've always just used Spam Assassin which is why we used it here. If there are any good reasons to look at switching to this, I'd be happy to hear them.

**Comment by pratik60** [comment]
@adamcooke Sorry for the late reply, it got lost in the mail thread.

Features listed here: https://rspamd.com/features.html
Some differences are listed here: https://rspamd.com/doc/tutorials/migrate_sa.html
Mailcow are on the process of a similar switch: https://github.com/mailcow/mailcow/issues/395

When you have time, might be worth of digging in to the features that you get out of spam-assassin,  they should almost certainly be all replaceable via rspamd, and be much improved. We definitely found it to be faster in our results. You could additionally have a chat with the maintainer (@vstakhov) of rspamd for more details. I have used it to a limited extent, so I'm not the best person to carry this forward.

**Comment by denji** [comment]
@adamcooke 
* https://github.com/hardware/mailserver/issues/11
* https://github.com/hardware/mailserver/issues/56

**Comment by Mr-Binary** [comment]
@pratik60 I was wondering if you can run rspamd as standalone for email quality check?
please see #422

**Comment by denji** [comment]
@adamcooke Bump!

**Comment by denji** [comment]
Without the support of rspamd this is not considered a not full solution.

DKIM, DMARC, ARC standard.

**Comment by denji** [comment]
@adamcooke Is it possible to support rspamd in future releases? SpamAssassin is terrible for production.

**Comment by windware-ono** [comment]
I was surprised to see rspamd integration was actually implemented despite this thread being closed without any mention of it.

https://github.com/postalserver/postal/blob/d808d15c28d1c4c626af44bedc05743b01e078b9/config/postal.defaults.yml#L105

The configuration allows you to enter rspamd connection parameters and it worked just fine.

And to also check for outgoing, doing as this [comment](https://github.com/postalserver/postal/issues/1330#issuecomment-811745894) suggested made it to work fine too.

**Comment by mredodos** [comment]
@windware-ono have you some simple example or little guide to install and use rspamd with postal, i cant figure out
